# generated by winmd2nim from Windows.Win32.winmd — activationregistration (do not edit)
import ./[inspectable]
export inspectable

type

  # typdefs
  RegisteredTrustLevel* = distinct TrustLevel

  # unscoped enums 
  ActivationType_2* = int32
  RegistrationScope* = int32

  # interfaces
  IActivatableClassRegistration* = distinct object

const
  # unscoped enum members
  ActivationType_InProcess*: ActivationType_2 = 0'i32
  ActivationType_OutOfProcess*: ActivationType_2 = 1'i32
  ActivationType_RemoteProcess*: ActivationType_2 = 2'i32
  RegistrationScope_PerMachine*: RegistrationScope = 0'i32
  RegistrationScope_PerUser*: RegistrationScope = 1'i32
  RegistrationScope_InboxApp*: RegistrationScope = 2'i32

