# generated by winmd2nim from Windows.Win32.winmd — bits3_0 (do not edit)

type

  # interfaces
  IBackgroundCopyCallback2* = distinct object
  IBackgroundCopyFile3* = distinct object
  IBackgroundCopyJob4* = distinct object
  IBitsPeer* = distinct object
  IBitsPeerCacheAdministration* = distinct object
  IBitsPeerCacheRecord* = distinct object
  IEnumBitsPeerCacheRecords* = distinct object
  IEnumBitsPeers* = distinct object

const
  # free constants
  BG_DISABLE_BRANCH_CACHE*: int32 = 4'i32
  BG_ENABLE_PEERCACHING_CLIENT*: int32 = 1'i32
  BG_ENABLE_PEERCACHING_SERVER*: int32 = 2'i32
  BG_JOB_DISABLE_BRANCH_CACHE*: int32 = 4'i32
  BG_JOB_ENABLE_PEERCACHING_CLIENT*: int32 = 1'i32
  BG_JOB_ENABLE_PEERCACHING_SERVER*: int32 = 2'i32

