# generated by winmd2nim from Windows.Win32.winmd — bits1_5 (do not edit)
import ./[winnt]
export winnt

type

  # structs
  BG_AUTH_CREDENTIALS* {.completeStruct.} = object
    Target*: BG_AUTH_TARGET
    Scheme*: BG_AUTH_SCHEME
    Credentials*: BG_AUTH_CREDENTIALS_UNION
  BG_AUTH_CREDENTIALS_UNION* {.completeStruct, union.} = object
    Basic*: BG_BASIC_CREDENTIALS
  BG_BASIC_CREDENTIALS* {.completeStruct.} = object
    UserName*: PWSTR
    Password*: PWSTR
  BG_JOB_REPLY_PROGRESS* {.completeStruct.} = object
    BytesTotal*: uint64
    BytesTransferred*: uint64

  # typdefs
  PBG_AUTH_CREDENTIALS* = ptr BG_AUTH_CREDENTIALS
  PBG_BASIC_CREDENTIALS* = ptr BG_BASIC_CREDENTIALS

  # unscoped enums 
  BG_AUTH_SCHEME* = int32
  BG_AUTH_TARGET* = int32

  # interfaces
  IBackgroundCopyJob2* = distinct object

const
  # unscoped enum members
  BG_AUTH_SCHEME_BASIC*: BG_AUTH_SCHEME = 1'i32
  BG_AUTH_SCHEME_DIGEST*: BG_AUTH_SCHEME = 2'i32
  BG_AUTH_SCHEME_NTLM*: BG_AUTH_SCHEME = 3'i32
  BG_AUTH_SCHEME_NEGOTIATE*: BG_AUTH_SCHEME = 4'i32
  BG_AUTH_SCHEME_PASSPORT*: BG_AUTH_SCHEME = 5'i32
  BG_AUTH_TARGET_SERVER*: BG_AUTH_TARGET = 1'i32
  BG_AUTH_TARGET_PROXY*: BG_AUTH_TARGET = 2'i32

