# generated by winmd2nim from Windows.Win32.winmd — certbase (do not edit)

type

  # structs
  CERTTRANSBLOB* {.completeStruct.} = object
    cb*: uint32
    pb*: ptr uint8
  CERTVIEWRESTRICTION* {.completeStruct.} = object
    ColumnIndex*: uint32
    SeekOperator*: int32
    SortOrder*: int32
    pbValue*: ptr uint8
    cbValue*: uint32

