# generated by winmd2nim from Windows.Win32.winmd — certpol (do not edit)

type

  # unscoped enums 
  X509SCEPDisposition* = int32
  X509SCEPFailInfo* = int32
  X509SCEPMessageType* = int32

  # interfaces
  ICertPolicy* = distinct object
  ICertPolicy2* = distinct object
  INDESPolicy* = distinct object

const
  # unscoped enum members
  SCEPDispositionUnknown*: X509SCEPDisposition = -1'i32
  SCEPDispositionSuccess*: X509SCEPDisposition = 0'i32
  SCEPDispositionFailure*: X509SCEPDisposition = 2'i32
  SCEPDispositionPending*: X509SCEPDisposition = 3'i32
  SCEPDispositionPendingChallenge*: X509SCEPDisposition = 11'i32
  SCEPFailUnknown*: X509SCEPFailInfo = -1'i32
  SCEPFailBadAlgorithm*: X509SCEPFailInfo = 0'i32
  SCEPFailBadMessageCheck*: X509SCEPFailInfo = 1'i32
  SCEPFailBadRequest*: X509SCEPFailInfo = 2'i32
  SCEPFailBadTime*: X509SCEPFailInfo = 3'i32
  SCEPFailBadCertId*: X509SCEPFailInfo = 4'i32
  SCEPMessageUnknown*: X509SCEPMessageType = -1'i32
  SCEPMessageCertResponse*: X509SCEPMessageType = 3'i32
  SCEPMessagePKCSRequest*: X509SCEPMessageType = 19'i32
  SCEPMessageGetCertInitial*: X509SCEPMessageType = 20'i32
  SCEPMessageGetCert*: X509SCEPMessageType = 21'i32
  SCEPMessageGetCRL*: X509SCEPMessageType = 22'i32
  SCEPMessageClaimChallengeAnswer*: X509SCEPMessageType = 41'i32

