# generated by winmd2nim from Windows.Win32.winmd — certbcli (do not edit)
import ./[winnt, minwindef]
export winnt, minwindef

type

  # structs
  CSEDB_RSTMAPW* {.completeStruct.} = object
    pwszDatabaseName*: ptr uint16
    pwszNewDatabaseName*: ptr uint16

  # typdefs
  CSBFT* = distinct uint16
  HCSBC* = distinct pointer

  # delegates
  FNCERTSRVBACKUPCLOSE* = proc (arg_1: HCSBC): HRESULT {.stdcall.}
  FNCERTSRVBACKUPEND* = proc (arg_1: HCSBC): HRESULT {.stdcall.}
  FNCERTSRVBACKUPFREE* = proc (arg_1: pointer): void {.stdcall.}
  FNCERTSRVBACKUPGETBACKUPLOGSW* = proc (arg_1: HCSBC, arg_2: ptr ptr uint16, arg_3: ptr uint32): HRESULT {.stdcall.}
  FNCERTSRVBACKUPGETDATABASENAMESW* = proc (arg_1: HCSBC, arg_2: ptr ptr uint16, arg_3: ptr uint32): HRESULT {.stdcall.}
  FNCERTSRVBACKUPGETDYNAMICFILELISTW* = proc (arg_1: HCSBC, arg_2: ptr ptr uint16, arg_3: ptr uint32): HRESULT {.stdcall.}
  FNCERTSRVBACKUPOPENFILEW* = proc (arg_1: HCSBC, arg_2: ptr uint16, arg_3: uint32, arg_4: ptr int64): HRESULT {.stdcall.}
  FNCERTSRVBACKUPPREPAREW* = proc (arg_1: ptr uint16, arg_2: uint32, arg_3: uint32, arg_4: ptr HCSBC): HRESULT {.stdcall.}
  FNCERTSRVBACKUPREAD* = proc (arg_1: HCSBC, arg_2: pointer, arg_3: uint32, arg_4: ptr uint32): HRESULT {.stdcall.}
  FNCERTSRVBACKUPTRUNCATELOGS* = proc (arg_1: HCSBC): HRESULT {.stdcall.}
  FNCERTSRVISSERVERONLINEW* = proc (arg_1: ptr uint16, arg_2: ptr BOOL): HRESULT {.stdcall.}
  FNCERTSRVRESTOREEND* = proc (arg_1: HCSBC): HRESULT {.stdcall.}
  FNCERTSRVRESTOREGETDATABASELOCATIONSW* = proc (arg_1: HCSBC, arg_2: ptr ptr uint16, arg_3: ptr uint32): HRESULT {.stdcall.}
  FNCERTSRVRESTOREPREPAREW* = proc (arg_1: ptr uint16, arg_2: uint32, arg_3: ptr HCSBC): HRESULT {.stdcall.}
  FNCERTSRVRESTOREREGISTERCOMPLETE* = proc (arg_1: HCSBC, arg_2: HRESULT): HRESULT {.stdcall.}
  FNCERTSRVRESTOREREGISTERW* = proc (arg_1: HCSBC, arg_2: ptr uint16, arg_3: ptr uint16, arg_4: ptr CSEDB_RSTMAPW, arg_5: int32, arg_6: ptr uint16, arg_7: uint32, arg_8: uint32): HRESULT {.stdcall.}
  FNCERTSRVSERVERCONTROLW* = proc (arg_1: ptr uint16, arg_2: uint32, arg_3: ptr uint32, arg_4: ptr ptr uint8): HRESULT {.stdcall.}

const
  # free constants
  CSBACKUP_DISABLE_INCREMENTAL*: uint32 = 0xffffffff'u32
  CSBACKUP_TYPE_FULL*: int32 = 1'i32
  CSBACKUP_TYPE_LOGS_ONLY*: int32 = 2'i32
  CSBACKUP_TYPE_MASK*: int32 = 3'i32
  CSBFT_CERTSERVER_DATABASE*: uint32 = 0x44'u32
  CSBFT_CHECKPOINT_DIR*: uint32 = 0x83'u32
  CSBFT_DATABASE_DIRECTORY*: int32 = 64'i32
  CSBFT_DIRECTORY*: int32 = 128'i32
  CSBFT_LOG*: uint32 = 0x21'u32
  CSBFT_LOG_DIR*: uint32 = 0x82'u32
  CSBFT_LOG_DIRECTORY*: int32 = 32'i32
  CSBFT_PATCH_FILE*: uint32 = 0x25'u32
  CSBFT_UNKNOWN*: uint32 = 0xf'u32
  CSCONTROL_RESTART*: int32 = 3'i32
  CSCONTROL_SHUTDOWN*: int32 = 1'i32
  CSCONTROL_SUSPEND*: int32 = 2'i32
  CSRESTORE_TYPE_CATCHUP*: int32 = 4'i32
  CSRESTORE_TYPE_FULL*: int32 = 1'i32
  CSRESTORE_TYPE_MASK*: int32 = 5'i32
  CSRESTORE_TYPE_ONLINE*: int32 = 2'i32
  szBACKUPANNOTATION*: string = "Cert Server Backup Interface"
  szRESTOREANNOTATION*: string = "Cert Server Restore Interface"

{.push dynlib: "certadm".}
proc CertSrvBackupClose*(hbc: HCSBC): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupEnd*(hbc: HCSBC): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupFree*(pv: pointer) {.sideEffect, importc, stdcall.}
proc CertSrvBackupGetBackupLogsW*(hbc: HCSBC, ppwszzBackupLogFiles: ptr PWSTR, pcbSize: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupGetDatabaseNamesW*(hbc: HCSBC, ppwszzAttachmentInformation: ptr PWSTR, pcbSize: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupGetDynamicFileListW*(hbc: HCSBC, ppwszzFileList: ptr PWSTR, pcbSize: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupOpenFileW*(hbc: HCSBC, pwszAttachmentName: ptr uint16, cbReadHintSize: uint32, pliFileSize: ptr int64): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupPrepareW*(pwszServerName: ptr uint16, grbitJet: uint32, dwBackupFlags: uint32, phbc: ptr HCSBC): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupRead*(hbc: HCSBC, pvBuffer: pointer, cbBuffer: uint32, pcbRead: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvBackupTruncateLogs*(hbc: HCSBC): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvIsServerOnlineW*(pwszServerName: ptr uint16, pfServerOnline: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvRestoreEnd*(hbc: HCSBC): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvRestoreGetDatabaseLocationsW*(hbc: HCSBC, ppwszzDatabaseLocationList: ptr PWSTR, pcbSize: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvRestorePrepareW*(pwszServerName: ptr uint16, dwRestoreFlags: uint32, phbc: ptr HCSBC): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvRestoreRegisterComplete*(hbc: HCSBC, hrRestoreState: HRESULT): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvRestoreRegisterThroughFile*(hbc: HCSBC, pwszCheckPointFilePath: ptr uint16, pwszLogPath: ptr uint16, rgrstmap: ptr CSEDB_RSTMAPW, crstmap: int32, pwszBackupLogPath: ptr uint16, genLow: uint32, genHigh: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvRestoreRegisterW*(hbc: HCSBC, pwszCheckPointFilePath: ptr uint16, pwszLogPath: ptr uint16, rgrstmap: ptr CSEDB_RSTMAPW, crstmap: int32, pwszBackupLogPath: ptr uint16, genLow: uint32, genHigh: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc CertSrvServerControlW*(pwszServerName: ptr uint16, dwControlFlags: uint32, pcbOut: ptr uint32, ppbOut: ptr ptr uint8): HRESULT {.sideEffect, importc, stdcall.}
{.pop.}
