# generated by winmd2nim from Windows.Win32.winmd — consoleapi3 (do not edit)
import ./[winnt, windef, minwindef, wincontypes]
export winnt, windef, minwindef, wincontypes

type

  # structs
  CONSOLE_FONT_INFOEX* {.completeStruct.} = object
    cbSize*: uint32
    nFont*: uint32
    dwFontSize*: COORD
    FontFamily*: uint32
    FontWeight*: uint32
    FaceName*: array[32, uint16]
  CONSOLE_HISTORY_INFO* {.completeStruct.} = object
    cbSize*: uint32
    HistoryBufferSize*: uint32
    NumberOfHistoryBuffers*: uint32
    dwFlags*: uint32
  CONSOLE_SELECTION_INFO* {.completeStruct.} = object
    dwFlags*: uint32
    dwSelectionAnchor*: COORD
    srSelection*: SMALL_RECT

  # typdefs
  PCONSOLE_FONT_INFOEX* = ptr CONSOLE_FONT_INFOEX
  PCONSOLE_HISTORY_INFO* = ptr CONSOLE_HISTORY_INFO
  PCONSOLE_SELECTION_INFO* = ptr CONSOLE_SELECTION_INFO

const
  # free constants
  CONSOLE_FULLSCREEN*: int32 = 1'i32
  CONSOLE_FULLSCREEN_HARDWARE*: int32 = 2'i32
  CONSOLE_FULLSCREEN_MODE*: int32 = 1'i32
  CONSOLE_MOUSE_DOWN*: int32 = 8'i32
  CONSOLE_MOUSE_SELECTION*: int32 = 4'i32
  CONSOLE_NO_SELECTION*: int32 = 0'i32
  CONSOLE_SELECTION_IN_PROGRESS*: int32 = 1'i32
  CONSOLE_SELECTION_NOT_EMPTY*: int32 = 2'i32
  CONSOLE_WINDOWED_MODE*: int32 = 2'i32
  HISTORY_NO_DUP_FLAG*: int32 = 1'i32

{.push dynlib: "kernel32".}
proc AddConsoleAliasA*(Source: PCSTR, Target: PCSTR, ExeName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc AddConsoleAliasW*(Source: PCWSTR, Target: PCWSTR, ExeName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc ExpungeConsoleCommandHistoryA*(ExeName: PCSTR) {.sideEffect, importc, stdcall.}
proc ExpungeConsoleCommandHistoryW*(ExeName: PCWSTR) {.sideEffect, importc, stdcall.}
proc GetConsoleAliasA*(Source: PCSTR, TargetBuffer: PSTR, TargetBufferLength: uint32, ExeName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasExesA*(ExeNameBuffer: PSTR, ExeNameBufferLength: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasExesLengthA*(): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasExesLengthW*(): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasExesW*(ExeNameBuffer: PWSTR, ExeNameBufferLength: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasW*(Source: PCWSTR, TargetBuffer: PWSTR, TargetBufferLength: uint32, ExeName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasesA*(AliasBuffer: PSTR, AliasBufferLength: uint32, ExeName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasesLengthA*(ExeName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasesLengthW*(ExeName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleAliasesW*(AliasBuffer: PWSTR, AliasBufferLength: uint32, ExeName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleCommandHistoryA*(Commands: PSTR, CommandBufferLength: uint32, ExeName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleCommandHistoryLengthA*(ExeName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleCommandHistoryLengthW*(ExeName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleCommandHistoryW*(Commands: PWSTR, CommandBufferLength: uint32, ExeName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleDisplayMode*(lpModeFlags: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetConsoleFontSize*(hConsoleOutput: HANDLE, nFont: uint32): COORD {.sideEffect, importc, stdcall.}
proc GetConsoleHistoryInfo*(lpConsoleHistoryInfo: ptr CONSOLE_HISTORY_INFO): BOOL {.sideEffect, importc, stdcall.}
proc GetConsoleProcessList*(lpdwProcessList: ptr uint32, dwProcessCount: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetConsoleSelectionInfo*(lpConsoleSelectionInfo: ptr CONSOLE_SELECTION_INFO): BOOL {.sideEffect, importc, stdcall.}
proc GetConsoleWindow*(): HWND {.sideEffect, importc, stdcall.}
proc GetCurrentConsoleFont*(hConsoleOutput: HANDLE, bMaximumWindow: BOOL, lpConsoleCurrentFont: ptr CONSOLE_FONT_INFO): BOOL {.sideEffect, importc, stdcall.}
proc GetCurrentConsoleFontEx*(hConsoleOutput: HANDLE, bMaximumWindow: BOOL, lpConsoleCurrentFontEx: ptr CONSOLE_FONT_INFOEX): BOOL {.sideEffect, importc, stdcall.}
proc GetNumberOfConsoleMouseButtons*(lpNumberOfMouseButtons: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetConsoleDisplayMode*(hConsoleOutput: HANDLE, dwFlags: uint32, lpNewScreenBufferDimensions: ptr COORD): BOOL {.sideEffect, importc, stdcall.}
proc SetConsoleHistoryInfo*(lpConsoleHistoryInfo: ptr CONSOLE_HISTORY_INFO): BOOL {.sideEffect, importc, stdcall.}
proc SetConsoleNumberOfCommandsA*(Number: uint32, ExeName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc SetConsoleNumberOfCommandsW*(Number: uint32, ExeName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc SetCurrentConsoleFontEx*(hConsoleOutput: HANDLE, bMaximumWindow: BOOL, lpConsoleCurrentFontEx: ptr CONSOLE_FONT_INFOEX): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
