# generated by winmd2nim from Windows.Win32.winmd — d2derr (do not edit)

const
  # free constants
  D2DERR_FILE_NOT_FOUND*: int32 = -2147024894'i32
  D2DERR_INSUFFICIENT_BUFFER*: int32 = -2147024774'i32
  D2DERR_UNSUPPORTED_PIXEL_FORMAT*: int32 = -2003292288'i32
  FACILITY_D2D*: int32 = 2201'i32

