# generated by winmd2nim from Windows.Win32.winmd — d3d10shader (do not edit)
import ./[d3d10, winnt, minwindef, d3dcommon]
export d3d10, winnt, minwindef, d3dcommon

type

  # structs
  D3D10_SHADER_BUFFER_DESC* {.completeStruct.} = object
    Name*: PCSTR
    Type*: D3D10_CBUFFER_TYPE
    Variables*: uint32
    Size*: uint32
    uFlags*: uint32
  D3D10_SHADER_DESC* {.completeStruct.} = object
    Version*: uint32
    Creator*: PCSTR
    Flags*: uint32
    ConstantBuffers*: uint32
    BoundResources*: uint32
    InputParameters*: uint32
    OutputParameters*: uint32
    InstructionCount*: uint32
    TempRegisterCount*: uint32
    TempArrayCount*: uint32
    DefCount*: uint32
    DclCount*: uint32
    TextureNormalInstructions*: uint32
    TextureLoadInstructions*: uint32
    TextureCompInstructions*: uint32
    TextureBiasInstructions*: uint32
    TextureGradientInstructions*: uint32
    FloatInstructionCount*: uint32
    IntInstructionCount*: uint32
    UintInstructionCount*: uint32
    StaticFlowControlCount*: uint32
    DynamicFlowControlCount*: uint32
    MacroInstructionCount*: uint32
    ArrayInstructionCount*: uint32
    CutInstructionCount*: uint32
    EmitInstructionCount*: uint32
    GSOutputTopology*: D3D10_PRIMITIVE_TOPOLOGY
    GSMaxOutputVertexCount*: uint32
  D3D10_SHADER_INPUT_BIND_DESC* {.completeStruct.} = object
    Name*: PCSTR
    Type*: D3D10_SHADER_INPUT_TYPE
    BindPoint*: uint32
    BindCount*: uint32
    uFlags*: uint32
    ReturnType*: D3D10_RESOURCE_RETURN_TYPE
    Dimension*: D3D10_SRV_DIMENSION
    NumSamples*: uint32
  D3D10_SHADER_TYPE_DESC* {.completeStruct.} = object
    Class*: D3D10_SHADER_VARIABLE_CLASS
    Type*: D3D10_SHADER_VARIABLE_TYPE
    Rows*: uint32
    Columns*: uint32
    Elements*: uint32
    Members*: uint32
    Offset*: uint32
  D3D10_SHADER_VARIABLE_DESC* {.completeStruct.} = object
    Name*: PCSTR
    StartOffset*: uint32
    Size*: uint32
    uFlags*: uint32
    DefaultValue*: pointer
  D3D10_SIGNATURE_PARAMETER_DESC* {.completeStruct.} = object
    SemanticName*: PCSTR
    SemanticIndex*: uint32
    Register*: uint32
    SystemValueType*: D3D10_NAME
    ComponentType*: D3D10_REGISTER_COMPONENT_TYPE
    Mask*: uint8
    ReadWriteMask*: uint8

  # typdefs
  D3D10_CBUFFER_TYPE* = distinct D3D_CBUFFER_TYPE
  D3D10_INCLUDE_TYPE* = distinct D3D_INCLUDE_TYPE
  D3D10_NAME* = distinct D3D_NAME
  D3D10_REGISTER_COMPONENT_TYPE* = distinct D3D_REGISTER_COMPONENT_TYPE
  D3D10_RESOURCE_RETURN_TYPE* = distinct D3D_RESOURCE_RETURN_TYPE
  D3D10_SHADER_CBUFFER_FLAGS* = distinct D3D_SHADER_CBUFFER_FLAGS
  D3D10_SHADER_INPUT_FLAGS* = distinct D3D_SHADER_INPUT_FLAGS
  D3D10_SHADER_INPUT_TYPE* = distinct D3D_SHADER_INPUT_TYPE
  D3D10_SHADER_MACRO* = D3D_SHADER_MACRO
  D3D10_SHADER_VARIABLE_CLASS* = distinct D3D_SHADER_VARIABLE_CLASS
  D3D10_SHADER_VARIABLE_FLAGS* = distinct D3D_SHADER_VARIABLE_FLAGS
  D3D10_SHADER_VARIABLE_TYPE* = distinct D3D_SHADER_VARIABLE_TYPE
  LPD3D10_CBUFFER_TYPE* = ptr D3D10_CBUFFER_TYPE
  LPD3D10_SHADER_CBUFFER_FLAGS* = ptr D3D10_SHADER_CBUFFER_FLAGS
  LPD3D10_SHADER_INPUT_FLAGS* = ptr D3D10_SHADER_INPUT_FLAGS
  LPD3D10_SHADER_INPUT_TYPE* = ptr D3D10_SHADER_INPUT_TYPE
  LPD3D10_SHADER_MACRO* = ptr D3D10_SHADER_MACRO
  LPD3D10_SHADER_VARIABLE_CLASS* = ptr D3D10_SHADER_VARIABLE_CLASS
  LPD3D10_SHADER_VARIABLE_FLAGS* = ptr D3D10_SHADER_VARIABLE_FLAGS
  LPD3D10_SHADER_VARIABLE_TYPE* = ptr D3D10_SHADER_VARIABLE_TYPE

  # interfaces
  ID3D10ShaderReflection* = distinct object
  ID3D10ShaderReflectionConstantBuffer* = distinct object
  ID3D10ShaderReflectionType* = distinct object
  ID3D10ShaderReflectionVariable* = distinct object

const
  # free constants
  D3D10_ALL_RESOURCES_BOUND*: int32 = 2097152'i32
  D3D10_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES*: int32 = 1048576'i32
  D3D10_SHADER_AVOID_FLOW_CONTROL*: int32 = 512'i32
  D3D10_SHADER_DEBUG*: int32 = 1'i32
  D3D10_SHADER_DEBUG_NAME_FOR_BINARY*: int32 = 8388608'i32
  D3D10_SHADER_DEBUG_NAME_FOR_SOURCE*: int32 = 4194304'i32
  D3D10_SHADER_ENABLE_BACKWARDS_COMPATIBILITY*: int32 = 4096'i32
  D3D10_SHADER_ENABLE_STRICTNESS*: int32 = 2048'i32
  D3D10_SHADER_FLAGS2_FORCE_ROOT_SIGNATURE_1_0*: int32 = 16'i32
  D3D10_SHADER_FLAGS2_FORCE_ROOT_SIGNATURE_1_1*: int32 = 32'i32
  D3D10_SHADER_FLAGS2_FORCE_ROOT_SIGNATURE_LATEST*: int32 = 0'i32
  D3D10_SHADER_FORCE_PS_SOFTWARE_NO_OPT*: int32 = 128'i32
  D3D10_SHADER_FORCE_VS_SOFTWARE_NO_OPT*: int32 = 64'i32
  D3D10_SHADER_IEEE_STRICTNESS*: int32 = 8192'i32
  D3D10_SHADER_NO_PRESHADER*: int32 = 256'i32
  D3D10_SHADER_OPTIMIZATION_LEVEL0*: int32 = 16384'i32
  D3D10_SHADER_OPTIMIZATION_LEVEL1*: int32 = 0'i32
  D3D10_SHADER_OPTIMIZATION_LEVEL2*: int32 = 49152'i32
  D3D10_SHADER_OPTIMIZATION_LEVEL3*: int32 = 32768'i32
  D3D10_SHADER_PACK_MATRIX_COLUMN_MAJOR*: int32 = 16'i32
  D3D10_SHADER_PACK_MATRIX_ROW_MAJOR*: int32 = 8'i32
  D3D10_SHADER_PARTIAL_PRECISION*: int32 = 32'i32
  D3D10_SHADER_PREFER_FLOW_CONTROL*: int32 = 1024'i32
  D3D10_SHADER_RESOURCES_MAY_ALIAS*: int32 = 524288'i32
  D3D10_SHADER_SKIP_OPTIMIZATION*: int32 = 4'i32
  D3D10_SHADER_SKIP_VALIDATION*: int32 = 2'i32
  D3D10_SHADER_WARNINGS_ARE_ERRORS*: int32 = 262144'i32

{.push dynlib: "d3d10".}
proc D3D10CompileShader*(pSrcData: PCSTR, SrcDataSize: uint, pFileName: PCSTR, pDefines: ptr D3D10_SHADER_MACRO, pInclude: ID3DInclude, pFunctionName: PCSTR, pProfile: PCSTR, Flags: uint32, ppShader: ptr ID3D10Blob, ppErrorMsgs: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10DisassembleShader*(pShader: pointer, BytecodeLength: uint, EnableColorCode: BOOL, pComments: PCSTR, ppDisassembly: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10GetGeometryShaderProfile*(pDevice: ID3D10Device): PCSTR {.sideEffect, importc, stdcall.}
proc D3D10GetInputAndOutputSignatureBlob*(pShaderBytecode: pointer, BytecodeLength: uint, ppSignatureBlob: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10GetInputSignatureBlob*(pShaderBytecode: pointer, BytecodeLength: uint, ppSignatureBlob: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10GetOutputSignatureBlob*(pShaderBytecode: pointer, BytecodeLength: uint, ppSignatureBlob: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10GetPixelShaderProfile*(pDevice: ID3D10Device): PCSTR {.sideEffect, importc, stdcall.}
proc D3D10GetShaderDebugInfo*(pShaderBytecode: pointer, BytecodeLength: uint, ppDebugInfo: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10GetVertexShaderProfile*(pDevice: ID3D10Device): PCSTR {.sideEffect, importc, stdcall.}
proc D3D10PreprocessShader*(pSrcData: PCSTR, SrcDataSize: uint, pFileName: PCSTR, pDefines: ptr D3D10_SHADER_MACRO, pInclude: ID3DInclude, ppShaderText: ptr ID3D10Blob, ppErrorMsgs: ptr ID3D10Blob): HRESULT {.sideEffect, importc, stdcall.}
proc D3D10ReflectShader*(pShaderBytecode: pointer, BytecodeLength: uint, ppReflector: ptr ID3D10ShaderReflection): HRESULT {.sideEffect, importc, stdcall.}
{.pop.}
