# generated by winmd2nim from Windows.Win32.winmd — d3d10_1shader (do not edit)
import ./[d3d10shader, minwindef]
export d3d10shader, minwindef

type

  # structs
  D3D10_SHADER_DEBUG_FILE_INFO* {.completeStruct.} = object
    FileName*: uint32
    FileNameLen*: uint32
    FileData*: uint32
    FileLen*: uint32
  D3D10_SHADER_DEBUG_INFO* {.completeStruct.} = object
    Size*: uint32
    Creator*: uint32
    EntrypointName*: uint32
    ShaderTarget*: uint32
    CompileFlags*: uint32
    Files*: uint32
    FileInfo*: uint32
    Instructions*: uint32
    InstructionInfo*: uint32
    Variables*: uint32
    VariableInfo*: uint32
    InputVariables*: uint32
    InputVariableInfo*: uint32
    Tokens*: uint32
    TokenInfo*: uint32
    Scopes*: uint32
    ScopeInfo*: uint32
    ScopeVariables*: uint32
    ScopeVariableInfo*: uint32
    UintOffset*: uint32
    StringOffset*: uint32
  D3D10_SHADER_DEBUG_INPUT_INFO* {.completeStruct.} = object
    Var*: uint32
    InitialRegisterSet*: D3D10_SHADER_DEBUG_REGTYPE
    InitialBank*: uint32
    InitialRegister*: uint32
    InitialComponent*: uint32
    InitialValue*: uint32
  D3D10_SHADER_DEBUG_INST_INFO* {.completeStruct.} = object
    Id*: uint32
    Opcode*: uint32
    uOutputs*: uint32
    pOutputs*: array[2, D3D10_SHADER_DEBUG_OUTPUTREG_INFO]
    TokenId*: uint32
    NestingLevel*: uint32
    Scopes*: uint32
    ScopeInfo*: uint32
    AccessedVars*: uint32
    AccessedVarsInfo*: uint32
  D3D10_SHADER_DEBUG_OUTPUTREG_INFO* {.completeStruct.} = object
    OutputRegisterSet*: D3D10_SHADER_DEBUG_REGTYPE
    OutputReg*: uint32
    TempArrayReg*: uint32
    OutputComponents*: array[4, uint32]
    OutputVars*: array[4, D3D10_SHADER_DEBUG_OUTPUTVAR]
    IndexReg*: uint32
    IndexComp*: uint32
  D3D10_SHADER_DEBUG_OUTPUTVAR* {.completeStruct.} = object
    Var*: uint32
    uValueMin*: uint32
    uValueMax*: uint32
    iValueMin*: int32
    iValueMax*: int32
    fValueMin*: float32
    fValueMax*: float32
    bNaNPossible*: BOOL
    bInfPossible*: BOOL
  D3D10_SHADER_DEBUG_SCOPEVAR_INFO* {.completeStruct.} = object
    TokenId*: uint32
    VarType*: D3D10_SHADER_DEBUG_VARTYPE
    Class*: D3D10_SHADER_VARIABLE_CLASS
    Rows*: uint32
    Columns*: uint32
    StructMemberScope*: uint32
    uArrayIndices*: uint32
    ArrayElements*: uint32
    ArrayStrides*: uint32
    uVariables*: uint32
    uFirstVariable*: uint32
  D3D10_SHADER_DEBUG_SCOPE_INFO* {.completeStruct.} = object
    ScopeType*: D3D10_SHADER_DEBUG_SCOPETYPE
    Name*: uint32
    uNameLen*: uint32
    uVariables*: uint32
    VariableData*: uint32
  D3D10_SHADER_DEBUG_TOKEN_INFO* {.completeStruct.} = object
    File*: uint32
    Line*: uint32
    Column*: uint32
    TokenLength*: uint32
    TokenId*: uint32
  D3D10_SHADER_DEBUG_VAR_INFO* {.completeStruct.} = object
    TokenId*: uint32
    Type*: D3D10_SHADER_VARIABLE_TYPE
    Register*: uint32
    Component*: uint32
    ScopeVar*: uint32
    ScopeVarOffset*: uint32

  # unscoped enums 
  D3D10_SHADER_DEBUG_REGTYPE* = int32
  D3D10_SHADER_DEBUG_SCOPETYPE* = int32
  D3D10_SHADER_DEBUG_VARTYPE* = int32

  # interfaces
  ID3D10ShaderReflection1* = distinct object

const
  # unscoped enum members
  D3D10_SHADER_DEBUG_REG_INPUT*: D3D10_SHADER_DEBUG_REGTYPE = 0'i32
  D3D10_SHADER_DEBUG_REG_OUTPUT*: D3D10_SHADER_DEBUG_REGTYPE = 1'i32
  D3D10_SHADER_DEBUG_REG_CBUFFER*: D3D10_SHADER_DEBUG_REGTYPE = 2'i32
  D3D10_SHADER_DEBUG_REG_TBUFFER*: D3D10_SHADER_DEBUG_REGTYPE = 3'i32
  D3D10_SHADER_DEBUG_REG_TEMP*: D3D10_SHADER_DEBUG_REGTYPE = 4'i32
  D3D10_SHADER_DEBUG_REG_TEMPARRAY*: D3D10_SHADER_DEBUG_REGTYPE = 5'i32
  D3D10_SHADER_DEBUG_REG_TEXTURE*: D3D10_SHADER_DEBUG_REGTYPE = 6'i32
  D3D10_SHADER_DEBUG_REG_SAMPLER*: D3D10_SHADER_DEBUG_REGTYPE = 7'i32
  D3D10_SHADER_DEBUG_REG_IMMEDIATECBUFFER*: D3D10_SHADER_DEBUG_REGTYPE = 8'i32
  D3D10_SHADER_DEBUG_REG_LITERAL*: D3D10_SHADER_DEBUG_REGTYPE = 9'i32
  D3D10_SHADER_DEBUG_REG_UNUSED*: D3D10_SHADER_DEBUG_REGTYPE = 10'i32
  D3D11_SHADER_DEBUG_REG_INTERFACE_POINTERS*: D3D10_SHADER_DEBUG_REGTYPE = 11'i32
  D3D11_SHADER_DEBUG_REG_UAV*: D3D10_SHADER_DEBUG_REGTYPE = 12'i32
  D3D10_SHADER_DEBUG_REG_FORCE_DWORD*: D3D10_SHADER_DEBUG_REGTYPE = 2147483647'i32
  D3D10_SHADER_DEBUG_SCOPE_GLOBAL*: D3D10_SHADER_DEBUG_SCOPETYPE = 0'i32
  D3D10_SHADER_DEBUG_SCOPE_BLOCK*: D3D10_SHADER_DEBUG_SCOPETYPE = 1'i32
  D3D10_SHADER_DEBUG_SCOPE_FORLOOP*: D3D10_SHADER_DEBUG_SCOPETYPE = 2'i32
  D3D10_SHADER_DEBUG_SCOPE_STRUCT*: D3D10_SHADER_DEBUG_SCOPETYPE = 3'i32
  D3D10_SHADER_DEBUG_SCOPE_FUNC_PARAMS*: D3D10_SHADER_DEBUG_SCOPETYPE = 4'i32
  D3D10_SHADER_DEBUG_SCOPE_STATEBLOCK*: D3D10_SHADER_DEBUG_SCOPETYPE = 5'i32
  D3D10_SHADER_DEBUG_SCOPE_NAMESPACE*: D3D10_SHADER_DEBUG_SCOPETYPE = 6'i32
  D3D10_SHADER_DEBUG_SCOPE_ANNOTATION*: D3D10_SHADER_DEBUG_SCOPETYPE = 7'i32
  D3D10_SHADER_DEBUG_SCOPE_FORCE_DWORD*: D3D10_SHADER_DEBUG_SCOPETYPE = 2147483647'i32
  D3D10_SHADER_DEBUG_VAR_VARIABLE*: D3D10_SHADER_DEBUG_VARTYPE = 0'i32
  D3D10_SHADER_DEBUG_VAR_FUNCTION*: D3D10_SHADER_DEBUG_VARTYPE = 1'i32
  D3D10_SHADER_DEBUG_VAR_FORCE_DWORD*: D3D10_SHADER_DEBUG_VARTYPE = 2147483647'i32

