# generated by winmd2nim from Windows.Win32.winmd — debugapi (do not edit)
import ./[winnt, minwindef, minwinbase]
export winnt, minwindef, minwinbase

{.push dynlib: "kernel32".}
proc CheckRemoteDebuggerPresent*(hProcess: HANDLE, pbDebuggerPresent: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc ContinueDebugEvent*(dwProcessId: uint32, dwThreadId: uint32, dwContinueStatus: uint32): BOOL {.sideEffect, importc, stdcall.}
proc DebugActiveProcess*(dwProcessId: uint32): BOOL {.sideEffect, importc, stdcall.}
proc DebugActiveProcessStop*(dwProcessId: uint32): BOOL {.sideEffect, importc, stdcall.}
proc DebugBreak*() {.sideEffect, importc, stdcall.}
proc IsDebuggerPresent*(): BOOL {.sideEffect, importc, stdcall.}
proc OutputDebugStringA*(lpOutputString: PCSTR) {.sideEffect, importc, stdcall.}
proc OutputDebugStringW*(lpOutputString: PCWSTR) {.sideEffect, importc, stdcall.}
proc WaitForDebugEvent*(lpDebugEvent: ptr DEBUG_EVENT, dwMilliseconds: uint32): BOOL {.sideEffect, importc, stdcall.}
proc WaitForDebugEventEx*(lpDebugEvent: ptr DEBUG_EVENT, dwMilliseconds: uint32): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
