# generated by winmd2nim from Windows.Win32.winmd — dsparse (do not edit)
import ./[winnt, minwindef, guiddef]
export winnt, minwindef, guiddef

type

  # unscoped enums 
  DS_MANGLE_FOR* = int32

const
  # unscoped enum members
  DS_MANGLE_UNKNOWN*: DS_MANGLE_FOR = 0'i32
  DS_MANGLE_OBJECT_RDN_FOR_DELETION*: DS_MANGLE_FOR = 1'i32
  DS_MANGLE_OBJECT_RDN_FOR_NAME_CONFLICT*: DS_MANGLE_FOR = 2'i32

{.push dynlib: "ntdsapi".}
proc DsCrackSpn2A*(pszSpn: PCSTR, cSpn: uint32, pcServiceClass: ptr uint32, ServiceClass: PSTR, pcServiceName: ptr uint32, ServiceName: PSTR, pcInstanceName: ptr uint32, InstanceName: PSTR, pInstancePort: ptr uint16): uint32 {.sideEffect, importc, stdcall.}
proc DsCrackSpn2W*(pszSpn: PCWSTR, cSpn: uint32, pcServiceClass: ptr uint32, ServiceClass: PWSTR, pcServiceName: ptr uint32, ServiceName: PWSTR, pcInstanceName: ptr uint32, InstanceName: PWSTR, pInstancePort: ptr uint16): uint32 {.sideEffect, importc, stdcall.}
proc DsCrackSpn3W*(pszSpn: PCWSTR, cSpn: uint32, pcHostName: ptr uint32, HostName: PWSTR, pcInstanceName: ptr uint32, InstanceName: PWSTR, pPortNumber: ptr uint16, pcDomainName: ptr uint32, DomainName: PWSTR, pcRealmName: ptr uint32, RealmName: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc DsCrackSpn4W*(pszSpn: PCWSTR, cSpn: uint32, pcHostName: ptr uint32, HostName: PWSTR, pcInstanceName: ptr uint32, InstanceName: PWSTR, pcPortName: ptr uint32, PortName: PWSTR, pcDomainName: ptr uint32, DomainName: PWSTR, pcRealmName: ptr uint32, RealmName: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc DsCrackSpnA*(pszSpn: PCSTR, pcServiceClass: ptr uint32, ServiceClass: PSTR, pcServiceName: ptr uint32, ServiceName: PSTR, pcInstanceName: ptr uint32, InstanceName: PSTR, pInstancePort: ptr uint16): uint32 {.sideEffect, importc, stdcall.}
proc DsCrackSpnW*(pszSpn: PCWSTR, pcServiceClass: ptr uint32, ServiceClass: PWSTR, pcServiceName: ptr uint32, ServiceName: PWSTR, pcInstanceName: ptr uint32, InstanceName: PWSTR, pInstancePort: ptr uint16): uint32 {.sideEffect, importc, stdcall.}
proc DsCrackUnquotedMangledRdnA*(pszRDN: PCSTR, cchRDN: uint32, pGuid: ptr GUID, peDsMangleFor: ptr DS_MANGLE_FOR): BOOL {.sideEffect, importc, stdcall.}
proc DsCrackUnquotedMangledRdnW*(pszRDN: PCWSTR, cchRDN: uint32, pGuid: ptr GUID, peDsMangleFor: ptr DS_MANGLE_FOR): BOOL {.sideEffect, importc, stdcall.}
proc DsGetRdnW*(ppDN: ptr LPCWCH, pcDN: ptr uint32, ppKey: ptr LPCWCH, pcKey: ptr uint32, ppVal: ptr LPCWCH, pcVal: ptr uint32): uint32 {.sideEffect, importc, stdcall.}
proc DsIsMangledDnA*(pszDn: PCSTR, eDsMangleFor: DS_MANGLE_FOR): BOOL {.sideEffect, importc, stdcall.}
proc DsIsMangledDnW*(pszDn: PCWSTR, eDsMangleFor: DS_MANGLE_FOR): BOOL {.sideEffect, importc, stdcall.}
proc DsIsMangledRdnValueA*(pszRdn: PCSTR, cRdn: uint32, eDsMangleForDesired: DS_MANGLE_FOR): BOOL {.sideEffect, importc, stdcall.}
proc DsIsMangledRdnValueW*(pszRdn: PCWSTR, cRdn: uint32, eDsMangleForDesired: DS_MANGLE_FOR): BOOL {.sideEffect, importc, stdcall.}
proc DsMakeSpnA*(ServiceClass: PCSTR, ServiceName: PCSTR, InstanceName: PCSTR, InstancePort: uint16, Referrer: PCSTR, pcSpnLength: ptr uint32, pszSpn: PSTR): uint32 {.sideEffect, importc, stdcall.}
proc DsMakeSpnW*(ServiceClass: PCWSTR, ServiceName: PCWSTR, InstanceName: PCWSTR, InstancePort: uint16, Referrer: PCWSTR, pcSpnLength: ptr uint32, pszSpn: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc DsQuoteRdnValueA*(cUnquotedRdnValueLength: uint32, psUnquotedRdnValue: ptr int8, pcQuotedRdnValueLength: ptr uint32, psQuotedRdnValue: ptr int8): uint32 {.sideEffect, importc, stdcall.}
proc DsQuoteRdnValueW*(cUnquotedRdnValueLength: uint32, psUnquotedRdnValue: ptr uint16, pcQuotedRdnValueLength: ptr uint32, psQuotedRdnValue: ptr uint16): uint32 {.sideEffect, importc, stdcall.}
proc DsUnquoteRdnValueA*(cQuotedRdnValueLength: uint32, psQuotedRdnValue: ptr int8, pcUnquotedRdnValueLength: ptr uint32, psUnquotedRdnValue: ptr int8): uint32 {.sideEffect, importc, stdcall.}
proc DsUnquoteRdnValueW*(cQuotedRdnValueLength: uint32, psQuotedRdnValue: ptr uint16, pcUnquotedRdnValueLength: ptr uint32, psUnquotedRdnValue: ptr uint16): uint32 {.sideEffect, importc, stdcall.}
{.pop.}
