# generated by winmd2nim from Windows.Win32.winmd — dwmapi.dll (do not edit)
import ./[uxtheme, winnt, windef, minwindef, guiddef]
export uxtheme, winnt, windef, minwindef, guiddef

type

  # structs
  DWM_BLURBEHIND* {.completeStruct, packed.} = object
    dwFlags*: uint32
    fEnable*: BOOL
    hRgnBlur*: HRGN
    fTransitionOnMaximized*: BOOL
  DWM_PRESENT_PARAMETERS* {.completeStruct, packed.} = object
    cbSize*: uint32
    fQueue*: BOOL
    cRefreshStart*: DWM_FRAME_COUNT
    cBuffer*: uint32
    fUseSourceRate*: BOOL
    rateSource*: UNSIGNED_RATIO
    cRefreshesPerFrame*: uint32
    eSampling*: DWM_SOURCE_FRAME_SAMPLING
  DWM_THUMBNAIL_PROPERTIES* {.completeStruct, packed.} = object
    dwFlags*: uint32
    rcDestination*: RECT
    rcSource*: RECT
    opacity*: uint8
    fVisible*: BOOL
    fSourceClientAreaOnly*: BOOL
  DWM_TIMING_INFO* {.completeStruct, packed.} = object
    cbSize*: uint32
    rateRefresh*: UNSIGNED_RATIO
    qpcRefreshPeriod*: QPC_TIME
    rateCompose*: UNSIGNED_RATIO
    qpcVBlank*: QPC_TIME
    cRefresh*: DWM_FRAME_COUNT
    cDXRefresh*: uint32
    qpcCompose*: QPC_TIME
    cFrame*: DWM_FRAME_COUNT
    cDXPresent*: uint32
    cRefreshFrame*: DWM_FRAME_COUNT
    cFrameSubmitted*: DWM_FRAME_COUNT
    cDXPresentSubmitted*: uint32
    cFrameConfirmed*: DWM_FRAME_COUNT
    cDXPresentConfirmed*: uint32
    cRefreshConfirmed*: DWM_FRAME_COUNT
    cDXRefreshConfirmed*: uint32
    cFramesLate*: DWM_FRAME_COUNT
    cFramesOutstanding*: uint32
    cFrameDisplayed*: DWM_FRAME_COUNT
    qpcFrameDisplayed*: QPC_TIME
    cRefreshFrameDisplayed*: DWM_FRAME_COUNT
    cFrameComplete*: DWM_FRAME_COUNT
    qpcFrameComplete*: QPC_TIME
    cFramePending*: DWM_FRAME_COUNT
    qpcFramePending*: QPC_TIME
    cFramesDisplayed*: DWM_FRAME_COUNT
    cFramesComplete*: DWM_FRAME_COUNT
    cFramesPending*: DWM_FRAME_COUNT
    cFramesAvailable*: DWM_FRAME_COUNT
    cFramesDropped*: DWM_FRAME_COUNT
    cFramesMissed*: DWM_FRAME_COUNT
    cRefreshNextDisplayed*: DWM_FRAME_COUNT
    cRefreshNextPresented*: DWM_FRAME_COUNT
    cRefreshesDisplayed*: DWM_FRAME_COUNT
    cRefreshesPresented*: DWM_FRAME_COUNT
    cRefreshStarted*: DWM_FRAME_COUNT
    cPixelsReceived*: uint64
    cPixelsDrawn*: uint64
    cBuffersEmpty*: DWM_FRAME_COUNT
  MilMatrix3x2D* {.completeStruct, packed.} = object
    S_11*: float64
    S_12*: float64
    S_21*: float64
    S_22*: float64
    DX*: float64
    DY*: float64
  UNSIGNED_RATIO* {.completeStruct, packed.} = object
    uiNumerator*: uint32
    uiDenominator*: uint32

  # typdefs
  DWM_FRAME_COUNT* = distinct uint64
  HTHUMBNAIL* = HANDLE
  MIL_MATRIX3X2D_2* = MilMatrix3x2D
  PDWM_BLURBEHIND* = ptr DWM_BLURBEHIND
  PDWM_THUMBNAIL_PROPERTIES* = ptr DWM_THUMBNAIL_PROPERTIES
  PHTHUMBNAIL* = ptr HTHUMBNAIL
  QPC_TIME* = distinct uint64

  # unscoped enums 
  DWMFLIP3DWINDOWPOLICY* = int32
  DWMNCRENDERINGPOLICY* = int32
  DWMTRANSITION_OWNEDWINDOW_TARGET* = int32
  DWMWINDOWATTRIBUTE* = int32
  DWM_SHOWCONTACT* = uint32
  DWM_SOURCE_FRAME_SAMPLING* = int32
  DWM_SYSTEMBACKDROP_TYPE* = int32
  DWM_TAB_WINDOW_REQUIREMENTS* = uint32
  DWM_WINDOW_CORNER_PREFERENCE* = int32
  GESTURE_TYPE* = int32

const
  # free constants
  DWMWA_COLOR_DEFAULT*: uint32 = 0xffffffff'u32
  DWMWA_COLOR_NONE*: uint32 = 0xfffffffe'u32
  DWM_BB_BLURREGION*: int32 = 2'i32
  DWM_BB_ENABLE*: int32 = 1'i32
  DWM_BB_TRANSITIONONMAXIMIZED*: int32 = 4'i32
  DWM_CLOAKED_APP*: int32 = 1'i32
  DWM_CLOAKED_INHERITED*: int32 = 4'i32
  DWM_CLOAKED_SHELL*: int32 = 2'i32
  DWM_EC_DISABLECOMPOSITION*: int32 = 0'i32
  DWM_EC_ENABLECOMPOSITION*: int32 = 1'i32
  DWM_FRAME_DURATION_DEFAULT*: int32 = -1'i32
  DWM_SIT_DISPLAYFRAME*: int32 = 1'i32
  DWM_TNP_OPACITY*: int32 = 4'i32
  DWM_TNP_RECTDESTINATION*: int32 = 1'i32
  DWM_TNP_RECTSOURCE*: int32 = 2'i32
  DWM_TNP_SOURCECLIENTAREAONLY*: int32 = 16'i32
  DWM_TNP_VISIBLE*: int32 = 8'i32

  # unscoped enum members
  DWMFLIP3D_DEFAULT*: DWMFLIP3DWINDOWPOLICY = 0'i32
  DWMFLIP3D_EXCLUDEBELOW*: DWMFLIP3DWINDOWPOLICY = 1'i32
  DWMFLIP3D_EXCLUDEABOVE*: DWMFLIP3DWINDOWPOLICY = 2'i32
  DWMFLIP3D_LAST*: DWMFLIP3DWINDOWPOLICY = 3'i32
  DWMNCRP_USEWINDOWSTYLE*: DWMNCRENDERINGPOLICY = 0'i32
  DWMNCRP_DISABLED*: DWMNCRENDERINGPOLICY = 1'i32
  DWMNCRP_ENABLED*: DWMNCRENDERINGPOLICY = 2'i32
  DWMNCRP_LAST*: DWMNCRENDERINGPOLICY = 3'i32
  DWMTRANSITION_OWNEDWINDOW_NULL*: DWMTRANSITION_OWNEDWINDOW_TARGET = -1'i32
  DWMTRANSITION_OWNEDWINDOW_REPOSITION*: DWMTRANSITION_OWNEDWINDOW_TARGET = 0'i32
  DWMWA_NCRENDERING_ENABLED*: DWMWINDOWATTRIBUTE = 1'i32
  DWMWA_NCRENDERING_POLICY*: DWMWINDOWATTRIBUTE = 2'i32
  DWMWA_TRANSITIONS_FORCEDISABLED*: DWMWINDOWATTRIBUTE = 3'i32
  DWMWA_ALLOW_NCPAINT*: DWMWINDOWATTRIBUTE = 4'i32
  DWMWA_CAPTION_BUTTON_BOUNDS*: DWMWINDOWATTRIBUTE = 5'i32
  DWMWA_NONCLIENT_RTL_LAYOUT*: DWMWINDOWATTRIBUTE = 6'i32
  DWMWA_FORCE_ICONIC_REPRESENTATION*: DWMWINDOWATTRIBUTE = 7'i32
  DWMWA_FLIP3D_POLICY*: DWMWINDOWATTRIBUTE = 8'i32
  DWMWA_EXTENDED_FRAME_BOUNDS*: DWMWINDOWATTRIBUTE = 9'i32
  DWMWA_HAS_ICONIC_BITMAP*: DWMWINDOWATTRIBUTE = 10'i32
  DWMWA_DISALLOW_PEEK*: DWMWINDOWATTRIBUTE = 11'i32
  DWMWA_EXCLUDED_FROM_PEEK*: DWMWINDOWATTRIBUTE = 12'i32
  DWMWA_CLOAK*: DWMWINDOWATTRIBUTE = 13'i32
  DWMWA_CLOAKED*: DWMWINDOWATTRIBUTE = 14'i32
  DWMWA_FREEZE_REPRESENTATION*: DWMWINDOWATTRIBUTE = 15'i32
  DWMWA_PASSIVE_UPDATE_MODE*: DWMWINDOWATTRIBUTE = 16'i32
  DWMWA_USE_HOSTBACKDROPBRUSH*: DWMWINDOWATTRIBUTE = 17'i32
  DWMWA_USE_IMMERSIVE_DARK_MODE*: DWMWINDOWATTRIBUTE = 20'i32
  DWMWA_WINDOW_CORNER_PREFERENCE*: DWMWINDOWATTRIBUTE = 33'i32
  DWMWA_BORDER_COLOR*: DWMWINDOWATTRIBUTE = 34'i32
  DWMWA_CAPTION_COLOR*: DWMWINDOWATTRIBUTE = 35'i32
  DWMWA_TEXT_COLOR*: DWMWINDOWATTRIBUTE = 36'i32
  DWMWA_VISIBLE_FRAME_BORDER_THICKNESS*: DWMWINDOWATTRIBUTE = 37'i32
  DWMWA_SYSTEMBACKDROP_TYPE*: DWMWINDOWATTRIBUTE = 38'i32
  DWMWA_REDIRECTIONBITMAP_ALPHA*: DWMWINDOWATTRIBUTE = 39'i32
  DWMWA_BORDER_MARGINS*: DWMWINDOWATTRIBUTE = 40'i32
  DWMWA_LAST*: DWMWINDOWATTRIBUTE = 41'i32
  DWMSC_DOWN*: DWM_SHOWCONTACT = 0x1'u32
  DWMSC_UP*: DWM_SHOWCONTACT = 0x2'u32
  DWMSC_DRAG*: DWM_SHOWCONTACT = 0x4'u32
  DWMSC_HOLD*: DWM_SHOWCONTACT = 0x8'u32
  DWMSC_PENBARREL*: DWM_SHOWCONTACT = 0x10'u32
  DWMSC_NONE*: DWM_SHOWCONTACT = 0x0'u32
  DWMSC_ALL*: DWM_SHOWCONTACT = 0xffffffff'u32
  DWM_SOURCE_FRAME_SAMPLING_POINT*: DWM_SOURCE_FRAME_SAMPLING = 0'i32
  DWM_SOURCE_FRAME_SAMPLING_COVERAGE*: DWM_SOURCE_FRAME_SAMPLING = 1'i32
  DWM_SOURCE_FRAME_SAMPLING_LAST*: DWM_SOURCE_FRAME_SAMPLING = 2'i32
  DWMSBT_AUTO*: DWM_SYSTEMBACKDROP_TYPE = 0'i32
  DWMSBT_NONE*: DWM_SYSTEMBACKDROP_TYPE = 1'i32
  DWMSBT_MAINWINDOW*: DWM_SYSTEMBACKDROP_TYPE = 2'i32
  DWMSBT_TRANSIENTWINDOW*: DWM_SYSTEMBACKDROP_TYPE = 3'i32
  DWMSBT_TABBEDWINDOW*: DWM_SYSTEMBACKDROP_TYPE = 4'i32
  DWMTWR_NONE*: DWM_TAB_WINDOW_REQUIREMENTS = 0x0'u32
  DWMTWR_IMPLEMENTED_BY_SYSTEM*: DWM_TAB_WINDOW_REQUIREMENTS = 0x1'u32
  DWMTWR_WINDOW_RELATIONSHIP*: DWM_TAB_WINDOW_REQUIREMENTS = 0x2'u32
  DWMTWR_WINDOW_STYLES*: DWM_TAB_WINDOW_REQUIREMENTS = 0x4'u32
  DWMTWR_WINDOW_REGION*: DWM_TAB_WINDOW_REQUIREMENTS = 0x8'u32
  DWMTWR_WINDOW_DWM_ATTRIBUTES*: DWM_TAB_WINDOW_REQUIREMENTS = 0x10'u32
  DWMTWR_WINDOW_MARGINS*: DWM_TAB_WINDOW_REQUIREMENTS = 0x20'u32
  DWMTWR_TABBING_ENABLED*: DWM_TAB_WINDOW_REQUIREMENTS = 0x40'u32
  DWMTWR_USER_POLICY*: DWM_TAB_WINDOW_REQUIREMENTS = 0x80'u32
  DWMTWR_GROUP_POLICY*: DWM_TAB_WINDOW_REQUIREMENTS = 0x100'u32
  DWMTWR_APP_COMPAT*: DWM_TAB_WINDOW_REQUIREMENTS = 0x200'u32
  DWMWCP_DEFAULT*: DWM_WINDOW_CORNER_PREFERENCE = 0'i32
  DWMWCP_DONOTROUND*: DWM_WINDOW_CORNER_PREFERENCE = 1'i32
  DWMWCP_ROUND*: DWM_WINDOW_CORNER_PREFERENCE = 2'i32
  DWMWCP_ROUNDSMALL*: DWM_WINDOW_CORNER_PREFERENCE = 3'i32
  GT_PEN_TAP*: GESTURE_TYPE = 0'i32
  GT_PEN_DOUBLETAP*: GESTURE_TYPE = 1'i32
  GT_PEN_RIGHTTAP*: GESTURE_TYPE = 2'i32
  GT_PEN_PRESSANDHOLD*: GESTURE_TYPE = 3'i32
  GT_PEN_PRESSANDHOLDABORT*: GESTURE_TYPE = 4'i32
  GT_TOUCH_TAP*: GESTURE_TYPE = 5'i32
  GT_TOUCH_DOUBLETAP*: GESTURE_TYPE = 6'i32
  GT_TOUCH_RIGHTTAP*: GESTURE_TYPE = 7'i32
  GT_TOUCH_PRESSANDHOLD*: GESTURE_TYPE = 8'i32
  GT_TOUCH_PRESSANDHOLDABORT*: GESTURE_TYPE = 9'i32
  GT_TOUCH_PRESSANDTAP*: GESTURE_TYPE = 10'i32

{.push dynlib: "dwmapi".}
proc DwmAttachMilContent*(hwnd: HWND): HRESULT {.sideEffect, importc, stdcall.}
proc DwmDefWindowProc*(hWnd: HWND, msg: uint32, wParam: WPARAM, lParam: LPARAM, plResult: ptr LRESULT): BOOL {.sideEffect, importc, stdcall.}
proc DwmDetachMilContent*(hwnd: HWND): HRESULT {.sideEffect, importc, stdcall.}
proc DwmEnableBlurBehindWindow*(hWnd: HWND, pBlurBehind: ptr DWM_BLURBEHIND): HRESULT {.sideEffect, importc, stdcall.}
proc DwmEnableComposition*(uCompositionAction: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmEnableMMCSS*(fEnableMMCSS: BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc DwmExtendFrameIntoClientArea*(hWnd: HWND, pMarInset: ptr MARGINS): HRESULT {.sideEffect, importc, stdcall.}
proc DwmFlush*(): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetColorizationColor*(pcrColorization: ptr uint32, pfOpaqueBlend: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetCompositionTimingInfo*(hwnd: HWND, pTimingInfo: ptr DWM_TIMING_INFO): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetGraphicsStreamClient*(uIndex: uint32, pClientUuid: ptr GUID): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetGraphicsStreamTransformHint*(uIndex: uint32, pTransform: ptr MilMatrix3x2D): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetTransportAttributes*(pfIsRemoting: ptr BOOL, pfIsConnected: ptr BOOL, pDwGeneration: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetUnmetTabRequirements*(appWindow: HWND, value: ptr DWM_TAB_WINDOW_REQUIREMENTS): HRESULT {.sideEffect, importc, stdcall.}
proc DwmGetWindowAttribute*(hwnd: HWND, dwAttribute: uint32, pvAttribute: pointer, cbAttribute: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmInvalidateIconicBitmaps*(hwnd: HWND): HRESULT {.sideEffect, importc, stdcall.}
proc DwmIsCompositionEnabled*(pfEnabled: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc DwmModifyPreviousDxFrameDuration*(hwnd: HWND, cRefreshes: int32, fRelative: BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc DwmQueryThumbnailSourceSize*(hThumbnail: HTHUMBNAIL, pSize: ptr SIZE): HRESULT {.sideEffect, importc, stdcall.}
proc DwmRegisterThumbnail*(hwndDestination: HWND, hwndSource: HWND, phThumbnailId: ptr HTHUMBNAIL): HRESULT {.sideEffect, importc, stdcall.}
proc DwmRenderGesture*(gt: GESTURE_TYPE, cContacts: uint32, pdwPointerID: ptr uint32, pPoints: ptr POINT): HRESULT {.sideEffect, importc, stdcall.}
proc DwmSetDxFrameDuration*(hwnd: HWND, cRefreshes: int32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmSetIconicLivePreviewBitmap*(hwnd: HWND, hbmp: HBITMAP, pptClient: ptr POINT, dwSITFlags: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmSetIconicThumbnail*(hwnd: HWND, hbmp: HBITMAP, dwSITFlags: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmSetPresentParameters*(hwnd: HWND, pPresentParams: ptr DWM_PRESENT_PARAMETERS): HRESULT {.sideEffect, importc, stdcall.}
proc DwmSetWindowAttribute*(hwnd: HWND, dwAttribute: uint32, pvAttribute: pointer, cbAttribute: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc DwmShowContact_2*(dwPointerID: uint32, eShowContact: DWM_SHOWCONTACT): HRESULT {.sideEffect, importc: "DwmShowContact", stdcall.}
proc DwmTetherContact*(dwPointerID: uint32, fEnable: BOOL, ptTether: POINT): HRESULT {.sideEffect, importc, stdcall.}
proc DwmTransitionOwnedWindow*(hwnd: HWND, target: DWMTRANSITION_OWNEDWINDOW_TARGET): HRESULT {.sideEffect, importc, stdcall.}
proc DwmUnregisterThumbnail*(hThumbnailId: HTHUMBNAIL): HRESULT {.sideEffect, importc, stdcall.}
proc DwmUpdateThumbnailProperties*(hThumbnailId: HTHUMBNAIL, ptnProperties: ptr DWM_THUMBNAIL_PROPERTIES): HRESULT {.sideEffect, importc, stdcall.}
{.pop.}
