# generated by winmd2nim from Windows.Win32.winmd — enclaveapi (do not edit)
import ./[winnt, minwindef, minwinbase]
export winnt, minwindef, minwinbase

{.push dynlib: "api-ms-win-core-enclave-l1-1-1".}
proc CallEnclave*(lpRoutine: LPENCLAVE_ROUTINE, lpParameter: pointer, fWaitForThread: BOOL, lpReturnValue: ptr pointer): BOOL {.sideEffect, importc, stdcall.}
proc DeleteEnclave*(lpAddress: pointer): BOOL {.sideEffect, importc, stdcall.}
proc LoadEnclaveImageA*(lpEnclaveAddress: pointer, lpImageName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc LoadEnclaveImageW*(lpEnclaveAddress: pointer, lpImageName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc TerminateEnclave*(lpAddress: pointer, fWait: BOOL): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
{.push dynlib: "kernel32".}
proc CreateEnclave*(hProcess: HANDLE, lpAddress: pointer, dwSize: uint, dwInitialCommitment: uint, flEnclaveType: uint32, lpEnclaveInformation: pointer, dwInfoLength: uint32, lpEnclaveError: ptr uint32): pointer {.sideEffect, importc, stdcall.}
proc InitializeEnclave*(hProcess: HANDLE, lpAddress: pointer, lpEnclaveInformation: pointer, dwInfoLength: uint32, lpEnclaveError: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc IsEnclaveTypeSupported*(flEnclaveType: uint32): BOOL {.sideEffect, importc, stdcall.}
proc LoadEnclaveData*(hProcess: HANDLE, lpAddress: pointer, lpBuffer: pointer, nSize: uint, flProtect: uint32, lpPageInformation: pointer, dwInfoLength: uint32, lpNumberOfBytesWritten: ptr uint, lpEnclaveError: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
