# generated by winmd2nim from Windows.Win32.winmd — exdisp (do not edit)

type

  # unscoped enums 
  BrowserNavConstants* = int32
  CommandStateChangeConstants* = int32
  NewProcessCauseConstants* = int32
  RefreshConstants* = int32
  SecureLockIconConstants* = int32
  ShellWindowFindWindowOptions* = int32
  ShellWindowTypeConstants* = int32

  # interfaces
  DShellNameSpaceEvents* = distinct object
  DShellWindowsEvents* = distinct object
  DWebBrowserEvents* = distinct object
  DWebBrowserEvents2* = distinct object
  IScriptErrorList* = distinct object
  IShellFavoritesNameSpace* = distinct object
  IShellNameSpace* = distinct object
  IShellUIHelper* = distinct object
  IShellUIHelper2* = distinct object
  IShellUIHelper3* = distinct object
  IShellUIHelper4* = distinct object
  IShellUIHelper5* = distinct object
  IShellUIHelper6* = distinct object
  IShellUIHelper7* = distinct object
  IShellUIHelper8* = distinct object
  IShellUIHelper9* = distinct object
  IShellWindows* = distinct object
  IWebBrowser* = distinct object
  IWebBrowser2* = distinct object
  IWebBrowserApp* = distinct object

const
  # free constants
  navCheckDontShowHVSINeedHost*: int32 = -2147483648'i32
  navCheckDontShowNeedHVSI*: int32 = 1073741824'i32
  navCheckDontShowNeedIE*: int32 = 536870912'i32
  navDisableDownloadSave*: int32 = 67108864'i32
  navServerRedirectedVtabSwitch*: int32 = 134217728'i32
  navUserInitiatedAction*: int32 = 4194304'i32
  navVtabSwitchNotUserInitiatedAction*: int32 = 268435456'i32

  # unscoped enum members
  navOpenInNewWindow*: BrowserNavConstants = 1'i32
  navNoHistory*: BrowserNavConstants = 2'i32
  navNoReadFromCache*: BrowserNavConstants = 4'i32
  navNoWriteToCache*: BrowserNavConstants = 8'i32
  navAllowAutosearch*: BrowserNavConstants = 16'i32
  navBrowserBar*: BrowserNavConstants = 32'i32
  navHyperlink*: BrowserNavConstants = 64'i32
  navEnforceRestricted*: BrowserNavConstants = 128'i32
  navNewWindowsManaged*: BrowserNavConstants = 256'i32
  navUntrustedForDownload*: BrowserNavConstants = 512'i32
  navTrustedForActiveX*: BrowserNavConstants = 1024'i32
  navOpenInNewTab*: BrowserNavConstants = 2048'i32
  navOpenInBackgroundTab*: BrowserNavConstants = 4096'i32
  navKeepWordWheelText*: BrowserNavConstants = 8192'i32
  navVirtualTab*: BrowserNavConstants = 16384'i32
  navBlockRedirectsXDomain*: BrowserNavConstants = 32768'i32
  navOpenNewForegroundTab*: BrowserNavConstants = 65536'i32
  navTravelLogScreenshot*: BrowserNavConstants = 131072'i32
  navDeferUnload*: BrowserNavConstants = 262144'i32
  navSpeculative*: BrowserNavConstants = 524288'i32
  navSuggestNewWindow*: BrowserNavConstants = 1048576'i32
  navSuggestNewTab*: BrowserNavConstants = 2097152'i32
  navReserved1*: BrowserNavConstants = 4194304'i32
  navHomepageNavigate*: BrowserNavConstants = 8388608'i32
  navRefresh*: BrowserNavConstants = 16777216'i32
  navHostNavigation*: BrowserNavConstants = 33554432'i32
  navReserved2*: BrowserNavConstants = 67108864'i32
  navReserved3*: BrowserNavConstants = 134217728'i32
  navReserved4*: BrowserNavConstants = 268435456'i32
  navReserved5*: BrowserNavConstants = 536870912'i32
  navReserved6*: BrowserNavConstants = 1073741824'i32
  navReserved7*: BrowserNavConstants = -2147483648'i32
  CSC_UPDATECOMMANDS*: CommandStateChangeConstants = -1'i32
  CSC_NAVIGATEFORWARD*: CommandStateChangeConstants = 1'i32
  CSC_NAVIGATEBACK*: CommandStateChangeConstants = 2'i32
  ProtectedModeRedirect*: NewProcessCauseConstants = 1'i32
  REFRESH_NORMAL*: RefreshConstants = 0'i32
  REFRESH_IFEXPIRED*: RefreshConstants = 1'i32
  REFRESH_COMPLETELY*: RefreshConstants = 3'i32
  secureLockIconUnsecure*: SecureLockIconConstants = 0'i32
  secureLockIconMixed*: SecureLockIconConstants = 1'i32
  secureLockIconSecureUnknownBits*: SecureLockIconConstants = 2'i32
  secureLockIconSecure40Bit*: SecureLockIconConstants = 3'i32
  secureLockIconSecure56Bit*: SecureLockIconConstants = 4'i32
  secureLockIconSecureFortezza*: SecureLockIconConstants = 5'i32
  secureLockIconSecure128Bit*: SecureLockIconConstants = 6'i32
  SWFO_NEEDDISPATCH*: ShellWindowFindWindowOptions = 1'i32
  SWFO_INCLUDEPENDING*: ShellWindowFindWindowOptions = 2'i32
  SWFO_COOKIEPASSED*: ShellWindowFindWindowOptions = 4'i32
  SWC_EXPLORER*: ShellWindowTypeConstants = 0'i32
  SWC_BROWSER*: ShellWindowTypeConstants = 1'i32
  SWC_3RDPARTY*: ShellWindowTypeConstants = 2'i32
  SWC_CALLBACK*: ShellWindowTypeConstants = 4'i32
  SWC_DESKTOP*: ShellWindowTypeConstants = 8'i32

