# generated by winmd2nim from Windows.Win32.winmd — fileapi (do not edit)
import ./[winnt, minwindef, minwinbase]
export winnt, minwindef, minwinbase

type

  # structs
  BY_HANDLE_FILE_INFORMATION* {.completeStruct.} = object
    dwFileAttributes*: uint32
    ftCreationTime*: FILETIME
    ftLastAccessTime*: FILETIME
    ftLastWriteTime*: FILETIME
    dwVolumeSerialNumber*: uint32
    nFileSizeHigh*: uint32
    nFileSizeLow*: uint32
    nNumberOfLinks*: uint32
    nFileIndexHigh*: uint32
    nFileIndexLow*: uint32
  CREATEFILE2_EXTENDED_PARAMETERS* {.completeStruct.} = object
    dwSize*: uint32
    dwFileAttributes*: uint32
    dwFileFlags*: uint32
    dwSecurityQosFlags*: uint32
    lpSecurityAttributes*: LPSECURITY_ATTRIBUTES
    hTemplateFile*: HANDLE
  CREATEFILE3_EXTENDED_PARAMETERS* {.completeStruct.} = object
    dwSize*: uint32
    dwFileAttributes*: uint32
    dwFileFlags*: uint32
    dwSecurityQosFlags*: uint32
    lpSecurityAttributes*: LPSECURITY_ATTRIBUTES
    hTemplateFile*: HANDLE
  DISK_SPACE_INFORMATION* {.completeStruct.} = object
    ActualTotalAllocationUnits*: uint64
    ActualAvailableAllocationUnits*: uint64
    ActualPoolUnavailableAllocationUnits*: uint64
    CallerTotalAllocationUnits*: uint64
    CallerAvailableAllocationUnits*: uint64
    CallerPoolUnavailableAllocationUnits*: uint64
    UsedAllocationUnits*: uint64
    TotalReservedAllocationUnits*: uint64
    VolumeStorageReserveAllocationUnits*: uint64
    AvailableCommittedAllocationUnits*: uint64
    PoolAvailableAllocationUnits*: uint64
    SectorsPerAllocationUnit*: uint32
    BytesPerSector*: uint32
  WIN32_FILE_ATTRIBUTE_DATA* {.completeStruct.} = object
    dwFileAttributes*: uint32
    ftCreationTime*: FILETIME
    ftLastAccessTime*: FILETIME
    ftLastWriteTime*: FILETIME
    nFileSizeHigh*: uint32
    nFileSizeLow*: uint32
  WIN32_FIND_STREAM_DATA* {.completeStruct.} = object
    StreamSize*: int64
    cStreamName*: array[296, uint16]

  # typdefs
  LPBY_HANDLE_FILE_INFORMATION* = ptr BY_HANDLE_FILE_INFORMATION
  LPCREATEFILE2_EXTENDED_PARAMETERS* = ptr CREATEFILE2_EXTENDED_PARAMETERS
  LPCREATEFILE3_EXTENDED_PARAMETERS* = ptr CREATEFILE3_EXTENDED_PARAMETERS
  LPWIN32_FILE_ATTRIBUTE_DATA* = ptr WIN32_FILE_ATTRIBUTE_DATA
  PBY_HANDLE_FILE_INFORMATION* = ptr BY_HANDLE_FILE_INFORMATION
  PCREATEFILE2_EXTENDED_PARAMETERS* = ptr CREATEFILE2_EXTENDED_PARAMETERS
  PCREATEFILE3_EXTENDED_PARAMETERS* = ptr CREATEFILE3_EXTENDED_PARAMETERS
  PWIN32_FIND_STREAM_DATA* = ptr WIN32_FIND_STREAM_DATA

  # unscoped enums 
  DIRECTORY_FLAGS* = uint32
  STREAM_INFO_LEVELS* = int32

const
  # free constants
  CREATE_ALWAYS*: int32 = 2'i32
  CREATE_NEW*: int32 = 1'i32
  INVALID_FILE_ATTRIBUTES*: uint32 = 0xffffffff'u32
  INVALID_FILE_SIZE*: uint32 = 0xffffffff'u32
  INVALID_SET_FILE_POINTER*: uint32 = 0xffffffff'u32
  OPEN_ALWAYS*: int32 = 4'i32
  OPEN_EXISTING*: int32 = 3'i32
  TRUNCATE_EXISTING*: int32 = 5'i32

  # unscoped enum members
  DIRECTORY_FLAGS_NONE*: DIRECTORY_FLAGS = 0x0'u32
  DIRECTORY_FLAGS_DISALLOW_PATH_REDIRECTS*: DIRECTORY_FLAGS = 0x1'u32
  FindStreamInfoStandard*: STREAM_INFO_LEVELS = 0'i32
  FindStreamInfoMaxInfoLevel*: STREAM_INFO_LEVELS = 1'i32

{.push dynlib: "kernel32".}
proc AreFileApisANSI*(): BOOL {.sideEffect, importc, stdcall.}
proc AreShortNamesEnabled*(Handle: HANDLE, Enabled: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc CompareFileTime*(lpFileTime1: ptr FILETIME, lpFileTime2: ptr FILETIME): int32 {.sideEffect, importc, stdcall.}
proc CreateDirectory2A*(lpPathName: PCSTR, dwDesiredAccess: uint32, dwShareMode: uint32, DirectoryFlags: DIRECTORY_FLAGS, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES): HANDLE {.sideEffect, importc, stdcall.}
proc CreateDirectory2W*(lpPathName: PCWSTR, dwDesiredAccess: uint32, dwShareMode: uint32, DirectoryFlags: DIRECTORY_FLAGS, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES): HANDLE {.sideEffect, importc, stdcall.}
proc CreateDirectoryA*(lpPathName: PCSTR, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES): BOOL {.sideEffect, importc, stdcall.}
proc CreateDirectoryW*(lpPathName: PCWSTR, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES): BOOL {.sideEffect, importc, stdcall.}
proc CreateFile2*(lpFileName: PCWSTR, dwDesiredAccess: uint32, dwShareMode: uint32, dwCreationDisposition: uint32, pCreateExParams: ptr CREATEFILE2_EXTENDED_PARAMETERS): HANDLE {.sideEffect, importc, stdcall.}
proc CreateFile3*(lpFileName: PCWSTR, dwDesiredAccess: uint32, dwShareMode: uint32, dwCreationDisposition: uint32, pCreateExParams: ptr CREATEFILE3_EXTENDED_PARAMETERS): HANDLE {.sideEffect, importc, stdcall.}
proc CreateFileA*(lpFileName: PCSTR, dwDesiredAccess: uint32, dwShareMode: uint32, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, dwCreationDisposition: uint32, dwFlagsAndAttributes: uint32, hTemplateFile: HANDLE): HANDLE {.sideEffect, importc, stdcall.}
proc CreateFileW*(lpFileName: PCWSTR, dwDesiredAccess: uint32, dwShareMode: uint32, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, dwCreationDisposition: uint32, dwFlagsAndAttributes: uint32, hTemplateFile: HANDLE): HANDLE {.sideEffect, importc, stdcall.}
proc DefineDosDeviceW*(dwFlags: uint32, lpDeviceName: PCWSTR, lpTargetPath: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc DeleteFile2A*(lpFileName: PCSTR, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc DeleteFile2W*(lpFileName: PCWSTR, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc DeleteFileA*(lpFileName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc DeleteFileW*(lpFileName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc DeleteVolumeMountPointW*(lpszVolumeMountPoint: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc FileTimeToLocalFileTime*(lpFileTime: ptr FILETIME, lpLocalFileTime: ptr FILETIME): BOOL {.sideEffect, importc, stdcall.}
proc FindClose*(hFindFile: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc FindCloseChangeNotification*(hChangeHandle: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc FindFirstChangeNotificationA*(lpPathName: PCSTR, bWatchSubtree: BOOL, dwNotifyFilter: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstChangeNotificationW*(lpPathName: PCWSTR, bWatchSubtree: BOOL, dwNotifyFilter: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstFileA*(lpFileName: PCSTR, lpFindFileData: ptr WIN32_FIND_DATAA): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstFileExA*(lpFileName: PCSTR, fInfoLevelId: FINDEX_INFO_LEVELS, lpFindFileData: pointer, fSearchOp: FINDEX_SEARCH_OPS, lpSearchFilter: pointer, dwAdditionalFlags: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstFileExW*(lpFileName: PCWSTR, fInfoLevelId: FINDEX_INFO_LEVELS, lpFindFileData: pointer, fSearchOp: FINDEX_SEARCH_OPS, lpSearchFilter: pointer, dwAdditionalFlags: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstFileNameW*(lpFileName: PCWSTR, dwFlags: uint32, StringLength: ptr uint32, LinkName: PWSTR): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstFileW*(lpFileName: PCWSTR, lpFindFileData: ptr WIN32_FIND_DATAW): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstStreamW*(lpFileName: PCWSTR, InfoLevel: STREAM_INFO_LEVELS, lpFindStreamData: pointer, dwFlags: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc FindFirstVolumeW*(lpszVolumeName: PWSTR, cchBufferLength: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc FindNextChangeNotification*(hChangeHandle: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc FindNextFileA*(hFindFile: HANDLE, lpFindFileData: ptr WIN32_FIND_DATAA): BOOL {.sideEffect, importc, stdcall.}
proc FindNextFileNameW*(hFindStream: HANDLE, StringLength: ptr uint32, LinkName: PWSTR): BOOL {.sideEffect, importc, stdcall.}
proc FindNextFileW*(hFindFile: HANDLE, lpFindFileData: ptr WIN32_FIND_DATAW): BOOL {.sideEffect, importc, stdcall.}
proc FindNextStreamW*(hFindStream: HANDLE, lpFindStreamData: pointer): BOOL {.sideEffect, importc, stdcall.}
proc FindNextVolumeW*(hFindVolume: HANDLE, lpszVolumeName: PWSTR, cchBufferLength: uint32): BOOL {.sideEffect, importc, stdcall.}
proc FindVolumeClose*(hFindVolume: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc FlushFileBuffers*(hFile: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc GetCompressedFileSizeA*(lpFileName: PCSTR, lpFileSizeHigh: ptr uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetCompressedFileSizeW*(lpFileName: PCWSTR, lpFileSizeHigh: ptr uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetDiskFreeSpaceA*(lpRootPathName: PCSTR, lpSectorsPerCluster: ptr uint32, lpBytesPerSector: ptr uint32, lpNumberOfFreeClusters: ptr uint32, lpTotalNumberOfClusters: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetDiskFreeSpaceExA*(lpDirectoryName: PCSTR, lpFreeBytesAvailableToCaller: ptr uint64, lpTotalNumberOfBytes: ptr uint64, lpTotalNumberOfFreeBytes: ptr uint64): BOOL {.sideEffect, importc, stdcall.}
proc GetDiskFreeSpaceExW*(lpDirectoryName: PCWSTR, lpFreeBytesAvailableToCaller: ptr uint64, lpTotalNumberOfBytes: ptr uint64, lpTotalNumberOfFreeBytes: ptr uint64): BOOL {.sideEffect, importc, stdcall.}
proc GetDiskFreeSpaceW*(lpRootPathName: PCWSTR, lpSectorsPerCluster: ptr uint32, lpBytesPerSector: ptr uint32, lpNumberOfFreeClusters: ptr uint32, lpTotalNumberOfClusters: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetDiskSpaceInformationA*(rootPath: PCSTR, diskSpaceInfo: ptr DISK_SPACE_INFORMATION): HRESULT {.sideEffect, importc, stdcall.}
proc GetDiskSpaceInformationW*(rootPath: PCWSTR, diskSpaceInfo: ptr DISK_SPACE_INFORMATION): HRESULT {.sideEffect, importc, stdcall.}
proc GetDriveTypeA*(lpRootPathName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetDriveTypeW*(lpRootPathName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetFileAttributesA*(lpFileName: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetFileAttributesExA*(lpFileName: PCSTR, fInfoLevelId: GET_FILEEX_INFO_LEVELS, lpFileInformation: pointer): BOOL {.sideEffect, importc, stdcall.}
proc GetFileAttributesExW*(lpFileName: PCWSTR, fInfoLevelId: GET_FILEEX_INFO_LEVELS, lpFileInformation: pointer): BOOL {.sideEffect, importc, stdcall.}
proc GetFileAttributesW*(lpFileName: PCWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetFileInformationByHandle*(hFile: HANDLE, lpFileInformation: ptr BY_HANDLE_FILE_INFORMATION): BOOL {.sideEffect, importc, stdcall.}
proc GetFileSizeEx*(hFile: HANDLE, lpFileSize: ptr int64): BOOL {.sideEffect, importc, stdcall.}
proc GetFileType*(hFile: HANDLE): uint32 {.sideEffect, importc, stdcall.}
proc GetFinalPathNameByHandleA*(hFile: HANDLE, lpszFilePath: PSTR, cchFilePath: uint32, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetFinalPathNameByHandleW*(hFile: HANDLE, lpszFilePath: PWSTR, cchFilePath: uint32, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetFullPathNameA*(lpFileName: PCSTR, nBufferLength: uint32, lpBuffer: PSTR, lpFilePart: ptr PSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetFullPathNameW*(lpFileName: PCWSTR, nBufferLength: uint32, lpBuffer: PWSTR, lpFilePart: ptr PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetLogicalDriveStringsW*(nBufferLength: uint32, lpBuffer: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetLogicalDrives*(): uint32 {.sideEffect, importc, stdcall.}
proc GetLongPathNameA*(lpszShortPath: PCSTR, lpszLongPath: PSTR, cchBuffer: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetLongPathNameW*(lpszShortPath: PCWSTR, lpszLongPath: PWSTR, cchBuffer: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetShortPathNameW*(lpszLongPath: PCWSTR, lpszShortPath: PWSTR, cchBuffer: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetTempFileNameA*(lpPathName: PCSTR, lpPrefixString: PCSTR, uUnique: uint32, lpTempFileName: PSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetTempFileNameW*(lpPathName: PCWSTR, lpPrefixString: PCWSTR, uUnique: uint32, lpTempFileName: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetTempPath2A*(BufferLength: uint32, Buffer: PSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetTempPath2W*(BufferLength: uint32, Buffer: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetTempPathA*(nBufferLength: uint32, lpBuffer: PSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetTempPathW*(nBufferLength: uint32, lpBuffer: PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc GetVolumeInformationA*(lpRootPathName: PCSTR, lpVolumeNameBuffer: PSTR, nVolumeNameSize: uint32, lpVolumeSerialNumber: ptr uint32, lpMaximumComponentLength: ptr uint32, lpFileSystemFlags: ptr uint32, lpFileSystemNameBuffer: PSTR, nFileSystemNameSize: uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetVolumeInformationByHandleW*(hFile: HANDLE, lpVolumeNameBuffer: PWSTR, nVolumeNameSize: uint32, lpVolumeSerialNumber: ptr uint32, lpMaximumComponentLength: ptr uint32, lpFileSystemFlags: ptr uint32, lpFileSystemNameBuffer: PWSTR, nFileSystemNameSize: uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetVolumeInformationW*(lpRootPathName: PCWSTR, lpVolumeNameBuffer: PWSTR, nVolumeNameSize: uint32, lpVolumeSerialNumber: ptr uint32, lpMaximumComponentLength: ptr uint32, lpFileSystemFlags: ptr uint32, lpFileSystemNameBuffer: PWSTR, nFileSystemNameSize: uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetVolumeNameForVolumeMountPointW*(lpszVolumeMountPoint: PCWSTR, lpszVolumeName: PWSTR, cchBufferLength: uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetVolumePathNameW*(lpszFileName: PCWSTR, lpszVolumePathName: PWSTR, cchBufferLength: uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetVolumePathNamesForVolumeNameW*(lpszVolumeName: PCWSTR, lpszVolumePathNames: ptr uint16, cchBufferLength: uint32, lpcchReturnLength: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc LocalFileTimeToFileTime*(lpLocalFileTime: ptr FILETIME, lpFileTime: ptr FILETIME): BOOL {.sideEffect, importc, stdcall.}
proc LockFile*(hFile: HANDLE, dwFileOffsetLow: uint32, dwFileOffsetHigh: uint32, nNumberOfBytesToLockLow: uint32, nNumberOfBytesToLockHigh: uint32): BOOL {.sideEffect, importc, stdcall.}
proc LockFileEx*(hFile: HANDLE, dwFlags: uint32, dwReserved: uint32, nNumberOfBytesToLockLow: uint32, nNumberOfBytesToLockHigh: uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc QueryDosDeviceW*(lpDeviceName: PCWSTR, lpTargetPath: PWSTR, ucchMax: uint32): uint32 {.sideEffect, importc, stdcall.}
proc ReadFile*(hFile: HANDLE, lpBuffer: pointer, nNumberOfBytesToRead: uint32, lpNumberOfBytesRead: ptr uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc ReadFileEx*(hFile: HANDLE, lpBuffer: pointer, nNumberOfBytesToRead: uint32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPOVERLAPPED_COMPLETION_ROUTINE): BOOL {.sideEffect, importc, stdcall.}
proc ReadFileScatter*(hFile: HANDLE, aSegmentArray: ptr FILE_SEGMENT_ELEMENT, nNumberOfBytesToRead: uint32, lpReserved: ptr uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc RemoveDirectory2A*(lpPathName: PCSTR, DirectoryFlags: DIRECTORY_FLAGS): BOOL {.sideEffect, importc, stdcall.}
proc RemoveDirectory2W*(lpPathName: PCWSTR, DirectoryFlags: DIRECTORY_FLAGS): BOOL {.sideEffect, importc, stdcall.}
proc RemoveDirectoryA*(lpPathName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc RemoveDirectoryW*(lpPathName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc SetEndOfFile*(hFile: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc SetFileApisToANSI*() {.sideEffect, importc, stdcall.}
proc SetFileApisToOEM*() {.sideEffect, importc, stdcall.}
proc SetFileAttributesA*(lpFileName: PCSTR, dwFileAttributes: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetFileAttributesW*(lpFileName: PCWSTR, dwFileAttributes: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetFileInformationByHandle*(hFile: HANDLE, FileInformationClass: FILE_INFO_BY_HANDLE_CLASS, lpFileInformation: pointer, dwBufferSize: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetFileIoOverlappedRange*(FileHandle: HANDLE, OverlappedRangeStart: ptr uint8, Length: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetFilePointer*(hFile: HANDLE, lDistanceToMove: int32, lpDistanceToMoveHigh: ptr int32, dwMoveMethod: uint32): uint32 {.sideEffect, importc, stdcall.}
proc SetFilePointerEx*(hFile: HANDLE, liDistanceToMove: int64, lpNewFilePointer: ptr int64, dwMoveMethod: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetFileValidData*(hFile: HANDLE, ValidDataLength: int64): BOOL {.sideEffect, importc, stdcall.}
proc UnlockFile*(hFile: HANDLE, dwFileOffsetLow: uint32, dwFileOffsetHigh: uint32, nNumberOfBytesToUnlockLow: uint32, nNumberOfBytesToUnlockHigh: uint32): BOOL {.sideEffect, importc, stdcall.}
proc UnlockFileEx*(hFile: HANDLE, dwReserved: uint32, nNumberOfBytesToUnlockLow: uint32, nNumberOfBytesToUnlockHigh: uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc WriteFile*(hFile: HANDLE, lpBuffer: pointer, nNumberOfBytesToWrite: uint32, lpNumberOfBytesWritten: ptr uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc WriteFileEx*(hFile: HANDLE, lpBuffer: pointer, nNumberOfBytesToWrite: uint32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPOVERLAPPED_COMPLETION_ROUTINE): BOOL {.sideEffect, importc, stdcall.}
proc WriteFileGather*(hFile: HANDLE, aSegmentArray: ptr FILE_SEGMENT_ELEMENT, nNumberOfBytesToWrite: uint32, lpReserved: ptr uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
