# generated by winmd2nim from Windows.Win32.winmd — heapapi (do not edit)
import ./[winnt, minwindef, minwinbase]
export winnt, minwindef, minwinbase

type

  # structs
  HEAP_SUMMARY* {.completeStruct.} = object
    cb*: uint32
    cbAllocated*: uint
    cbCommitted*: uint
    cbReserved*: uint
    cbMaxReserve*: uint

  # typdefs
  LPHEAP_SUMMARY* = PHEAP_SUMMARY
  PHEAP_SUMMARY* = ptr HEAP_SUMMARY

{.push dynlib: "kernel32".}
proc GetProcessHeap*(): HANDLE {.sideEffect, importc, stdcall.}
proc GetProcessHeaps*(NumberOfHeaps: uint32, ProcessHeaps: ptr HANDLE): uint32 {.sideEffect, importc, stdcall.}
proc HeapAlloc*(hHeap: HANDLE, dwFlags: uint32, dwBytes: uint): pointer {.sideEffect, importc, stdcall.}
proc HeapCompact*(hHeap: HANDLE, dwFlags: uint32): uint {.sideEffect, importc, stdcall.}
proc HeapCreate*(flOptions: uint32, dwInitialSize: uint, dwMaximumSize: uint): HANDLE {.sideEffect, importc, stdcall.}
proc HeapDestroy*(hHeap: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc HeapFree*(hHeap: HANDLE, dwFlags: uint32, lpMem: pointer): BOOL {.sideEffect, importc, stdcall.}
proc HeapLock*(hHeap: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc HeapQueryInformation*(HeapHandle: HANDLE, HeapInformationClass: HEAP_INFORMATION_CLASS, HeapInformation: pointer, HeapInformationLength: uint, ReturnLength: ptr uint): BOOL {.sideEffect, importc, stdcall.}
proc HeapReAlloc*(hHeap: HANDLE, dwFlags: uint32, lpMem: pointer, dwBytes: uint): pointer {.sideEffect, importc, stdcall.}
proc HeapSetInformation*(HeapHandle: HANDLE, HeapInformationClass: HEAP_INFORMATION_CLASS, HeapInformation: pointer, HeapInformationLength: uint): BOOL {.sideEffect, importc, stdcall.}
proc HeapSize*(hHeap: HANDLE, dwFlags: uint32, lpMem: pointer): uint {.sideEffect, importc, stdcall.}
proc HeapSummary_2*(hHeap: HANDLE, dwFlags: uint32, lpSummary: LPHEAP_SUMMARY): BOOL {.sideEffect, importc: "HeapSummary", stdcall.}
proc HeapUnlock*(hHeap: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc HeapValidate*(hHeap: HANDLE, dwFlags: uint32, lpMem: pointer): BOOL {.sideEffect, importc, stdcall.}
proc HeapWalk*(hHeap: HANDLE, lpEntry: ptr PROCESS_HEAP_ENTRY): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
