# generated by winmd2nim from Windows.Win32.winmd — icm (do not edit)
import ./[wingdi, winuser, winnt, windef, minwindef]
export wingdi, winuser, winnt, windef, minwindef

type

  # structs
  CMYKCOLOR* {.completeStruct.} = object
    cyan*: uint16
    magenta*: uint16
    yellow*: uint16
    black*: uint16
  COLOR* {.completeStruct, union.} = object
    gray*: GRAYCOLOR
    rgb*: RGBCOLOR
    cmyk*: CMYKCOLOR
    XYZ*: XYZCOLOR
    Yxy*: YxyCOLOR
    Lab*: LabCOLOR
    gen3ch*: GENERIC3CHANNEL
    named*: NAMEDCOLOR
    hifi*: HiFiCOLOR
    Anonymous*: COLOR_9
  COLOR_9* {.completeStruct.} = object
    reserved1*: uint32
    reserved2*: pointer
  COLORMATCHSETUPA* {.completeStruct.} = object
    dwSize*: uint32
    dwVersion*: uint32
    dwFlags*: uint32
    hwndOwner*: HWND
    pSourceName*: PCSTR
    pDisplayName*: PCSTR
    pPrinterName*: PCSTR
    dwRenderIntent*: uint32
    dwProofingIntent*: uint32
    pMonitorProfile*: PSTR
    ccMonitorProfile*: uint32
    pPrinterProfile*: PSTR
    ccPrinterProfile*: uint32
    pTargetProfile*: PSTR
    ccTargetProfile*: uint32
    lpfnHook*: DLGPROC
    lParam*: LPARAM
    lpfnApplyCallback*: PCMSCALLBACKA
    lParamApplyCallback*: LPARAM
  COLORMATCHSETUPW* {.completeStruct.} = object
    dwSize*: uint32
    dwVersion*: uint32
    dwFlags*: uint32
    hwndOwner*: HWND
    pSourceName*: PCWSTR
    pDisplayName*: PCWSTR
    pPrinterName*: PCWSTR
    dwRenderIntent*: uint32
    dwProofingIntent*: uint32
    pMonitorProfile*: PWSTR
    ccMonitorProfile*: uint32
    pPrinterProfile*: PWSTR
    ccPrinterProfile*: uint32
    pTargetProfile*: PWSTR
    ccTargetProfile*: uint32
    lpfnHook*: DLGPROC
    lParam*: LPARAM
    lpfnApplyCallback*: PCMSCALLBACKW
    lParamApplyCallback*: LPARAM
  ENUMTYPEA* {.completeStruct.} = object
    dwSize*: uint32
    dwVersion*: uint32
    dwFields*: uint32
    pDeviceName*: PCSTR
    dwMediaType*: uint32
    dwDitheringMode*: uint32
    dwResolution*: array[2, uint32]
    dwCMMType*: uint32
    dwClass*: uint32
    dwDataColorSpace*: uint32
    dwConnectionSpace*: uint32
    dwSignature*: uint32
    dwPlatform*: uint32
    dwProfileFlags*: uint32
    dwManufacturer*: uint32
    dwModel*: uint32
    dwAttributes*: array[2, uint32]
    dwRenderingIntent*: uint32
    dwCreator*: uint32
    dwDeviceClass*: uint32
  ENUMTYPEW* {.completeStruct.} = object
    dwSize*: uint32
    dwVersion*: uint32
    dwFields*: uint32
    pDeviceName*: PCWSTR
    dwMediaType*: uint32
    dwDitheringMode*: uint32
    dwResolution*: array[2, uint32]
    dwCMMType*: uint32
    dwClass*: uint32
    dwDataColorSpace*: uint32
    dwConnectionSpace*: uint32
    dwSignature*: uint32
    dwPlatform*: uint32
    dwProfileFlags*: uint32
    dwManufacturer*: uint32
    dwModel*: uint32
    dwAttributes*: array[2, uint32]
    dwRenderingIntent*: uint32
    dwCreator*: uint32
    dwDeviceClass*: uint32
  GENERIC3CHANNEL* {.completeStruct.} = object
    ch1*: uint16
    ch2*: uint16
    ch3*: uint16
  GRAYCOLOR* {.completeStruct.} = object
    gray*: uint16
  HiFiCOLOR* {.completeStruct.} = object
    channel*: array[8, uint8]
  LabCOLOR* {.completeStruct.} = object
    L*: uint16
    a*: uint16
    b*: uint16
  NAMEDCOLOR* {.completeStruct.} = object
    dwIndex*: uint32
  NAMED_PROFILE_INFO* {.completeStruct.} = object
    dwFlags*: uint32
    dwCount*: uint32
    dwCountDevCoordinates*: uint32
    szPrefix*: COLOR_NAME
    szSuffix*: COLOR_NAME
  PROFILE* {.completeStruct.} = object
    dwType*: uint32
    pProfileData*: pointer
    cbDataSize*: uint32
  PROFILEHEADER* {.completeStruct.} = object
    phSize*: uint32
    phCMMType*: uint32
    phVersion*: uint32
    phClass*: uint32
    phDataColorSpace*: uint32
    phConnectionSpace*: uint32
    phDateTime*: array[3, uint32]
    phSignature*: uint32
    phPlatform*: uint32
    phProfileFlags*: uint32
    phManufacturer*: uint32
    phModel*: uint32
    phAttributes*: array[2, uint32]
    phRenderingIntent*: uint32
    phIlluminant*: CIEXYZ
    phCreator*: uint32
    phReserved*: array[44, uint8]
  RGBCOLOR* {.completeStruct.} = object
    red*: uint16
    green*: uint16
    blue*: uint16
  WCS_DEVICE_MHC2_CAPABILITIES* {.completeStruct.} = object
    Size*: uint32
    SupportsMhc2*: BOOL
    RegammaLutEntryCount*: uint32
    CscXyzMatrixRows*: uint32
    CscXyzMatrixColumns*: uint32
  WCS_DEVICE_VCGT_CAPABILITIES* {.completeStruct.} = object
    Size*: uint32
    SupportsVcgt*: BOOL
  XYZCOLOR* {.completeStruct.} = object
    X*: uint16
    Y*: uint16
    Z*: uint16
  YxyCOLOR* {.completeStruct.} = object
    Y*: uint16
    x*: uint16
    y*: uint16

  # typdefs
  COLOR_NAME* = distinct array[32, int8]
  HCMTRANSFORM* = HANDLE
  HPROFILE* = HANDLE
  HTRANSFORM* = HANDLE
  LPBMCALLBACKFN* = PBMCALLBACKFN
  LPBMFORMAT* = distinct ptr BMFORMAT
  LPCOLOR* = ptr COLOR
  LPCOLORDATATYPE* = distinct ptr COLORDATATYPE
  LPCOLORMATCHSETUPA* = ptr COLORMATCHSETUPA
  LPCOLORMATCHSETUPW* = ptr COLORMATCHSETUPW
  LPCOLORPROFILESUBTYPE* = distinct ptr COLORPROFILESUBTYPE
  LPCOLORPROFILETYPE* = distinct ptr COLORPROFILETYPE
  LPCOLORTYPE* = distinct ptr COLORTYPE
  LPCOLOR_NAME* = distinct pointer
  LPDEVCHARACTER* = distinct pointer
  LPENUMTYPEA* = ptr ENUMTYPEA
  LPENUMTYPEW* = ptr ENUMTYPEW
  LPNAMED_PROFILE_INFO* = ptr NAMED_PROFILE_INFO
  LPPROFILE* = ptr PROFILE
  LPPROFILEHEADER* = ptr PROFILEHEADER
  LPTAGTYPE* = ptr TAGTYPE
  PBMFORMAT* = distinct ptr BMFORMAT
  PCOLOR* = ptr COLOR
  PCOLORDATATYPE* = distinct ptr COLORDATATYPE
  PCOLORMATCHSETUPA* = ptr COLORMATCHSETUPA
  PCOLORMATCHSETUPW* = ptr COLORMATCHSETUPW
  PCOLORPROFILESUBTYPE* = distinct ptr COLORPROFILESUBTYPE
  PCOLORPROFILETYPE* = distinct ptr COLORPROFILETYPE
  PCOLORTYPE* = distinct ptr COLORTYPE
  PCOLOR_NAME* = distinct pointer
  PENUMTYPEA* = ptr ENUMTYPEA
  PENUMTYPEW* = ptr ENUMTYPEW
  PHPROFILE* = ptr HPROFILE
  PNAMED_PROFILE_INFO* = ptr NAMED_PROFILE_INFO
  PPROFILE* = ptr PROFILE
  PPROFILEHEADER* = ptr PROFILEHEADER
  PTAGTYPE* = ptr TAGTYPE
  TAGTYPE* = distinct uint32

  # unscoped enums 
  BMFORMAT* = int32
  COLORDATATYPE* = int32
  COLORPROFILESUBTYPE* = int32
  COLORPROFILETYPE* = int32
  COLORTYPE* = int32
  WCS_DEVICE_CAPABILITIES_TYPE* = int32
  WCS_PROFILE_MANAGEMENT_SCOPE* = int32

  # delegates
  PBMCALLBACKFN* = proc (arg_1: uint32, arg_2: uint32, arg_3: LPARAM): BOOL {.stdcall.}
  PCMSCALLBACKA* = proc (arg_1: ptr COLORMATCHSETUPA, arg_2: LPARAM): BOOL {.stdcall.}
  PCMSCALLBACKW* = proc (arg_1: ptr COLORMATCHSETUPW, arg_2: LPARAM): BOOL {.stdcall.}

const
  # free constants
  ATTRIB_MATTE*: int32 = 2'i32
  ATTRIB_TRANSPARENCY*: int32 = 1'i32
  BEST_MODE*: int32 = 3'i32
  CLASS_ABSTRACT*: int32 = 1633842036'i32
  CLASS_CAMP*: int32 = 1667329392'i32
  CLASS_COLORSPACE*: int32 = 1936744803'i32
  CLASS_GMMP*: int32 = 1735224688'i32
  CLASS_LINK*: int32 = 1818848875'i32
  CLASS_MONITOR*: int32 = 1835955314'i32
  CLASS_NAMED*: int32 = 1852662636'i32
  CLASS_PRINTER*: int32 = 1886549106'i32
  CLASS_SCANNER*: int32 = 1935896178'i32
  CMM_DESCRIPTION*: int32 = 5'i32
  CMM_DLL_VERSION*: int32 = 3'i32
  CMM_DRIVER_VERSION*: int32 = 2'i32
  CMM_FROM_PROFILE*: int32 = 0'i32
  CMM_IDENT*: int32 = 1'i32
  CMM_LOGOICON*: int32 = 6'i32
  CMM_VERSION*: int32 = 4'i32
  CMM_WINDOWS_DEFAULT*: int32 = 1466527264'i32
  CMM_WIN_VERSION*: int32 = 0'i32
  CMS_BACKWARD*: int32 = 1'i32
  CMS_DISABLEICM*: int32 = 1'i32
  CMS_DISABLEINTENT*: int32 = 1024'i32
  CMS_DISABLERENDERINTENT*: int32 = 2048'i32
  CMS_ENABLEPROOFING*: int32 = 2'i32
  CMS_FORWARD*: int32 = 0'i32
  CMS_MONITOROVERFLOW*: uint32 = 0x80000000'u32
  CMS_PRINTEROVERFLOW*: int32 = 1073741824'i32
  CMS_SETMONITORPROFILE*: int32 = 16'i32
  CMS_SETPRINTERPROFILE*: int32 = 32'i32
  CMS_SETPROOFINTENT*: int32 = 8'i32
  CMS_SETRENDERINTENT*: int32 = 4'i32
  CMS_SETTARGETPROFILE*: int32 = 64'i32
  CMS_TARGETOVERFLOW*: int32 = 536870912'i32
  CMS_USEAPPLYCALLBACK*: int32 = 256'i32
  CMS_USEDESCRIPTION*: int32 = 512'i32
  CMS_USEHOOK*: int32 = 128'i32
  COLOR_MATCH_VERSION*: int32 = 512'i32
  CSA_A*: int32 = 1'i32
  CSA_ABC*: int32 = 2'i32
  CSA_CMYK*: int32 = 7'i32
  CSA_DEF*: int32 = 3'i32
  CSA_DEFG*: int32 = 4'i32
  CSA_GRAY*: int32 = 5'i32
  CSA_Lab*: int32 = 8'i32
  CSA_RGB*: int32 = 6'i32
  DONT_USE_EMBEDDED_WCS_PROFILES*: int32 = 1'i32
  ENABLE_GAMUT_CHECKING*: int32 = 65536'i32
  ENUM_TYPE_VERSION*: int32 = 768'i32
  ET_ATTRIBUTES*: int32 = 8192'i32
  ET_CLASS*: int32 = 32'i32
  ET_CMMTYPE*: int32 = 16'i32
  ET_CONNECTIONSPACE*: int32 = 128'i32
  ET_CREATOR*: int32 = 32768'i32
  ET_DATACOLORSPACE*: int32 = 64'i32
  ET_DEVICECLASS*: int32 = 65536'i32
  ET_DEVICENAME*: int32 = 1'i32
  ET_DITHERMODE*: int32 = 4'i32
  ET_EXTENDEDDISPLAYCOLOR*: int32 = 262144'i32
  ET_MANUFACTURER*: int32 = 2048'i32
  ET_MEDIATYPE*: int32 = 2'i32
  ET_MODEL*: int32 = 4096'i32
  ET_PLATFORM*: int32 = 512'i32
  ET_PROFILEFLAGS*: int32 = 1024'i32
  ET_RENDERINGINTENT*: int32 = 16384'i32
  ET_RESOLUTION*: int32 = 8'i32
  ET_SIGNATURE*: int32 = 256'i32
  ET_STANDARDDISPLAYCOLOR*: int32 = 131072'i32
  FAST_TRANSLATE*: int32 = 262144'i32
  FLAG_DEPENDENTONDATA*: int32 = 2'i32
  FLAG_EMBEDDEDPROFILE*: int32 = 1'i32
  FLAG_ENABLE_CHROMATIC_ADAPTATION*: int32 = 33554432'i32
  INDEX_DONT_CARE*: int32 = 0'i32
  INTENT_ABSOLUTE_COLORIMETRIC*: int32 = 3'i32
  INTENT_PERCEPTUAL*: int32 = 0'i32
  INTENT_RELATIVE_COLORIMETRIC*: int32 = 1'i32
  INTENT_SATURATION*: int32 = 2'i32
  MAX_COLOR_CHANNELS*: int32 = 8'i32
  NORMAL_MODE*: int32 = 2'i32
  PRESERVEBLACK*: int32 = 1048576'i32
  PROFILE_FILENAME*: int32 = 1'i32
  PROFILE_MEMBUFFER*: int32 = 2'i32
  PROFILE_READ*: int32 = 1'i32
  PROFILE_READWRITE*: int32 = 2'i32
  PROOF_MODE*: int32 = 1'i32
  RESERVED*: uint32 = 0x80000000'u32
  SEQUENTIAL_TRANSFORM*: uint32 = 0x80800000'u32
  SPACE_2_CHANNEL*: int32 = 843271250'i32
  SPACE_3_CHANNEL*: int32 = 860048466'i32
  SPACE_4_CHANNEL*: int32 = 876825682'i32
  SPACE_5_CHANNEL*: int32 = 893602898'i32
  SPACE_6_CHANNEL*: int32 = 910380114'i32
  SPACE_7_CHANNEL*: int32 = 927157330'i32
  SPACE_8_CHANNEL*: int32 = 943934546'i32
  SPACE_CMY*: int32 = 1129142560'i32
  SPACE_CMYK*: int32 = 1129142603'i32
  SPACE_GRAY*: int32 = 1196573017'i32
  SPACE_HLS*: int32 = 1212961568'i32
  SPACE_HSV*: int32 = 1213421088'i32
  SPACE_Lab*: int32 = 1281450528'i32
  SPACE_Luv*: int32 = 1282766368'i32
  SPACE_RGB*: int32 = 1380401696'i32
  SPACE_XYZ*: int32 = 1482250784'i32
  SPACE_YCbCr*: int32 = 1497588338'i32
  SPACE_Yxy*: int32 = 1501067552'i32
  USE_RELATIVE_COLORIMETRIC*: int32 = 131072'i32
  WCS_ALWAYS*: int32 = 2097152'i32
  WCS_DEFAULT*: int32 = 0'i32
  WCS_EMBEDDED_TAG_SIGNATURE*: int32 = 1297297456'i32
  WCS_EMBEDDED_TAG_TYPE_SIGNATURE*: int32 = 1297297712'i32
  WCS_ICCONLY*: int32 = 65536'i32

  # unscoped enum members
  BM_x555RGB*: BMFORMAT = 0'i32
  BM_x555XYZ*: BMFORMAT = 257'i32
  BM_x555Yxy*: BMFORMAT = 258'i32
  BM_x555Lab*: BMFORMAT = 259'i32
  BM_x555G3CH*: BMFORMAT = 260'i32
  BM_RGBTRIPLETS*: BMFORMAT = 2'i32
  BM_BGRTRIPLETS*: BMFORMAT = 4'i32
  BM_XYZTRIPLETS*: BMFORMAT = 513'i32
  BM_YxyTRIPLETS*: BMFORMAT = 514'i32
  BM_LabTRIPLETS*: BMFORMAT = 515'i32
  BM_G3CHTRIPLETS*: BMFORMAT = 516'i32
  BM_5CHANNEL*: BMFORMAT = 517'i32
  BM_6CHANNEL*: BMFORMAT = 518'i32
  BM_7CHANNEL*: BMFORMAT = 519'i32
  BM_8CHANNEL*: BMFORMAT = 520'i32
  BM_GRAY*: BMFORMAT = 521'i32
  BM_xRGBQUADS*: BMFORMAT = 8'i32
  BM_xBGRQUADS*: BMFORMAT = 16'i32
  BM_xG3CHQUADS*: BMFORMAT = 772'i32
  BM_KYMCQUADS*: BMFORMAT = 773'i32
  BM_CMYKQUADS*: BMFORMAT = 32'i32
  BM_10b_RGB*: BMFORMAT = 9'i32
  BM_10b_XYZ*: BMFORMAT = 1025'i32
  BM_10b_Yxy*: BMFORMAT = 1026'i32
  BM_10b_Lab*: BMFORMAT = 1027'i32
  BM_10b_G3CH*: BMFORMAT = 1028'i32
  BM_NAMED_INDEX*: BMFORMAT = 1029'i32
  BM_16b_RGB*: BMFORMAT = 10'i32
  BM_16b_XYZ*: BMFORMAT = 1281'i32
  BM_16b_Yxy*: BMFORMAT = 1282'i32
  BM_16b_Lab*: BMFORMAT = 1283'i32
  BM_16b_G3CH*: BMFORMAT = 1284'i32
  BM_16b_GRAY*: BMFORMAT = 1285'i32
  BM_565RGB*: BMFORMAT = 1'i32
  BM_32b_scRGB*: BMFORMAT = 1537'i32
  BM_32b_scARGB*: BMFORMAT = 1538'i32
  BM_S2DOT13FIXED_scRGB*: BMFORMAT = 1539'i32
  BM_S2DOT13FIXED_scARGB*: BMFORMAT = 1540'i32
  BM_R10G10B10A2*: BMFORMAT = 1793'i32
  BM_R10G10B10A2_XR*: BMFORMAT = 1794'i32
  BM_R16G16B16A16_FLOAT*: BMFORMAT = 1795'i32
  COLOR_BYTE*: COLORDATATYPE = 1'i32
  COLOR_WORD*: COLORDATATYPE = 2'i32
  COLOR_FLOAT*: COLORDATATYPE = 3'i32
  COLOR_S2DOT13FIXED*: COLORDATATYPE = 4'i32
  COLOR_10b_R10G10B10A2*: COLORDATATYPE = 5'i32
  COLOR_10b_R10G10B10A2_XR*: COLORDATATYPE = 6'i32
  COLOR_FLOAT16*: COLORDATATYPE = 7'i32
  CPST_PERCEPTUAL*: COLORPROFILESUBTYPE = 0'i32
  CPST_RELATIVE_COLORIMETRIC*: COLORPROFILESUBTYPE = 1'i32
  CPST_SATURATION*: COLORPROFILESUBTYPE = 2'i32
  CPST_ABSOLUTE_COLORIMETRIC*: COLORPROFILESUBTYPE = 3'i32
  CPST_NONE*: COLORPROFILESUBTYPE = 4'i32
  CPST_RGB_WORKING_SPACE*: COLORPROFILESUBTYPE = 5'i32
  CPST_CUSTOM_WORKING_SPACE*: COLORPROFILESUBTYPE = 6'i32
  CPST_STANDARD_DISPLAY_COLOR_MODE*: COLORPROFILESUBTYPE = 7'i32
  CPST_EXTENDED_DISPLAY_COLOR_MODE*: COLORPROFILESUBTYPE = 8'i32
  CPT_ICC*: COLORPROFILETYPE = 0'i32
  CPT_DMP*: COLORPROFILETYPE = 1'i32
  CPT_CAMP*: COLORPROFILETYPE = 2'i32
  CPT_GMMP*: COLORPROFILETYPE = 3'i32
  COLOR_GRAY*: COLORTYPE = 1'i32
  COLOR_RGB*: COLORTYPE = 2'i32
  COLOR_XYZ*: COLORTYPE = 3'i32
  COLOR_Yxy*: COLORTYPE = 4'i32
  COLOR_Lab*: COLORTYPE = 5'i32
  COLOR_3_CHANNEL*: COLORTYPE = 6'i32
  COLOR_CMYK*: COLORTYPE = 7'i32
  COLOR_5_CHANNEL*: COLORTYPE = 8'i32
  COLOR_6_CHANNEL*: COLORTYPE = 9'i32
  COLOR_7_CHANNEL*: COLORTYPE = 10'i32
  COLOR_8_CHANNEL*: COLORTYPE = 11'i32
  COLOR_NAMED*: COLORTYPE = 12'i32
  VideoCardGammaTable*: WCS_DEVICE_CAPABILITIES_TYPE = 1'i32
  MicrosoftHardwareColorV2*: WCS_DEVICE_CAPABILITIES_TYPE = 2'i32
  WCS_PROFILE_MANAGEMENT_SCOPE_SYSTEM_WIDE*: WCS_PROFILE_MANAGEMENT_SCOPE = 0'i32
  WCS_PROFILE_MANAGEMENT_SCOPE_CURRENT_USER*: WCS_PROFILE_MANAGEMENT_SCOPE = 1'i32

{.push dynlib: "icm32".}
proc CMCheckColors*(hcmTransform: HCMTRANSFORM, lpaInputColors: ptr COLOR, nColors: uint32, ctInput: COLORTYPE, lpaResult: ptr uint8): BOOL {.sideEffect, importc, stdcall.}
proc CMCheckColorsInGamut*(hcmTransform: HCMTRANSFORM, lpaRGBTriple: ptr RGBTRIPLE, lpaResult: ptr uint8, nCount: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CMCheckRGBs*(hcmTransform: HCMTRANSFORM, lpSrcBits: pointer, bmInput: BMFORMAT, dwWidth: uint32, dwHeight: uint32, dwStride: uint32, lpaResult: ptr uint8, pfnCallback: PBMCALLBACKFN, ulCallbackData: LPARAM): BOOL {.sideEffect, importc, stdcall.}
proc CMConvertColorNameToIndex*(hProfile: HPROFILE, paColorName: pointer, paIndex: ptr uint32, dwCount: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CMConvertIndexToColorName*(hProfile: HPROFILE, paIndex: ptr uint32, paColorName: pointer, dwCount: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CMCreateDeviceLinkProfile*(pahProfiles: ptr HPROFILE, nProfiles: uint32, padwIntents: ptr uint32, nIntents: uint32, dwFlags: uint32, lpProfileData: ptr LPBYTE): BOOL {.sideEffect, importc, stdcall.}
proc CMCreateMultiProfileTransform*(pahProfiles: ptr HPROFILE, nProfiles: uint32, padwIntents: ptr uint32, nIntents: uint32, dwFlags: uint32): HCMTRANSFORM {.sideEffect, importc, stdcall.}
proc CMCreateProfile*(lpColorSpace: ptr LOGCOLORSPACEA, lpProfileData: ptr LPDEVCHARACTER): BOOL {.sideEffect, importc, stdcall.}
proc CMCreateProfileW*(lpColorSpace: ptr LOGCOLORSPACEW, lpProfileData: ptr LPDEVCHARACTER): BOOL {.sideEffect, importc, stdcall.}
proc CMCreateTransform*(lpColorSpace: ptr LOGCOLORSPACEA, lpDevCharacter: LPDEVCHARACTER, lpTargetDevCharacter: LPDEVCHARACTER): HCMTRANSFORM {.sideEffect, importc, stdcall.}
proc CMCreateTransformExt*(lpColorSpace: ptr LOGCOLORSPACEA, lpDevCharacter: LPDEVCHARACTER, lpTargetDevCharacter: LPDEVCHARACTER, dwFlags: uint32): HCMTRANSFORM {.sideEffect, importc, stdcall.}
proc CMCreateTransformExtW*(lpColorSpace: ptr LOGCOLORSPACEW, lpDevCharacter: LPDEVCHARACTER, lpTargetDevCharacter: LPDEVCHARACTER, dwFlags: uint32): HCMTRANSFORM {.sideEffect, importc, stdcall.}
proc CMCreateTransformW*(lpColorSpace: ptr LOGCOLORSPACEW, lpDevCharacter: LPDEVCHARACTER, lpTargetDevCharacter: LPDEVCHARACTER): HCMTRANSFORM {.sideEffect, importc, stdcall.}
proc CMDeleteTransform*(hcmTransform: HCMTRANSFORM): BOOL {.sideEffect, importc, stdcall.}
proc CMGetInfo*(dwInfo: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CMGetNamedProfileInfo*(hProfile: HPROFILE, pNamedProfileInfo: ptr NAMED_PROFILE_INFO): BOOL {.sideEffect, importc, stdcall.}
proc CMIsProfileValid*(hProfile: HPROFILE, lpbValid: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc CMTranslateColors*(hcmTransform: HCMTRANSFORM, lpaInputColors: ptr COLOR, nColors: uint32, ctInput: COLORTYPE, lpaOutputColors: ptr COLOR, ctOutput: COLORTYPE): BOOL {.sideEffect, importc, stdcall.}
proc CMTranslateRGB*(hcmTransform: HCMTRANSFORM, ColorRef: COLORREF, lpColorRef: ptr uint32, dwFlags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CMTranslateRGBs*(hcmTransform: HCMTRANSFORM, lpSrcBits: pointer, bmInput: BMFORMAT, dwWidth: uint32, dwHeight: uint32, dwStride: uint32, lpDestBits: pointer, bmOutput: BMFORMAT, dwTranslateDirection: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CMTranslateRGBsExt*(hcmTransform: HCMTRANSFORM, lpSrcBits: pointer, bmInput: BMFORMAT, dwWidth: uint32, dwHeight: uint32, dwInputStride: uint32, lpDestBits: pointer, bmOutput: BMFORMAT, dwOutputStride: uint32, lpfnCallback: LPBMCALLBACKFN, ulCallbackData: LPARAM): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
{.push dynlib: "icmui".}
proc SetupColorMatchingA*(pcms: ptr COLORMATCHSETUPA): BOOL {.sideEffect, importc, stdcall.}
proc SetupColorMatchingW*(pcms: ptr COLORMATCHSETUPW): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
{.push dynlib: "mscms".}
proc AssociateColorProfileWithDeviceA*(pMachineName: PCSTR, pProfileName: PCSTR, pDeviceName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc AssociateColorProfileWithDeviceW*(pMachineName: PCWSTR, pProfileName: PCWSTR, pDeviceName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc CheckBitmapBits*(hColorTransform: HTRANSFORM, pSrcBits: pointer, bmInput: BMFORMAT, dwWidth: uint32, dwHeight: uint32, dwStride: uint32, paResult: ptr uint8, pfnCallback: PBMCALLBACKFN, lpCallbackData: LPARAM): BOOL {.sideEffect, importc, stdcall.}
proc CheckColors*(hColorTransform: HTRANSFORM, paInputColors: ptr COLOR, nColors: uint32, ctInput: COLORTYPE, paResult: ptr uint8): BOOL {.sideEffect, importc, stdcall.}
proc CloseColorProfile*(hProfile: HPROFILE): BOOL {.sideEffect, importc, stdcall.}
proc ColorProfileAddDisplayAssociation*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, profileName: PCWSTR, targetAdapterID: LUID, sourceID: uint32, setAsDefault: BOOL, associateAsAdvancedColor: BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc ColorProfileGetDeviceCapabilities*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, targetAdapterID: LUID, sourceID: uint32, capsType: WCS_DEVICE_CAPABILITIES_TYPE, outputCapabilities: pointer): HRESULT {.sideEffect, importc, stdcall.}
proc ColorProfileGetDisplayDefault*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, targetAdapterID: LUID, sourceID: uint32, profileType: COLORPROFILETYPE, profileSubType: COLORPROFILESUBTYPE, profileName: ptr PWSTR): HRESULT {.sideEffect, importc, stdcall.}
proc ColorProfileGetDisplayList*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, targetAdapterID: LUID, sourceID: uint32, profileList: ptr ptr PWSTR, profileCount: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc ColorProfileGetDisplayUserScope*(targetAdapterID: LUID, sourceID: uint32, scope: ptr WCS_PROFILE_MANAGEMENT_SCOPE): HRESULT {.sideEffect, importc, stdcall.}
proc ColorProfileRemoveDisplayAssociation*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, profileName: PCWSTR, targetAdapterID: LUID, sourceID: uint32, dissociateAdvancedColor: BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc ColorProfileSetDisplayDefaultAssociation*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, profileName: PCWSTR, profileType: COLORPROFILETYPE, profileSubType: COLORPROFILESUBTYPE, targetAdapterID: LUID, sourceID: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc ConvertColorNameToIndex*(hProfile: HPROFILE, paColorName: pointer, paIndex: ptr uint32, dwCount: uint32): BOOL {.sideEffect, importc, stdcall.}
proc ConvertIndexToColorName*(hProfile: HPROFILE, paIndex: ptr uint32, paColorName: pointer, dwCount: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CreateColorTransformA*(pLogColorSpace: ptr LOGCOLORSPACEA, hDestProfile: HPROFILE, hTargetProfile: HPROFILE, dwFlags: uint32): HTRANSFORM {.sideEffect, importc, stdcall.}
proc CreateColorTransformW*(pLogColorSpace: ptr LOGCOLORSPACEW, hDestProfile: HPROFILE, hTargetProfile: HPROFILE, dwFlags: uint32): HTRANSFORM {.sideEffect, importc, stdcall.}
proc CreateDeviceLinkProfile*(hProfile: ptr HPROFILE, nProfiles: uint32, padwIntent: ptr uint32, nIntents: uint32, dwFlags: uint32, pProfileData: ptr PBYTE, indexPreferredCMM: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CreateMultiProfileTransform*(pahProfiles: ptr HPROFILE, nProfiles: uint32, padwIntent: ptr uint32, nIntents: uint32, dwFlags: uint32, indexPreferredCMM: uint32): HTRANSFORM {.sideEffect, importc, stdcall.}
proc CreateProfileFromLogColorSpaceA*(pLogColorSpace: ptr LOGCOLORSPACEA, pProfile: ptr PBYTE): BOOL {.sideEffect, importc, stdcall.}
proc CreateProfileFromLogColorSpaceW*(pLogColorSpace: ptr LOGCOLORSPACEW, pProfile: ptr PBYTE): BOOL {.sideEffect, importc, stdcall.}
proc DeleteColorTransform*(hxform: HTRANSFORM): BOOL {.sideEffect, importc, stdcall.}
proc DisassociateColorProfileFromDeviceA*(pMachineName: PCSTR, pProfileName: PCSTR, pDeviceName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc DisassociateColorProfileFromDeviceW*(pMachineName: PCWSTR, pProfileName: PCWSTR, pDeviceName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc EnumColorProfilesA*(pMachineName: PCSTR, pEnumRecord: ptr ENUMTYPEA, pEnumerationBuffer: ptr uint8, pdwSizeOfEnumerationBuffer: ptr uint32, pnProfiles: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc EnumColorProfilesW*(pMachineName: PCWSTR, pEnumRecord: ptr ENUMTYPEW, pEnumerationBuffer: ptr uint8, pdwSizeOfEnumerationBuffer: ptr uint32, pnProfiles: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetCMMInfo*(hColorTransform: HTRANSFORM, param1: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetColorDirectoryA*(pMachineName: PCSTR, pBuffer: PSTR, pdwSize: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetColorDirectoryW*(pMachineName: PCWSTR, pBuffer: PWSTR, pdwSize: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetColorProfileElement*(hProfile: HPROFILE, tag: TAGTYPE, dwOffset: uint32, pcbElement: ptr uint32, pElement: pointer, pbReference: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc GetColorProfileElementTag*(hProfile: HPROFILE, dwIndex: uint32, pTag: ptr TAGTYPE): BOOL {.sideEffect, importc, stdcall.}
proc GetColorProfileFromHandle*(hProfile: HPROFILE, pProfile: ptr uint8, pcbProfile: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetColorProfileHeader*(hProfile: HPROFILE, pHeader: ptr PROFILEHEADER): BOOL {.sideEffect, importc, stdcall.}
proc GetCountColorProfileElements*(hProfile: HPROFILE, pnElementCount: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetNamedProfileInfo*(hProfile: HPROFILE, pNamedProfileInfo: ptr NAMED_PROFILE_INFO): BOOL {.sideEffect, importc, stdcall.}
proc GetPS2ColorRenderingDictionary*(hProfile: HPROFILE, dwIntent: uint32, pPS2ColorRenderingDictionary: ptr uint8, pcbPS2ColorRenderingDictionary: ptr uint32, pbBinary: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc GetPS2ColorRenderingIntent*(hProfile: HPROFILE, dwIntent: uint32, pBuffer: ptr uint8, pcbPS2ColorRenderingIntent: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetPS2ColorSpaceArray*(hProfile: HPROFILE, dwIntent: uint32, dwCSAType: uint32, pPS2ColorSpaceArray: ptr uint8, pcbPS2ColorSpaceArray: ptr uint32, pbBinary: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc GetStandardColorSpaceProfileA*(pMachineName: PCSTR, dwSCS: uint32, pBuffer: PSTR, pcbSize: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc GetStandardColorSpaceProfileW*(pMachineName: PCWSTR, dwSCS: uint32, pBuffer: PWSTR, pcbSize: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc InstallColorProfileA*(pMachineName: PCSTR, pProfileName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc InstallColorProfileW*(pMachineName: PCWSTR, pProfileName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc IsColorProfileTagPresent*(hProfile: HPROFILE, tag: TAGTYPE, pbPresent: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc IsColorProfileValid*(hProfile: HPROFILE, pbValid: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc OpenColorProfileA*(pProfile: ptr PROFILE, dwDesiredAccess: uint32, dwShareMode: uint32, dwCreationMode: uint32): HPROFILE {.sideEffect, importc, stdcall.}
proc OpenColorProfileW*(pProfile: ptr PROFILE, dwDesiredAccess: uint32, dwShareMode: uint32, dwCreationMode: uint32): HPROFILE {.sideEffect, importc, stdcall.}
proc RegisterCMMA*(pMachineName: PCSTR, cmmID: uint32, pCMMdll: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc RegisterCMMW*(pMachineName: PCWSTR, cmmID: uint32, pCMMdll: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc SelectCMM*(dwCMMType: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetColorProfileElement*(hProfile: HPROFILE, tag: TAGTYPE, dwOffset: uint32, pcbElement: ptr uint32, pElement: pointer): BOOL {.sideEffect, importc, stdcall.}
proc SetColorProfileElementReference*(hProfile: HPROFILE, newTag: TAGTYPE, refTag: TAGTYPE): BOOL {.sideEffect, importc, stdcall.}
proc SetColorProfileElementSize*(hProfile: HPROFILE, tagType: TAGTYPE, pcbElement: uint32): BOOL {.sideEffect, importc, stdcall.}
proc SetColorProfileHeader*(hProfile: HPROFILE, pHeader: ptr PROFILEHEADER): BOOL {.sideEffect, importc, stdcall.}
proc SetStandardColorSpaceProfileA*(pMachineName: PCSTR, dwProfileID: uint32, pProfilename: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc SetStandardColorSpaceProfileW*(pMachineName: PCWSTR, dwProfileID: uint32, pProfileName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc TranslateBitmapBits*(hColorTransform: HTRANSFORM, pSrcBits: pointer, bmInput: BMFORMAT, dwWidth: uint32, dwHeight: uint32, dwInputStride: uint32, pDestBits: pointer, bmOutput: BMFORMAT, dwOutputStride: uint32, pfnCallBack: PBMCALLBACKFN, ulCallbackData: LPARAM): BOOL {.sideEffect, importc, stdcall.}
proc TranslateColors*(hColorTransform: HTRANSFORM, paInputColors: ptr COLOR, nColors: uint32, ctInput: COLORTYPE, paOutputColors: ptr COLOR, ctOutput: COLORTYPE): BOOL {.sideEffect, importc, stdcall.}
proc UninstallColorProfileA*(pMachineName: PCSTR, pProfileName: PCSTR, bDelete: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc UninstallColorProfileW*(pMachineName: PCWSTR, pProfileName: PCWSTR, bDelete: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc UnregisterCMMA*(pMachineName: PCSTR, cmmID: uint32): BOOL {.sideEffect, importc, stdcall.}
proc UnregisterCMMW*(pMachineName: PCWSTR, cmmID: uint32): BOOL {.sideEffect, importc, stdcall.}
proc WcsAssociateColorProfileWithDevice*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pProfileName: PCWSTR, pDeviceName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc WcsCheckColors*(hColorTransform: HTRANSFORM, nColors: uint32, nInputChannels: uint32, cdtInput: COLORDATATYPE, cbInput: uint32, pInputData: pointer, paResult: ptr uint8): BOOL {.sideEffect, importc, stdcall.}
proc WcsCreateIccProfile*(hWcsProfile: HPROFILE, dwOptions: uint32): HPROFILE {.sideEffect, importc, stdcall.}
proc WcsDisassociateColorProfileFromDevice*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pProfileName: PCWSTR, pDeviceName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc WcsEnumColorProfiles*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pEnumRecord: ptr ENUMTYPEW, pBuffer: ptr uint8, dwSize: uint32, pnProfiles: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc WcsEnumColorProfilesSize*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pEnumRecord: ptr ENUMTYPEW, pdwSize: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc WcsGetCalibrationManagementState*(pbIsEnabled: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc WcsGetDefaultColorProfile*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pDeviceName: PCWSTR, cptColorProfileType: COLORPROFILETYPE, cpstColorProfileSubType: COLORPROFILESUBTYPE, dwProfileID: uint32, cbProfileName: uint32, pProfileName: PWSTR): BOOL {.sideEffect, importc, stdcall.}
proc WcsGetDefaultColorProfileSize*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pDeviceName: PCWSTR, cptColorProfileType: COLORPROFILETYPE, cpstColorProfileSubType: COLORPROFILESUBTYPE, dwProfileID: uint32, pcbProfileName: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc WcsGetDefaultRenderingIntent*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pdwRenderingIntent: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc WcsGetUsePerUserProfiles*(pDeviceName: PCWSTR, dwDeviceClass: uint32, pUsePerUserProfiles: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc WcsOpenColorProfileA*(pCDMPProfile: ptr PROFILE, pCAMPProfile: ptr PROFILE, pGMMPProfile: ptr PROFILE, dwDesireAccess: uint32, dwShareMode: uint32, dwCreationMode: uint32, dwFlags: uint32): HPROFILE {.sideEffect, importc, stdcall.}
proc WcsOpenColorProfileW*(pCDMPProfile: ptr PROFILE, pCAMPProfile: ptr PROFILE, pGMMPProfile: ptr PROFILE, dwDesireAccess: uint32, dwShareMode: uint32, dwCreationMode: uint32, dwFlags: uint32): HPROFILE {.sideEffect, importc, stdcall.}
proc WcsSetCalibrationManagementState*(bIsEnabled: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc WcsSetDefaultColorProfile*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, pDeviceName: PCWSTR, cptColorProfileType: COLORPROFILETYPE, cpstColorProfileSubType: COLORPROFILESUBTYPE, dwProfileID: uint32, pProfileName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc WcsSetDefaultRenderingIntent*(scope: WCS_PROFILE_MANAGEMENT_SCOPE, dwRenderingIntent: uint32): BOOL {.sideEffect, importc, stdcall.}
proc WcsSetUsePerUserProfiles*(pDeviceName: PCWSTR, dwDeviceClass: uint32, usePerUserProfiles: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc WcsTranslateColors*(hColorTransform: HTRANSFORM, nColors: uint32, nInputChannels: uint32, cdtInput: COLORDATATYPE, cbInput: uint32, pInputData: pointer, nOutputChannels: uint32, cdtOutput: COLORDATATYPE, cbOutput: uint32, pOutputData: pointer): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
