# generated by winmd2nim from Windows.Win32.winmd — icmpapi (do not edit)
import ./[winnt, ipexport, minwindef, ntddndis, ws2ipdef]
export winnt, ipexport, minwindef, ntddndis, ws2ipdef

{.push dynlib: "iphlpapi".}
proc Icmp6CreateFile*(): HANDLE {.sideEffect, importc, stdcall.}
proc Icmp6ParseReplies*(ReplyBuffer: pointer, ReplySize: uint32): uint32 {.sideEffect, importc, stdcall.}
proc Icmp6SendEcho2*(IcmpHandle: HANDLE, Event: HANDLE, ApcRoutine: FARPROC, ApcContext: pointer, SourceAddress: ptr SOCKADDR_IN6_LH, DestinationAddress: ptr SOCKADDR_IN6_LH, RequestData: pointer, RequestSize: uint16, RequestOptions: ptr IP_OPTION_INFORMATION, ReplyBuffer: pointer, ReplySize: uint32, Timeout: uint32): uint32 {.sideEffect, importc, stdcall.}
proc IcmpCloseHandle*(IcmpHandle: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc IcmpCreateFile*(): HANDLE {.sideEffect, importc, stdcall.}
proc IcmpParseReplies*(ReplyBuffer: pointer, ReplySize: uint32): uint32 {.sideEffect, importc, stdcall.}
proc IcmpSendEcho*(IcmpHandle: HANDLE, DestinationAddress: IPAddr, RequestData: pointer, RequestSize: uint16, RequestOptions: ptr IP_OPTION_INFORMATION, ReplyBuffer: pointer, ReplySize: uint32, Timeout: uint32): uint32 {.sideEffect, importc, stdcall.}
proc IcmpSendEcho2*(IcmpHandle: HANDLE, Event: HANDLE, ApcRoutine: FARPROC, ApcContext: pointer, DestinationAddress: IPAddr, RequestData: pointer, RequestSize: uint16, RequestOptions: ptr IP_OPTION_INFORMATION, ReplyBuffer: pointer, ReplySize: uint32, Timeout: uint32): uint32 {.sideEffect, importc, stdcall.}
proc IcmpSendEcho2Ex*(IcmpHandle: HANDLE, Event: HANDLE, ApcRoutine: FARPROC, ApcContext: pointer, SourceAddress: IPAddr, DestinationAddress: IPAddr, RequestData: pointer, RequestSize: uint16, RequestOptions: ptr IP_OPTION_INFORMATION, ReplyBuffer: pointer, ReplySize: uint32, Timeout: uint32): uint32 {.sideEffect, importc, stdcall.}
{.pop.}
