# generated by winmd2nim from Windows.Win32.winmd — ipexport (do not edit)
import ./[minwindef, ntddndis, in6addr]
export minwindef, ntddndis, in6addr

type

  # structs
  ARP_SEND_REPLY* {.completeStruct.} = object
    DestAddress*: IPAddr
    SrcAddress*: IPAddr
  ICMPV6_ECHO_REPLY_LH* {.completeStruct.} = object
    Address*: IPV6_ADDRESS_EX
    Status*: uint32
    RoundTripTime*: uint32
  ICMP_ECHO_REPLY* {.completeStruct.} = object
    Address*: IPAddr
    Status*: uint32
    RoundTripTime*: uint32
    DataSize*: uint16
    Reserved*: uint16
    Data*: pointer
    Options*: IP_OPTION_INFORMATION
  ICMP_ECHO_REPLY32* {.completeStruct.} = object
    Address*: IPAddr
    Status*: uint32
    RoundTripTime*: uint32
    DataSize*: uint16
    Reserved*: uint16
    Data*: pointer
    Options*: IP_OPTION_INFORMATION32
  IPV6_ADDRESS_EX* {.completeStruct, packed.} = object
    sin6_port*: uint16
    sin6_flowinfo*: uint32
    sin6_addr*: array[8, uint16]
    sin6_scope_id*: uint32
  IP_ADAPTER_INDEX_MAP* {.completeStruct.} = object
    Index*: uint32
    Name*: array[128, uint16]
  IP_ADAPTER_ORDER_MAP* {.completeStruct.} = object
    NumAdapters*: uint32
    AdapterOrder*: array[1, uint32]
  IP_INTERFACE_INFO* {.completeStruct.} = object
    NumAdapters*: int32
    Adapter*: array[1, IP_ADAPTER_INDEX_MAP]
  IP_MCAST_COUNTER_INFO* {.completeStruct.} = object
    InMcastOctets*: uint64
    OutMcastOctets*: uint64
    InMcastPkts*: uint64
    OutMcastPkts*: uint64
  IP_OPTION_INFORMATION* {.completeStruct.} = object
    Ttl*: uint8
    Tos*: uint8
    Flags*: uint8
    OptionsSize*: uint8
    OptionsData*: PUCHAR
  IP_OPTION_INFORMATION32* {.completeStruct.} = object
    Ttl*: uint8
    Tos*: uint8
    Flags*: uint8
    OptionsSize*: uint8
    OptionsData*: ptr uint8
  IP_UNIDIRECTIONAL_ADAPTER_ADDRESS* {.completeStruct.} = object
    NumAdapters*: uint32
    Address*: array[1, IPAddr]
  TCP_RESERVE_PORT_RANGE* {.completeStruct.} = object
    UpperRange*: uint16
    LowerRange*: uint16

  # typdefs
  ICMPV6_ECHO_REPLY* = ICMPV6_ECHO_REPLY_LH
  IP_STATUS* = distinct uint32
  IPv6Addr* = IN6_ADDR
  PARP_SEND_REPLY* = ptr ARP_SEND_REPLY
  PICMPV6_ECHO_REPLY* = ptr ICMPV6_ECHO_REPLY_LH
  PICMPV6_ECHO_REPLY_LH* = ptr ICMPV6_ECHO_REPLY_LH
  PICMP_ECHO_REPLY* = ptr ICMP_ECHO_REPLY
  PICMP_ECHO_REPLY32* = ptr ICMP_ECHO_REPLY32
  PIPV6_ADDRESS_EX* = ptr IPV6_ADDRESS_EX
  PIP_ADAPTER_INDEX_MAP* = ptr IP_ADAPTER_INDEX_MAP
  PIP_ADAPTER_ORDER_MAP* = ptr IP_ADAPTER_ORDER_MAP
  PIP_INTERFACE_INFO* = ptr IP_INTERFACE_INFO
  PIP_MCAST_COUNTER_INFO* = ptr IP_MCAST_COUNTER_INFO
  PIP_OPTION_INFORMATION* = ptr IP_OPTION_INFORMATION
  PIP_OPTION_INFORMATION32* = ptr IP_OPTION_INFORMATION32
  PIP_UNIDIRECTIONAL_ADAPTER_ADDRESS* = ptr IP_UNIDIRECTIONAL_ADAPTER_ADDRESS
  PTCP_RESERVE_PORT_RANGE* = ptr TCP_RESERVE_PORT_RANGE

const
  # free constants
  IP_ADDR_ADDED*: int32 = 11023'i32
  IP_ADDR_DELETED*: int32 = 11019'i32
  IP_BAD_DESTINATION*: int32 = 11018'i32
  IP_BAD_HEADER*: int32 = 11042'i32
  IP_BAD_OPTION*: int32 = 11007'i32
  IP_BAD_REQ*: int32 = 11011'i32
  IP_BAD_ROUTE*: int32 = 11012'i32
  IP_BIND_ADAPTER*: int32 = 11026'i32
  IP_BUF_TOO_SMALL*: int32 = 11001'i32
  IP_DEST_ADDR_UNREACHABLE*: int32 = 11003'i32
  IP_DEST_HOST_UNREACHABLE*: int32 = 11003'i32
  IP_DEST_NET_UNREACHABLE*: int32 = 11002'i32
  IP_DEST_NO_ROUTE*: int32 = 11002'i32
  IP_DEST_PORT_UNREACHABLE*: int32 = 11005'i32
  IP_DEST_PROHIBITED*: int32 = 11004'i32
  IP_DEST_PROT_UNREACHABLE*: int32 = 11004'i32
  IP_DEST_SCOPE_MISMATCH*: int32 = 11045'i32
  IP_DEST_UNREACHABLE*: int32 = 11040'i32
  IP_DEVICE_DOES_NOT_EXIST*: int32 = 11028'i32
  IP_DUPLICATE_ADDRESS*: int32 = 11029'i32
  IP_DUPLICATE_IPADD*: int32 = 11034'i32
  IP_EXPORT_INCLUDED*: int32 = 1'i32
  IP_FLAG_DF*: int32 = 2'i32
  IP_FLAG_REVERSE*: int32 = 1'i32
  IP_GENERAL_FAILURE*: int32 = 11050'i32
  IP_HOP_LIMIT_EXCEEDED*: int32 = 11013'i32
  IP_HW_ERROR*: int32 = 11008'i32
  IP_ICMP_ERROR*: int32 = 11044'i32
  IP_INTERFACE_METRIC_CHANGE*: int32 = 11030'i32
  IP_INTERFACE_WOL_CAPABILITY_CHANGE*: int32 = 11033'i32
  IP_MEDIA_CONNECT*: int32 = 11024'i32
  IP_MEDIA_DISCONNECT*: int32 = 11025'i32
  IP_MTU_CHANGE*: int32 = 11021'i32
  IP_NEGOTIATING_IPSEC*: int32 = 11032'i32
  IP_NO_RESOURCES*: int32 = 11006'i32
  IP_OPTION_TOO_BIG*: int32 = 11017'i32
  IP_OPT_EOL*: int32 = 0'i32
  IP_OPT_LSRR*: int32 = 131'i32
  IP_OPT_NOP*: int32 = 1'i32
  IP_OPT_ROUTER_ALERT*: int32 = 148'i32
  IP_OPT_RR*: int32 = 7'i32
  IP_OPT_SECURITY*: int32 = 130'i32
  IP_OPT_SID*: int32 = 136'i32
  IP_OPT_SSRR*: int32 = 137'i32
  IP_OPT_TS*: int32 = 68'i32
  IP_PACKET_TOO_BIG*: int32 = 11009'i32
  IP_PARAMETER_PROBLEM*: int32 = 11015'i32
  IP_PARAM_PROBLEM*: int32 = 11015'i32
  IP_PENDING*: int32 = 11255'i32
  IP_REASSEMBLY_TIME_EXCEEDED*: int32 = 11014'i32
  IP_RECONFIG_SECFLTR*: int32 = 11031'i32
  IP_REQ_TIMED_OUT*: int32 = 11010'i32
  IP_SOURCE_QUENCH*: int32 = 11016'i32
  IP_SPEC_MTU_CHANGE*: int32 = 11020'i32
  IP_STATUS_BASE*: int32 = 11000'i32
  IP_SUCCESS*: int32 = 0'i32
  IP_TIME_EXCEEDED*: int32 = 11041'i32
  IP_TTL_EXPIRED_REASSEM*: int32 = 11014'i32
  IP_TTL_EXPIRED_TRANSIT*: int32 = 11013'i32
  IP_UNBIND_ADAPTER*: int32 = 11027'i32
  IP_UNLOAD*: int32 = 11022'i32
  IP_UNRECOGNIZED_NEXT_HEADER*: int32 = 11043'i32
  MAX_ADAPTER_NAME*: int32 = 128'i32
  MAX_IP_STATUS*: int32 = 11050'i32
  MAX_OPT_SIZE*: int32 = 40'i32

