# generated by winmd2nim from Windows.Win32.winmd — lmcons (do not edit)

const
  # free constants
  ALERTSZ*: int32 = 128'i32
  CLTYPE_LEN*: int32 = 12'i32
  CNLEN*: int32 = 15'i32
  CRYPT_KEY_LEN*: int32 = 7'i32
  CRYPT_TXT_LEN*: int32 = 8'i32
  DEVLEN*: int32 = 80'i32
  DNLEN*: int32 = 15'i32
  ENCRYPTED_PWLEN*: int32 = 16'i32
  EVLEN*: int32 = 16'i32
  GNLEN*: int32 = 256'i32
  LM20_CNLEN*: int32 = 15'i32
  LM20_DEVLEN*: int32 = 8'i32
  LM20_DNLEN*: int32 = 15'i32
  LM20_GNLEN*: int32 = 20'i32
  LM20_MAXCOMMENTSZ*: int32 = 48'i32
  LM20_NNLEN*: int32 = 12'i32
  LM20_PATHLEN*: int32 = 256'i32
  LM20_PWLEN*: int32 = 14'i32
  LM20_QNLEN*: int32 = 12'i32
  LM20_RMLEN*: int32 = 30'i32
  LM20_SNLEN*: int32 = 15'i32
  LM20_STXTLEN*: int32 = 63'i32
  LM20_UNCLEN*: int32 = 17'i32
  LM20_UNLEN*: int32 = 20'i32
  LM_DNS_MAX_NAME_LENGTH*: int32 = 255'i32
  MAXCOMMENTSZ*: int32 = 256'i32
  MAX_LANMAN_MESSAGE_ID*: int32 = 5899'i32
  MAX_PREFERRED_LENGTH*: uint32 = 0xffffffff'u32
  MIN_LANMAN_MESSAGE_ID*: int32 = 2100'i32
  NETBIOS_NAME_LEN*: int32 = 16'i32
  NNLEN*: int32 = 80'i32
  PARMNUM_ALL*: int32 = 0'i32
  PARMNUM_BASE_INFOLEVEL*: int32 = 1000'i32
  PARM_ERROR_NONE*: int32 = 0'i32
  PARM_ERROR_UNKNOWN*: uint32 = 0xffffffff'u32
  PATHLEN*: int32 = 256'i32
  PLATFORM_ID_DOS*: int32 = 300'i32
  PLATFORM_ID_NT*: int32 = 500'i32
  PLATFORM_ID_OS2*: int32 = 400'i32
  PLATFORM_ID_OSF*: int32 = 600'i32
  PLATFORM_ID_VMS*: int32 = 700'i32
  PWLEN*: int32 = 256'i32
  QNLEN*: int32 = 80'i32
  RMLEN*: int32 = 98'i32
  SESSION_CRYPT_KLEN*: int32 = 21'i32
  SESSION_PWLEN*: int32 = 24'i32
  SHPWLEN*: int32 = 8'i32
  SNLEN*: int32 = 80'i32
  STXTLEN*: int32 = 256'i32
  UNCLEN*: int32 = 17'i32
  UNLEN*: int32 = 256'i32

