# generated by winmd2nim from Windows.Win32.winmd — lmremutl (do not edit)
import ./[winnt, minwindef]
export winnt, minwindef

type

  # structs
  TIME_OF_DAY_INFO* {.completeStruct.} = object
    tod_elapsedt*: uint32
    tod_msecs*: uint32
    tod_hours*: uint32
    tod_mins*: uint32
    tod_secs*: uint32
    tod_hunds*: uint32
    tod_timezone*: int32
    tod_tinterval*: uint32
    tod_day*: uint32
    tod_month*: uint32
    tod_year*: uint32
    tod_weekday*: uint32

  # typdefs
  DESC_CHAR* = distinct int8
  LPDESC* = PSTR
  LPTIME_OF_DAY_INFO* = ptr TIME_OF_DAY_INFO
  PTIME_OF_DAY_INFO* = ptr TIME_OF_DAY_INFO

const
  # free constants
  ALLOCATE_RESPONSE*: int32 = 2'i32
  NO_PERMISSION_REQUIRED*: int32 = 1'i32
  SUPPORTS_ANY*: uint32 = 0xffffffff'u32
  SUPPORTS_LOCAL*: int32 = 32'i32
  SUPPORTS_REMOTE_ADMIN_PROTOCOL*: int32 = 2'i32
  SUPPORTS_RPC*: int32 = 4'i32
  SUPPORTS_SAM_PROTOCOL*: int32 = 8'i32
  SUPPORTS_UNICODE*: int32 = 16'i32
  USE_SPECIFIC_TRANSPORT*: uint32 = 0x80000000'u32

{.push dynlib: "netapi32".}
proc NetRemoteComputerSupports*(UncServerName: PCWSTR, OptionsWanted: uint32, OptionsSupported: ptr uint32): uint32 {.sideEffect, importc, stdcall.}
proc NetRemoteTOD*(UncServerName: PCWSTR, BufferPtr: ptr LPBYTE): uint32 {.sideEffect, importc, stdcall.}
{.pop.}
