# generated by winmd2nim from Windows.Win32.winmd — lmsvc (do not edit)
import ./[winnt, minwindef]
export winnt, minwindef

type

  # structs
  SERVICE_INFO_0* {.completeStruct.} = object
    svci0_name*: PWSTR
  SERVICE_INFO_1* {.completeStruct.} = object
    svci1_name*: PWSTR
    svci1_status*: uint32
    svci1_code*: uint32
    svci1_pid*: uint32
  SERVICE_INFO_2* {.completeStruct.} = object
    svci2_name*: PWSTR
    svci2_status*: uint32
    svci2_code*: uint32
    svci2_pid*: uint32
    svci2_text*: PWSTR
    svci2_specific_error*: uint32
    svci2_display_name*: PWSTR

  # typdefs
  LPSERVICE_INFO_0* = ptr SERVICE_INFO_0
  LPSERVICE_INFO_1* = ptr SERVICE_INFO_1
  LPSERVICE_INFO_2* = ptr SERVICE_INFO_2
  PSERVICE_INFO_0* = ptr SERVICE_INFO_0
  PSERVICE_INFO_1* = ptr SERVICE_INFO_1
  PSERVICE_INFO_2* = ptr SERVICE_INFO_2

const
  # free constants
  LM20_SERVICE_ACTIVE*: int32 = 0'i32
  LM20_SERVICE_CONTINUE_PENDING*: int32 = 4'i32
  LM20_SERVICE_PAUSED*: int32 = 12'i32
  LM20_SERVICE_PAUSE_PENDING*: int32 = 8'i32
  LOWER_GET_HINT_MASK*: int32 = 65280'i32
  LOWER_HINT_MASK*: int32 = 255'i32
  SERVICE2_BASE*: int32 = 5600'i32
  SERVICE_BASE*: int32 = 3050'i32
  SERVICE_CCP_CHKPT_NUM*: int32 = 255'i32
  SERVICE_CCP_NO_HINT*: int32 = 0'i32
  SERVICE_CCP_QUERY_HINT*: int32 = 65536'i32
  SERVICE_CCP_WAIT_TIME*: int32 = 65280'i32
  SERVICE_CTRL_CONTINUE*: int32 = 2'i32
  SERVICE_CTRL_INTERROGATE*: int32 = 0'i32
  SERVICE_CTRL_PAUSE*: int32 = 1'i32
  SERVICE_CTRL_REDIR_COMM*: int32 = 4'i32
  SERVICE_CTRL_REDIR_DISK*: int32 = 1'i32
  SERVICE_CTRL_REDIR_PRINT*: int32 = 2'i32
  SERVICE_CTRL_UNINSTALL*: int32 = 3'i32
  # SERVICE_DOS_ENCRYPTION = "ENCRYPT"  # TODO: wide string constant (utf-16)
  SERVICE_INSTALLED*: int32 = 3'i32
  SERVICE_INSTALL_PENDING*: int32 = 1'i32
  SERVICE_INSTALL_STATE*: int32 = 3'i32
  SERVICE_IP_CHKPT_NUM*: int32 = 255'i32
  SERVICE_IP_NO_HINT*: int32 = 0'i32
  SERVICE_IP_QUERY_HINT*: int32 = 65536'i32
  SERVICE_IP_WAITTIME_SHIFT*: int32 = 8'i32
  SERVICE_IP_WAIT_TIME*: int32 = 65280'i32
  SERVICE_MAXTIME*: int32 = 255'i32
  SERVICE_NOT_PAUSABLE*: int32 = 0'i32
  SERVICE_NOT_UNINSTALLABLE*: int32 = 0'i32
  SERVICE_NTIP_WAITTIME_SHIFT*: int32 = 12'i32
  SERVICE_NT_MAXTIME*: int32 = 65535'i32
  SERVICE_PAUSABLE*: int32 = 32'i32
  SERVICE_PAUSE_STATE*: int32 = 12'i32
  SERVICE_REDIR_COMM_PAUSED*: int32 = 1024'i32
  SERVICE_REDIR_DISK_PAUSED*: int32 = 256'i32
  SERVICE_REDIR_PAUSED*: int32 = 1792'i32
  SERVICE_REDIR_PRINT_PAUSED*: int32 = 512'i32
  SERVICE_RESRV_MASK*: int32 = 131071'i32
  SERVICE_UIC_AMBIGPARM*: int32 = 3058'i32
  SERVICE_UIC_BADPARMVAL*: int32 = 3051'i32
  SERVICE_UIC_CONFIG*: int32 = 3055'i32
  SERVICE_UIC_CONFLPARM*: int32 = 3063'i32
  SERVICE_UIC_DUPPARM*: int32 = 3059'i32
  SERVICE_UIC_EXEC*: int32 = 3061'i32
  SERVICE_UIC_FILE*: int32 = 3064'i32
  SERVICE_UIC_INTERNAL*: int32 = 3057'i32
  SERVICE_UIC_KILL*: int32 = 3060'i32
  SERVICE_UIC_MISSPARM*: int32 = 3052'i32
  SERVICE_UIC_M_ADDPAK*: int32 = 3090'i32
  SERVICE_UIC_M_ANNOUNCE*: int32 = 3083'i32
  SERVICE_UIC_M_DATABASE_ERROR*: int32 = 5602'i32
  SERVICE_UIC_M_DISK*: int32 = 3071'i32
  SERVICE_UIC_M_ERRLOG*: int32 = 3088'i32
  SERVICE_UIC_M_FILES*: int32 = 3079'i32
  SERVICE_UIC_M_FILE_UW*: int32 = 3089'i32
  SERVICE_UIC_M_LANGROUP*: int32 = 3081'i32
  SERVICE_UIC_M_LANROOT*: int32 = 3075'i32
  SERVICE_UIC_M_LAZY*: int32 = 3091'i32
  SERVICE_UIC_M_LOGS*: int32 = 3080'i32
  SERVICE_UIC_M_LSA_MACHINE_ACCT*: int32 = 5601'i32
  SERVICE_UIC_M_MEMORY*: int32 = 3070'i32
  SERVICE_UIC_M_MSGNAME*: int32 = 3082'i32
  SERVICE_UIC_M_NETLOGON_AUTH*: int32 = 3098'i32
  SERVICE_UIC_M_NETLOGON_DC_CFLCT*: int32 = 3097'i32
  SERVICE_UIC_M_NETLOGON_MPATH*: int32 = 5600'i32
  SERVICE_UIC_M_NETLOGON_NO_DC*: int32 = 3096'i32
  SERVICE_UIC_M_NULL*: int32 = 0'i32
  SERVICE_UIC_M_PROCESSES*: int32 = 3073'i32
  SERVICE_UIC_M_REDIR*: int32 = 3076'i32
  SERVICE_UIC_M_SECURITY*: int32 = 3074'i32
  SERVICE_UIC_M_SEC_FILE_ERR*: int32 = 3078'i32
  SERVICE_UIC_M_SERVER*: int32 = 3077'i32
  SERVICE_UIC_M_SERVER_SEC_ERR*: int32 = 3085'i32
  SERVICE_UIC_M_THREADS*: int32 = 3072'i32
  SERVICE_UIC_M_UAS*: int32 = 3084'i32
  SERVICE_UIC_M_UAS_INVALID_ROLE*: int32 = 3095'i32
  SERVICE_UIC_M_UAS_MACHINE_ACCT*: int32 = 3092'i32
  SERVICE_UIC_M_UAS_PROLOG*: int32 = 3099'i32
  SERVICE_UIC_M_UAS_SERVERS_NMEMB*: int32 = 3093'i32
  SERVICE_UIC_M_UAS_SERVERS_NOGRP*: int32 = 3094'i32
  SERVICE_UIC_M_WKSTA*: int32 = 3087'i32
  SERVICE_UIC_NORMAL*: int32 = 0'i32
  SERVICE_UIC_RESOURCE*: int32 = 3054'i32
  SERVICE_UIC_SUBSERV*: int32 = 3062'i32
  SERVICE_UIC_SYSTEM*: int32 = 3056'i32
  SERVICE_UIC_UNKPARM*: int32 = 3053'i32
  SERVICE_UNINSTALLABLE*: int32 = 16'i32
  SERVICE_UNINSTALLED*: int32 = 0'i32
  SERVICE_UNINSTALL_PENDING*: int32 = 2'i32
  UPPER_GET_HINT_MASK*: int32 = 267386880'i32
  UPPER_HINT_MASK*: int32 = 65280'i32

{.push dynlib: "netapi32".}
proc NetServiceControl*(servername: PCWSTR, service: PCWSTR, opcode: uint32, arg: uint32, bufptr: ptr LPBYTE): uint32 {.sideEffect, importc, stdcall.}
proc NetServiceEnum*(servername: PCWSTR, level: uint32, bufptr: ptr LPBYTE, prefmaxlen: uint32, entriesread: ptr uint32, totalentries: ptr uint32, resume_handle: ptr uint32): uint32 {.sideEffect, importc, stdcall.}
proc NetServiceGetInfo*(servername: PCWSTR, service: PCWSTR, level: uint32, bufptr: ptr LPBYTE): uint32 {.sideEffect, importc, stdcall.}
proc NetServiceInstall*(servername: PCWSTR, service: PCWSTR, argc: uint32, argv: ptr PCWSTR, bufptr: ptr LPBYTE): uint32 {.sideEffect, importc, stdcall.}
{.pop.}
