# generated by winmd2nim from Windows.Win32.winmd — lsalookup (do not edit)
import ./[winnt, guiddef]
export winnt, guiddef

type

  # structs
  LSA_OBJECT_ATTRIBUTES* {.completeStruct.} = object
    Length*: uint32
    RootDirectory*: HANDLE
    ObjectName*: PLSA_UNICODE_STRING
    Attributes*: uint32
    SecurityDescriptor*: pointer
    SecurityQualityOfService*: pointer
  LSA_REFERENCED_DOMAIN_LIST* {.completeStruct.} = object
    Entries*: uint32
    Domains*: PLSA_TRUST_INFORMATION
  LSA_STRING* {.completeStruct.} = object
    Length*: uint16
    MaximumLength*: uint16
    Buffer*: PCHAR
  LSA_TRANSLATED_NAME* {.completeStruct.} = object
    Use*: SID_NAME_USE
    Name*: LSA_UNICODE_STRING
    DomainIndex*: int32
  LSA_TRANSLATED_SID2* {.completeStruct.} = object
    Use*: SID_NAME_USE
    Sid*: PSID
    DomainIndex*: int32
    Flags*: uint32
  LSA_TRUST_INFORMATION* {.completeStruct.} = object
    Name*: LSA_UNICODE_STRING
    Sid*: PSID
  LSA_UNICODE_STRING* {.completeStruct.} = object
    Length*: uint16
    MaximumLength*: uint16
    Buffer*: PWSTR
  POLICY_ACCOUNT_DOMAIN_INFO* {.completeStruct.} = object
    DomainName*: LSA_UNICODE_STRING
    DomainSid*: PSID
  POLICY_DNS_DOMAIN_INFO* {.completeStruct.} = object
    Name*: LSA_UNICODE_STRING
    DnsDomainName*: LSA_UNICODE_STRING
    DnsForestName*: LSA_UNICODE_STRING
    DomainGuid*: GUID
    Sid*: PSID

  # typdefs
  LSA_LOOKUP_HANDLE* = distinct pointer
  PLSA_LOOKUP_DOMAIN_INFO_CLASS* = distinct ptr LSA_LOOKUP_DOMAIN_INFO_CLASS
  PLSA_LOOKUP_HANDLE* = distinct ptr pointer
  PLSA_OBJECT_ATTRIBUTES* = ptr LSA_OBJECT_ATTRIBUTES
  PLSA_REFERENCED_DOMAIN_LIST* = ptr LSA_REFERENCED_DOMAIN_LIST
  PLSA_STRING* = ptr LSA_STRING
  PLSA_TRANSLATED_NAME* = ptr LSA_TRANSLATED_NAME
  PLSA_TRANSLATED_SID2* = ptr LSA_TRANSLATED_SID2
  PLSA_TRUST_INFORMATION* = ptr LSA_TRUST_INFORMATION
  PLSA_UNICODE_STRING* = ptr LSA_UNICODE_STRING
  PPOLICY_ACCOUNT_DOMAIN_INFO* = ptr POLICY_ACCOUNT_DOMAIN_INFO
  PPOLICY_DNS_DOMAIN_INFO* = ptr POLICY_DNS_DOMAIN_INFO

  # unscoped enums 
  LSA_LOOKUP_DOMAIN_INFO_CLASS* = int32

const
  # free constants
  LOOKUP_TRANSLATE_NAMES*: int32 = 2048'i32
  LOOKUP_VIEW_LOCAL_INFORMATION*: int32 = 1'i32

  # unscoped enum members
  AccountDomainInformation*: LSA_LOOKUP_DOMAIN_INFO_CLASS = 5'i32
  DnsDomainInformation*: LSA_LOOKUP_DOMAIN_INFO_CLASS = 12'i32

