# generated by winmd2nim from Windows.Win32.winmd — lzexpand (do not edit)
import ./[winbase, winnt]
export winbase, winnt

const
  # free constants
  LZERROR_BADINHANDLE*: int32 = -1'i32
  LZERROR_BADOUTHANDLE*: int32 = -2'i32
  LZERROR_BADVALUE*: int32 = -7'i32
  LZERROR_GLOBALLOC*: int32 = -5'i32
  LZERROR_GLOBLOCK*: int32 = -6'i32
  LZERROR_READ*: int32 = -3'i32
  LZERROR_UNKNOWNALG*: int32 = -8'i32
  LZERROR_WRITE*: int32 = -4'i32

{.push dynlib: "lz32".}
proc CopyLZFile*(hfSource: int32, hfDest: int32): int32 {.sideEffect, importc, stdcall.}
proc GetExpandedNameA*(lpszSource: PCSTR, lpszBuffer: PSTR): int32 {.sideEffect, importc, stdcall.}
proc GetExpandedNameW*(lpszSource: PCWSTR, lpszBuffer: PWSTR): int32 {.sideEffect, importc, stdcall.}
proc LZClose*(hFile: int32) {.sideEffect, importc, stdcall.}
proc LZCopy*(hfSource: int32, hfDest: int32): int32 {.sideEffect, importc, stdcall.}
proc LZDone*() {.sideEffect, importc, stdcall.}
proc LZInit*(hfSource: int32): int32 {.sideEffect, importc, stdcall.}
proc LZOpenFileA*(lpFileName: PCSTR, lpReOpenBuf: ptr OFSTRUCT, wStyle: uint16): int32 {.sideEffect, importc, stdcall.}
proc LZOpenFileW*(lpFileName: PCWSTR, lpReOpenBuf: ptr OFSTRUCT, wStyle: uint16): int32 {.sideEffect, importc, stdcall.}
proc LZRead*(hFile: int32, lpBuffer: ptr int8, cbRead: int32): int32 {.sideEffect, importc, stdcall.}
proc LZSeek*(hFile: int32, lOffset: int32, iOrigin: int32): int32 {.sideEffect, importc, stdcall.}
proc LZStart*(): int32 {.sideEffect, importc, stdcall.}
{.pop.}
