# generated by winmd2nim from Windows.Win32.winmd — mce (do not edit)

type

  # structs
  MCA_EXCEPTION_5_1* {.completeStruct.} = object
    Address*: uint64
    Type*: uint64
  MCI_ADDR* {.completeStruct, union.} = object
    Anonymous*: MCI_ADDR_0
    QuadPart*: uint64
  MCI_ADDR_0* {.completeStruct.} = object
    Address*: uint32
    Reserved*: uint32
  MCI_STATS_I386* {.completeStruct, union.} = object
    MciStats*: MCI_STATS_0_I386
    QuadPart*: uint64
  MCI_STATS_0_I386* {.completeStruct.} = object
    McaCod*: uint16
    MsCod*: uint16
    X_bitfield*: uint32
  MCI_STATS_AMD64* {.completeStruct, union.} = object
    MciStatus*: MCI_STATS_0_AMD64
    QuadPart*: uint64
  MCI_STATS_0_AMD64* {.completeStruct.} = object
    McaErrorCode*: uint16
    ModelErrorCode*: uint16
    X_bitfield*: uint32

  # typdefs
  ERROR_SEVERITY* = distinct uint8
  PERROR_SEVERITY* = distinct ptr uint8
  PMCI_ADDR* = ptr MCI_ADDR

  # unscoped enums 
  ERROR_SEVERITY_VALUE* = int32
  MCA_EXCEPTION_TYPE* = int32

when defined(i386):
  type MCI_STATS* = MCI_STATS_I386
elif defined(amd64):
  type MCI_STATS* = MCI_STATS_AMD64
else:
  type MCI_STATS* = MCI_STATS_I386
when defined(i386):
  type MCI_STATS_0* = MCI_STATS_0_I386
elif defined(amd64):
  type MCI_STATS_0* = MCI_STATS_0_AMD64
else:
  type MCI_STATS_0* = MCI_STATS_0_I386

type

  # structs
  MCA_EXCEPTION* {.completeStruct.} = object
    VersionNumber*: uint32
    ExceptionType*: MCA_EXCEPTION_TYPE
    TimeStamp*: int64
    ProcessorNumber*: uint32
    Reserved1*: uint32
    u*: MCA_EXCEPTION_5
    ExtCnt*: uint32
    Reserved3*: uint32
    ExtReg*: array[24, uint64]
  MCA_EXCEPTION_5* {.completeStruct, union.} = object
    Mca*: MCA_EXCEPTION_5_0
    Mce*: MCA_EXCEPTION_5_1
  MCA_EXCEPTION_5_0* {.completeStruct.} = object
    BankNumber*: uint8
    Reserved2*: array[7, uint8]
    Status*: MCI_STATS
    Address*: MCI_ADDR
    Misc*: uint64
  MCA_EXCEPTION_2* {.completeStruct.} = object
    Dummy*: uint32

  # typdefs
  CMC_EXCEPTION* = MCA_EXCEPTION_2
  CPE_EXCEPTION* = MCA_EXCEPTION_2
  PCMC_EXCEPTION* = ptr MCA_EXCEPTION_2
  PCMC_EXCEPTION_2* = distinct pointer
  PCPE_EXCEPTION* = ptr MCA_EXCEPTION_2
  PCPE_EXCEPTION_2* = distinct pointer
  PMCA_EXCEPTION* = ptr MCA_EXCEPTION_2
  PMCI_STATS* = ptr MCI_STATS

const
  # free constants
  MCA_EXCEPTION_V1_SIZE*: int32 = 56'i32
  MCA_EXTREG_V2MAX*: int32 = 24'i32

  # unscoped enum members
  ErrorRecoverable*: ERROR_SEVERITY_VALUE = 0'i32
  ErrorFatal*: ERROR_SEVERITY_VALUE = 1'i32
  ErrorCorrected*: ERROR_SEVERITY_VALUE = 2'i32
  ErrorOthers*: ERROR_SEVERITY_VALUE = 3'i32
  HAL_MCE_RECORD*: MCA_EXCEPTION_TYPE = 0'i32
  HAL_MCA_RECORD*: MCA_EXCEPTION_TYPE = 1'i32

