# generated by winmd2nim from Windows.Win32.winmd — mciapi (do not edit)
import ./[winnt, windef, minwindef]
export winnt, windef, minwindef

type

  # structs
  MCI_ANIM_OPEN_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCSTR
    lpstrElementName*: PCSTR
    lpstrAlias*: PCSTR
    dwStyle*: uint32
    hWndParent*: HWND
  MCI_ANIM_OPEN_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCWSTR
    lpstrElementName*: PCWSTR
    lpstrAlias*: PCWSTR
    dwStyle*: uint32
    hWndParent*: HWND
  MCI_ANIM_PLAY_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrom*: uint32
    dwTo*: uint32
    dwSpeed*: uint32
  MCI_ANIM_RECT_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    rc*: RECT
  MCI_ANIM_STEP_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrames*: uint32
  MCI_ANIM_UPDATE_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    rc*: RECT
    hDC*: HDC
  MCI_ANIM_WINDOW_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    hWnd*: HWND
    nCmdShow*: uint32
    lpstrText*: PCSTR
  MCI_ANIM_WINDOW_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    hWnd*: HWND
    nCmdShow*: uint32
    lpstrText*: PCWSTR
  MCI_BREAK_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    nVirtKey*: int32
    hwndBreak*: HWND
  MCI_GENERIC_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
  MCI_GETDEVCAPS_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwReturn*: uint32
    dwItem*: uint32
  MCI_INFO_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpstrReturn*: PSTR
    dwRetSize*: uint32
  MCI_INFO_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpstrReturn*: PWSTR
    dwRetSize*: uint32
  MCI_LOAD_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCSTR
  MCI_LOAD_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCWSTR
  MCI_OPEN_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCSTR
    lpstrElementName*: PCSTR
    lpstrAlias*: PCSTR
  MCI_OPEN_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCWSTR
    lpstrElementName*: PCWSTR
    lpstrAlias*: PCWSTR
  MCI_OVLY_LOAD_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCSTR
    rc*: RECT
  MCI_OVLY_LOAD_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCWSTR
    rc*: RECT
  MCI_OVLY_OPEN_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCSTR
    lpstrElementName*: PCSTR
    lpstrAlias*: PCSTR
    dwStyle*: uint32
    hWndParent*: HWND
  MCI_OVLY_OPEN_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCWSTR
    lpstrElementName*: PCWSTR
    lpstrAlias*: PCWSTR
    dwStyle*: uint32
    hWndParent*: HWND
  MCI_OVLY_RECT_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    rc*: RECT
  MCI_OVLY_SAVE_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCSTR
    rc*: RECT
  MCI_OVLY_SAVE_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCWSTR
    rc*: RECT
  MCI_OVLY_WINDOW_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    hWnd*: HWND
    nCmdShow*: uint32
    lpstrText*: PCSTR
  MCI_OVLY_WINDOW_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    hWnd*: HWND
    nCmdShow*: uint32
    lpstrText*: PCWSTR
  MCI_PLAY_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrom*: uint32
    dwTo*: uint32
  MCI_RECORD_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrom*: uint32
    dwTo*: uint32
  MCI_SAVE_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCSTR
  MCI_SAVE_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpfilename*: PCWSTR
  MCI_SEEK_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwTo*: uint32
  MCI_SEQ_SET_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwTimeFormat*: uint32
    dwAudio*: uint32
    dwTempo*: uint32
    dwPort*: uint32
    dwSlave*: uint32
    dwMaster*: uint32
    dwOffset*: uint32
  MCI_SET_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwTimeFormat*: uint32
    dwAudio*: uint32
  MCI_STATUS_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwReturn*: uint
    dwItem*: uint32
    dwTrack*: uint32
  MCI_SYSINFO_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpstrReturn*: PSTR
    dwRetSize*: uint32
    dwNumber*: uint32
    wDeviceType*: uint32
  MCI_SYSINFO_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpstrReturn*: PWSTR
    dwRetSize*: uint32
    dwNumber*: uint32
    wDeviceType*: uint32
  MCI_VD_ESCAPE_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpstrCommand*: PCSTR
  MCI_VD_ESCAPE_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    lpstrCommand*: PCWSTR
  MCI_VD_PLAY_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrom*: uint32
    dwTo*: uint32
    dwSpeed*: uint32
  MCI_VD_STEP_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrames*: uint32
  MCI_WAVE_DELETE_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwFrom*: uint32
    dwTo*: uint32
  MCI_WAVE_OPEN_PARMSA* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCSTR
    lpstrElementName*: PCSTR
    lpstrAlias*: PCSTR
    dwBufferSeconds*: uint32
  MCI_WAVE_OPEN_PARMSW* {.completeStruct, packed.} = object
    dwCallback*: uint
    wDeviceID*: MCIDEVICEID
    lpstrDeviceType*: PCWSTR
    lpstrElementName*: PCWSTR
    lpstrAlias*: PCWSTR
    dwBufferSeconds*: uint32
  MCI_WAVE_SET_PARMS* {.completeStruct, packed.} = object
    dwCallback*: uint
    dwTimeFormat*: uint32
    dwAudio*: uint32
    wInput*: uint32
    wOutput*: uint32
    wFormatTag*: uint16
    wReserved2*: uint16
    nChannels*: uint16
    wReserved3*: uint16
    nSamplesPerSec*: uint32
    nAvgBytesPerSec*: uint32
    nBlockAlign*: uint16
    wReserved4*: uint16
    wBitsPerSample*: uint16
    wReserved5*: uint16

  # typdefs
  LPMCI_ANIM_OPEN_PARMSA* = ptr MCI_ANIM_OPEN_PARMSA
  LPMCI_ANIM_OPEN_PARMSW* = ptr MCI_ANIM_OPEN_PARMSW
  LPMCI_ANIM_PLAY_PARMS* = ptr MCI_ANIM_PLAY_PARMS
  LPMCI_ANIM_RECT_PARMS* = ptr MCI_ANIM_RECT_PARMS
  LPMCI_ANIM_STEP_PARMS* = ptr MCI_ANIM_STEP_PARMS
  LPMCI_ANIM_UPDATE_PARMS* = ptr MCI_ANIM_UPDATE_PARMS
  LPMCI_ANIM_WINDOW_PARMSA* = ptr MCI_ANIM_WINDOW_PARMSA
  LPMCI_ANIM_WINDOW_PARMSW* = ptr MCI_ANIM_WINDOW_PARMSW
  LPMCI_BREAK_PARMS* = ptr MCI_BREAK_PARMS
  LPMCI_GENERIC_PARMS* = ptr MCI_GENERIC_PARMS
  LPMCI_GETDEVCAPS_PARMS* = ptr MCI_GETDEVCAPS_PARMS
  LPMCI_INFO_PARMSA* = ptr MCI_INFO_PARMSA
  LPMCI_INFO_PARMSW* = ptr MCI_INFO_PARMSW
  LPMCI_LOAD_PARMSA* = ptr MCI_LOAD_PARMSA
  LPMCI_LOAD_PARMSW* = ptr MCI_LOAD_PARMSW
  LPMCI_OPEN_PARMSA* = ptr MCI_OPEN_PARMSA
  LPMCI_OPEN_PARMSW* = ptr MCI_OPEN_PARMSW
  LPMCI_OVLY_LOAD_PARMSA* = ptr MCI_OVLY_LOAD_PARMSA
  LPMCI_OVLY_LOAD_PARMSW* = ptr MCI_OVLY_LOAD_PARMSW
  LPMCI_OVLY_OPEN_PARMSA* = ptr MCI_OVLY_OPEN_PARMSA
  LPMCI_OVLY_OPEN_PARMSW* = ptr MCI_OVLY_OPEN_PARMSW
  LPMCI_OVLY_RECT_PARMS* = ptr MCI_OVLY_RECT_PARMS
  LPMCI_OVLY_SAVE_PARMSA* = ptr MCI_OVLY_SAVE_PARMSA
  LPMCI_OVLY_SAVE_PARMSW* = ptr MCI_OVLY_SAVE_PARMSW
  LPMCI_OVLY_WINDOW_PARMSA* = ptr MCI_OVLY_WINDOW_PARMSA
  LPMCI_OVLY_WINDOW_PARMSW* = ptr MCI_OVLY_WINDOW_PARMSW
  LPMCI_PLAY_PARMS* = ptr MCI_PLAY_PARMS
  LPMCI_RECORD_PARMS* = ptr MCI_RECORD_PARMS
  LPMCI_SAVE_PARMSA* = ptr MCI_SAVE_PARMSA
  LPMCI_SAVE_PARMSW* = ptr MCI_SAVE_PARMSW
  LPMCI_SEEK_PARMS* = ptr MCI_SEEK_PARMS
  LPMCI_SEQ_SET_PARMS* = ptr MCI_SEQ_SET_PARMS
  LPMCI_SET_PARMS* = ptr MCI_SET_PARMS
  LPMCI_STATUS_PARMS* = ptr MCI_STATUS_PARMS
  LPMCI_SYSINFO_PARMSA* = ptr MCI_SYSINFO_PARMSA
  LPMCI_SYSINFO_PARMSW* = ptr MCI_SYSINFO_PARMSW
  LPMCI_VD_ESCAPE_PARMSA* = ptr MCI_VD_ESCAPE_PARMSA
  LPMCI_VD_ESCAPE_PARMSW* = ptr MCI_VD_ESCAPE_PARMSW
  LPMCI_VD_PLAY_PARMS* = ptr MCI_VD_PLAY_PARMS
  LPMCI_VD_STEP_PARMS* = ptr MCI_VD_STEP_PARMS
  LPMCI_WAVE_DELETE_PARMS* = ptr MCI_WAVE_DELETE_PARMS
  LPMCI_WAVE_OPEN_PARMSA* = ptr MCI_WAVE_OPEN_PARMSA
  LPMCI_WAVE_OPEN_PARMSW* = ptr MCI_WAVE_OPEN_PARMSW
  LPMCI_WAVE_SET_PARMS* = ptr MCI_WAVE_SET_PARMS
  MCIDEVICEID* = distinct uint32
  MCIERROR* = distinct uint32
  PMCI_ANIM_OPEN_PARMSA* = ptr MCI_ANIM_OPEN_PARMSA
  PMCI_ANIM_OPEN_PARMSW* = ptr MCI_ANIM_OPEN_PARMSW
  PMCI_ANIM_PLAY_PARMS* = ptr MCI_ANIM_PLAY_PARMS
  PMCI_ANIM_RECT_PARMS* = ptr MCI_ANIM_RECT_PARMS
  PMCI_ANIM_STEP_PARMS* = ptr MCI_ANIM_STEP_PARMS
  PMCI_ANIM_UPDATE_PARMS* = ptr MCI_ANIM_UPDATE_PARMS
  PMCI_ANIM_WINDOW_PARMSA* = ptr MCI_ANIM_WINDOW_PARMSA
  PMCI_ANIM_WINDOW_PARMSW* = ptr MCI_ANIM_WINDOW_PARMSW
  PMCI_BREAK_PARMS* = ptr MCI_BREAK_PARMS
  PMCI_GENERIC_PARMS* = ptr MCI_GENERIC_PARMS
  PMCI_GETDEVCAPS_PARMS* = ptr MCI_GETDEVCAPS_PARMS
  PMCI_LOAD_PARMSA* = ptr MCI_LOAD_PARMSA
  PMCI_LOAD_PARMSW* = ptr MCI_LOAD_PARMSW
  PMCI_OPEN_PARMSA* = ptr MCI_OPEN_PARMSA
  PMCI_OPEN_PARMSW* = ptr MCI_OPEN_PARMSW
  PMCI_OVLY_LOAD_PARMSA* = ptr MCI_OVLY_LOAD_PARMSA
  PMCI_OVLY_LOAD_PARMSW* = ptr MCI_OVLY_LOAD_PARMSW
  PMCI_OVLY_OPEN_PARMSA* = ptr MCI_OVLY_OPEN_PARMSA
  PMCI_OVLY_OPEN_PARMSW* = ptr MCI_OVLY_OPEN_PARMSW
  PMCI_OVLY_RECT_PARMS* = ptr MCI_OVLY_RECT_PARMS
  PMCI_OVLY_SAVE_PARMSA* = ptr MCI_OVLY_SAVE_PARMSA
  PMCI_OVLY_SAVE_PARMSW* = ptr MCI_OVLY_SAVE_PARMSW
  PMCI_OVLY_WINDOW_PARMSA* = ptr MCI_OVLY_WINDOW_PARMSA
  PMCI_OVLY_WINDOW_PARMSW* = ptr MCI_OVLY_WINDOW_PARMSW
  PMCI_PLAY_PARMS* = ptr MCI_PLAY_PARMS
  PMCI_SAVE_PARMSA* = ptr MCI_SAVE_PARMSA
  PMCI_SAVE_PARMSW* = ptr MCI_SAVE_PARMSW
  PMCI_SEEK_PARMS* = ptr MCI_SEEK_PARMS
  PMCI_SEQ_SET_PARMS* = ptr MCI_SEQ_SET_PARMS
  PMCI_SET_PARMS* = ptr MCI_SET_PARMS
  PMCI_STATUS_PARMS* = ptr MCI_STATUS_PARMS
  PMCI_SYSINFO_PARMSA* = ptr MCI_SYSINFO_PARMSA
  PMCI_SYSINFO_PARMSW* = ptr MCI_SYSINFO_PARMSW
  PMCI_VD_ESCAPE_PARMSA* = ptr MCI_VD_ESCAPE_PARMSA
  PMCI_VD_ESCAPE_PARMSW* = ptr MCI_VD_ESCAPE_PARMSW
  PMCI_VD_PLAY_PARMS* = ptr MCI_VD_PLAY_PARMS
  PMCI_VD_STEP_PARMS* = ptr MCI_VD_STEP_PARMS
  PMCI_WAVE_DELETE_PARMS* = ptr MCI_WAVE_DELETE_PARMS
  PMCI_WAVE_OPEN_PARMSA* = ptr MCI_WAVE_OPEN_PARMSA
  PMCI_WAVE_OPEN_PARMSW* = ptr MCI_WAVE_OPEN_PARMSW
  PMCI_WAVE_SET_PARMS* = ptr MCI_WAVE_SET_PARMS

  # delegates
  YIELDPROC* = proc (arg_1: MCIDEVICEID, arg_2: uint32): uint32 {.stdcall.}

const
  # free constants
  MCIERR_BAD_CONSTANT*: int32 = 290'i32
  MCIERR_BAD_INTEGER*: int32 = 270'i32
  MCIERR_BAD_TIME_FORMAT*: int32 = 293'i32
  MCIERR_CANNOT_LOAD_DRIVER*: int32 = 266'i32
  MCIERR_CANNOT_USE_ALL*: int32 = 279'i32
  MCIERR_CREATEWINDOW*: int32 = 347'i32
  MCIERR_CUSTOM_DRIVER_BASE*: int32 = 512'i32
  MCIERR_DEVICE_LENGTH*: int32 = 310'i32
  MCIERR_DEVICE_LOCKED*: int32 = 288'i32
  MCIERR_DEVICE_NOT_INSTALLED*: int32 = 306'i32
  MCIERR_DEVICE_NOT_READY*: int32 = 276'i32
  MCIERR_DEVICE_OPEN*: int32 = 265'i32
  MCIERR_DEVICE_ORD_LENGTH*: int32 = 311'i32
  MCIERR_DEVICE_TYPE_REQUIRED*: int32 = 287'i32
  MCIERR_DRIVER*: int32 = 278'i32
  MCIERR_DRIVER_INTERNAL*: int32 = 272'i32
  MCIERR_DUPLICATE_ALIAS*: int32 = 289'i32
  MCIERR_DUPLICATE_FLAGS*: int32 = 295'i32
  MCIERR_EXTENSION_NOT_FOUND*: int32 = 281'i32
  MCIERR_EXTRA_CHARACTERS*: int32 = 305'i32
  MCIERR_FILENAME_REQUIRED*: int32 = 304'i32
  MCIERR_FILE_NOT_FOUND*: int32 = 275'i32
  MCIERR_FILE_NOT_SAVED*: int32 = 286'i32
  MCIERR_FILE_READ*: int32 = 348'i32
  MCIERR_FILE_WRITE*: int32 = 349'i32
  MCIERR_FLAGS_NOT_COMPATIBLE*: int32 = 284'i32
  MCIERR_GET_CD*: int32 = 307'i32
  MCIERR_HARDWARE*: int32 = 262'i32
  MCIERR_ILLEGAL_FOR_AUTO_OPEN*: int32 = 303'i32
  MCIERR_INTERNAL*: int32 = 277'i32
  MCIERR_INVALID_DEVICE_ID*: int32 = 257'i32
  MCIERR_INVALID_DEVICE_NAME*: int32 = 263'i32
  MCIERR_INVALID_FILE*: int32 = 296'i32
  MCIERR_MISSING_COMMAND_STRING*: int32 = 267'i32
  MCIERR_MISSING_DEVICE_NAME*: int32 = 292'i32
  MCIERR_MISSING_PARAMETER*: int32 = 273'i32
  MCIERR_MISSING_STRING_ARGUMENT*: int32 = 269'i32
  MCIERR_MULTIPLE*: int32 = 280'i32
  MCIERR_MUST_USE_SHAREABLE*: int32 = 291'i32
  MCIERR_NEW_REQUIRES_ALIAS*: int32 = 299'i32
  MCIERR_NONAPPLICABLE_FUNCTION*: int32 = 302'i32
  MCIERR_NOTIFY_ON_AUTO_OPEN*: int32 = 300'i32
  MCIERR_NO_CLOSING_QUOTE*: int32 = 294'i32
  MCIERR_NO_ELEMENT_ALLOWED*: int32 = 301'i32
  MCIERR_NO_IDENTITY*: int32 = 350'i32
  MCIERR_NO_INTEGER*: int32 = 312'i32
  MCIERR_NO_WINDOW*: int32 = 346'i32
  MCIERR_NULL_PARAMETER_BLOCK*: int32 = 297'i32
  MCIERR_OUTOFRANGE*: int32 = 282'i32
  MCIERR_OUT_OF_MEMORY*: int32 = 264'i32
  MCIERR_PARAM_OVERFLOW*: int32 = 268'i32
  MCIERR_PARSER_INTERNAL*: int32 = 271'i32
  MCIERR_SEQ_DIV_INCOMPATIBLE*: int32 = 336'i32
  MCIERR_SEQ_NOMIDIPRESENT*: int32 = 343'i32
  MCIERR_SEQ_PORTUNSPECIFIED*: int32 = 342'i32
  MCIERR_SEQ_PORT_INUSE*: int32 = 337'i32
  MCIERR_SEQ_PORT_MAPNODEVICE*: int32 = 339'i32
  MCIERR_SEQ_PORT_MISCERROR*: int32 = 340'i32
  MCIERR_SEQ_PORT_NONEXISTENT*: int32 = 338'i32
  MCIERR_SEQ_TIMER*: int32 = 341'i32
  MCIERR_SET_CD*: int32 = 308'i32
  MCIERR_SET_DRIVE*: int32 = 309'i32
  MCIERR_UNNAMED_RESOURCE*: int32 = 298'i32
  MCIERR_UNRECOGNIZED_COMMAND*: int32 = 261'i32
  MCIERR_UNRECOGNIZED_KEYWORD*: int32 = 259'i32
  MCIERR_UNSUPPORTED_FUNCTION*: int32 = 274'i32
  MCIERR_WAVE_INPUTSINUSE*: int32 = 322'i32
  MCIERR_WAVE_INPUTSUNSUITABLE*: int32 = 328'i32
  MCIERR_WAVE_INPUTUNSPECIFIED*: int32 = 325'i32
  MCIERR_WAVE_OUTPUTSINUSE*: int32 = 320'i32
  MCIERR_WAVE_OUTPUTSUNSUITABLE*: int32 = 326'i32
  MCIERR_WAVE_OUTPUTUNSPECIFIED*: int32 = 324'i32
  MCIERR_WAVE_SETINPUTINUSE*: int32 = 323'i32
  MCIERR_WAVE_SETINPUTUNSUITABLE*: int32 = 329'i32
  MCIERR_WAVE_SETOUTPUTINUSE*: int32 = 321'i32
  MCIERR_WAVE_SETOUTPUTUNSUITABLE*: int32 = 327'i32
  MCI_ALL_DEVICE_ID*: MCIDEVICEID = MCIDEVICEID(0xffffffff'u32)
  MCI_ANIM_GETDEVCAPS_CAN_REVERSE*: int32 = 16385'i32
  MCI_ANIM_GETDEVCAPS_CAN_STRETCH*: int32 = 16391'i32
  MCI_ANIM_GETDEVCAPS_FAST_RATE*: int32 = 16386'i32
  MCI_ANIM_GETDEVCAPS_MAX_WINDOWS*: int32 = 16392'i32
  MCI_ANIM_GETDEVCAPS_NORMAL_RATE*: int32 = 16388'i32
  MCI_ANIM_GETDEVCAPS_PALETTES*: int32 = 16390'i32
  MCI_ANIM_GETDEVCAPS_SLOW_RATE*: int32 = 16387'i32
  MCI_ANIM_INFO_TEXT*: int32 = 65536'i32
  MCI_ANIM_OPEN_NOSTATIC*: int32 = 262144'i32
  MCI_ANIM_OPEN_PARENT*: int32 = 131072'i32
  MCI_ANIM_OPEN_WS*: int32 = 65536'i32
  MCI_ANIM_PLAY_FAST*: int32 = 262144'i32
  MCI_ANIM_PLAY_REVERSE*: int32 = 131072'i32
  MCI_ANIM_PLAY_SCAN*: int32 = 1048576'i32
  MCI_ANIM_PLAY_SLOW*: int32 = 524288'i32
  MCI_ANIM_PLAY_SPEED*: int32 = 65536'i32
  MCI_ANIM_PUT_DESTINATION*: int32 = 262144'i32
  MCI_ANIM_PUT_SOURCE*: int32 = 131072'i32
  MCI_ANIM_REALIZE_BKGD*: int32 = 131072'i32
  MCI_ANIM_REALIZE_NORM*: int32 = 65536'i32
  MCI_ANIM_RECT*: int32 = 65536'i32
  MCI_ANIM_STATUS_FORWARD*: int32 = 16386'i32
  MCI_ANIM_STATUS_HPAL*: int32 = 16388'i32
  MCI_ANIM_STATUS_HWND*: int32 = 16387'i32
  MCI_ANIM_STATUS_SPEED*: int32 = 16385'i32
  MCI_ANIM_STATUS_STRETCH*: int32 = 16389'i32
  MCI_ANIM_STEP_FRAMES*: int32 = 131072'i32
  MCI_ANIM_STEP_REVERSE*: int32 = 65536'i32
  MCI_ANIM_UPDATE_HDC*: int32 = 131072'i32
  MCI_ANIM_WHERE_DESTINATION*: int32 = 262144'i32
  MCI_ANIM_WHERE_SOURCE*: int32 = 131072'i32
  MCI_ANIM_WINDOW_DEFAULT*: int32 = 0'i32
  MCI_ANIM_WINDOW_DISABLE_STRETCH*: int32 = 2097152'i32
  MCI_ANIM_WINDOW_ENABLE_STRETCH*: int32 = 1048576'i32
  MCI_ANIM_WINDOW_HWND*: int32 = 65536'i32
  MCI_ANIM_WINDOW_STATE*: int32 = 262144'i32
  MCI_ANIM_WINDOW_TEXT*: int32 = 524288'i32
  MCI_BREAK*: int32 = 2065'i32
  MCI_BREAK_HWND*: int32 = 512'i32
  MCI_BREAK_KEY*: int32 = 256'i32
  MCI_BREAK_OFF*: int32 = 1024'i32
  MCI_CDA_STATUS_TYPE_TRACK*: int32 = 16385'i32
  MCI_CDA_TRACK_AUDIO*: int32 = 1088'i32
  MCI_CDA_TRACK_OTHER*: int32 = 1089'i32
  MCI_CLOSE*: int32 = 2052'i32
  MCI_COPY*: int32 = 2130'i32
  MCI_CUE*: int32 = 2096'i32
  MCI_CUT*: int32 = 2129'i32
  MCI_DELETE*: int32 = 2134'i32
  MCI_DEVTYPE_ANIMATION*: int32 = 519'i32
  MCI_DEVTYPE_CD_AUDIO*: int32 = 516'i32
  MCI_DEVTYPE_DAT*: int32 = 517'i32
  MCI_DEVTYPE_DIGITAL_VIDEO*: int32 = 520'i32
  MCI_DEVTYPE_FIRST*: int32 = 513'i32
  MCI_DEVTYPE_FIRST_USER*: int32 = 4096'i32
  MCI_DEVTYPE_LAST*: int32 = 523'i32
  MCI_DEVTYPE_OTHER*: int32 = 521'i32
  MCI_DEVTYPE_OVERLAY*: int32 = 515'i32
  MCI_DEVTYPE_SCANNER*: int32 = 518'i32
  MCI_DEVTYPE_SEQUENCER*: int32 = 523'i32
  MCI_DEVTYPE_VCR*: int32 = 513'i32
  MCI_DEVTYPE_VIDEODISC*: int32 = 514'i32
  MCI_DEVTYPE_WAVEFORM_AUDIO*: int32 = 522'i32
  MCI_ESCAPE*: int32 = 2053'i32
  MCI_FIRST*: int32 = 2048'i32
  MCI_FORMAT_BYTES*: int32 = 8'i32
  MCI_FORMAT_FRAMES*: int32 = 3'i32
  MCI_FORMAT_HMS*: int32 = 1'i32
  MCI_FORMAT_MILLISECONDS*: int32 = 0'i32
  MCI_FORMAT_MSF*: int32 = 2'i32
  MCI_FORMAT_SAMPLES*: int32 = 9'i32
  MCI_FORMAT_SMPTE_24*: int32 = 4'i32
  MCI_FORMAT_SMPTE_25*: int32 = 5'i32
  MCI_FORMAT_SMPTE_30*: int32 = 6'i32
  MCI_FORMAT_SMPTE_30DROP*: int32 = 7'i32
  MCI_FORMAT_TMSF*: int32 = 10'i32
  MCI_FREEZE*: int32 = 2116'i32
  MCI_FROM*: int32 = 4'i32
  MCI_GETDEVCAPS*: int32 = 2059'i32
  MCI_GETDEVCAPS_CAN_EJECT*: int32 = 7'i32
  MCI_GETDEVCAPS_CAN_PLAY*: int32 = 8'i32
  MCI_GETDEVCAPS_CAN_RECORD*: int32 = 1'i32
  MCI_GETDEVCAPS_CAN_SAVE*: int32 = 9'i32
  MCI_GETDEVCAPS_COMPOUND_DEVICE*: int32 = 6'i32
  MCI_GETDEVCAPS_DEVICE_TYPE*: int32 = 4'i32
  MCI_GETDEVCAPS_HAS_AUDIO*: int32 = 2'i32
  MCI_GETDEVCAPS_HAS_VIDEO*: int32 = 3'i32
  MCI_GETDEVCAPS_ITEM*: int32 = 256'i32
  MCI_GETDEVCAPS_USES_FILES*: int32 = 5'i32
  MCI_INFO*: int32 = 2058'i32
  MCI_INFO_COPYRIGHT*: int32 = 8192'i32
  MCI_INFO_FILE*: int32 = 512'i32
  MCI_INFO_MEDIA_IDENTITY*: int32 = 2048'i32
  MCI_INFO_MEDIA_UPC*: int32 = 1024'i32
  MCI_INFO_NAME*: int32 = 4096'i32
  MCI_INFO_PRODUCT*: int32 = 256'i32
  MCI_LAST*: int32 = 4095'i32
  MCI_LOAD*: int32 = 2128'i32
  MCI_LOAD_FILE*: int32 = 256'i32
  MCI_MODE_NOT_READY*: int32 = 524'i32
  MCI_MODE_OPEN*: int32 = 530'i32
  MCI_MODE_PAUSE*: int32 = 529'i32
  MCI_MODE_PLAY*: int32 = 526'i32
  MCI_MODE_RECORD*: int32 = 527'i32
  MCI_MODE_SEEK*: int32 = 528'i32
  MCI_MODE_STOP*: int32 = 525'i32
  MCI_NOTIFY*: int32 = 1'i32
  MCI_NOTIFY_ABORTED*: int32 = 4'i32
  MCI_NOTIFY_FAILURE*: int32 = 8'i32
  MCI_NOTIFY_SUCCESSFUL*: int32 = 1'i32
  MCI_NOTIFY_SUPERSEDED*: int32 = 2'i32
  MCI_OPEN*: int32 = 2051'i32
  MCI_OPEN_ALIAS*: int32 = 1024'i32
  MCI_OPEN_ELEMENT*: int32 = 512'i32
  MCI_OPEN_ELEMENT_ID*: int32 = 2048'i32
  MCI_OPEN_SHAREABLE*: int32 = 256'i32
  MCI_OPEN_TYPE*: int32 = 8192'i32
  MCI_OPEN_TYPE_ID*: int32 = 4096'i32
  MCI_OVLY_GETDEVCAPS_CAN_FREEZE*: int32 = 16386'i32
  MCI_OVLY_GETDEVCAPS_CAN_STRETCH*: int32 = 16385'i32
  MCI_OVLY_GETDEVCAPS_MAX_WINDOWS*: int32 = 16387'i32
  MCI_OVLY_INFO_TEXT*: int32 = 65536'i32
  MCI_OVLY_OPEN_PARENT*: int32 = 131072'i32
  MCI_OVLY_OPEN_WS*: int32 = 65536'i32
  MCI_OVLY_PUT_DESTINATION*: int32 = 262144'i32
  MCI_OVLY_PUT_FRAME*: int32 = 524288'i32
  MCI_OVLY_PUT_SOURCE*: int32 = 131072'i32
  MCI_OVLY_PUT_VIDEO*: int32 = 1048576'i32
  MCI_OVLY_RECT*: int32 = 65536'i32
  MCI_OVLY_STATUS_HWND*: int32 = 16385'i32
  MCI_OVLY_STATUS_STRETCH*: int32 = 16386'i32
  MCI_OVLY_WHERE_DESTINATION*: int32 = 262144'i32
  MCI_OVLY_WHERE_FRAME*: int32 = 524288'i32
  MCI_OVLY_WHERE_SOURCE*: int32 = 131072'i32
  MCI_OVLY_WHERE_VIDEO*: int32 = 1048576'i32
  MCI_OVLY_WINDOW_DEFAULT*: int32 = 0'i32
  MCI_OVLY_WINDOW_DISABLE_STRETCH*: int32 = 2097152'i32
  MCI_OVLY_WINDOW_ENABLE_STRETCH*: int32 = 1048576'i32
  MCI_OVLY_WINDOW_HWND*: int32 = 65536'i32
  MCI_OVLY_WINDOW_STATE*: int32 = 262144'i32
  MCI_OVLY_WINDOW_TEXT*: int32 = 524288'i32
  MCI_PASTE*: int32 = 2131'i32
  MCI_PAUSE*: int32 = 2057'i32
  MCI_PLAY*: int32 = 2054'i32
  MCI_PUT*: int32 = 2114'i32
  MCI_REALIZE*: int32 = 2112'i32
  MCI_RECORD*: int32 = 2063'i32
  MCI_RECORD_INSERT*: int32 = 256'i32
  MCI_RECORD_OVERWRITE*: int32 = 512'i32
  MCI_RESUME*: int32 = 2133'i32
  MCI_SAVE*: int32 = 2067'i32
  MCI_SAVE_FILE*: int32 = 256'i32
  MCI_SEEK*: int32 = 2055'i32
  MCI_SEEK_TO_END*: int32 = 512'i32
  MCI_SEEK_TO_START*: int32 = 256'i32
  MCI_SEQ_DIV_PPQN*: int32 = 1216'i32
  MCI_SEQ_DIV_SMPTE_24*: int32 = 1217'i32
  MCI_SEQ_DIV_SMPTE_25*: int32 = 1218'i32
  MCI_SEQ_DIV_SMPTE_30*: int32 = 1220'i32
  MCI_SEQ_DIV_SMPTE_30DROP*: int32 = 1219'i32
  MCI_SEQ_FILE*: int32 = 16386'i32
  MCI_SEQ_FORMAT_SONGPTR*: int32 = 16385'i32
  MCI_SEQ_MAPPER*: int32 = 65535'i32
  MCI_SEQ_MIDI*: int32 = 16387'i32
  MCI_SEQ_NONE*: int32 = 65533'i32
  MCI_SEQ_SET_MASTER*: int32 = 524288'i32
  MCI_SEQ_SET_OFFSET*: int32 = 16777216'i32
  MCI_SEQ_SET_PORT*: int32 = 131072'i32
  MCI_SEQ_SET_SLAVE*: int32 = 262144'i32
  MCI_SEQ_SET_TEMPO*: int32 = 65536'i32
  MCI_SEQ_SMPTE*: int32 = 16388'i32
  MCI_SEQ_STATUS_COPYRIGHT*: int32 = 16396'i32
  MCI_SEQ_STATUS_DIVTYPE*: int32 = 16394'i32
  MCI_SEQ_STATUS_MASTER*: int32 = 16392'i32
  MCI_SEQ_STATUS_NAME*: int32 = 16395'i32
  MCI_SEQ_STATUS_OFFSET*: int32 = 16393'i32
  MCI_SEQ_STATUS_PORT*: int32 = 16387'i32
  MCI_SEQ_STATUS_SLAVE*: int32 = 16391'i32
  MCI_SEQ_STATUS_TEMPO*: int32 = 16386'i32
  MCI_SET*: int32 = 2061'i32
  MCI_SET_AUDIO*: int32 = 2048'i32
  MCI_SET_AUDIO_ALL*: int32 = 0'i32
  MCI_SET_AUDIO_LEFT*: int32 = 1'i32
  MCI_SET_AUDIO_RIGHT*: int32 = 2'i32
  MCI_SET_DOOR_CLOSED*: int32 = 512'i32
  MCI_SET_DOOR_OPEN*: int32 = 256'i32
  MCI_SET_OFF*: int32 = 16384'i32
  MCI_SET_ON*: int32 = 8192'i32
  MCI_SET_TIME_FORMAT*: int32 = 1024'i32
  MCI_SET_VIDEO*: int32 = 4096'i32
  MCI_SPIN*: int32 = 2060'i32
  MCI_STATUS_CURRENT_TRACK*: int32 = 8'i32
  MCI_STATUS_ITEM*: int32 = 256'i32
  MCI_STATUS_LENGTH*: int32 = 1'i32
  MCI_STATUS_MEDIA_PRESENT*: int32 = 5'i32
  MCI_STATUS_MODE*: int32 = 4'i32
  MCI_STATUS_NUMBER_OF_TRACKS*: int32 = 3'i32
  MCI_STATUS_POSITION*: int32 = 2'i32
  MCI_STATUS_READY*: int32 = 7'i32
  MCI_STATUS_START*: int32 = 512'i32
  MCI_STATUS_TIME_FORMAT*: int32 = 6'i32
  MCI_STEP*: int32 = 2062'i32
  MCI_STOP*: int32 = 2056'i32
  MCI_SYSINFO*: int32 = 2064'i32
  MCI_SYSINFO_INSTALLNAME*: int32 = 2048'i32
  MCI_SYSINFO_NAME*: int32 = 1024'i32
  MCI_SYSINFO_OPEN*: int32 = 512'i32
  MCI_SYSINFO_QUANTITY*: int32 = 256'i32
  MCI_TO*: int32 = 8'i32
  MCI_TRACK*: int32 = 16'i32
  MCI_UNFREEZE*: int32 = 2117'i32
  MCI_UPDATE*: int32 = 2132'i32
  MCI_USER_MESSAGES*: int32 = 3072'i32
  MCI_VD_ESCAPE_STRING*: int32 = 256'i32
  MCI_VD_FORMAT_TRACK*: int32 = 16385'i32
  MCI_VD_GETDEVCAPS_CAN_REVERSE*: int32 = 16386'i32
  MCI_VD_GETDEVCAPS_CAV*: int32 = 131072'i32
  MCI_VD_GETDEVCAPS_CLV*: int32 = 65536'i32
  MCI_VD_GETDEVCAPS_FAST_RATE*: int32 = 16387'i32
  MCI_VD_GETDEVCAPS_NORMAL_RATE*: int32 = 16389'i32
  MCI_VD_GETDEVCAPS_SLOW_RATE*: int32 = 16388'i32
  MCI_VD_MEDIA_CAV*: int32 = 1027'i32
  MCI_VD_MEDIA_CLV*: int32 = 1026'i32
  MCI_VD_MEDIA_OTHER*: int32 = 1028'i32
  MCI_VD_MODE_PARK*: int32 = 1025'i32
  MCI_VD_PLAY_FAST*: int32 = 131072'i32
  MCI_VD_PLAY_REVERSE*: int32 = 65536'i32
  MCI_VD_PLAY_SCAN*: int32 = 524288'i32
  MCI_VD_PLAY_SLOW*: int32 = 1048576'i32
  MCI_VD_PLAY_SPEED*: int32 = 262144'i32
  MCI_VD_SEEK_REVERSE*: int32 = 65536'i32
  MCI_VD_SPIN_DOWN*: int32 = 131072'i32
  MCI_VD_SPIN_UP*: int32 = 65536'i32
  MCI_VD_STATUS_DISC_SIZE*: int32 = 16390'i32
  MCI_VD_STATUS_FORWARD*: int32 = 16387'i32
  MCI_VD_STATUS_MEDIA_TYPE*: int32 = 16388'i32
  MCI_VD_STATUS_SIDE*: int32 = 16389'i32
  MCI_VD_STATUS_SPEED*: int32 = 16386'i32
  MCI_VD_STEP_FRAMES*: int32 = 65536'i32
  MCI_VD_STEP_REVERSE*: int32 = 131072'i32
  MCI_WAIT*: int32 = 2'i32
  MCI_WAVE_GETDEVCAPS_INPUTS*: int32 = 16385'i32
  MCI_WAVE_GETDEVCAPS_OUTPUTS*: int32 = 16386'i32
  MCI_WAVE_INPUT*: int32 = 4194304'i32
  MCI_WAVE_MAPPER*: int32 = 1153'i32
  MCI_WAVE_OPEN_BUFFER*: int32 = 65536'i32
  MCI_WAVE_OUTPUT*: int32 = 8388608'i32
  MCI_WAVE_PCM*: int32 = 1152'i32
  MCI_WAVE_SET_ANYINPUT*: int32 = 67108864'i32
  MCI_WAVE_SET_ANYOUTPUT*: int32 = 134217728'i32
  MCI_WAVE_SET_AVGBYTESPERSEC*: int32 = 524288'i32
  MCI_WAVE_SET_BITSPERSAMPLE*: int32 = 2097152'i32
  MCI_WAVE_SET_BLOCKALIGN*: int32 = 1048576'i32
  MCI_WAVE_SET_CHANNELS*: int32 = 131072'i32
  MCI_WAVE_SET_FORMATTAG*: int32 = 65536'i32
  MCI_WAVE_SET_SAMPLESPERSEC*: int32 = 262144'i32
  MCI_WAVE_STATUS_AVGBYTESPERSEC*: int32 = 16388'i32
  MCI_WAVE_STATUS_BITSPERSAMPLE*: int32 = 16390'i32
  MCI_WAVE_STATUS_BLOCKALIGN*: int32 = 16389'i32
  MCI_WAVE_STATUS_CHANNELS*: int32 = 16386'i32
  MCI_WAVE_STATUS_FORMATTAG*: int32 = 16385'i32
  MCI_WAVE_STATUS_LEVEL*: int32 = 16391'i32
  MCI_WAVE_STATUS_SAMPLESPERSEC*: int32 = 16387'i32
  MCI_WHERE*: int32 = 2115'i32
  MCI_WINDOW*: int32 = 2113'i32

{.push dynlib: "winmm".}
proc mciDriverNotify*(hwndCallback: HANDLE, wDeviceID: MCIDEVICEID, uStatus: uint32): BOOL {.sideEffect, importc, stdcall.}
proc mciDriverYield*(wDeviceID: MCIDEVICEID): uint32 {.sideEffect, importc, stdcall.}
proc mciFreeCommandResource*(wTable: uint32): BOOL {.sideEffect, importc, stdcall.}
proc mciGetCreatorTask*(mciId: MCIDEVICEID): HTASK {.sideEffect, importc, stdcall.}
proc mciGetDeviceIDA*(pszDevice: PCSTR): MCIDEVICEID {.sideEffect, importc, stdcall.}
proc mciGetDeviceIDFromElementIDA*(dwElementID: uint32, lpstrType: PCSTR): MCIDEVICEID {.sideEffect, importc, stdcall.}
proc mciGetDeviceIDFromElementIDW*(dwElementID: uint32, lpstrType: PCWSTR): MCIDEVICEID {.sideEffect, importc, stdcall.}
proc mciGetDeviceIDW*(pszDevice: PCWSTR): MCIDEVICEID {.sideEffect, importc, stdcall.}
proc mciGetDriverData*(wDeviceID: MCIDEVICEID): uint {.sideEffect, importc, stdcall.}
proc mciGetErrorStringA*(mcierr: MCIERROR, pszText: PSTR, cchText: uint32): BOOL {.sideEffect, importc, stdcall.}
proc mciGetErrorStringW*(mcierr: MCIERROR, pszText: PWSTR, cchText: uint32): BOOL {.sideEffect, importc, stdcall.}
proc mciGetYieldProc*(mciId: MCIDEVICEID, pdwYieldData: ptr uint32): YIELDPROC {.sideEffect, importc, stdcall.}
proc mciLoadCommandResource*(hInstance: HANDLE, lpResName: PCWSTR, wType: uint32): uint32 {.sideEffect, importc, stdcall.}
proc mciSendCommandA*(mciId: MCIDEVICEID, uMsg: uint32, dwParam1: uint, dwParam2: uint): MCIERROR {.sideEffect, importc, stdcall.}
proc mciSendCommandW*(mciId: MCIDEVICEID, uMsg: uint32, dwParam1: uint, dwParam2: uint): MCIERROR {.sideEffect, importc, stdcall.}
proc mciSendStringA*(lpstrCommand: PCSTR, lpstrReturnString: PSTR, uReturnLength: uint32, hwndCallback: HWND): MCIERROR {.sideEffect, importc, stdcall.}
proc mciSendStringW*(lpstrCommand: PCWSTR, lpstrReturnString: PWSTR, uReturnLength: uint32, hwndCallback: HWND): MCIERROR {.sideEffect, importc, stdcall.}
proc mciSetDriverData*(wDeviceID: MCIDEVICEID, dwData: uint): BOOL {.sideEffect, importc, stdcall.}
proc mciSetYieldProc*(mciId: MCIDEVICEID, fpYieldProc: YIELDPROC, dwYieldData: uint32): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
