# generated by winmd2nim from Windows.Win32.winmd — msctf (do not edit)
import ./[propsys, winnt, windef, oaidl, minwindef, guiddef, textstor]
export propsys, winnt, windef, oaidl, minwindef, guiddef, textstor

type

  # structs
  TF_DA_COLOR* {.completeStruct.} = object
    `type`*: TF_DA_COLORTYPE
    Anonymous*: TF_DA_COLOR_1
  TF_DA_COLOR_1* {.completeStruct, union.} = object
    nIndex*: int32
    cr*: COLORREF
  TF_DISPLAYATTRIBUTE* {.completeStruct.} = object
    crText*: TF_DA_COLOR
    crBk*: TF_DA_COLOR
    lsStyle*: TF_DA_LINESTYLE
    fBoldLine*: BOOL
    crLine*: TF_DA_COLOR
    bAttr*: TF_DA_ATTR_INFO
  TF_HALTCOND* {.completeStruct.} = object
    pHaltRange*: ITfRange
    aHaltPos*: TfAnchor
    dwFlags*: uint32
  TF_INPUTPROCESSORPROFILE* {.completeStruct.} = object
    dwProfileType*: uint32
    langid*: LANGID
    clsid*: GUID
    guidProfile*: GUID
    catid*: GUID
    hklSubstitute*: HKL
    dwCaps*: uint32
    hkl*: HKL
    dwFlags*: uint32
  TF_LANGUAGEPROFILE* {.completeStruct.} = object
    clsid*: GUID
    langid*: LANGID
    catid*: GUID
    fActive*: BOOL
    guidProfile*: GUID
  TF_PERSISTENT_PROPERTY_HEADER_ACP* {.completeStruct.} = object
    guidType*: GUID
    ichStart*: int32
    cch*: int32
    cb*: uint32
    dwPrivate*: uint32
    clsidTIP*: GUID
  TF_PRESERVEDKEY* {.completeStruct.} = object
    uVKey*: uint32
    uModifiers*: uint32
  TF_PROPERTYVAL* {.completeStruct.} = object
    guidId*: GUID
    varValue*: VARIANT
  TF_SELECTION* {.completeStruct.} = object
    range*: ITfRange
    style*: TF_SELECTIONSTYLE
  TF_SELECTIONSTYLE* {.completeStruct.} = object
    ase*: TfActiveSelEnd
    fInterimChar*: BOOL

  # typdefs
  TF_STATUS* = TS_STATUS
  TfClientId* = distinct uint32
  TfEditCookie* = distinct uint32
  TfGuidAtom* = distinct uint32

  # unscoped enums 
  TF_DA_ATTR_INFO* = int32
  TF_DA_COLORTYPE* = int32
  TF_DA_LINESTYLE* = int32
  TfActiveSelEnd* = int32
  TfAnchor* = int32
  TfGravity* = int32
  TfLayoutCode* = int32
  TfShiftDir* = int32

  # interfaces
  IEnumITfCompositionView* = distinct object
  IEnumTfContextViews* = distinct object
  IEnumTfContexts* = distinct object
  IEnumTfDisplayAttributeInfo* = distinct object
  IEnumTfDocumentMgrs* = distinct object
  IEnumTfFunctionProviders* = distinct object
  IEnumTfInputProcessorProfiles* = distinct object
  IEnumTfLanguageProfiles* = distinct object
  IEnumTfProperties* = distinct object
  IEnumTfPropertyValue* = distinct object
  IEnumTfRanges* = distinct object
  IEnumTfUIElements* = distinct object
  ITextStoreACPServices* = distinct object
  ITfActiveLanguageProfileNotifySink* = distinct object
  ITfCandidateListUIElement* = distinct object
  ITfCandidateListUIElementBehavior* = distinct object
  ITfCategoryMgr* = distinct object
  ITfCleanupContextDurationSink* = distinct object
  ITfCleanupContextSink* = distinct object
  ITfClientId* = distinct object
  ITfCompartment* = distinct object
  ITfCompartmentEventSink* = distinct object
  ITfCompartmentMgr* = distinct object
  ITfComposition* = distinct object
  ITfCompositionSink* = distinct object
  ITfCompositionView* = distinct object
  ITfConfigureSystemKeystrokeFeed* = distinct object
  ITfContext* = distinct object
  ITfContextComposition* = distinct object
  ITfContextKeyEventSink* = distinct object
  ITfContextOwner* = distinct object
  ITfContextOwnerCompositionServices* = distinct object
  ITfContextOwnerCompositionSink* = distinct object
  ITfContextOwnerServices* = distinct object
  ITfContextView* = distinct object
  ITfCreatePropertyStore* = distinct object
  ITfDisplayAttributeInfo* = distinct object
  ITfDisplayAttributeMgr* = distinct object
  ITfDisplayAttributeNotifySink* = distinct object
  ITfDisplayAttributeProvider* = distinct object
  ITfDocumentMgr* = distinct object
  ITfEditRecord* = distinct object
  ITfEditSession* = distinct object
  ITfEditTransactionSink* = distinct object
  ITfFunction* = distinct object
  ITfFunctionProvider* = distinct object
  ITfInputProcessorProfileActivationSink* = distinct object
  ITfInputProcessorProfileMgr* = distinct object
  ITfInputProcessorProfileSubstituteLayout* = distinct object
  ITfInputProcessorProfiles* = distinct object
  ITfInputProcessorProfilesEx* = distinct object
  ITfInsertAtSelection* = distinct object
  ITfKeyEventSink* = distinct object
  ITfKeyTraceEventSink* = distinct object
  ITfKeystrokeMgr* = distinct object
  ITfLanguageProfileNotifySink* = distinct object
  ITfMessagePump* = distinct object
  ITfMouseSink* = distinct object
  ITfMouseTracker* = distinct object
  ITfMouseTrackerACP* = distinct object
  ITfPersistentPropertyLoaderACP* = distinct object
  ITfPreservedKeyNotifySink* = distinct object
  ITfProperty* = distinct object
  ITfPropertyStore* = distinct object
  ITfQueryEmbedded* = distinct object
  ITfRange* = distinct object
  ITfRangeACP* = distinct object
  ITfRangeBackup* = distinct object
  ITfReadOnlyProperty* = distinct object
  ITfReadingInformationUIElement* = distinct object
  ITfReverseConversion* = distinct object
  ITfReverseConversionList* = distinct object
  ITfReverseConversionMgr* = distinct object
  ITfSource* = distinct object
  ITfSourceSingle* = distinct object
  ITfStatusSink* = distinct object
  ITfTextEditSink* = distinct object
  ITfTextInputProcessor* = distinct object
  ITfTextInputProcessorEx* = distinct object
  ITfTextLayoutSink* = distinct object
  ITfThreadFocusSink* = distinct object
  ITfThreadMgr* = distinct object
  ITfThreadMgr2* = distinct object
  ITfThreadMgrEventSink* = distinct object
  ITfThreadMgrEx* = distinct object
  ITfToolTipUIElement* = distinct object
  ITfTransitoryExtensionSink* = distinct object
  ITfTransitoryExtensionUIElement* = distinct object
  ITfUIElement* = distinct object
  ITfUIElementMgr* = distinct object
  ITfUIElementSink* = distinct object

const
  # free constants
  TF_CHAR_EMBEDDED*: int32 = 65532'i32
  TF_CLIENTID_NULL*: TfClientId = TfClientId(0x0'u32)
  TF_CLUIE_COUNT*: int32 = 2'i32
  TF_CLUIE_CURRENTPAGE*: int32 = 32'i32
  TF_CLUIE_DOCUMENTMGR*: int32 = 1'i32
  TF_CLUIE_PAGEINDEX*: int32 = 16'i32
  TF_CLUIE_SELECTION*: int32 = 4'i32
  TF_CLUIE_STRING*: int32 = 8'i32
  TF_CONVERSIONMODE_ALPHANUMERIC*: int32 = 0'i32
  TF_CONVERSIONMODE_CHARCODE*: int32 = 32'i32
  TF_CONVERSIONMODE_EUDC*: int32 = 512'i32
  TF_CONVERSIONMODE_FIXED*: int32 = 2048'i32
  TF_CONVERSIONMODE_FULLSHAPE*: int32 = 8'i32
  TF_CONVERSIONMODE_KATAKANA*: int32 = 2'i32
  TF_CONVERSIONMODE_NATIVE*: int32 = 1'i32
  TF_CONVERSIONMODE_NOCONVERSION*: int32 = 256'i32
  TF_CONVERSIONMODE_ROMAN*: int32 = 16'i32
  TF_CONVERSIONMODE_SOFTKEYBOARD*: int32 = 128'i32
  TF_CONVERSIONMODE_SYMBOL*: int32 = 1024'i32
  TF_DEFAULT_SELECTION*: uint32 = 0xffffffff'u32
  TF_DISABLE_COMMANDING*: int32 = 4'i32
  TF_DISABLE_DICTATION*: int32 = 2'i32
  TF_DISABLE_SPEECH*: int32 = 1'i32
  TF_ES_ASYNC*: int32 = 8'i32
  TF_ES_ASYNCDONTCARE*: int32 = 0'i32
  TF_ES_READ*: int32 = 2'i32
  TF_ES_READWRITE*: int32 = 6'i32
  TF_ES_SYNC*: int32 = 1'i32
  TF_E_ALREADY_EXISTS*: int32 = -2147220218'i32
  TF_E_COMPOSITION_REJECTED*: int32 = -2147220216'i32
  TF_E_DISCONNECTED*: int32 = -2147220220'i32
  TF_E_EMPTYCONTEXT*: int32 = -2147220215'i32
  TF_E_FORMAT*: int32 = -2147220982'i32
  TF_E_INVALIDPOINT*: int32 = -2147220985'i32
  TF_E_INVALIDPOS*: int32 = -2147220992'i32
  TF_E_INVALIDVIEW*: int32 = -2147220219'i32
  TF_E_LOCKED*: int32 = -2147220224'i32
  TF_E_NOINTERFACE*: int32 = -2147220988'i32
  TF_E_NOLAYOUT*: int32 = -2147220986'i32
  TF_E_NOLOCK*: int32 = -2147220991'i32
  TF_E_NOOBJECT*: int32 = -2147220990'i32
  TF_E_NOPROVIDER*: int32 = -2147220221'i32
  TF_E_NOSELECTION*: int32 = -2147220987'i32
  TF_E_NOSERVICE*: int32 = -2147220989'i32
  TF_E_NOTOWNEDRANGE*: int32 = -2147220222'i32
  TF_E_RANGE_NOT_COVERED*: int32 = -2147220217'i32
  TF_E_READONLY*: int32 = -2147220983'i32
  TF_E_STACKFULL*: int32 = -2147220223'i32
  TF_E_SYNCHRONOUS*: int32 = -2147220984'i32
  TF_GTP_INCL_TEXT*: int32 = 1'i32
  TF_HF_OBJECT*: int32 = 1'i32
  TF_IAS_NOQUERY*: int32 = 1'i32
  TF_IAS_NO_DEFAULT_COMPOSITION*: uint32 = 0x80000000'u32
  TF_IAS_QUERYONLY*: int32 = 2'i32
  TF_IE_CORRECTION*: int32 = 1'i32
  TF_INVALID_COOKIE*: uint32 = 0xffffffff'u32
  TF_INVALID_EDIT_COOKIE*: int32 = 0'i32
  TF_INVALID_GUIDATOM*: TfGuidAtom = TfGuidAtom(0x0'u32)
  TF_INVALID_UIELEMENTID*: uint32 = 0xffffffff'u32
  TF_IPPMF_DISABLEPROFILE*: int32 = 2'i32
  TF_IPPMF_DONTCARECURRENTINPUTLANGUAGE*: int32 = 4'i32
  TF_IPPMF_ENABLEPROFILE*: int32 = 1'i32
  TF_IPPMF_FORPROCESS*: int32 = 268435456'i32
  TF_IPPMF_FORSESSION*: int32 = 536870912'i32
  TF_IPPMF_FORSYSTEMALL*: int32 = 1073741824'i32
  TF_IPP_CAPS_COMLESSSUPPORT*: int32 = 8'i32
  TF_IPP_CAPS_DISABLEONTRANSITORY*: int32 = 1'i32
  TF_IPP_CAPS_IMMERSIVESUPPORT*: int32 = 65536'i32
  TF_IPP_CAPS_SECUREMODESUPPORT*: int32 = 2'i32
  TF_IPP_CAPS_SYSTRAYSUPPORT*: int32 = 131072'i32
  TF_IPP_CAPS_UIELEMENTENABLED*: int32 = 4'i32
  TF_IPP_CAPS_WOW16SUPPORT*: int32 = 16'i32
  TF_IPP_FLAG_ACTIVE*: int32 = 1'i32
  TF_IPP_FLAG_ENABLED*: int32 = 2'i32
  TF_IPP_FLAG_SUBSTITUTEDBYINPUTPROCESSOR*: int32 = 4'i32
  TF_IPSINK_FLAG_ACTIVE*: int32 = 1'i32
  TF_MOD_ALT*: int32 = 1'i32
  TF_MOD_CONTROL*: int32 = 2'i32
  TF_MOD_IGNORE_ALL_MODIFIER*: int32 = 1024'i32
  TF_MOD_LALT*: int32 = 64'i32
  TF_MOD_LCONTROL*: int32 = 128'i32
  TF_MOD_LSHIFT*: int32 = 256'i32
  TF_MOD_ON_KEYUP*: int32 = 512'i32
  TF_MOD_RALT*: int32 = 8'i32
  TF_MOD_RCONTROL*: int32 = 16'i32
  TF_MOD_RSHIFT*: int32 = 32'i32
  TF_MOD_SHIFT*: int32 = 4'i32
  TF_POPF_ALL*: int32 = 1'i32
  TF_PROFILETYPE_INPUTPROCESSOR*: int32 = 1'i32
  TF_PROFILETYPE_KEYBOARDLAYOUT*: int32 = 2'i32
  TF_RCM_COMLESS*: int32 = 1'i32
  TF_RCM_HINT_COLLISION*: int32 = 8'i32
  TF_RCM_HINT_READING_LENGTH*: int32 = 4'i32
  TF_RCM_VKEY*: int32 = 2'i32
  TF_RIP_FLAG_FREEUNUSEDLIBRARIES*: int32 = 1'i32
  TF_RIUIE_CONTEXT*: int32 = 1'i32
  TF_RIUIE_ERRORINDEX*: int32 = 8'i32
  TF_RIUIE_MAXREADINGSTRINGLENGTH*: int32 = 4'i32
  TF_RIUIE_STRING*: int32 = 2'i32
  TF_RIUIE_VERTICALORDER*: int32 = 16'i32
  TF_RP_HIDDENINSETTINGUI*: int32 = 2'i32
  TF_RP_LOCALPROCESS*: int32 = 4'i32
  TF_RP_LOCALTHREAD*: int32 = 8'i32
  TF_RP_SUBITEMINSETTINGUI*: int32 = 16'i32
  TF_SD_LOADING*: int32 = 2'i32
  TF_SD_READONLY*: int32 = 1'i32
  TF_SENTENCEMODE_AUTOMATIC*: int32 = 4'i32
  TF_SENTENCEMODE_CONVERSATION*: int32 = 16'i32
  TF_SENTENCEMODE_NONE*: int32 = 0'i32
  TF_SENTENCEMODE_PHRASEPREDICT*: int32 = 8'i32
  TF_SENTENCEMODE_PLAURALCLAUSE*: int32 = 1'i32
  TF_SENTENCEMODE_SINGLECONVERT*: int32 = 2'i32
  TF_SS_DISJOINTSEL*: int32 = 1'i32
  TF_SS_REGIONS*: int32 = 2'i32
  TF_SS_TKBAUTOCORRECTENABLE*: int32 = 16'i32
  TF_SS_TKBPREDICTIONENABLE*: int32 = 32'i32
  TF_SS_TRANSITORY*: int32 = 4'i32
  TF_ST_CORRECTION*: int32 = 1'i32
  TF_S_ASYNC*: int32 = 262912'i32
  TF_TF_IGNOREEND*: int32 = 2'i32
  TF_TF_MOVESTART*: int32 = 1'i32
  TF_TMAE_COMLESS*: int32 = 8'i32
  TF_TMAE_CONSOLE*: int32 = 64'i32
  TF_TMAE_NOACTIVATEKEYBOARDLAYOUT*: int32 = 32'i32
  TF_TMAE_NOACTIVATETIP*: int32 = 1'i32
  TF_TMAE_SECUREMODE*: int32 = 2'i32
  TF_TMAE_UIELEMENTENABLEDONLY*: int32 = 4'i32
  TF_TMAE_WOW16*: int32 = 16'i32
  TF_TMF_ACTIVATED*: uint32 = 0x80000000'u32
  TF_TMF_COMLESS*: int32 = 8'i32
  TF_TMF_CONSOLE*: int32 = 64'i32
  TF_TMF_IMMERSIVEMODE*: int32 = 1073741824'i32
  TF_TMF_NOACTIVATETIP*: int32 = 1'i32
  TF_TMF_SECUREMODE*: int32 = 2'i32
  TF_TMF_UIELEMENTENABLEDONLY*: int32 = 4'i32
  TF_TMF_WOW16*: int32 = 16'i32
  TF_TRANSITORYEXTENSION_ATSELECTION*: int32 = 2'i32
  TF_TRANSITORYEXTENSION_FLOATING*: int32 = 1'i32
  TF_TRANSITORYEXTENSION_NONE*: int32 = 0'i32
  TF_TU_CORRECTION*: int32 = 1'i32
  TF_URP_ALLPROFILES*: int32 = 2'i32
  TF_URP_LOCALPROCESS*: int32 = 4'i32
  TF_URP_LOCALTHREAD*: int32 = 8'i32
  TF_US_HIDETIPUI*: int32 = 1'i32
  TKB_ALTERNATES_AUTOCORRECTION_APPLIED*: int32 = 4'i32
  TKB_ALTERNATES_FOR_AUTOCORRECTION*: int32 = 2'i32
  TKB_ALTERNATES_FOR_PREDICTION*: int32 = 3'i32
  TKB_ALTERNATES_STANDARD*: int32 = 1'i32

  # unscoped enum members
  TF_ATTR_INPUT*: TF_DA_ATTR_INFO = 0'i32
  TF_ATTR_TARGET_CONVERTED*: TF_DA_ATTR_INFO = 1'i32
  TF_ATTR_CONVERTED*: TF_DA_ATTR_INFO = 2'i32
  TF_ATTR_TARGET_NOTCONVERTED*: TF_DA_ATTR_INFO = 3'i32
  TF_ATTR_INPUT_ERROR*: TF_DA_ATTR_INFO = 4'i32
  TF_ATTR_FIXEDCONVERTED*: TF_DA_ATTR_INFO = 5'i32
  TF_ATTR_OTHER*: TF_DA_ATTR_INFO = -1'i32
  TF_CT_NONE*: TF_DA_COLORTYPE = 0'i32
  TF_CT_SYSCOLOR*: TF_DA_COLORTYPE = 1'i32
  TF_CT_COLORREF*: TF_DA_COLORTYPE = 2'i32
  TF_LS_NONE*: TF_DA_LINESTYLE = 0'i32
  TF_LS_SOLID*: TF_DA_LINESTYLE = 1'i32
  TF_LS_DOT*: TF_DA_LINESTYLE = 2'i32
  TF_LS_DASH*: TF_DA_LINESTYLE = 3'i32
  TF_LS_SQUIGGLE*: TF_DA_LINESTYLE = 4'i32
  TF_AE_NONE*: TfActiveSelEnd = 0'i32
  TF_AE_START*: TfActiveSelEnd = 1'i32
  TF_AE_END*: TfActiveSelEnd = 2'i32
  TF_ANCHOR_START*: TfAnchor = 0'i32
  TF_ANCHOR_END*: TfAnchor = 1'i32
  TF_GRAVITY_BACKWARD*: TfGravity = 0'i32
  TF_GRAVITY_FORWARD*: TfGravity = 1'i32
  TF_LC_CREATE*: TfLayoutCode = 0'i32
  TF_LC_CHANGE*: TfLayoutCode = 1'i32
  TF_LC_DESTROY*: TfLayoutCode = 2'i32
  TF_SD_BACKWARD*: TfShiftDir = 0'i32
  TF_SD_FORWARD*: TfShiftDir = 1'i32

{.push dynlib: "mfplat".}
proc CreatePropertyStore*(ppStore: ptr IPropertyStore): HRESULT {.sideEffect, importc, stdcall.}
{.pop.}
