# generated by winmd2nim from Windows.Win32.winmd — mstcpip (do not edit)
import ./[winnt, ws2def, guiddef, in6addr, inaddr]
export winnt, ws2def, guiddef, in6addr, inaddr

type

  # structs
  ASSOCIATE_NAMERES_CONTEXT_INPUT* {.completeStruct.} = object
    TransportSettingId*: TRANSPORT_SETTING_ID
    Handle*: uint64
  DL_EUI48* = object
  INET_PORT_RANGE* {.completeStruct.} = object
    StartPort*: uint16
    NumberOfPorts*: uint16
  INET_PORT_RESERVATION_INFORMATION* {.completeStruct.} = object
    OwningPid*: uint32
  INET_PORT_RESERVATION_INSTANCE* {.completeStruct.} = object
    Reservation*: INET_PORT_RESERVATION
    Token*: INET_PORT_RESERVATION_TOKEN
  INET_PORT_RESERVATION_TOKEN* {.completeStruct.} = object
    Token*: uint64
  PRIORITY_STATUS* {.completeStruct.} = object
    Sender*: SOCKET_PRIORITY_HINT
    Receiver*: SOCKET_PRIORITY_HINT
  RCVALL_IF* {.completeStruct.} = object
    Mode*: RCVALL_VALUE
    Interface*: uint32
  REAL_TIME_NOTIFICATION_SETTING_INPUT* {.completeStruct.} = object
    TransportSettingId*: TRANSPORT_SETTING_ID
    BrokerEventGuid*: GUID
  REAL_TIME_NOTIFICATION_SETTING_INPUT_EX* {.completeStruct.} = object
    TransportSettingId*: TRANSPORT_SETTING_ID
    BrokerEventGuid*: GUID
    Unmark*: bool
  REAL_TIME_NOTIFICATION_SETTING_OUTPUT* {.completeStruct.} = object
    ChannelStatus*: CONTROL_CHANNEL_TRIGGER_STATUS
  RSS_SCALABILITY_INFO* {.completeStruct.} = object
    RssEnabled*: bool
  SOCKET_PEER_TARGET_NAME* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    PeerAddress*: SOCKADDR_STORAGE
    PeerTargetNameStringLen*: uint32
    AllStrings*: pointer
  SOCKET_SECURITY_QUERY_INFO* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    Flags*: uint32
    PeerApplicationAccessTokenHandle*: uint64
    PeerMachineAccessTokenHandle*: uint64
  SOCKET_SECURITY_QUERY_INFO_IPSEC2* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    Flags*: uint32
    PeerApplicationAccessTokenHandle*: uint64
    PeerMachineAccessTokenHandle*: uint64
    MmSaId*: uint64
    QmSaId*: uint64
    NegotiationWinerr*: uint32
    SaLookupContext*: GUID
  SOCKET_SECURITY_QUERY_TEMPLATE* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    PeerAddress*: SOCKADDR_STORAGE
    PeerTokenAccessMask*: uint32
  SOCKET_SECURITY_QUERY_TEMPLATE_IPSEC2* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    PeerAddress*: SOCKADDR_STORAGE
    PeerTokenAccessMask*: uint32
    Flags*: uint32
    FieldMask*: uint32
  SOCKET_SECURITY_SETTINGS* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    SecurityFlags*: uint32
  SOCKET_SECURITY_SETTINGS_IPSEC* {.completeStruct.} = object
    SecurityProtocol*: SOCKET_SECURITY_PROTOCOL
    SecurityFlags*: uint32
    IpsecFlags*: uint32
    AuthipMMPolicyKey*: GUID
    AuthipQMPolicyKey*: GUID
    Reserved*: GUID
    Reserved2*: uint64
    UserNameStringLen*: uint32
    DomainNameStringLen*: uint32
    PasswordStringLen*: uint32
    AllStrings*: pointer
  TCP_ACK_FREQUENCY_PARAMETERS* {.completeStruct.} = object
    TcpDelayedAckFrequency*: uint8
  TCP_ICW_PARAMETERS* {.completeStruct.} = object
    Level*: TCP_ICW_LEVEL
  TCP_INFO_v0* {.completeStruct.} = object
    State*: TCPSTATE
    Mss*: uint32
    ConnectionTimeMs*: uint64
    TimestampsEnabled*: bool
    RttUs*: uint32
    MinRttUs*: uint32
    BytesInFlight*: uint32
    Cwnd*: uint32
    SndWnd*: uint32
    RcvWnd*: uint32
    RcvBuf*: uint32
    BytesOut*: uint64
    BytesIn*: uint64
    BytesReordered*: uint32
    BytesRetrans*: uint32
    FastRetrans*: uint32
    DupAcksIn*: uint32
    TimeoutEpisodes*: uint32
    SynRetrans*: uint8
  TCP_INFO_v1* {.completeStruct.} = object
    State*: TCPSTATE
    Mss*: uint32
    ConnectionTimeMs*: uint64
    TimestampsEnabled*: bool
    RttUs*: uint32
    MinRttUs*: uint32
    BytesInFlight*: uint32
    Cwnd*: uint32
    SndWnd*: uint32
    RcvWnd*: uint32
    RcvBuf*: uint32
    BytesOut*: uint64
    BytesIn*: uint64
    BytesReordered*: uint32
    BytesRetrans*: uint32
    FastRetrans*: uint32
    DupAcksIn*: uint32
    TimeoutEpisodes*: uint32
    SynRetrans*: uint8
    SndLimTransRwin*: uint32
    SndLimTimeRwin*: uint32
    SndLimBytesRwin*: uint64
    SndLimTransCwnd*: uint32
    SndLimTimeCwnd*: uint32
    SndLimBytesCwnd*: uint64
    SndLimTransSnd*: uint32
    SndLimTimeSnd*: uint32
    SndLimBytesSnd*: uint64
  TCP_INFO_v2* {.completeStruct.} = object
    State*: TCPSTATE
    Mss*: uint32
    ConnectionTimeMs*: uint64
    TimestampsEnabled*: bool
    RttUs*: uint32
    MinRttUs*: uint32
    BytesInFlight*: uint32
    Cwnd*: uint32
    SndWnd*: uint32
    RcvWnd*: uint32
    RcvBuf*: uint32
    BytesOut*: uint64
    BytesIn*: uint64
    BytesReordered*: uint32
    BytesRetrans*: uint32
    FastRetrans*: uint32
    DupAcksIn*: uint32
    TimeoutEpisodes*: uint32
    SynRetrans*: uint8
    SndLimTransRwin*: uint32
    SndLimTimeRwin*: uint32
    SndLimBytesRwin*: uint64
    SndLimTransCwnd*: uint32
    SndLimTimeCwnd*: uint32
    SndLimBytesCwnd*: uint64
    SndLimTransSnd*: uint32
    SndLimTimeSnd*: uint32
    SndLimBytesSnd*: uint64
    OutOfOrderPktsIn*: uint32
    EcnNegotiated*: bool
    EceAcksIn*: uint32
    PtoEpisodes*: uint32
  TCP_INITIAL_RTO_PARAMETERS* {.completeStruct.} = object
    Rtt*: uint16
    MaxSynRetransmissions*: uint8
  TIMESTAMPING_CONFIG* {.completeStruct.} = object
    Flags*: uint32
    TxTimestampsBuffered*: uint16
  TRANSPORT_SETTING_ID* {.completeStruct.} = object
    Guid*: GUID
  tcp_keepalive* {.completeStruct.} = object
    onoff*: uint32
    keepalivetime*: uint32
    keepaliveinterval*: uint32

  # typdefs
  INET_PORT_RESERVATION* = INET_PORT_RANGE
  PASSOCIATE_NAMERES_CONTEXT_INPUT* = ptr ASSOCIATE_NAMERES_CONTEXT_INPUT
  PCONTROL_CHANNEL_TRIGGER_STATUS* = distinct ptr CONTROL_CHANNEL_TRIGGER_STATUS
  PDL_EUI48* = ptr DL_EUI48
  PINET_PORT_RANGE* = ptr INET_PORT_RANGE
  PINET_PORT_RESERVATION* = ptr INET_PORT_RANGE
  PINET_PORT_RESERVATION_INFORMATION* = ptr INET_PORT_RESERVATION_INFORMATION
  PINET_PORT_RESERVATION_INSTANCE* = ptr INET_PORT_RESERVATION_INSTANCE
  PINET_PORT_RESERVATION_TOKEN* = ptr INET_PORT_RESERVATION_TOKEN
  PPRIORITY_STATUS* = ptr PRIORITY_STATUS
  PRCVALL_IF* = ptr RCVALL_IF
  PRCVALL_VALUE* = distinct ptr RCVALL_VALUE
  PREAL_TIME_NOTIFICATION_SETTING_INPUT* = ptr REAL_TIME_NOTIFICATION_SETTING_INPUT
  PREAL_TIME_NOTIFICATION_SETTING_INPUT_EX* = ptr REAL_TIME_NOTIFICATION_SETTING_INPUT_EX
  PREAL_TIME_NOTIFICATION_SETTING_OUTPUT* = ptr REAL_TIME_NOTIFICATION_SETTING_OUTPUT
  PRSS_SCALABILITY_INFO* = ptr RSS_SCALABILITY_INFO
  PSOCKET_PRIORITY_HINT* = distinct ptr SOCKET_PRIORITY_HINT
  PTCP_ACK_FREQUENCY_PARAMETERS* = ptr TCP_ACK_FREQUENCY_PARAMETERS
  PTCP_ICW_LEVEL* = distinct ptr TCP_ICW_LEVEL
  PTCP_ICW_PARAMETERS* = ptr TCP_ICW_PARAMETERS
  PTCP_INFO_v0* = ptr TCP_INFO_v0
  PTCP_INFO_v1* = ptr TCP_INFO_v1
  PTCP_INFO_v2* = ptr TCP_INFO_v2
  PTCP_INITIAL_RTO_PARAMETERS* = ptr TCP_INITIAL_RTO_PARAMETERS
  PTIMESTAMPING_CONFIG* = ptr TIMESTAMPING_CONFIG
  PTRANSPORT_SETTING_ID* = ptr TRANSPORT_SETTING_ID

  # unscoped enums 
  CONTROL_CHANNEL_TRIGGER_STATUS* = int32
  RCVALL_VALUE* = int32
  SOCKET_PRIORITY_HINT* = int32
  SOCKET_SECURITY_PROTOCOL* = int32
  SOCKET_USAGE_TYPE* = int32
  TCPSTATE* = int32
  TCP_ICW_LEVEL* = int32

const
  # free constants
  CONTROL_CHANNEL_TRIGGER_STATUS_MAX*: int32 = 4'i32
  IN4ADDR_ANY*: uint32 = 0x0'u32
  IN4ADDR_BROADCAST*: uint32 = 0xffffffff'u32
  IN4ADDR_LINKLOCALPREFIX_LENGTH*: int32 = 16'i32
  IN4ADDR_LOOPBACK*: int32 = 16777343'i32
  IN4ADDR_LOOPBACKPREFIX_LENGTH*: int32 = 8'i32
  IN4ADDR_MULTICASTPREFIX_LENGTH*: int32 = 4'i32
  IN4ADDR_NONE*: uint32 = 0xffffffff'u32
  INVALID_PORT_RESERVATION_TOKEN*: uint64 = 0x0'u64
  RCVALL_MAX*: int32 = 3'i32
  SIO_ABSORB_RTRALERT*: uint32 = 0x98000005'u32
  SIO_ACQUIRE_PORT_RESERVATION*: uint32 = 0x98000064'u32
  SIO_APPLY_TRANSPORT_SETTING*: uint32 = 0x98000013'u32
  SIO_ASSOCIATE_PORT_RESERVATION*: uint32 = 0x98000066'u32
  SIO_CPU_AFFINITY*: uint32 = 0x98000015'u32
  SIO_DELETE_PEER_TARGET_NAME*: uint32 = 0x980000cb'u32
  SIO_GET_TX_TIMESTAMP*: uint32 = 0x980000ea'u32
  SIO_INDEX_ADD_MCAST*: uint32 = 0x9800000a'u32
  SIO_INDEX_BIND*: uint32 = 0x98000008'u32
  SIO_INDEX_DEL_MCAST*: uint32 = 0x9800000b'u32
  SIO_INDEX_MCASTIF*: uint32 = 0x98000009'u32
  SIO_KEEPALIVE_VALS*: uint32 = 0x98000004'u32
  SIO_LIMIT_BROADCASTS*: uint32 = 0x98000007'u32
  SIO_LOOPBACK_FAST_PATH*: uint32 = 0x98000010'u32
  SIO_PRIORITY_HINT*: uint32 = 0x98000018'u32
  SIO_QUERY_RSS_SCALABILITY_INFO*: int32 = 1476395218'i32
  SIO_QUERY_SECURITY*: uint32 = 0xd80000c9'u32
  SIO_QUERY_TRANSPORT_SETTING*: uint32 = 0x98000014'u32
  SIO_QUERY_WFP_ALE_ENDPOINT_HANDLE*: int32 = 1476395213'i32
  SIO_QUERY_WFP_CONNECTION_REDIRECT_CONTEXT*: uint32 = 0x980000dd'u32
  SIO_QUERY_WFP_CONNECTION_REDIRECT_RECORDS*: uint32 = 0x980000dc'u32
  SIO_RCVALL*: uint32 = 0x98000001'u32
  SIO_RCVALL_IF*: uint32 = 0x9800000e'u32
  SIO_RCVALL_IGMPMCAST*: uint32 = 0x98000003'u32
  SIO_RCVALL_MCAST*: uint32 = 0x98000002'u32
  SIO_RCVALL_MCAST_IF*: uint32 = 0x9800000d'u32
  SIO_RELEASE_PORT_RESERVATION*: uint32 = 0x98000065'u32
  SIO_SET_PEER_TARGET_NAME*: uint32 = 0x980000ca'u32
  SIO_SET_PRIORITY_HINT*: uint32 = 0x98000018'u32
  SIO_SET_SECURITY*: uint32 = 0x980000c8'u32
  SIO_SET_WFP_CONNECTION_REDIRECT_RECORDS*: uint32 = 0x980000de'u32
  SIO_SOCKET_USAGE_NOTIFICATION*: uint32 = 0x980000cc'u32
  SIO_TCP_INFO*: uint32 = 0xd8000027'u32
  SIO_TCP_INITIAL_RTO*: uint32 = 0x98000011'u32
  SIO_TCP_SET_ACK_FREQUENCY*: uint32 = 0x98000017'u32
  SIO_TCP_SET_ICW*: uint32 = 0x98000016'u32
  SIO_TIMESTAMPING*: uint32 = 0x980000eb'u32
  SIO_UCAST_IF*: uint32 = 0x98000006'u32
  SOCKET_INFO_CONNECTION_ENCRYPTED*: int32 = 2'i32
  SOCKET_INFO_CONNECTION_IMPERSONATED*: int32 = 4'i32
  SOCKET_INFO_CONNECTION_SECURED*: int32 = 1'i32
  SOCKET_QUERY_IPSEC2_ABORT_CONNECTION_ON_FIELD_CHANGE*: int32 = 1'i32
  SOCKET_QUERY_IPSEC2_FIELD_MASK_MM_SA_ID*: int32 = 1'i32
  SOCKET_QUERY_IPSEC2_FIELD_MASK_QM_SA_ID*: int32 = 2'i32
  SOCKET_SETTINGS_ALLOW_INSECURE*: int32 = 2'i32
  SOCKET_SETTINGS_GUARANTEE_ENCRYPTION*: int32 = 1'i32
  SOCKET_SETTINGS_IPSEC_ALLOW_FIRST_INBOUND_PKT_UNENCRYPTED*: int32 = 4'i32
  SOCKET_SETTINGS_IPSEC_OPTIONAL_PEER_NAME_VERIFICATION*: int32 = 2'i32
  SOCKET_SETTINGS_IPSEC_PEER_NAME_IS_RAW_FORMAT*: int32 = 8'i32
  SOCKET_SETTINGS_IPSEC_SKIP_FILTER_INSTANTIATION*: int32 = 1'i32
  SO_TIMESTAMP*: int32 = 12298'i32
  SO_TIMESTAMP_ID*: int32 = 12299'i32
  TCP_INITIAL_RTO_DEFAULT_MAX_SYN_RETRANSMISSIONS*: int32 = 0'i32
  TCP_INITIAL_RTO_DEFAULT_RTT*: int32 = 0'i32
  TCP_INITIAL_RTO_NO_SYN_RETRANSMISSIONS*: uint8 = 0xfe'u8
  TCP_INITIAL_RTO_UNSPECIFIED_MAX_SYN_RETRANSMISSIONS*: uint8 = 0xff'u8
  TCP_INITIAL_RTO_UNSPECIFIED_RTT*: uint16 = 0xffff'u16
  TIMESTAMPING_FLAG_RX*: int32 = 1'i32
  TIMESTAMPING_FLAG_TX*: int32 = 2'i32

  # unscoped enum members
  CONTROL_CHANNEL_TRIGGER_STATUS_INVALID*: CONTROL_CHANNEL_TRIGGER_STATUS = 0'i32
  CONTROL_CHANNEL_TRIGGER_STATUS_SOFTWARE_SLOT_ALLOCATED*: CONTROL_CHANNEL_TRIGGER_STATUS = 1'i32
  CONTROL_CHANNEL_TRIGGER_STATUS_HARDWARE_SLOT_ALLOCATED*: CONTROL_CHANNEL_TRIGGER_STATUS = 2'i32
  CONTROL_CHANNEL_TRIGGER_STATUS_POLICY_ERROR*: CONTROL_CHANNEL_TRIGGER_STATUS = 3'i32
  CONTROL_CHANNEL_TRIGGER_STATUS_SYSTEM_ERROR*: CONTROL_CHANNEL_TRIGGER_STATUS = 4'i32
  CONTROL_CHANNEL_TRIGGER_STATUS_TRANSPORT_DISCONNECTED*: CONTROL_CHANNEL_TRIGGER_STATUS = 5'i32
  CONTROL_CHANNEL_TRIGGER_STATUS_SERVICE_UNAVAILABLE*: CONTROL_CHANNEL_TRIGGER_STATUS = 6'i32
  RCVALL_OFF*: RCVALL_VALUE = 0'i32
  RCVALL_ON*: RCVALL_VALUE = 1'i32
  RCVALL_SOCKETLEVELONLY*: RCVALL_VALUE = 2'i32
  RCVALL_IPLEVEL*: RCVALL_VALUE = 3'i32
  SocketPriorityHintVeryLow*: SOCKET_PRIORITY_HINT = 0'i32
  SocketPriorityHintLow*: SOCKET_PRIORITY_HINT = 1'i32
  SocketPriorityHintNormal*: SOCKET_PRIORITY_HINT = 2'i32
  SocketMaximumPriorityHintType*: SOCKET_PRIORITY_HINT = 3'i32
  SOCKET_SECURITY_PROTOCOL_DEFAULT*: SOCKET_SECURITY_PROTOCOL = 0'i32
  SOCKET_SECURITY_PROTOCOL_IPSEC*: SOCKET_SECURITY_PROTOCOL = 1'i32
  SOCKET_SECURITY_PROTOCOL_IPSEC2*: SOCKET_SECURITY_PROTOCOL = 2'i32
  SOCKET_SECURITY_PROTOCOL_INVALID*: SOCKET_SECURITY_PROTOCOL = 3'i32
  SYSTEM_CRITICAL_SOCKET*: SOCKET_USAGE_TYPE = 1'i32
  TCPSTATE_CLOSED*: TCPSTATE = 0'i32
  TCPSTATE_LISTEN*: TCPSTATE = 1'i32
  TCPSTATE_SYN_SENT*: TCPSTATE = 2'i32
  TCPSTATE_SYN_RCVD*: TCPSTATE = 3'i32
  TCPSTATE_ESTABLISHED*: TCPSTATE = 4'i32
  TCPSTATE_FIN_WAIT_1*: TCPSTATE = 5'i32
  TCPSTATE_FIN_WAIT_2*: TCPSTATE = 6'i32
  TCPSTATE_CLOSE_WAIT*: TCPSTATE = 7'i32
  TCPSTATE_CLOSING*: TCPSTATE = 8'i32
  TCPSTATE_LAST_ACK*: TCPSTATE = 9'i32
  TCPSTATE_TIME_WAIT*: TCPSTATE = 10'i32
  TCPSTATE_MAX*: TCPSTATE = 11'i32
  TCP_ICW_LEVEL_DEFAULT*: TCP_ICW_LEVEL = 0'i32
  TCP_ICW_LEVEL_HIGH*: TCP_ICW_LEVEL = 1'i32
  TCP_ICW_LEVEL_VERY_HIGH*: TCP_ICW_LEVEL = 2'i32
  TCP_ICW_LEVEL_AGGRESSIVE*: TCP_ICW_LEVEL = 3'i32
  TCP_ICW_LEVEL_EXPERIMENTAL*: TCP_ICW_LEVEL = 4'i32
  TCP_ICW_LEVEL_COMPAT*: TCP_ICW_LEVEL = 254'i32
  TCP_ICW_LEVEL_MAX*: TCP_ICW_LEVEL = 255'i32

{.push dynlib: "ntdll".}
proc RtlEthernetAddressToStringA*(Addr: ptr DL_EUI48, S: PSTR): PSTR {.sideEffect, importc, stdcall.}
proc RtlEthernetAddressToStringW*(Addr: ptr DL_EUI48, S: PWSTR): PWSTR {.sideEffect, importc, stdcall.}
proc RtlEthernetStringToAddressA*(S: PCSTR, Terminator: ptr PCSTR, Addr: ptr DL_EUI48): int32 {.sideEffect, importc, stdcall.}
proc RtlEthernetStringToAddressW*(S: PCWSTR, Terminator: ptr PCWSTR, Addr: ptr DL_EUI48): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv4AddressToStringA*(Addr: ptr IN_ADDR, S: PSTR): PSTR {.sideEffect, importc, stdcall.}
proc RtlIpv4AddressToStringExA*(Address: ptr IN_ADDR, Port: uint16, AddressString: PSTR, AddressStringLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv4AddressToStringExW*(Address: ptr IN_ADDR, Port: uint16, AddressString: PWSTR, AddressStringLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv4AddressToStringW*(Addr: ptr IN_ADDR, S: PWSTR): PWSTR {.sideEffect, importc, stdcall.}
proc RtlIpv4StringToAddressA*(S: PCSTR, Strict: bool, Terminator: ptr PCSTR, Addr: ptr IN_ADDR): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv4StringToAddressExA*(AddressString: PCSTR, Strict: bool, Address: ptr IN_ADDR, Port: ptr uint16): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv4StringToAddressExW*(AddressString: PCWSTR, Strict: bool, Address: ptr IN_ADDR, Port: ptr uint16): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv4StringToAddressW*(S: PCWSTR, Strict: bool, Terminator: ptr PCWSTR, Addr: ptr IN_ADDR): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv6AddressToStringA*(Addr: ptr IN6_ADDR, S: PSTR): PSTR {.sideEffect, importc, stdcall.}
proc RtlIpv6AddressToStringExA*(Address: ptr IN6_ADDR, ScopeId: uint32, Port: uint16, AddressString: PSTR, AddressStringLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv6AddressToStringExW*(Address: ptr IN6_ADDR, ScopeId: uint32, Port: uint16, AddressString: PWSTR, AddressStringLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv6AddressToStringW*(Addr: ptr IN6_ADDR, S: PWSTR): PWSTR {.sideEffect, importc, stdcall.}
proc RtlIpv6StringToAddressA*(S: PCSTR, Terminator: ptr PCSTR, Addr: ptr IN6_ADDR): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv6StringToAddressExA*(AddressString: PCSTR, Address: ptr IN6_ADDR, ScopeId: ptr uint32, Port: ptr uint16): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv6StringToAddressExW*(AddressString: PCWSTR, Address: ptr IN6_ADDR, ScopeId: ptr uint32, Port: ptr uint16): int32 {.sideEffect, importc, stdcall.}
proc RtlIpv6StringToAddressW*(S: PCWSTR, Terminator: ptr PCWSTR, Addr: ptr IN6_ADDR): int32 {.sideEffect, importc, stdcall.}
{.pop.}
