# generated by winmd2nim from Windows.Win32.winmd — MSWSOCK.dll (do not edit)
import ./[winsock2, winnt, ws2def, minwindef, minwinbase, mswsockdef]
export winsock2, winnt, ws2def, minwindef, minwinbase, mswsockdef

type

  # structs
  NLA_BLOB* {.completeStruct.} = object
    header*: NLA_BLOB_0
    data*: NLA_BLOB_1
  NLA_BLOB_0* {.completeStruct.} = object
    `type`*: NLA_BLOB_DATA_TYPE
    dwSize*: uint32
    nextOffset*: uint32
  NLA_BLOB_1* {.completeStruct, union.} = object
    rawData*: array[1, int8]
    interfaceData*: NLA_BLOB_1_1
    locationData*: NLA_BLOB_1_2
    connectivity*: NLA_BLOB_1_3
    ICS*: NLA_BLOB_1_4
  NLA_BLOB_1_1* {.completeStruct.} = object
    dwType*: uint32
    dwSpeed*: uint32
    adapterName*: array[1, int8]
  NLA_BLOB_1_2* {.completeStruct.} = object
    information*: array[1, int8]
  NLA_BLOB_1_3* {.completeStruct.} = object
    `type`*: NLA_CONNECTIVITY_TYPE
    internet*: NLA_INTERNET
  NLA_BLOB_1_4* {.completeStruct.} = object
    remote*: NLA_BLOB_1_4_0
  NLA_BLOB_1_4_0* {.completeStruct.} = object
    speed*: uint32
    `type`*: uint32
    state*: uint32
    machineName*: array[256, uint16]
    sharedAdapterName*: array[256, uint16]
  RIO_EXTENSION_FUNCTION_TABLE* {.completeStruct.} = object
    cbSize*: uint32
    RIOReceive*: LPFN_RIORECEIVE
    RIOReceiveEx*: LPFN_RIORECEIVEEX
    RIOSend*: LPFN_RIOSEND
    RIOSendEx*: LPFN_RIOSENDEX
    RIOCloseCompletionQueue*: LPFN_RIOCLOSECOMPLETIONQUEUE
    RIOCreateCompletionQueue*: LPFN_RIOCREATECOMPLETIONQUEUE
    RIOCreateRequestQueue*: LPFN_RIOCREATEREQUESTQUEUE
    RIODequeueCompletion*: LPFN_RIODEQUEUECOMPLETION
    RIODeregisterBuffer*: LPFN_RIODEREGISTERBUFFER
    RIONotify*: LPFN_RIONOTIFY
    RIORegisterBuffer*: LPFN_RIOREGISTERBUFFER
    RIOResizeCompletionQueue*: LPFN_RIORESIZECOMPLETIONQUEUE
    RIOResizeRequestQueue*: LPFN_RIORESIZEREQUESTQUEUE
  RIO_NOTIFICATION_COMPLETION* {.completeStruct.} = object
    Type*: RIO_NOTIFICATION_COMPLETION_TYPE
    Anonymous*: RIO_NOTIFICATION_COMPLETION_1
  RIO_NOTIFICATION_COMPLETION_1* {.completeStruct, union.} = object
    Event*: RIO_NOTIFICATION_COMPLETION_1_0
    Iocp*: RIO_NOTIFICATION_COMPLETION_1_1
  RIO_NOTIFICATION_COMPLETION_1_0* {.completeStruct.} = object
    EventHandle*: HANDLE
    NotifyReset*: BOOL
  RIO_NOTIFICATION_COMPLETION_1_1* {.completeStruct.} = object
    IocpHandle*: HANDLE
    CompletionKey*: pointer
    Overlapped*: pointer
  TRANSMIT_FILE_BUFFERS* {.completeStruct.} = object
    Head*: pointer
    HeadLength*: uint32
    Tail*: pointer
    TailLength*: uint32
  TRANSMIT_PACKETS_ELEMENT* {.completeStruct.} = object
    dwElFlags*: uint32
    cLength*: uint32
    Anonymous*: TRANSMIT_PACKETS_ELEMENT_2
  TRANSMIT_PACKETS_ELEMENT_2* {.completeStruct, union.} = object
    Anonymous*: TRANSMIT_PACKETS_ELEMENT_2_0
    pBuffer*: pointer
  TRANSMIT_PACKETS_ELEMENT_2_0* {.completeStruct.} = object
    nFileOffset*: int64
    hFile*: HANDLE
  WSAPOLLDATA* {.completeStruct.} = object
    result*: int32
    fds*: uint32
    timeout*: int32
    fdArray*: pointer
  WSASENDMSG* {.completeStruct.} = object
    lpMsg*: LPWSAMSG
    dwFlags*: uint32
    lpNumberOfBytesSent*: LPDWORD
    lpOverlapped*: LPWSAOVERLAPPED
    lpCompletionRoutine*: LPWSAOVERLAPPED_COMPLETION_ROUTINE

  # typdefs
  LPNLA_BLOB* = ptr NLA_BLOB
  LPTRANSMIT_FILE_BUFFERS* = ptr TRANSMIT_FILE_BUFFERS
  LPTRANSMIT_PACKETS_ELEMENT* = ptr TRANSMIT_PACKETS_ELEMENT
  LPWSAPOLLDATA* = ptr WSAPOLLDATA
  LPWSASENDMSG* = ptr WSASENDMSG
  PNLA_BLOB* = ptr NLA_BLOB
  PNLA_BLOB_DATA_TYPE* = distinct ptr NLA_BLOB_DATA_TYPE
  PNLA_CONNECTIVITY_TYPE* = distinct ptr NLA_CONNECTIVITY_TYPE
  PNLA_INTERNET* = distinct ptr NLA_INTERNET
  PRIO_EXTENSION_FUNCTION_TABLE* = ptr RIO_EXTENSION_FUNCTION_TABLE
  PRIO_NOTIFICATION_COMPLETION* = ptr RIO_NOTIFICATION_COMPLETION
  PRIO_NOTIFICATION_COMPLETION_TYPE* = distinct ptr RIO_NOTIFICATION_COMPLETION_TYPE
  PTRANSMIT_FILE_BUFFERS* = ptr TRANSMIT_FILE_BUFFERS
  PTRANSMIT_PACKETS_ELEMENT* = ptr TRANSMIT_PACKETS_ELEMENT

  # unscoped enums 
  NLA_BLOB_DATA_TYPE* = int32
  NLA_CONNECTIVITY_TYPE* = int32
  NLA_INTERNET* = int32
  RIO_NOTIFICATION_COMPLETION_TYPE* = int32

  # delegates
  LPFN_ACCEPTEX* = proc (arg_1: SOCKET, arg_2: SOCKET, arg_3: pointer, arg_4: uint32, arg_5: uint32, arg_6: uint32, arg_7: ptr uint32, arg_8: ptr OVERLAPPED): BOOL {.stdcall.}
  LPFN_CONNECTEX* = proc (arg_1: SOCKET, arg_2: ptr SOCKADDR, arg_3: int32, arg_4: pointer, arg_5: uint32, arg_6: ptr uint32, arg_7: ptr OVERLAPPED): BOOL {.stdcall.}
  LPFN_DISCONNECTEX* = proc (arg_1: SOCKET, arg_2: ptr OVERLAPPED, arg_3: uint32, arg_4: uint32): BOOL {.stdcall.}
  LPFN_GETACCEPTEXSOCKADDRS* = proc (arg_1: pointer, arg_2: uint32, arg_3: uint32, arg_4: uint32, arg_5: ptr ptr SOCKADDR, arg_6: ptr int32, arg_7: ptr ptr SOCKADDR, arg_8: ptr int32): void {.stdcall.}
  LPFN_RIOCLOSECOMPLETIONQUEUE* = proc (arg_1: ptr RIO_CQ_t): void {.stdcall.}
  LPFN_RIOCREATECOMPLETIONQUEUE* = proc (arg_1: uint32, arg_2: ptr RIO_NOTIFICATION_COMPLETION): RIO_CQ {.stdcall.}
  LPFN_RIOCREATEREQUESTQUEUE* = proc (arg_1: SOCKET, arg_2: uint32, arg_3: uint32, arg_4: uint32, arg_5: uint32, arg_6: ptr RIO_CQ_t, arg_7: ptr RIO_CQ_t, arg_8: pointer): RIO_RQ {.stdcall.}
  LPFN_RIODEQUEUECOMPLETION* = proc (arg_1: ptr RIO_CQ_t, arg_2: ptr RIORESULT, arg_3: uint32): uint32 {.stdcall.}
  LPFN_RIODEREGISTERBUFFER* = proc (arg_1: ptr RIO_BUFFERID_t): void {.stdcall.}
  LPFN_RIONOTIFY* = proc (arg_1: ptr RIO_CQ_t): int32 {.stdcall.}
  LPFN_RIORECEIVE* = proc (arg_1: ptr RIO_RQ_t, arg_2: ptr RIO_BUF, arg_3: uint32, arg_4: uint32, arg_5: pointer): BOOL {.stdcall.}
  LPFN_RIORECEIVEEX* = proc (arg_1: ptr RIO_RQ_t, arg_2: ptr RIO_BUF, arg_3: uint32, arg_4: ptr RIO_BUF, arg_5: ptr RIO_BUF, arg_6: ptr RIO_BUF, arg_7: ptr RIO_BUF, arg_8: uint32, arg_9: pointer): int32 {.stdcall.}
  LPFN_RIOREGISTERBUFFER* = proc (arg_1: ptr int8, arg_2: uint32): RIO_BUFFERID {.stdcall.}
  LPFN_RIORESIZECOMPLETIONQUEUE* = proc (arg_1: ptr RIO_CQ_t, arg_2: uint32): BOOL {.stdcall.}
  LPFN_RIORESIZEREQUESTQUEUE* = proc (arg_1: ptr RIO_RQ_t, arg_2: uint32, arg_3: uint32): BOOL {.stdcall.}
  LPFN_RIOSEND* = proc (arg_1: ptr RIO_RQ_t, arg_2: ptr RIO_BUF, arg_3: uint32, arg_4: uint32, arg_5: pointer): BOOL {.stdcall.}
  LPFN_RIOSENDEX* = proc (arg_1: ptr RIO_RQ_t, arg_2: ptr RIO_BUF, arg_3: uint32, arg_4: ptr RIO_BUF, arg_5: ptr RIO_BUF, arg_6: ptr RIO_BUF, arg_7: ptr RIO_BUF, arg_8: uint32, arg_9: pointer): BOOL {.stdcall.}
  LPFN_TRANSMITFILE* = proc (arg_1: SOCKET, arg_2: HANDLE, arg_3: uint32, arg_4: uint32, arg_5: ptr OVERLAPPED, arg_6: ptr TRANSMIT_FILE_BUFFERS, arg_7: uint32): BOOL {.stdcall.}
  LPFN_TRANSMITPACKETS* = proc (arg_1: SOCKET, arg_2: ptr TRANSMIT_PACKETS_ELEMENT, arg_3: uint32, arg_4: uint32, arg_5: ptr OVERLAPPED, arg_6: uint32): BOOL {.stdcall.}
  LPFN_WSAPOLL* = proc (arg_1: ptr WSAPOLLFD, arg_2: uint32, arg_3: int32): int32 {.stdcall.}
  LPFN_WSARECVMSG* = proc (arg_1: SOCKET, arg_2: ptr WSAMSG, arg_3: ptr uint32, arg_4: ptr OVERLAPPED, arg_5: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.stdcall.}
  LPFN_WSASENDMSG* = proc (arg_1: SOCKET, arg_2: ptr WSAMSG, arg_3: uint32, arg_4: ptr uint32, arg_5: ptr OVERLAPPED, arg_6: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.stdcall.}

const
  # free constants
  DE_REUSE_SOCKET*: int32 = 2'i32
  NLA_ALLUSERS_NETWORK*: int32 = 1'i32
  NLA_FRIENDLY_NAME*: int32 = 2'i32
  SIO_BASE_HANDLE*: int32 = 1207959586'i32
  SIO_BSP_HANDLE*: int32 = 1207959579'i32
  SIO_BSP_HANDLE_POLL*: int32 = 1207959581'i32
  SIO_BSP_HANDLE_SELECT*: int32 = 1207959580'i32
  SIO_EXT_POLL*: uint32 = 0xc800001f'u32
  SIO_EXT_SELECT*: uint32 = 0xc800001e'u32
  SIO_EXT_SENDMSG*: uint32 = 0xc8000020'u32
  SIO_UDP_CONNRESET*: uint32 = 0x9800000c'u32
  SIO_UDP_NETRESET*: uint32 = 0x9800000f'u32
  SO_CONNDATA*: int32 = 28672'i32
  SO_CONNDATALEN*: int32 = 28676'i32
  SO_CONNECT_TIME*: int32 = 28684'i32
  SO_CONNOPT*: int32 = 28673'i32
  SO_CONNOPTLEN*: int32 = 28677'i32
  SO_DISCDATA*: int32 = 28674'i32
  SO_DISCDATALEN*: int32 = 28678'i32
  SO_DISCOPT*: int32 = 28675'i32
  SO_DISCOPTLEN*: int32 = 28679'i32
  SO_MAXDG*: int32 = 28681'i32
  SO_MAXPATHDG*: int32 = 28682'i32
  SO_OPENTYPE*: int32 = 28680'i32
  SO_SYNCHRONOUS_ALERT*: int32 = 16'i32
  SO_SYNCHRONOUS_NONALERT*: int32 = 32'i32
  SO_UPDATE_ACCEPT_CONTEXT*: int32 = 28683'i32
  SO_UPDATE_CONNECT_CONTEXT*: int32 = 28688'i32
  TCP_BSDURGENT*: int32 = 28672'i32
  TF_DISCONNECT*: int32 = 1'i32
  TF_REUSE_SOCKET*: int32 = 2'i32
  TF_USE_DEFAULT_WORKER*: int32 = 0'i32
  TF_USE_KERNEL_APC*: int32 = 32'i32
  TF_USE_SYSTEM_THREAD*: int32 = 16'i32
  TF_WRITE_BEHIND*: int32 = 4'i32
  TP_DISCONNECT*: int32 = 1'i32
  TP_ELEMENT_EOP*: int32 = 4'i32
  TP_ELEMENT_FILE*: int32 = 2'i32
  TP_ELEMENT_MEMORY*: int32 = 1'i32
  TP_REUSE_SOCKET*: int32 = 2'i32
  TP_USE_DEFAULT_WORKER*: int32 = 0'i32
  TP_USE_KERNEL_APC*: int32 = 32'i32
  TP_USE_SYSTEM_THREAD*: int32 = 16'i32

  # unscoped enum members
  NLA_RAW_DATA*: NLA_BLOB_DATA_TYPE = 0'i32
  NLA_INTERFACE*: NLA_BLOB_DATA_TYPE = 1'i32
  NLA_802_1X_LOCATION*: NLA_BLOB_DATA_TYPE = 2'i32
  NLA_CONNECTIVITY*: NLA_BLOB_DATA_TYPE = 3'i32
  NLA_ICS*: NLA_BLOB_DATA_TYPE = 4'i32
  NLA_NETWORK_AD_HOC*: NLA_CONNECTIVITY_TYPE = 0'i32
  NLA_NETWORK_MANAGED*: NLA_CONNECTIVITY_TYPE = 1'i32
  NLA_NETWORK_UNMANAGED*: NLA_CONNECTIVITY_TYPE = 2'i32
  NLA_NETWORK_UNKNOWN*: NLA_CONNECTIVITY_TYPE = 3'i32
  NLA_INTERNET_UNKNOWN*: NLA_INTERNET = 0'i32
  NLA_INTERNET_NO*: NLA_INTERNET = 1'i32
  NLA_INTERNET_YES*: NLA_INTERNET = 2'i32
  RIO_EVENT_COMPLETION*: RIO_NOTIFICATION_COMPLETION_TYPE = 1'i32
  RIO_IOCP_COMPLETION*: RIO_NOTIFICATION_COMPLETION_TYPE = 2'i32

{.push dynlib: "mswsock".}
proc AcceptEx*(sListenSocket: SOCKET, sAcceptSocket: SOCKET, lpOutputBuffer: pointer, dwReceiveDataLength: uint32, dwLocalAddressLength: uint32, dwRemoteAddressLength: uint32, lpdwBytesReceived: ptr uint32, lpOverlapped: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc GetAcceptExSockaddrs*(lpOutputBuffer: pointer, dwReceiveDataLength: uint32, dwLocalAddressLength: uint32, dwRemoteAddressLength: uint32, LocalSockaddr: ptr ptr SOCKADDR, LocalSockaddrLength: ptr int32, RemoteSockaddr: ptr ptr SOCKADDR, RemoteSockaddrLength: ptr int32) {.sideEffect, importc, stdcall.}
proc TransmitFile*(hSocket: SOCKET, hFile: HANDLE, nNumberOfBytesToWrite: uint32, nNumberOfBytesPerSend: uint32, lpOverlapped: ptr OVERLAPPED, lpTransmitBuffers: ptr TRANSMIT_FILE_BUFFERS, dwReserved: uint32): BOOL {.sideEffect, importc, stdcall.}
proc WSARecvEx*(s: SOCKET, buf: ptr int8, len: int32, flags: ptr int32): int32 {.sideEffect, importc, stdcall.}
{.pop.}
