# generated by winmd2nim from Windows.Win32.winmd — namespaceapi (do not edit)
import ./[winnt, minwindef, minwinbase]
export winnt, minwindef, minwinbase

const
  # free constants
  PRIVATE_NAMESPACE_FLAG_DESTROY*: int32 = 1'i32

{.push dynlib: "kernel32".}
proc AddSIDToBoundaryDescriptor*(BoundaryDescriptor: ptr HANDLE, RequiredSid: PSID): BOOL {.sideEffect, importc, stdcall.}
proc ClosePrivateNamespace*(Handle: HANDLE, Flags: uint32): bool {.sideEffect, importc, stdcall.}
proc CreateBoundaryDescriptorW*(Name: PCWSTR, Flags: uint32): HANDLE {.sideEffect, importc, stdcall.}
proc CreatePrivateNamespaceW*(lpPrivateNamespaceAttributes: ptr SECURITY_ATTRIBUTES, lpBoundaryDescriptor: pointer, lpAliasPrefix: PCWSTR): HANDLE {.sideEffect, importc, stdcall.}
proc DeleteBoundaryDescriptor*(BoundaryDescriptor: HANDLE) {.sideEffect, importc, stdcall.}
proc OpenPrivateNamespaceW*(lpBoundaryDescriptor: pointer, lpAliasPrefix: PCWSTR): HANDLE {.sideEffect, importc, stdcall.}
{.pop.}
