# generated by winmd2nim from Windows.Win32.winmd — ndisport (do not edit)

type

  # typdefs
  NDIS_PORT_NUMBER* = distinct uint32
  PNDIS_PORT_NUMBER* = distinct ptr uint32
  PNDIS_PORT_TYPE* = distinct ptr NDIS_PORT_TYPE

  # unscoped enums 
  NDIS_PORT_TYPE* = int32

const
  # free constants
  NDIS_DEFAULT_PORT_NUMBER*: NDIS_PORT_NUMBER = NDIS_PORT_NUMBER(0x0'u32)
  NDIS_MAXIMUM_PORTS*: int32 = 16777216'i32

  # unscoped enum members
  NdisPortTypeUndefined*: NDIS_PORT_TYPE = 0'i32
  NdisPortTypeBridge*: NDIS_PORT_TYPE = 1'i32
  NdisPortTypeRasConnection*: NDIS_PORT_TYPE = 2'i32
  NdisPortType8021xSupplicant*: NDIS_PORT_TYPE = 3'i32
  NdisPortTypeMax*: NDIS_PORT_TYPE = 4'i32

