# generated by winmd2nim from Windows.Win32.winmd — ntddvol (do not edit)

type

  # structs
  FILE_EXTENT* {.completeStruct.} = object
    VolumeOffset*: uint64
    ExtentLength*: uint64
  VOLUME_ALLOCATE_BC_STREAM_INPUT* {.completeStruct.} = object
    Version*: uint32
    RequestsPerPeriod*: uint32
    Period*: uint32
    RetryFailures*: bool
    Discardable*: bool
    Reserved1*: array[2, bool]
    LowestByteOffset*: uint64
    HighestByteOffset*: uint64
    AccessType*: uint32
    AccessMode*: uint32
  VOLUME_ALLOCATE_BC_STREAM_OUTPUT* {.completeStruct.} = object
    RequestSize*: uint64
    NumOutStandingRequests*: uint32
  VOLUME_ALLOCATION_HINT_INPUT* {.completeStruct.} = object
    ClusterSize*: uint32
    NumberOfClusters*: uint32
    StartingClusterNumber*: int64
  VOLUME_ALLOCATION_HINT_OUTPUT* {.completeStruct.} = object
    Bitmap*: array[1, uint32]
  VOLUME_CRITICAL_IO* {.completeStruct.} = object
    AccessType*: uint32
    ExtentsCount*: uint32
    Extents*: array[1, FILE_EXTENT]
  VOLUME_FAILOVER_SET* {.completeStruct.} = object
    NumberOfDisks*: uint32
    DiskNumbers*: array[1, uint32]
  VOLUME_GET_BC_PROPERTIES_INPUT* {.completeStruct.} = object
    Version*: uint32
    Reserved1*: uint32
    LowestByteOffset*: uint64
    HighestByteOffset*: uint64
    AccessType*: uint32
    AccessMode*: uint32
  VOLUME_GET_BC_PROPERTIES_OUTPUT* {.completeStruct.} = object
    MaximumRequestsPerPeriod*: uint32
    MinimumPeriod*: uint32
    MaximumRequestSize*: uint64
    EstimatedTimePerRequest*: uint32
    NumOutStandingRequests*: uint32
    RequestSize*: uint64
  VOLUME_LOGICAL_OFFSET* {.completeStruct.} = object
    LogicalOffset*: int64
  VOLUME_NUMBER* {.completeStruct.} = object
    VolumeNumber*: uint32
    VolumeManagerName*: array[8, uint16]
  VOLUME_PHYSICAL_OFFSET* {.completeStruct.} = object
    DiskNumber*: uint32
    Offset*: int64
  VOLUME_PHYSICAL_OFFSETS* {.completeStruct.} = object
    NumberOfPhysicalOffsets*: uint32
    PhysicalOffset*: array[1, VOLUME_PHYSICAL_OFFSET]
  VOLUME_READ_PLEX_INPUT* {.completeStruct.} = object
    ByteOffset*: int64
    Length*: uint32
    PlexNumber*: uint32
  VOLUME_SET_GPT_ATTRIBUTES_INFORMATION* {.completeStruct.} = object
    GptAttributes*: uint64
    RevertOnClose*: bool
    ApplyToAllConnectedVolumes*: bool
    Reserved1*: uint16
    Reserved2*: uint32
  VOLUME_SHRINK_INFO* {.completeStruct.} = object
    VolumeSize*: uint64

  # typdefs
  PFILE_EXTENT* = ptr FILE_EXTENT
  PVOLUME_ALLOCATE_BC_STREAM_INPUT* = ptr VOLUME_ALLOCATE_BC_STREAM_INPUT
  PVOLUME_ALLOCATE_BC_STREAM_OUTPUT* = ptr VOLUME_ALLOCATE_BC_STREAM_OUTPUT
  PVOLUME_ALLOCATION_HINT_INPUT* = ptr VOLUME_ALLOCATION_HINT_INPUT
  PVOLUME_ALLOCATION_HINT_OUTPUT* = ptr VOLUME_ALLOCATION_HINT_OUTPUT
  PVOLUME_CRITICAL_IO* = ptr VOLUME_CRITICAL_IO
  PVOLUME_FAILOVER_SET* = ptr VOLUME_FAILOVER_SET
  PVOLUME_GET_BC_PROPERTIES_INPUT* = ptr VOLUME_GET_BC_PROPERTIES_INPUT
  PVOLUME_GET_BC_PROPERTIES_OUTPUT* = ptr VOLUME_GET_BC_PROPERTIES_OUTPUT
  PVOLUME_LOGICAL_OFFSET* = ptr VOLUME_LOGICAL_OFFSET
  PVOLUME_NUMBER* = ptr VOLUME_NUMBER
  PVOLUME_PHYSICAL_OFFSET* = ptr VOLUME_PHYSICAL_OFFSET
  PVOLUME_PHYSICAL_OFFSETS* = ptr VOLUME_PHYSICAL_OFFSETS
  PVOLUME_READ_PLEX_INPUT* = ptr VOLUME_READ_PLEX_INPUT
  PVOLUME_SET_GPT_ATTRIBUTES_INFORMATION* = ptr VOLUME_SET_GPT_ATTRIBUTES_INFORMATION
  PVOLUME_SHRINK_INFO* = ptr VOLUME_SHRINK_INFO

const
  # free constants
  IOCTL_VOLUME_ALLOCATE_BC_STREAM*: int32 = 5685312'i32
  IOCTL_VOLUME_BC_VERSION*: int32 = 1'i32
  IOCTL_VOLUME_FREE_BC_STREAM*: int32 = 5685316'i32
  IOCTL_VOLUME_GET_BC_PROPERTIES*: int32 = 5652540'i32
  IOCTL_VOLUME_GET_CSVBLOCKCACHE_CALLBACK*: int32 = 5685352'i32
  IOCTL_VOLUME_IS_CSV*: int32 = 5636192'i32
  IOCTL_VOLUME_IS_DYNAMIC*: int32 = 5636168'i32
  IOCTL_VOLUME_IS_IO_CAPABLE*: int32 = 5636116'i32
  IOCTL_VOLUME_IS_OFFLINE*: int32 = 5636112'i32
  IOCTL_VOLUME_IS_PARTITION*: int32 = 5636136'i32
  IOCTL_VOLUME_LOGICAL_TO_PHYSICAL*: int32 = 5636128'i32
  IOCTL_VOLUME_PHYSICAL_TO_LOGICAL*: int32 = 5636132'i32
  IOCTL_VOLUME_POST_ONLINE*: int32 = 5685348'i32
  IOCTL_VOLUME_PREPARE_FOR_CRITICAL_IO*: int32 = 5685324'i32
  IOCTL_VOLUME_PREPARE_FOR_SHRINK*: int32 = 5685340'i32
  IOCTL_VOLUME_QUERY_ALLOCATION_HINT*: int32 = 5652562'i32
  IOCTL_VOLUME_QUERY_FAILOVER_SET*: int32 = 5636120'i32
  IOCTL_VOLUME_QUERY_MINIMUM_SHRINK_SIZE*: int32 = 5652568'i32
  IOCTL_VOLUME_QUERY_VOLUME_NUMBER*: int32 = 5636124'i32
  IOCTL_VOLUME_READ_PLEX*: int32 = 5652526'i32
  IOCTL_VOLUME_SET_GPT_ATTRIBUTES*: int32 = 5636148'i32
  IOCTL_VOLUME_SUPPORTS_ONLINE_OFFLINE*: int32 = 5636100'i32
  IOCTL_VOLUME_UPDATE_PROPERTIES*: int32 = 5636180'i32

