# generated by winmd2nim from Windows.Win32.winmd — ntenclv (do not edit)

type

  # structs
  ENCLAVE_IDENTITY* {.completeStruct, packed.} = object
    OwnerId*: array[32, uint8]
    UniqueId*: array[32, uint8]
    AuthorId*: array[32, uint8]
    FamilyId*: array[16, uint8]
    ImageId*: array[16, uint8]
    EnclaveSvn*: uint32
    SecureKernelSvn*: uint32
    PlatformSvn*: uint32
    Flags*: uint32
    SigningLevel*: uint32
    EnclaveType*: uint32
  ENCLAVE_INFORMATION* {.completeStruct.} = object
    EnclaveType*: uint32
    Reserved*: uint32
    BaseAddress*: pointer
    Size*: uint
    Identity*: ENCLAVE_IDENTITY
  ENCLAVE_PACKAGE_IDENTITY* {.completeStruct, packed.} = object
    PackageId*: array[32, uint8]
    PackageSvn*: uint64
  ENCLAVE_VBS_BASIC_KEY_REQUEST* {.completeStruct.} = object
    RequestSize*: uint32
    Flags*: uint32
    EnclaveSVN*: uint32
    SystemKeyID*: uint32
    CurrentSystemKeyID*: uint32
  VBS_BASIC_ENCLAVE_EXCEPTION_AMD64_2* {.completeStruct.} = object
    ExceptionCode*: uint32
    NumberParameters*: uint32
    ExceptionInformation*: array[3, uint]
    ExceptionRAX*: uint
    ExceptionRCX*: uint
    ExceptionRIP*: uint
    ExceptionRFLAGS*: uint
    ExceptionRSP*: uint
  VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32* {.completeStruct.} = object
    ThreadContext*: array[4, uint32]
    EntryPoint*: uint32
    StackPointer*: uint32
    ExceptionEntryPoint*: uint32
    ExceptionStack*: uint32
    ExceptionActive*: uint32
  VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64* {.completeStruct.} = object
    ThreadContext*: array[4, uint64]
    EntryPoint*: uint64
    StackPointer*: uint64
    ExceptionEntryPoint*: uint64
    ExceptionStack*: uint64
    ExceptionActive*: uint32
  VBS_ENCLAVE_REPORT* {.completeStruct, packed.} = object
    ReportSize*: uint32
    ReportVersion*: uint32
    EnclaveData*: array[64, uint8]
    EnclaveIdentity*: ENCLAVE_IDENTITY
  VBS_ENCLAVE_REPORT_MODULE* {.completeStruct, packed.} = object
    Header*: VBS_ENCLAVE_REPORT_VARDATA_HEADER
    UniqueId*: array[32, uint8]
    AuthorId*: array[32, uint8]
    FamilyId*: array[16, uint8]
    ImageId*: array[16, uint8]
    Svn*: uint32
    ModuleName*: array[1, uint16]
  VBS_ENCLAVE_REPORT_PACKAGE_ID* {.completeStruct.} = object
    Header*: VBS_ENCLAVE_REPORT_VARDATA_HEADER
    PackageIdentity*: ENCLAVE_PACKAGE_IDENTITY
  VBS_ENCLAVE_REPORT_PKG_HEADER* {.completeStruct, packed.} = object
    PackageSize*: uint32
    Version*: uint32
    SignatureScheme*: uint32
    SignedStatementSize*: uint32
    SignatureSize*: uint32
    Reserved*: uint32
  VBS_ENCLAVE_REPORT_VARDATA_HEADER* {.completeStruct, packed.} = object
    DataType*: uint32
    Size*: uint32

  # typdefs
  PENCLAVE_VBS_BASIC_KEY_REQUEST* = ptr ENCLAVE_VBS_BASIC_KEY_REQUEST
  PVBS_BASIC_ENCLAVE_EXCEPTION_AMD64* = PVBS_BASIC_ENCLAVE_EXCEPTION_AMD64_2
  PVBS_BASIC_ENCLAVE_EXCEPTION_I386_ARM64* = distinct pointer
  PVBS_BASIC_ENCLAVE_EXCEPTION_AMD64_2* = ptr VBS_BASIC_ENCLAVE_EXCEPTION_AMD64_2
  PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_I386* = PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32
  PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_AMD64_ARM64* = PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64
  PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32* = ptr VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32
  PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64* = ptr VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64
  VBS_BASIC_ENCLAVE_EXCEPTION_AMD64* = VBS_BASIC_ENCLAVE_EXCEPTION_AMD64_2
  VBS_BASIC_ENCLAVE_EXCEPTION_I386_ARM64* = void
  VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_I386* = VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR32
  VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_AMD64_ARM64* = VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR64

  # unscoped enums 
  ENCLAVE_SEALING_IDENTITY_POLICY* = int32

  # delegates
  VBS_BASIC_ENCLAVE_BASIC_CALL_COMMIT_PAGES* = proc (arg_1: pointer, arg_2: uint, arg_3: pointer, arg_4: uint32): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_DECOMMIT_PAGES* = proc (arg_1: pointer, arg_2: uint): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_KEY* = proc (arg_1: ptr ENCLAVE_VBS_BASIC_KEY_REQUEST, arg_2: uint32, arg_3: ptr uint8): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_RANDOM_DATA* = proc (arg_1: ptr uint8, arg_2: uint32, arg_3: ptr uint64): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_REPORT* = proc (arg_1: ptr uint8, arg_2: pointer, arg_3: uint32, arg_4: ptr uint32): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_GET_ENCLAVE_INFORMATION* = proc (arg_1: ptr ENCLAVE_INFORMATION): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_PROTECT_PAGES* = proc (arg_1: pointer, arg_2: uint, arg_3: uint32): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_ENCLAVE* = proc (arg_1: uint): void {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_VERIFY_REPORT* = proc (arg_1: pointer, arg_2: uint32): int32 {.stdcall.}

when defined(amd64):
  type PVBS_BASIC_ENCLAVE_EXCEPTION* = PVBS_BASIC_ENCLAVE_EXCEPTION_AMD64
elif defined(i386) or defined(arm64):
  type PVBS_BASIC_ENCLAVE_EXCEPTION* = PVBS_BASIC_ENCLAVE_EXCEPTION_I386_ARM64
else:
  type PVBS_BASIC_ENCLAVE_EXCEPTION* = PVBS_BASIC_ENCLAVE_EXCEPTION_AMD64
when defined(i386):
  type PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR* = PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_I386
elif defined(amd64) or defined(arm64):
  type PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR* = PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_AMD64_ARM64
else:
  type PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR* = PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_I386
when defined(amd64):
  type VBS_BASIC_ENCLAVE_EXCEPTION* = VBS_BASIC_ENCLAVE_EXCEPTION_AMD64
elif defined(i386) or defined(arm64):
  type VBS_BASIC_ENCLAVE_EXCEPTION* = VBS_BASIC_ENCLAVE_EXCEPTION_I386_ARM64
else:
  type VBS_BASIC_ENCLAVE_EXCEPTION* = VBS_BASIC_ENCLAVE_EXCEPTION_AMD64
when defined(i386):
  type VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR* = VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_I386
elif defined(amd64) or defined(arm64):
  type VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR* = VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_AMD64_ARM64
else:
  type VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR* = VBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR_I386

type

  # structs
  VBS_BASIC_ENCLAVE_SYSCALL_PAGE* {.completeStruct.} = object
    ReturnFromEnclave*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_ENCLAVE
    ReturnFromException*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_EXCEPTION
    TerminateThread*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_TERMINATE_THREAD
    InterruptThread*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_INTERRUPT_THREAD
    CommitPages*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_COMMIT_PAGES
    DecommitPages*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_DECOMMIT_PAGES
    ProtectPages*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_PROTECT_PAGES
    CreateThread*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_CREATE_THREAD
    GetEnclaveInformation*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_GET_ENCLAVE_INFORMATION
    GenerateKey*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_KEY
    GenerateReport*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_REPORT
    VerifyReport*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_VERIFY_REPORT
    GenerateRandomData*: ptr VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_RANDOM_DATA

  # typdefs
  PVBS_BASIC_ENCLAVE_SYSCALL_PAGE* = ptr VBS_BASIC_ENCLAVE_SYSCALL_PAGE

  # delegates
  VBS_BASIC_ENCLAVE_BASIC_CALL_CREATE_THREAD* = proc (arg_1: PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_INTERRUPT_THREAD* = proc (arg_1: PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_EXCEPTION* = proc (arg_1: PVBS_BASIC_ENCLAVE_EXCEPTION): int32 {.stdcall.}
  VBS_BASIC_ENCLAVE_BASIC_CALL_TERMINATE_THREAD* = proc (arg_1: PVBS_BASIC_ENCLAVE_THREAD_DESCRIPTOR): int32 {.stdcall.}

const
  # free constants
  ENCLAVE_FLAG_DYNAMIC_DEBUG_ACTIVE*: int32 = 4'i32
  ENCLAVE_FLAG_DYNAMIC_DEBUG_ENABLED*: int32 = 2'i32
  ENCLAVE_FLAG_FULL_DEBUG_ENABLED*: int32 = 1'i32
  ENCLAVE_REPORT_DATA_LENGTH*: int32 = 64'i32
  ENCLAVE_RUNTIME_POLICY_ALLOW_DYNAMIC_DEBUG*: int32 = 2'i32
  ENCLAVE_RUNTIME_POLICY_ALLOW_FULL_DEBUG*: int32 = 1'i32
  ENCLAVE_UNSEAL_FLAG_STALE_KEY*: int32 = 1'i32
  ENCLAVE_VBS_BASIC_KEY_FLAG_DEBUG_KEY*: int32 = 8'i32
  ENCLAVE_VBS_BASIC_KEY_FLAG_FAMILY_ID*: int32 = 2'i32
  ENCLAVE_VBS_BASIC_KEY_FLAG_IMAGE_ID*: int32 = 4'i32
  ENCLAVE_VBS_BASIC_KEY_FLAG_MEASUREMENT*: int32 = 1'i32
  VBS_ENCLAVE_REPORT_PKG_HEADER_VERSION_CURRENT*: int32 = 1'i32
  VBS_ENCLAVE_REPORT_SIGNATURE_SCHEME_SHA256_RSA_PSS_SHA256*: int32 = 1'i32
  VBS_ENCLAVE_REPORT_VERSION_CURRENT*: int32 = 1'i32
  VBS_ENCLAVE_VARDATA_INVALID*: int32 = 0'i32
  VBS_ENCLAVE_VARDATA_MODULE*: int32 = 1'i32
  VBS_ENCLAVE_VARDATA_PACKAGE*: int32 = 2'i32

  # unscoped enum members
  ENCLAVE_IDENTITY_POLICY_SEAL_INVALID*: ENCLAVE_SEALING_IDENTITY_POLICY = 0'i32
  ENCLAVE_IDENTITY_POLICY_SEAL_EXACT_CODE*: ENCLAVE_SEALING_IDENTITY_POLICY = 1'i32
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_PRIMARY_CODE*: ENCLAVE_SEALING_IDENTITY_POLICY = 2'i32
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_IMAGE*: ENCLAVE_SEALING_IDENTITY_POLICY = 3'i32
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_FAMILY*: ENCLAVE_SEALING_IDENTITY_POLICY = 4'i32
  ENCLAVE_IDENTITY_POLICY_SEAL_SAME_AUTHOR*: ENCLAVE_SEALING_IDENTITY_POLICY = 5'i32

