# generated by winmd2nim from Windows.Win32.winmd — oaidl (do not edit)
import ./[unknwnbase, rpcndr, winnt, wtypesbase, wtypes, guiddef]
export unknwnbase, rpcndr, winnt, wtypesbase, wtypes, guiddef

type

  # structs
  ARRAYDESC* {.completeStruct.} = object
    tdescElem*: TYPEDESC
    cDims*: uint16
    rgbounds*: array[1, SAFEARRAYBOUND]
  BINDPTR* {.completeStruct, union.} = object
    lpfuncdesc*: ptr FUNCDESC
    lpvardesc*: ptr VARDESC
    lptcomp*: ITypeComp
  CLEANLOCALSTORAGE* {.completeStruct.} = object
    pInterface*: IUnknown
    pStorage*: pointer
    flags*: uint32
  CUSTDATA* {.completeStruct.} = object
    cCustData*: uint32
    prgCustData*: LPCUSTDATAITEM
  CUSTDATAITEM* {.completeStruct.} = object
    guid*: GUID
    varValue*: VARIANTARG
  DISPPARAMS* {.completeStruct.} = object
    rgvarg*: ptr VARIANTARG
    rgdispidNamedArgs*: ptr DISPID
    cArgs*: uint32
    cNamedArgs*: uint32
  ELEMDESC* {.completeStruct.} = object
    tdesc*: TYPEDESC
    Anonymous*: ELEMDESC_1
  ELEMDESC_1* {.completeStruct, union.} = object
    idldesc*: IDLDESC
    paramdesc*: PARAMDESC
  EXCEPINFO* {.completeStruct.} = object
    wCode*: uint16
    wReserved*: uint16
    bstrSource*: BSTR
    bstrDescription*: BSTR
    bstrHelpFile*: BSTR
    dwHelpContext*: uint32
    pvReserved*: pointer
    pfnDeferredFillIn*: ptr uint8
    scode*: SCODE
  FUNCDESC* {.completeStruct.} = object
    memid*: MEMBERID
    lprgscode*: ptr SCODE
    lprgelemdescParam*: ptr ELEMDESC
    funckind*: FUNCKIND
    invkind*: INVOKEKIND
    callconv*: CALLCONV
    cParams*: int16
    cParamsOpt*: int16
    oVft*: int16
    cScodes*: int16
    elemdescFunc*: ELEMDESC
    wFuncFlags*: uint16
  IDLDESC* {.completeStruct.} = object
    dwReserved*: uint
    wIDLFlags*: uint16
  PARAMDESC* {.completeStruct.} = object
    pparamdescex*: LPPARAMDESCEX
    wParamFlags*: uint16
  PARAMDESCEX* {.completeStruct.} = object
    cBytes*: uint32
    varDefaultValue*: VARIANTARG
  SAFEARRAY* {.completeStruct.} = object
    cDims*: uint16
    fFeatures*: uint16
    cbElements*: uint32
    cLocks*: uint32
    pvData*: pointer
    rgsabound*: array[1, SAFEARRAYBOUND]
  SAFEARRAYBOUND* {.completeStruct.} = object
    cElements*: uint32
    lLbound*: int32
  SAFEARRAYUNION* {.completeStruct.} = object
    sfType*: uint32
    u*: SAFEARRAYUNION_0
  SAFEARRAYUNION_0* {.completeStruct, union.} = object
    BstrStr*: SAFEARR_BSTR
    UnknownStr*: SAFEARR_UNKNOWN
    DispatchStr*: SAFEARR_DISPATCH
    VariantStr*: SAFEARR_VARIANT
    RecordStr*: SAFEARR_BRECORD
    HaveIidStr*: SAFEARR_HAVEIID
    ByteStr*: BYTE_SIZEDARR
    WordStr*: WORD_SIZEDARR
    LongStr*: DWORD_SIZEDARR
    HyperStr*: HYPER_SIZEDARR
  SAFEARR_BRECORD* {.completeStruct.} = object
    Size*: uint32
    aRecord*: ptr wireBRECORD
  SAFEARR_BSTR* {.completeStruct.} = object
    Size*: uint32
    aBstr*: ptr wireBSTR
  SAFEARR_DISPATCH* {.completeStruct.} = object
    Size*: uint32
    apDispatch*: ptr IDispatch
  SAFEARR_HAVEIID* {.completeStruct.} = object
    Size*: uint32
    apUnknown*: ptr IUnknown
    iid*: GUID
  SAFEARR_UNKNOWN* {.completeStruct.} = object
    Size*: uint32
    apUnknown*: ptr IUnknown
  SAFEARR_VARIANT* {.completeStruct.} = object
    Size*: uint32
    aVariant*: ptr wireVARIANT
  TLIBATTR* {.completeStruct.} = object
    guid*: GUID
    lcid*: LCID
    syskind*: SYSKIND
    wMajorVerNum*: uint16
    wMinorVerNum*: uint16
    wLibFlags*: uint16
  TYPEATTR* {.completeStruct.} = object
    guid*: GUID
    lcid*: LCID
    dwReserved*: uint32
    memidConstructor*: MEMBERID
    memidDestructor*: MEMBERID
    lpstrSchema*: PWSTR
    cbSizeInstance*: uint32
    typekind*: TYPEKIND
    cFuncs*: uint16
    cVars*: uint16
    cImplTypes*: uint16
    cbSizeVft*: uint16
    cbAlignment*: uint16
    wTypeFlags*: uint16
    wMajorVerNum*: uint16
    wMinorVerNum*: uint16
    tdescAlias*: TYPEDESC
    idldescType*: IDLDESC
  TYPEDESC* {.completeStruct.} = object
    Anonymous*: TYPEDESC_0
    vt*: VARTYPE
  TYPEDESC_0* {.completeStruct, union.} = object
    lptdesc*: ptr TYPEDESC
    lpadesc*: ptr ARRAYDESC
    hreftype*: HREFTYPE
  VARDESC* {.completeStruct.} = object
    memid*: MEMBERID
    lpstrSchema*: PWSTR
    Anonymous*: VARDESC_2
    elemdescVar*: ELEMDESC
    wVarFlags*: uint16
    varkind*: VARKIND
  VARDESC_2* {.completeStruct, union.} = object
    oInst*: uint32
    lpvarValue*: ptr VARIANT
  VARIANT* {.completeStruct.} = object
    Anonymous*: VARIANT_0
  VARIANT_0* {.completeStruct, union.} = object
    Anonymous*: VARIANT_0_0
    decVal*: DECIMAL
  VARIANT_0_0* {.completeStruct.} = object
    vt*: VARTYPE
    wReserved1*: uint16
    wReserved2*: uint16
    wReserved3*: uint16
    Anonymous*: VARIANT_0_0_4
  VARIANT_0_0_4* {.completeStruct, union.} = object
    llVal*: int64
    lVal*: int32
    bVal*: uint8
    iVal*: int16
    fltVal*: float32
    dblVal*: float64
    boolVal*: VARIANT_BOOL
    X_OBSOLETE_VARIANT_BOOL*: VARIANT_BOOL
    scode*: SCODE
    cyVal*: CY
    date*: float64
    bstrVal*: BSTR
    punkVal*: IUnknown
    pdispVal*: IDispatch
    parray*: ptr SAFEARRAY
    pbVal*: ptr uint8
    piVal*: ptr int16
    plVal*: ptr int32
    pllVal*: ptr int64
    pfltVal*: ptr float32
    pdblVal*: ptr float64
    pboolVal*: ptr VARIANT_BOOL
    X_OBSOLETE_VARIANT_PBOOL*: ptr VARIANT_BOOL
    pscode*: ptr SCODE
    pcyVal*: ptr CY
    pdate*: ptr float64
    pbstrVal*: ptr BSTR
    ppunkVal*: ptr IUnknown
    ppdispVal*: ptr IDispatch
    pparray*: ptr ptr SAFEARRAY
    pvarVal*: ptr VARIANT
    byref*: pointer
    cVal*: int8
    uiVal*: uint16
    ulVal*: uint32
    ullVal*: uint64
    intVal*: int32
    uintVal*: uint32
    pdecVal*: ptr DECIMAL
    pcVal*: ptr int8
    puiVal*: ptr uint16
    pulVal*: ptr uint32
    pullVal*: ptr uint64
    pintVal*: ptr int32
    puintVal*: ptr uint32
    Anonymous*: VARIANT_0_0_4_45
  VARIANT_0_0_4_45* {.completeStruct.} = object
    pvRecord*: pointer
    pRecInfo*: IRecordInfo
  X_wireBRECORD* {.completeStruct.} = object
    fFlags*: uint32
    clSize*: uint32
    pRecInfo*: IRecordInfo
    pRecord*: ptr byte_2
  X_wireSAFEARRAY* {.completeStruct.} = object
    cDims*: uint16
    fFeatures*: uint16
    cbElements*: uint32
    cLocks*: uint32
    uArrayStructs*: SAFEARRAYUNION
    rgsabound*: array[1, SAFEARRAYBOUND]
  X_wireVARIANT* {.completeStruct.} = object
    clSize*: uint32
    rpcReserved*: uint32
    vt*: uint16
    wReserved1*: uint16
    wReserved2*: uint16
    wReserved3*: uint16
    Anonymous*: X_wireVARIANT_6
  X_wireVARIANT_6* {.completeStruct, union.} = object
    llVal*: int64
    lVal*: int32
    bVal*: uint8
    iVal*: int16
    fltVal*: float32
    dblVal*: float64
    boolVal*: VARIANT_BOOL
    scode*: SCODE
    cyVal*: CY
    date*: float64
    bstrVal*: wireBSTR
    punkVal*: IUnknown
    pdispVal*: IDispatch
    parray*: wirePSAFEARRAY
    brecVal*: wireBRECORD
    pbVal*: ptr uint8
    piVal*: ptr int16
    plVal*: ptr int32
    pllVal*: ptr int64
    pfltVal*: ptr float32
    pdblVal*: ptr float64
    pboolVal*: ptr VARIANT_BOOL
    pscode*: ptr SCODE
    pcyVal*: ptr CY
    pdate*: ptr float64
    pbstrVal*: ptr wireBSTR
    ppunkVal*: ptr IUnknown
    ppdispVal*: ptr IDispatch
    pparray*: ptr wirePSAFEARRAY
    pvarVal*: ptr wireVARIANT
    cVal*: int8
    uiVal*: uint16
    ulVal*: uint32
    ullVal*: uint64
    intVal*: int32
    uintVal*: uint32
    decVal*: DECIMAL
    pdecVal*: ptr DECIMAL
    pcVal*: ptr int8
    puiVal*: ptr uint16
    pulVal*: ptr uint32
    pullVal*: ptr uint64
    pintVal*: ptr int32
    puintVal*: ptr uint32

  # typdefs
  CURRENCY* = CY
  DISPID* = distinct int32
  HREFTYPE* = distinct uint32
  LPBINDPTR* = ptr BINDPTR
  LPCUSTDATA* = ptr CUSTDATA
  LPCUSTDATAITEM* = ptr CUSTDATAITEM
  LPELEMDESC* = ptr ELEMDESC
  LPEXCEPINFO* = ptr EXCEPINFO
  LPFUNCDESC* = ptr FUNCDESC
  LPIDLDESC* = ptr IDLDESC
  LPPARAMDESC* = ptr PARAMDESC
  LPPARAMDESCEX* = ptr PARAMDESCEX
  LPSAFEARRAY* = ptr SAFEARRAY
  LPSAFEARRAYBOUND* = ptr SAFEARRAYBOUND
  LPTLIBATTR* = ptr TLIBATTR
  LPTYPEATTR* = ptr TYPEATTR
  LPVARDESC* = ptr VARDESC
  LPVARIANT* = ptr VARIANT
  LPVARIANTARG* = ptr VARIANT
  MEMBERID* = DISPID
  VARIANTARG* = VARIANT
  wireBRECORD* = ptr X_wireBRECORD
  wirePSAFEARRAY* = ptr wireSAFEARRAY
  wireSAFEARRAY* = ptr X_wireSAFEARRAY
  wireVARIANT* = ptr X_wireVARIANT

  # unscoped enums 
  CALLCONV* = int32
  CHANGEKIND* = int32
  DESCKIND* = int32
  FUNCFLAGS* = int32
  FUNCKIND* = int32
  INVOKEKIND* = int32
  LIBFLAGS* = int32
  SF_TYPE* = int32
  SYSKIND* = int32
  TYPEFLAGS* = int32
  TYPEKIND* = int32
  VARFLAGS* = int32
  VARKIND* = int32

  # interfaces
  ICreateErrorInfo* = distinct object
  ICreateTypeInfo* = distinct object
  ICreateTypeInfo2* = distinct object
  ICreateTypeLib* = distinct object
  ICreateTypeLib2* = distinct object
  IDispatch* = distinct object
  IEnumVARIANT* = distinct object
  IErrorInfo* = distinct object
  IErrorLog* = distinct object
  IPropertyBag* = distinct object
  IRecordInfo* = distinct object
  ISupportErrorInfo* = distinct object
  ITypeChangeEvents* = distinct object
  ITypeComp* = distinct object
  ITypeFactory* = distinct object
  ITypeInfo* = distinct object
  ITypeInfo2* = distinct object
  ITypeLib* = distinct object
  ITypeLib2* = distinct object
  ITypeLibRegistration* = distinct object
  ITypeLibRegistrationReader* = distinct object
  ITypeMarshal* = distinct object

const
  # free constants
  DISPID_COLLECT*: int32 = -8'i32
  DISPID_CONSTRUCTOR*: int32 = -6'i32
  DISPID_DESTRUCTOR*: int32 = -7'i32
  DISPID_EVALUATE*: int32 = -5'i32
  DISPID_NEWENUM*: int32 = -4'i32
  DISPID_PROPERTYPUT*: int32 = -3'i32
  DISPID_UNKNOWN*: int32 = -1'i32
  DISPID_VALUE*: int32 = 0'i32
  FADF_AUTO*: int32 = 1'i32
  FADF_BSTR*: int32 = 256'i32
  FADF_DISPATCH*: int32 = 1024'i32
  FADF_EMBEDDED*: int32 = 4'i32
  FADF_FIXEDSIZE*: int32 = 16'i32
  FADF_HAVEIID*: int32 = 64'i32
  FADF_HAVEVARTYPE*: int32 = 128'i32
  FADF_RECORD*: int32 = 32'i32
  FADF_RESERVED*: int32 = 61448'i32
  FADF_STATIC*: int32 = 2'i32
  FADF_UNKNOWN*: int32 = 512'i32
  FADF_VARIANT*: int32 = 2048'i32
  IDLFLAG_FIN*: int32 = 1'i32
  IDLFLAG_FLCID*: int32 = 4'i32
  IDLFLAG_FOUT*: int32 = 2'i32
  IDLFLAG_FRETVAL*: int32 = 8'i32
  IDLFLAG_NONE*: int32 = 0'i32
  IMPLTYPEFLAG_FDEFAULT*: int32 = 1'i32
  IMPLTYPEFLAG_FDEFAULTVTABLE*: int32 = 8'i32
  IMPLTYPEFLAG_FRESTRICTED*: int32 = 4'i32
  IMPLTYPEFLAG_FSOURCE*: int32 = 2'i32
  PARAMFLAG_FHASCUSTDATA*: int32 = 64'i32
  PARAMFLAG_FHASDEFAULT*: int32 = 32'i32
  PARAMFLAG_FIN*: int32 = 1'i32
  PARAMFLAG_FLCID*: int32 = 4'i32
  PARAMFLAG_FOPT*: int32 = 16'i32
  PARAMFLAG_FOUT*: int32 = 2'i32
  PARAMFLAG_FRETVAL*: int32 = 8'i32
  PARAMFLAG_NONE*: int32 = 0'i32

  # unscoped enum members
  CC_FASTCALL*: CALLCONV = 0'i32
  CC_CDECL*: CALLCONV = 1'i32
  CC_MSCPASCAL*: CALLCONV = 2'i32
  CC_PASCAL*: CALLCONV = 2'i32
  CC_MACPASCAL*: CALLCONV = 3'i32
  CC_STDCALL*: CALLCONV = 4'i32
  CC_FPFASTCALL*: CALLCONV = 5'i32
  CC_SYSCALL*: CALLCONV = 6'i32
  CC_MPWCDECL*: CALLCONV = 7'i32
  CC_MPWPASCAL*: CALLCONV = 8'i32
  CC_MAX*: CALLCONV = 9'i32
  CHANGEKIND_ADDMEMBER*: CHANGEKIND = 0'i32
  CHANGEKIND_DELETEMEMBER*: CHANGEKIND = 1'i32
  CHANGEKIND_SETNAMES*: CHANGEKIND = 2'i32
  CHANGEKIND_SETDOCUMENTATION*: CHANGEKIND = 3'i32
  CHANGEKIND_GENERAL*: CHANGEKIND = 4'i32
  CHANGEKIND_INVALIDATE*: CHANGEKIND = 5'i32
  CHANGEKIND_CHANGEFAILED*: CHANGEKIND = 6'i32
  CHANGEKIND_MAX*: CHANGEKIND = 7'i32
  DESCKIND_NONE*: DESCKIND = 0'i32
  DESCKIND_FUNCDESC*: DESCKIND = 1'i32
  DESCKIND_VARDESC*: DESCKIND = 2'i32
  DESCKIND_TYPECOMP*: DESCKIND = 3'i32
  DESCKIND_IMPLICITAPPOBJ*: DESCKIND = 4'i32
  DESCKIND_MAX*: DESCKIND = 5'i32
  FUNCFLAG_FRESTRICTED*: FUNCFLAGS = 1'i32
  FUNCFLAG_FSOURCE*: FUNCFLAGS = 2'i32
  FUNCFLAG_FBINDABLE*: FUNCFLAGS = 4'i32
  FUNCFLAG_FREQUESTEDIT*: FUNCFLAGS = 8'i32
  FUNCFLAG_FDISPLAYBIND*: FUNCFLAGS = 16'i32
  FUNCFLAG_FDEFAULTBIND*: FUNCFLAGS = 32'i32
  FUNCFLAG_FHIDDEN*: FUNCFLAGS = 64'i32
  FUNCFLAG_FUSESGETLASTERROR*: FUNCFLAGS = 128'i32
  FUNCFLAG_FDEFAULTCOLLELEM*: FUNCFLAGS = 256'i32
  FUNCFLAG_FUIDEFAULT*: FUNCFLAGS = 512'i32
  FUNCFLAG_FNONBROWSABLE*: FUNCFLAGS = 1024'i32
  FUNCFLAG_FREPLACEABLE*: FUNCFLAGS = 2048'i32
  FUNCFLAG_FIMMEDIATEBIND*: FUNCFLAGS = 4096'i32
  FUNC_VIRTUAL*: FUNCKIND = 0'i32
  FUNC_PUREVIRTUAL*: FUNCKIND = 1'i32
  FUNC_NONVIRTUAL*: FUNCKIND = 2'i32
  FUNC_STATIC*: FUNCKIND = 3'i32
  FUNC_DISPATCH*: FUNCKIND = 4'i32
  INVOKE_FUNC*: INVOKEKIND = 1'i32
  INVOKE_PROPERTYGET*: INVOKEKIND = 2'i32
  INVOKE_PROPERTYPUT*: INVOKEKIND = 4'i32
  INVOKE_PROPERTYPUTREF*: INVOKEKIND = 8'i32
  LIBFLAG_FRESTRICTED*: LIBFLAGS = 1'i32
  LIBFLAG_FCONTROL*: LIBFLAGS = 2'i32
  LIBFLAG_FHIDDEN*: LIBFLAGS = 4'i32
  LIBFLAG_FHASDISKIMAGE*: LIBFLAGS = 8'i32
  SF_ERROR*: SF_TYPE = 10'i32
  SF_I1*: SF_TYPE = 16'i32
  SF_I2*: SF_TYPE = 2'i32
  SF_I4*: SF_TYPE = 3'i32
  SF_I8*: SF_TYPE = 20'i32
  SF_BSTR*: SF_TYPE = 8'i32
  SF_UNKNOWN*: SF_TYPE = 13'i32
  SF_DISPATCH*: SF_TYPE = 9'i32
  SF_VARIANT*: SF_TYPE = 12'i32
  SF_RECORD*: SF_TYPE = 36'i32
  SF_HAVEIID*: SF_TYPE = 32781'i32
  SYS_WIN16*: SYSKIND = 0'i32
  SYS_WIN32*: SYSKIND = 1'i32
  SYS_MAC*: SYSKIND = 2'i32
  SYS_WIN64*: SYSKIND = 3'i32
  TYPEFLAG_FAPPOBJECT*: TYPEFLAGS = 1'i32
  TYPEFLAG_FCANCREATE*: TYPEFLAGS = 2'i32
  TYPEFLAG_FLICENSED*: TYPEFLAGS = 4'i32
  TYPEFLAG_FPREDECLID*: TYPEFLAGS = 8'i32
  TYPEFLAG_FHIDDEN*: TYPEFLAGS = 16'i32
  TYPEFLAG_FCONTROL*: TYPEFLAGS = 32'i32
  TYPEFLAG_FDUAL*: TYPEFLAGS = 64'i32
  TYPEFLAG_FNONEXTENSIBLE*: TYPEFLAGS = 128'i32
  TYPEFLAG_FOLEAUTOMATION*: TYPEFLAGS = 256'i32
  TYPEFLAG_FRESTRICTED*: TYPEFLAGS = 512'i32
  TYPEFLAG_FAGGREGATABLE*: TYPEFLAGS = 1024'i32
  TYPEFLAG_FREPLACEABLE*: TYPEFLAGS = 2048'i32
  TYPEFLAG_FDISPATCHABLE*: TYPEFLAGS = 4096'i32
  TYPEFLAG_FREVERSEBIND*: TYPEFLAGS = 8192'i32
  TYPEFLAG_FPROXY*: TYPEFLAGS = 16384'i32
  TKIND_ENUM*: TYPEKIND = 0'i32
  TKIND_RECORD*: TYPEKIND = 1'i32
  TKIND_MODULE*: TYPEKIND = 2'i32
  TKIND_INTERFACE*: TYPEKIND = 3'i32
  TKIND_DISPATCH*: TYPEKIND = 4'i32
  TKIND_COCLASS*: TYPEKIND = 5'i32
  TKIND_ALIAS*: TYPEKIND = 6'i32
  TKIND_UNION*: TYPEKIND = 7'i32
  TKIND_MAX*: TYPEKIND = 8'i32
  VARFLAG_FREADONLY*: VARFLAGS = 1'i32
  VARFLAG_FSOURCE*: VARFLAGS = 2'i32
  VARFLAG_FBINDABLE*: VARFLAGS = 4'i32
  VARFLAG_FREQUESTEDIT*: VARFLAGS = 8'i32
  VARFLAG_FDISPLAYBIND*: VARFLAGS = 16'i32
  VARFLAG_FDEFAULTBIND*: VARFLAGS = 32'i32
  VARFLAG_FHIDDEN*: VARFLAGS = 64'i32
  VARFLAG_FRESTRICTED*: VARFLAGS = 128'i32
  VARFLAG_FDEFAULTCOLLELEM*: VARFLAGS = 256'i32
  VARFLAG_FUIDEFAULT*: VARFLAGS = 512'i32
  VARFLAG_FNONBROWSABLE*: VARFLAGS = 1024'i32
  VARFLAG_FREPLACEABLE*: VARFLAGS = 2048'i32
  VARFLAG_FIMMEDIATEBIND*: VARFLAGS = 4096'i32
  VAR_PERINSTANCE*: VARKIND = 0'i32
  VAR_STATIC*: VARKIND = 1'i32
  VAR_CONST*: VARKIND = 2'i32
  VAR_DISPATCH*: VARKIND = 3'i32

