# generated by winmd2nim from Windows.Win32.winmd — propvarutil (do not edit)
import ./[winnt, propidl, oaidl, minwindef, wtypes, propidlbase, shtypes, guiddef]
export winnt, propidl, oaidl, minwindef, wtypes, propidlbase, shtypes, guiddef

type

  # typdefs
  PROPVAR_CHANGE_FLAGS* = distinct int32
  PROPVAR_COMPARE_FLAGS* = distinct int32
  PSTIME_FLAGS* = distinct int32

  # unscoped enums 
  DRAWPROGRESSFLAGS* = int32
  PROPVAR_COMPARE_UNIT* = int32
  tagPROPVAR_CHANGE_FLAGS* = int32
  tagPROPVAR_COMPARE_FLAGS* = int32
  tagPSTIME_FLAGS* = int32

const
  # unscoped enum members
  DPF_NONE*: DRAWPROGRESSFLAGS = 0'i32
  DPF_MARQUEE*: DRAWPROGRESSFLAGS = 1'i32
  DPF_MARQUEE_COMPLETE*: DRAWPROGRESSFLAGS = 2'i32
  DPF_ERROR*: DRAWPROGRESSFLAGS = 4'i32
  DPF_WARNING*: DRAWPROGRESSFLAGS = 8'i32
  DPF_STOPPED*: DRAWPROGRESSFLAGS = 16'i32
  PVCU_DEFAULT*: PROPVAR_COMPARE_UNIT = 0'i32
  PVCU_SECOND*: PROPVAR_COMPARE_UNIT = 1'i32
  PVCU_MINUTE*: PROPVAR_COMPARE_UNIT = 2'i32
  PVCU_HOUR*: PROPVAR_COMPARE_UNIT = 3'i32
  PVCU_DAY*: PROPVAR_COMPARE_UNIT = 4'i32
  PVCU_MONTH*: PROPVAR_COMPARE_UNIT = 5'i32
  PVCU_YEAR*: PROPVAR_COMPARE_UNIT = 6'i32
  PVCHF_DEFAULT*: tagPROPVAR_CHANGE_FLAGS = 0'i32
  PVCHF_NOVALUEPROP*: tagPROPVAR_CHANGE_FLAGS = 1'i32
  PVCHF_ALPHABOOL*: tagPROPVAR_CHANGE_FLAGS = 2'i32
  PVCHF_NOUSEROVERRIDE*: tagPROPVAR_CHANGE_FLAGS = 4'i32
  PVCHF_LOCALBOOL*: tagPROPVAR_CHANGE_FLAGS = 8'i32
  PVCHF_NOHEXSTRING*: tagPROPVAR_CHANGE_FLAGS = 16'i32
  PVCF_DEFAULT*: tagPROPVAR_COMPARE_FLAGS = 0'i32
  PVCF_TREATEMPTYASGREATERTHAN*: tagPROPVAR_COMPARE_FLAGS = 1'i32
  PVCF_USESTRCMP*: tagPROPVAR_COMPARE_FLAGS = 2'i32
  PVCF_USESTRCMPC*: tagPROPVAR_COMPARE_FLAGS = 4'i32
  PVCF_USESTRCMPI*: tagPROPVAR_COMPARE_FLAGS = 8'i32
  PVCF_USESTRCMPIC*: tagPROPVAR_COMPARE_FLAGS = 16'i32
  PVCF_DIGITSASNUMBERS_CASESENSITIVE*: tagPROPVAR_COMPARE_FLAGS = 32'i32
  PSTF_UTC*: tagPSTIME_FLAGS = 0'i32
  PSTF_LOCAL*: tagPSTIME_FLAGS = 1'i32

{.push dynlib: "propsys".}
proc ClearPropVariantArray*(rgPropVar: ptr PROPVARIANT, cVars: uint32) {.sideEffect, importc, stdcall.}
proc ClearVariantArray*(pvars: ptr VARIANT, cvars: uint32) {.sideEffect, importc, stdcall.}
proc InitPropVariantFromBooleanVector*(prgf: ptr BOOL, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromBuffer*(pv: pointer, cb: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromCLSID*(clsid: ptr GUID, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromDoubleVector*(prgn: ptr float64, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromFileTime*(pftIn: ptr FILETIME, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromFileTimeVector*(prgft: ptr FILETIME, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromGUIDAsString*(guid: ptr GUID, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromInt16Vector*(prgn: ptr int16, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromInt32Vector*(prgn: ptr int32, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromInt64Vector*(prgn: ptr int64, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromPropVariantVectorElem*(propvarIn: ptr PROPVARIANT, iElem: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromResource*(hinst: HINSTANCE, id: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromStrRet*(pstrret: ptr STRRET, pidl: ptr ITEMIDLIST, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromStringAsVector*(psz: PCWSTR, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromStringVector*(prgsz: ptr PCWSTR, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromUInt16Vector*(prgn: ptr uint16, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromUInt32Vector*(prgn: ptr uint32, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantFromUInt64Vector*(prgn: ptr uint64, cElems: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitPropVariantVectorFromPropVariant*(propvarSingle: ptr PROPVARIANT, ppropvarVector: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromBooleanArray*(prgf: ptr BOOL, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromBuffer*(pv: pointer, cb: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromDoubleArray*(prgn: ptr float64, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromFileTime*(pft: ptr FILETIME, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromFileTimeArray*(prgft: ptr FILETIME, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromGUIDAsString*(guid: ptr GUID, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromInt16Array*(prgn: ptr int16, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromInt32Array*(prgn: ptr int32, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromInt64Array*(prgn: ptr int64, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromResource*(hinst: HINSTANCE, id: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromStrRet*(pstrret: ptr STRRET, pidl: ptr ITEMIDLIST, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromStringArray*(prgsz: ptr PCWSTR, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromUInt16Array*(prgn: ptr uint16, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromUInt32Array*(prgn: ptr uint32, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromUInt64Array*(prgn: ptr uint64, cElems: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc InitVariantFromVariantArrayElem*(varIn: ptr VARIANT, iElem: uint32, pvar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantChangeType*(ppropvarDest: ptr PROPVARIANT, propvarSrc: ptr PROPVARIANT, flags: PROPVAR_CHANGE_FLAGS, vt: VARTYPE): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantCompareEx*(propvar1: ptr PROPVARIANT, propvar2: ptr PROPVARIANT, unit: PROPVAR_COMPARE_UNIT, flags: PROPVAR_COMPARE_FLAGS): int32 {.sideEffect, importc, stdcall.}
proc PropVariantGetBooleanElem*(propvar: ptr PROPVARIANT, iElem: uint32, pfVal: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetDoubleElem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr float64): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetElementCount*(propvar: ptr PROPVARIANT): uint32 {.sideEffect, importc, stdcall.}
proc PropVariantGetFileTimeElem*(propvar: ptr PROPVARIANT, iElem: uint32, pftVal: ptr FILETIME): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetInt16Elem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr int16): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetInt32Elem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr int32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetInt64Elem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr int64): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetStringElem*(propvar: ptr PROPVARIANT, iElem: uint32, ppszVal: ptr PWSTR): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetUInt16Elem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr uint16): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetUInt32Elem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantGetUInt64Elem*(propvar: ptr PROPVARIANT, iElem: uint32, pnVal: ptr uint64): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToBSTR*(propvar: ptr PROPVARIANT, pbstrOut: ptr BSTR): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToBoolean*(propvarIn: ptr PROPVARIANT, pfRet: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToBooleanVector*(propvar: ptr PROPVARIANT, prgf: ptr BOOL, crgf: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToBooleanVectorAlloc*(propvar: ptr PROPVARIANT, pprgf: ptr ptr BOOL, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToBooleanWithDefault*(propvarIn: ptr PROPVARIANT, fDefault: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc PropVariantToBuffer*(propvar: ptr PROPVARIANT, pv: pointer, cb: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToDouble*(propvarIn: ptr PROPVARIANT, pdblRet: ptr float64): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToDoubleVector*(propvar: ptr PROPVARIANT, prgn: ptr float64, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToDoubleVectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr float64, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToDoubleWithDefault*(propvarIn: ptr PROPVARIANT, dblDefault: float64): float64 {.sideEffect, importc, stdcall.}
proc PropVariantToFileTime*(propvar: ptr PROPVARIANT, pstfOut: PSTIME_FLAGS, pftOut: ptr FILETIME): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToFileTimeVector*(propvar: ptr PROPVARIANT, prgft: ptr FILETIME, crgft: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToFileTimeVectorAlloc*(propvar: ptr PROPVARIANT, pprgft: ptr ptr FILETIME, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToGUID*(propvar: ptr PROPVARIANT, pguid: ptr GUID): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt16*(propvarIn: ptr PROPVARIANT, piRet: ptr int16): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt16Vector*(propvar: ptr PROPVARIANT, prgn: ptr int16, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt16VectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr int16, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt16WithDefault*(propvarIn: ptr PROPVARIANT, iDefault: int16): int16 {.sideEffect, importc, stdcall.}
proc PropVariantToInt32*(propvarIn: ptr PROPVARIANT, plRet: ptr int32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt32Vector*(propvar: ptr PROPVARIANT, prgn: ptr int32, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt32VectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr int32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt32WithDefault*(propvarIn: ptr PROPVARIANT, lDefault: int32): int32 {.sideEffect, importc, stdcall.}
proc PropVariantToInt64*(propvarIn: ptr PROPVARIANT, pllRet: ptr int64): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt64Vector*(propvar: ptr PROPVARIANT, prgn: ptr int64, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt64VectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr int64, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToInt64WithDefault*(propvarIn: ptr PROPVARIANT, llDefault: int64): int64 {.sideEffect, importc, stdcall.}
proc PropVariantToStrRet*(propvar: ptr PROPVARIANT, pstrret: ptr STRRET): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToString*(propvar: ptr PROPVARIANT, psz: PWSTR, cch: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToStringAlloc*(propvar: ptr PROPVARIANT, ppszOut: ptr PWSTR): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToStringVector*(propvar: ptr PROPVARIANT, prgsz: ptr PWSTR, crgsz: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToStringVectorAlloc*(propvar: ptr PROPVARIANT, pprgsz: ptr ptr PWSTR, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToStringWithDefault*(propvarIn: ptr PROPVARIANT, pszDefault: PCWSTR): PCWSTR {.sideEffect, importc, stdcall.}
proc PropVariantToUInt16*(propvarIn: ptr PROPVARIANT, puiRet: ptr uint16): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt16Vector*(propvar: ptr PROPVARIANT, prgn: ptr uint16, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt16VectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr uint16, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt16WithDefault*(propvarIn: ptr PROPVARIANT, uiDefault: uint16): uint16 {.sideEffect, importc, stdcall.}
proc PropVariantToUInt32*(propvarIn: ptr PROPVARIANT, pulRet: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt32Vector*(propvar: ptr PROPVARIANT, prgn: ptr uint32, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt32VectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt32WithDefault*(propvarIn: ptr PROPVARIANT, ulDefault: uint32): uint32 {.sideEffect, importc, stdcall.}
proc PropVariantToUInt64*(propvarIn: ptr PROPVARIANT, pullRet: ptr uint64): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt64Vector*(propvar: ptr PROPVARIANT, prgn: ptr uint64, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt64VectorAlloc*(propvar: ptr PROPVARIANT, pprgn: ptr ptr uint64, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc PropVariantToUInt64WithDefault*(propvarIn: ptr PROPVARIANT, ullDefault: uint64): uint64 {.sideEffect, importc, stdcall.}
proc PropVariantToVariant*(pPropVar: ptr PROPVARIANT, pVar: ptr VARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc StgDeserializePropVariant*(pprop: ptr SERIALIZEDPROPERTYVALUE, cbMax: uint32, ppropvar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc StgSerializePropVariant*(ppropvar: ptr PROPVARIANT, ppProp: ptr ptr SERIALIZEDPROPERTYVALUE, pcb: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantCompare*(var1: ptr VARIANT, var2: ptr VARIANT): int32 {.sideEffect, importc, stdcall.}
proc VariantGetBooleanElem*(`var`: ptr VARIANT, iElem: uint32, pfVal: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetDoubleElem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr float64): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetElementCount*(varIn: ptr VARIANT): uint32 {.sideEffect, importc, stdcall.}
proc VariantGetInt16Elem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr int16): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetInt32Elem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr int32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetInt64Elem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr int64): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetStringElem*(`var`: ptr VARIANT, iElem: uint32, ppszVal: ptr PWSTR): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetUInt16Elem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr uint16): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetUInt32Elem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantGetUInt64Elem*(`var`: ptr VARIANT, iElem: uint32, pnVal: ptr uint64): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToBoolean*(varIn: ptr VARIANT, pfRet: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToBooleanArray*(`var`: ptr VARIANT, prgf: ptr BOOL, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToBooleanArrayAlloc*(`var`: ptr VARIANT, pprgf: ptr ptr BOOL, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToBooleanWithDefault*(varIn: ptr VARIANT, fDefault: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc VariantToBuffer*(varIn: ptr VARIANT, pv: pointer, cb: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToDosDateTime*(varIn: ptr VARIANT, pwDate: ptr uint16, pwTime: ptr uint16): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToDouble*(varIn: ptr VARIANT, pdblRet: ptr float64): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToDoubleArray*(`var`: ptr VARIANT, prgn: ptr float64, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToDoubleArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr float64, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToDoubleWithDefault*(varIn: ptr VARIANT, dblDefault: float64): float64 {.sideEffect, importc, stdcall.}
proc VariantToFileTime*(varIn: ptr VARIANT, stfOut: PSTIME_FLAGS, pftOut: ptr FILETIME): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToGUID*(varIn: ptr VARIANT, pguid: ptr GUID): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt16*(varIn: ptr VARIANT, piRet: ptr int16): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt16Array*(`var`: ptr VARIANT, prgn: ptr int16, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt16ArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr int16, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt16WithDefault*(varIn: ptr VARIANT, iDefault: int16): int16 {.sideEffect, importc, stdcall.}
proc VariantToInt32*(varIn: ptr VARIANT, plRet: ptr int32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt32Array*(`var`: ptr VARIANT, prgn: ptr int32, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt32ArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr int32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt32WithDefault*(varIn: ptr VARIANT, lDefault: int32): int32 {.sideEffect, importc, stdcall.}
proc VariantToInt64*(varIn: ptr VARIANT, pllRet: ptr int64): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt64Array*(`var`: ptr VARIANT, prgn: ptr int64, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt64ArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr int64, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToInt64WithDefault*(varIn: ptr VARIANT, llDefault: int64): int64 {.sideEffect, importc, stdcall.}
proc VariantToPropVariant*(pVar: ptr VARIANT, pPropVar: ptr PROPVARIANT): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToStrRet*(varIn: ptr VARIANT, pstrret: ptr STRRET): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToString*(varIn: ptr VARIANT, pszBuf: PWSTR, cchBuf: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToStringAlloc*(varIn: ptr VARIANT, ppszBuf: ptr PWSTR): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToStringArray*(`var`: ptr VARIANT, prgsz: ptr PWSTR, crgsz: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToStringArrayAlloc*(`var`: ptr VARIANT, pprgsz: ptr ptr PWSTR, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToStringWithDefault*(varIn: ptr VARIANT, pszDefault: PCWSTR): PCWSTR {.sideEffect, importc, stdcall.}
proc VariantToUInt16*(varIn: ptr VARIANT, puiRet: ptr uint16): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt16Array*(`var`: ptr VARIANT, prgn: ptr uint16, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt16ArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr uint16, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt16WithDefault*(varIn: ptr VARIANT, uiDefault: uint16): uint16 {.sideEffect, importc, stdcall.}
proc VariantToUInt32*(varIn: ptr VARIANT, pulRet: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt32Array*(`var`: ptr VARIANT, prgn: ptr uint32, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt32ArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt32WithDefault*(varIn: ptr VARIANT, ulDefault: uint32): uint32 {.sideEffect, importc, stdcall.}
proc VariantToUInt64*(varIn: ptr VARIANT, pullRet: ptr uint64): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt64Array*(`var`: ptr VARIANT, prgn: ptr uint64, crgn: uint32, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt64ArrayAlloc*(`var`: ptr VARIANT, pprgn: ptr ptr uint64, pcElem: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc VariantToUInt64WithDefault*(varIn: ptr VARIANT, ullDefault: uint64): uint64 {.sideEffect, importc, stdcall.}
{.pop.}
