# generated by winmd2nim from Windows.Win32.winmd — psapi (do not edit)
import ./[winnt, minwindef]
export winnt, minwindef

type

  # structs
  ENUM_PAGE_FILE_INFORMATION* {.completeStruct.} = object
    cb*: uint32
    Reserved*: uint32
    TotalSize*: uint
    TotalInUse*: uint
    PeakUsage*: uint
  MODULEINFO* {.completeStruct.} = object
    lpBaseOfDll*: pointer
    SizeOfImage*: uint32
    EntryPoint*: pointer
  PERFORMANCE_INFORMATION* {.completeStruct.} = object
    cb*: uint32
    CommitTotal*: uint
    CommitLimit*: uint
    CommitPeak*: uint
    PhysicalTotal*: uint
    PhysicalAvailable*: uint
    SystemCache*: uint
    KernelTotal*: uint
    KernelPaged*: uint
    KernelNonpaged*: uint
    PageSize*: uint
    HandleCount*: uint32
    ProcessCount*: uint32
    ThreadCount*: uint32
  PROCESS_MEMORY_COUNTERS* {.completeStruct.} = object
    cb*: uint32
    PageFaultCount*: uint32
    PeakWorkingSetSize*: uint
    WorkingSetSize*: uint
    QuotaPeakPagedPoolUsage*: uint
    QuotaPagedPoolUsage*: uint
    QuotaPeakNonPagedPoolUsage*: uint
    QuotaNonPagedPoolUsage*: uint
    PagefileUsage*: uint
    PeakPagefileUsage*: uint
  PROCESS_MEMORY_COUNTERS_EX* {.completeStruct.} = object
    cb*: uint32
    PageFaultCount*: uint32
    PeakWorkingSetSize*: uint
    WorkingSetSize*: uint
    QuotaPeakPagedPoolUsage*: uint
    QuotaPagedPoolUsage*: uint
    QuotaPeakNonPagedPoolUsage*: uint
    QuotaNonPagedPoolUsage*: uint
    PagefileUsage*: uint
    PeakPagefileUsage*: uint
    PrivateUsage*: uint
  PROCESS_MEMORY_COUNTERS_EX2* {.completeStruct.} = object
    cb*: uint32
    PageFaultCount*: uint32
    PeakWorkingSetSize*: uint
    WorkingSetSize*: uint
    QuotaPeakPagedPoolUsage*: uint
    QuotaPagedPoolUsage*: uint
    QuotaPeakNonPagedPoolUsage*: uint
    QuotaNonPagedPoolUsage*: uint
    PagefileUsage*: uint
    PeakPagefileUsage*: uint
    PrivateUsage*: uint
    PrivateWorkingSetSize*: uint
    SharedCommitUsage*: uint64
  PSAPI_WORKING_SET_BLOCK* {.completeStruct, union.} = object
    Flags*: uint
    Anonymous*: PSAPI_WORKING_SET_BLOCK_1
  PSAPI_WORKING_SET_BLOCK_1* {.completeStruct.} = object
    X_bitfield*: uint
  PSAPI_WORKING_SET_EX_BLOCK* {.completeStruct, union.} = object
    Flags*: uint
    Anonymous*: PSAPI_WORKING_SET_EX_BLOCK_1
  PSAPI_WORKING_SET_EX_BLOCK_1* {.completeStruct, union.} = object
    Anonymous*: PSAPI_WORKING_SET_EX_BLOCK_1_0
    Invalid*: PSAPI_WORKING_SET_EX_BLOCK_1_1
  PSAPI_WORKING_SET_EX_BLOCK_1_0* {.completeStruct.} = object
    X_bitfield*: uint
  PSAPI_WORKING_SET_EX_BLOCK_1_1* {.completeStruct.} = object
    X_bitfield*: uint
  PSAPI_WORKING_SET_EX_INFORMATION* {.completeStruct.} = object
    VirtualAddress*: pointer
    VirtualAttributes*: PSAPI_WORKING_SET_EX_BLOCK
  PSAPI_WORKING_SET_INFORMATION* {.completeStruct.} = object
    NumberOfEntries*: uint
    WorkingSetInfo*: array[1, PSAPI_WORKING_SET_BLOCK]
  PSAPI_WS_WATCH_INFORMATION* {.completeStruct.} = object
    FaultingPc*: pointer
    FaultingVa*: pointer
  PSAPI_WS_WATCH_INFORMATION_EX* {.completeStruct.} = object
    BasicInfo*: PSAPI_WS_WATCH_INFORMATION
    FaultingThreadId*: uint
    Flags*: uint

  # typdefs
  LPMODULEINFO* = ptr MODULEINFO
  PENUM_PAGE_FILE_INFORMATION* = ptr ENUM_PAGE_FILE_INFORMATION
  PERFORMACE_INFORMATION* = PERFORMANCE_INFORMATION
  PPERFORMACE_INFORMATION* = ptr PERFORMANCE_INFORMATION
  PPERFORMANCE_INFORMATION* = ptr PERFORMANCE_INFORMATION
  PPROCESS_MEMORY_COUNTERS* = ptr PROCESS_MEMORY_COUNTERS
  PPROCESS_MEMORY_COUNTERS_EX* = ptr PROCESS_MEMORY_COUNTERS_EX
  PPROCESS_MEMORY_COUNTERS_EX2* = ptr PROCESS_MEMORY_COUNTERS_EX2
  PPSAPI_WORKING_SET_BLOCK* = ptr PSAPI_WORKING_SET_BLOCK
  PPSAPI_WORKING_SET_EX_BLOCK* = ptr PSAPI_WORKING_SET_EX_BLOCK
  PPSAPI_WORKING_SET_EX_INFORMATION* = ptr PSAPI_WORKING_SET_EX_INFORMATION
  PPSAPI_WORKING_SET_INFORMATION* = ptr PSAPI_WORKING_SET_INFORMATION
  PPSAPI_WS_WATCH_INFORMATION* = ptr PSAPI_WS_WATCH_INFORMATION
  PPSAPI_WS_WATCH_INFORMATION_EX* = ptr PSAPI_WS_WATCH_INFORMATION_EX

  # delegates
  PENUM_PAGE_FILE_CALLBACKA* = proc (arg_1: pointer, arg_2: ptr ENUM_PAGE_FILE_INFORMATION, arg_3: PCSTR): BOOL {.stdcall.}
  PENUM_PAGE_FILE_CALLBACKW* = proc (arg_1: pointer, arg_2: ptr ENUM_PAGE_FILE_INFORMATION, arg_3: PCWSTR): BOOL {.stdcall.}

const
  # free constants
  LIST_MODULES_32BIT*: int32 = 1'i32
  LIST_MODULES_64BIT*: int32 = 2'i32
  LIST_MODULES_ALL*: int32 = 3'i32
  LIST_MODULES_DEFAULT*: int32 = 0'i32
  PSAPI_VERSION*: int32 = 2'i32

{.push dynlib: "kernel32".}
proc EmptyWorkingSet*(hProcess: HANDLE): BOOL {.sideEffect, importc: "K32EmptyWorkingSet", stdcall.}
proc EnumDeviceDrivers*(lpImageBase: ptr pointer, cb: uint32, lpcbNeeded: ptr uint32): BOOL {.sideEffect, importc: "K32EnumDeviceDrivers", stdcall.}
proc EnumPageFilesA*(pCallBackRoutine: PENUM_PAGE_FILE_CALLBACKA, pContext: pointer): BOOL {.sideEffect, importc: "K32EnumPageFilesA", stdcall.}
proc EnumPageFilesW*(pCallBackRoutine: PENUM_PAGE_FILE_CALLBACKW, pContext: pointer): BOOL {.sideEffect, importc: "K32EnumPageFilesW", stdcall.}
proc EnumProcessModules*(hProcess: HANDLE, lphModule: ptr HMODULE, cb: uint32, lpcbNeeded: ptr uint32): BOOL {.sideEffect, importc: "K32EnumProcessModules", stdcall.}
proc EnumProcessModulesEx*(hProcess: HANDLE, lphModule: ptr HMODULE, cb: uint32, lpcbNeeded: ptr uint32, dwFilterFlag: uint32): BOOL {.sideEffect, importc: "K32EnumProcessModulesEx", stdcall.}
proc EnumProcesses*(lpidProcess: ptr uint32, cb: uint32, lpcbNeeded: ptr uint32): BOOL {.sideEffect, importc: "K32EnumProcesses", stdcall.}
proc GetDeviceDriverBaseNameA*(ImageBase: pointer, lpFilename: PSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetDeviceDriverBaseNameA", stdcall.}
proc GetDeviceDriverBaseNameW*(ImageBase: pointer, lpBaseName: PWSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetDeviceDriverBaseNameW", stdcall.}
proc GetDeviceDriverFileNameA*(ImageBase: pointer, lpFilename: PSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetDeviceDriverFileNameA", stdcall.}
proc GetDeviceDriverFileNameW*(ImageBase: pointer, lpFilename: PWSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetDeviceDriverFileNameW", stdcall.}
proc GetMappedFileNameA*(hProcess: HANDLE, lpv: pointer, lpFilename: PSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetMappedFileNameA", stdcall.}
proc GetMappedFileNameW*(hProcess: HANDLE, lpv: pointer, lpFilename: PWSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetMappedFileNameW", stdcall.}
proc GetModuleBaseNameA*(hProcess: HANDLE, hModule: HMODULE, lpBaseName: PSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetModuleBaseNameA", stdcall.}
proc GetModuleBaseNameW*(hProcess: HANDLE, hModule: HMODULE, lpBaseName: PWSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetModuleBaseNameW", stdcall.}
proc GetModuleFileNameExA*(hProcess: HANDLE, hModule: HMODULE, lpFilename: PSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetModuleFileNameExA", stdcall.}
proc GetModuleFileNameExW*(hProcess: HANDLE, hModule: HMODULE, lpFilename: PWSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetModuleFileNameExW", stdcall.}
proc GetModuleInformation*(hProcess: HANDLE, hModule: HMODULE, lpmodinfo: ptr MODULEINFO, cb: uint32): BOOL {.sideEffect, importc: "K32GetModuleInformation", stdcall.}
proc GetPerformanceInfo*(pPerformanceInformation: ptr PERFORMANCE_INFORMATION, cb: uint32): BOOL {.sideEffect, importc: "K32GetPerformanceInfo", stdcall.}
proc GetProcessImageFileNameA*(hProcess: HANDLE, lpImageFileName: PSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetProcessImageFileNameA", stdcall.}
proc GetProcessImageFileNameW*(hProcess: HANDLE, lpImageFileName: PWSTR, nSize: uint32): uint32 {.sideEffect, importc: "K32GetProcessImageFileNameW", stdcall.}
proc GetProcessMemoryInfo*(Process: HANDLE, ppsmemCounters: ptr PROCESS_MEMORY_COUNTERS, cb: uint32): BOOL {.sideEffect, importc: "K32GetProcessMemoryInfo", stdcall.}
proc GetWsChanges*(hProcess: HANDLE, lpWatchInfo: ptr PSAPI_WS_WATCH_INFORMATION, cb: uint32): BOOL {.sideEffect, importc: "K32GetWsChanges", stdcall.}
proc GetWsChangesEx*(hProcess: HANDLE, lpWatchInfoEx: ptr PSAPI_WS_WATCH_INFORMATION_EX, cb: ptr uint32): BOOL {.sideEffect, importc: "K32GetWsChangesEx", stdcall.}
proc InitializeProcessForWsWatch*(hProcess: HANDLE): BOOL {.sideEffect, importc: "K32InitializeProcessForWsWatch", stdcall.}
proc QueryWorkingSet*(hProcess: HANDLE, pv: pointer, cb: uint32): BOOL {.sideEffect, importc: "K32QueryWorkingSet", stdcall.}
proc QueryWorkingSetEx*(hProcess: HANDLE, pv: pointer, cb: uint32): BOOL {.sideEffect, importc: "K32QueryWorkingSetEx", stdcall.}
{.pop.}
