# generated by winmd2nim from Windows.Win32.winmd — restrictederrorinfo (do not edit)

type

  # interfaces
  ILanguageExceptionErrorInfo* = distinct object
  ILanguageExceptionErrorInfo2* = distinct object
  ILanguageExceptionStackBackTrace* = distinct object
  ILanguageExceptionTransform* = distinct object
  IRestrictedErrorInfo* = distinct object

