# generated by winmd2nim from Windows.Win32.winmd — rpcdcep (do not edit)
import ./[rpcdce, guiddef, rpc]
export rpcdce, guiddef, rpc

type

  # structs
  I_RpcProxyCallbackInterface* {.completeStruct.} = object
    IsValidMachineFn*: I_RpcProxyIsValidMachineFn
    GetClientAddressFn*: I_RpcProxyGetClientAddressFn
    GetConnectionTimeoutFn*: I_RpcProxyGetConnectionTimeoutFn
    PerformCalloutFn*: I_RpcPerformCalloutFn
    FreeCalloutStateFn*: I_RpcFreeCalloutStateFn
    GetClientSessionAndResourceUUIDFn*: I_RpcProxyGetClientSessionAndResourceUUID
    ProxyFilterIfFn*: I_RpcProxyFilterIfFn
    RpcProxyUpdatePerfCounterFn*: I_RpcProxyUpdatePerfCounterFn
    RpcProxyUpdatePerfCounterBackendServerFn*: I_RpcProxyUpdatePerfCounterBackendServerFn
  RDR_CALLOUT_STATE* {.completeStruct.} = object
    LastError*: RPC_STATUS
    LastEEInfo*: pointer
    LastCalledStage*: RPC_HTTP_REDIRECTOR_STAGE
    ServerName*: ptr uint16
    ServerPort*: ptr uint16
    RemoteUser*: ptr uint16
    AuthType*: ptr uint16
    ResourceTypePresent*: uint8
    SessionIdPresent*: uint8
    InterfacePresent*: uint8
    ResourceType*: GUID
    SessionId*: GUID
    Interface*: RPC_SYNTAX_IDENTIFIER
    CertContext*: pointer
  RPC_CLIENT_INTERFACE* {.completeStruct.} = object
    Length*: uint32
    InterfaceId*: RPC_SYNTAX_IDENTIFIER
    TransferSyntax*: RPC_SYNTAX_IDENTIFIER
    DispatchTable*: PRPC_DISPATCH_TABLE
    RpcProtseqEndpointCount*: uint32
    RpcProtseqEndpoint*: PRPC_PROTSEQ_ENDPOINT
    Reserved*: uint
    InterpreterInfo*: pointer
    Flags*: uint32
  RPC_C_OPT_COOKIE_AUTH_DESCRIPTOR* {.completeStruct.} = object
    BufferSize*: uint32
    Buffer*: ptr int8
  RPC_DISPATCH_TABLE* {.completeStruct.} = object
    DispatchTableCount*: uint32
    DispatchTable*: ptr RPC_DISPATCH_FUNCTION
    Reserved*: int
  RPC_MESSAGE* {.completeStruct.} = object
    Handle*: RPC_BINDING_HANDLE
    DataRepresentation*: uint32
    Buffer*: pointer
    BufferLength*: uint32
    ProcNum*: uint32
    TransferSyntax*: PRPC_SYNTAX_IDENTIFIER
    RpcInterfaceInformation*: pointer
    ReservedForRuntime*: pointer
    ManagerEpv*: pointer
    ImportContext*: pointer
    RpcFlags*: uint32
  RPC_PROTSEQ_ENDPOINT* {.completeStruct.} = object
    RpcProtocolSequence*: ptr uint8
    Endpoint*: ptr uint8
  RPC_SEC_CONTEXT_KEY_INFO* {.completeStruct.} = object
    EncryptAlgorithm*: uint32
    KeySize*: uint32
    SignatureAlgorithm*: uint32
  RPC_SERVER_INTERFACE* {.completeStruct.} = object
    Length*: uint32
    InterfaceId*: RPC_SYNTAX_IDENTIFIER
    TransferSyntax*: RPC_SYNTAX_IDENTIFIER
    DispatchTable*: PRPC_DISPATCH_TABLE
    RpcProtseqEndpointCount*: uint32
    RpcProtseqEndpoint*: PRPC_PROTSEQ_ENDPOINT
    DefaultManagerEpv*: pointer
    InterpreterInfo*: pointer
    Flags*: uint32
  RPC_SYNTAX_IDENTIFIER* {.completeStruct.} = object
    SyntaxGUID*: GUID
    SyntaxVersion*: RPC_VERSION
  RPC_TRANSFER_SYNTAX* {.completeStruct.} = object
    Uuid*: GUID
    VersMajor*: uint16
    VersMinor*: uint16
  RPC_VERSION* {.completeStruct.} = object
    MajorVersion*: uint16
    MinorVersion*: uint16

  # typdefs
  I_RPC_MUTEX* = distinct pointer
  PRPC_CLIENT_INTERFACE* = ptr RPC_CLIENT_INTERFACE
  PRPC_DISPATCH_TABLE* = ptr RPC_DISPATCH_TABLE
  PRPC_MESSAGE* = ptr RPC_MESSAGE
  PRPC_PROTSEQ_ENDPOINT* = ptr RPC_PROTSEQ_ENDPOINT
  PRPC_SEC_CONTEXT_KEY_INFO* = ptr RPC_SEC_CONTEXT_KEY_INFO
  PRPC_SERVER_INTERFACE* = ptr RPC_SERVER_INTERFACE
  PRPC_SYNTAX_IDENTIFIER* = ptr RPC_SYNTAX_IDENTIFIER

  # unscoped enums 
  LRPC_SYSTEM_HANDLE_MARSHAL_DIRECTION* = int32
  RPC_ADDRESS_CHANGE_TYPE* = int32
  RpcPerfCounters* = int32

  # delegates
  I_RpcFreeCalloutStateFn* = proc (arg_1: ptr RDR_CALLOUT_STATE): void {.stdcall.}
  I_RpcPerformCalloutFn* = proc (arg_1: pointer, arg_2: ptr RDR_CALLOUT_STATE, arg_3: RPC_HTTP_REDIRECTOR_STAGE): RPC_STATUS {.stdcall.}
  I_RpcProxyFilterIfFn* = proc (arg_1: pointer, arg_2: ptr GUID, arg_3: uint16, arg_4: ptr int32): RPC_STATUS {.stdcall.}
  I_RpcProxyGetClientAddressFn* = proc (arg_1: pointer, arg_2: ptr int8, arg_3: ptr uint32): RPC_STATUS {.stdcall.}
  I_RpcProxyGetClientSessionAndResourceUUID* = proc (arg_1: pointer, arg_2: ptr int32, arg_3: ptr GUID, arg_4: ptr int32, arg_5: ptr GUID): RPC_STATUS {.stdcall.}
  I_RpcProxyGetConnectionTimeoutFn* = proc (arg_1: ptr uint32): RPC_STATUS {.stdcall.}
  I_RpcProxyIsValidMachineFn* = proc (arg_1: ptr uint16, arg_2: ptr uint16, arg_3: uint32): RPC_STATUS {.stdcall.}
  I_RpcProxyUpdatePerfCounterBackendServerFn* = proc (arg_1: ptr uint16, arg_2: int32): void {.stdcall.}
  I_RpcProxyUpdatePerfCounterFn* = proc (arg_1: RpcPerfCounters, arg_2: int32, arg_3: uint32): void {.stdcall.}
  PRPC_RUNDOWN* = proc (arg_1: pointer): void {.stdcall.}
  RPCLT_PDU_FILTER_FUNC* = proc (arg_1: pointer, arg_2: uint32, arg_3: int32): void {.stdcall.}
  RPC_ADDRESS_CHANGE_FN* = proc (arg_1: pointer): void {.stdcall.}
  RPC_BLOCKING_FN* = proc (arg_1: pointer, arg_2: pointer, arg_3: pointer): RPC_STATUS {.stdcall.}
  RPC_DISPATCH_FUNCTION* = proc (arg_1: ptr RPC_MESSAGE): void {.stdcall.}
  RPC_FORWARD_FUNCTION* = proc (arg_1: ptr GUID, arg_2: ptr RPC_VERSION, arg_3: ptr GUID, arg_4: ptr uint8, arg_5: ptr pointer): RPC_STATUS {.stdcall.}
  RPC_SETFILTER_FUNC* = proc (arg_1: RPCLT_PDU_FILTER_FUNC): void {.stdcall.}

const
  # free constants
  NDR_CUSTOM_OR_DEFAULT_ALLOCATOR*: uint32 = 0x10000000'u32
  NDR_DEFAULT_ALLOCATOR*: uint32 = 0x20000000'u32
  NT351_INTERFACE_SIZE*: int32 = 64'i32
  RPCFLG_ACCESSIBILITY_BIT1*: uint32 = 0x100000'u32
  RPCFLG_ACCESSIBILITY_BIT2*: uint32 = 0x200000'u32
  RPCFLG_ACCESS_LOCAL*: uint32 = 0x400000'u32
  RPCFLG_ASYNCHRONOUS*: uint32 = 0x40000000'u32
  RPCFLG_AUTO_COMPLETE*: uint32 = 0x8000000'u32
  RPCFLG_HAS_CALLBACK*: uint32 = 0x4000000'u32
  RPCFLG_HAS_GUARANTEE*: uint32 = 0x10'u32
  RPCFLG_HAS_MULTI_SYNTAXES*: uint32 = 0x2000000'u32
  RPCFLG_INPUT_SYNCHRONOUS*: uint32 = 0x20000000'u32
  RPCFLG_LOCAL_CALL*: uint32 = 0x10000000'u32
  RPCFLG_MESSAGE*: uint32 = 0x1000000'u32
  RPCFLG_NDR64_CONTAINS_ARM_LAYOUT*: uint32 = 0x4000000'u32
  RPCFLG_NON_NDR*: uint32 = 0x80000000'u32
  RPCFLG_SENDER_WAITING_FOR_REPLY*: uint32 = 0x800000'u32
  RPCFLG_WINRT_REMOTE_ASYNC*: uint32 = 0x20'u32
  RPC_BUFFER_ASYNC*: int32 = 32768'i32
  RPC_BUFFER_COMPLETE*: int32 = 4096'i32
  RPC_BUFFER_EXTRA*: int32 = 16384'i32
  RPC_BUFFER_NONOTIFY*: int32 = 65536'i32
  RPC_BUFFER_PARTIAL*: int32 = 8192'i32
  RPC_CONTEXT_HANDLE_DEFAULT_FLAGS*: uint32 = 0x0'u32
  RPC_CONTEXT_HANDLE_DONT_SERIALIZE*: uint32 = 0x20000000'u32
  RPC_CONTEXT_HANDLE_FLAGS*: uint32 = 0x30000000'u32
  RPC_CONTEXT_HANDLE_SERIALIZE*: uint32 = 0x10000000'u32
  RPC_C_OPT_COOKIE_AUTH*: int32 = 7'i32
  RPC_C_OPT_PRIVATE_BREAK_ON_SUSPEND*: int32 = 3'i32
  RPC_C_OPT_PRIVATE_DO_NOT_DISTURB*: int32 = 2'i32
  RPC_C_OPT_PRIVATE_SUPPRESS_WAKE*: int32 = 1'i32
  RPC_C_OPT_RESOURCE_TYPE_UUID*: int32 = 8'i32
  RPC_C_OPT_SESSION_ID*: int32 = 6'i32
  RPC_FLAGS_VALID_BIT*: int32 = 32768'i32
  RPC_INTERFACE_HAS_PIPES*: int32 = 1'i32
  RPC_NCA_FLAGS_BROADCAST*: int32 = 2'i32
  RPC_NCA_FLAGS_DEFAULT*: int32 = 0'i32
  RPC_NCA_FLAGS_IDEMPOTENT*: int32 = 1'i32
  RPC_NCA_FLAGS_MAYBE*: int32 = 4'i32
  RPC_PROXY_CONNECTION_TYPE_IN_PROXY*: int32 = 0'i32
  RPC_PROXY_CONNECTION_TYPE_OUT_PROXY*: int32 = 1'i32
  RPC_P_ADDR_FORMAT_TCP_IPV4*: int32 = 1'i32
  RPC_P_ADDR_FORMAT_TCP_IPV6*: int32 = 2'i32
  RPC_SYSTEM_HANDLE_FREE_ALL*: int32 = 3'i32
  RPC_SYSTEM_HANDLE_FREE_ERROR_ON_CLOSE*: int32 = 4'i32
  RPC_SYSTEM_HANDLE_FREE_RETRIEVED*: int32 = 2'i32
  RPC_SYSTEM_HANDLE_FREE_UNRETRIEVED*: int32 = 1'i32
  RPC_TYPE_DISCONNECT_EVENT_CONTEXT_HANDLE*: uint32 = 0x80000000'u32
  RPC_TYPE_STRICT_CONTEXT_HANDLE*: uint32 = 0x40000000'u32
  TRANSPORT_TYPE_CN*: int32 = 1'i32
  TRANSPORT_TYPE_DG*: int32 = 2'i32
  TRANSPORT_TYPE_LPC*: int32 = 4'i32
  TRANSPORT_TYPE_WMSG*: int32 = 8'i32

  # unscoped enum members
  MarshalDirectionMarshal*: LRPC_SYSTEM_HANDLE_MARSHAL_DIRECTION = 0'i32
  MarshalDirectionUnmarshal*: LRPC_SYSTEM_HANDLE_MARSHAL_DIRECTION = 1'i32
  PROTOCOL_NOT_LOADED*: RPC_ADDRESS_CHANGE_TYPE = 1'i32
  PROTOCOL_LOADED*: RPC_ADDRESS_CHANGE_TYPE = 2'i32
  PROTOCOL_ADDRESS_CHANGE*: RPC_ADDRESS_CHANGE_TYPE = 3'i32
  RpcCurrentUniqueUser*: RpcPerfCounters = 1'i32
  RpcBackEndConnectionAttempts*: RpcPerfCounters = 2'i32
  RpcBackEndConnectionFailed*: RpcPerfCounters = 3'i32
  RpcRequestsPerSecond*: RpcPerfCounters = 4'i32
  RpcIncomingConnections*: RpcPerfCounters = 5'i32
  RpcIncomingBandwidth*: RpcPerfCounters = 6'i32
  RpcOutgoingBandwidth*: RpcPerfCounters = 7'i32
  RpcAttemptedLbsDecisions*: RpcPerfCounters = 8'i32
  RpcFailedLbsDecisions*: RpcPerfCounters = 9'i32
  RpcAttemptedLbsMessages*: RpcPerfCounters = 10'i32
  RpcFailedLbsMessages*: RpcPerfCounters = 11'i32
  RpcLastCounter*: RpcPerfCounters = 12'i32

{.push dynlib: "rpcrt4".}
proc I_RpcAllocate*(Size: uint32): pointer {.sideEffect, importc, stdcall.}
proc I_RpcBindingCopy*(SourceBinding: RPC_BINDING_HANDLE, DestinationBinding: ptr RPC_BINDING_HANDLE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingCreateNP*(ServerName: ptr uint16, ServiceName: ptr uint16, NetworkOptions: ptr uint16, Binding: ptr RPC_BINDING_HANDLE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingHandleToAsyncHandle*(Binding: RPC_BINDING_HANDLE, AsyncHandle: ptr pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqDynamicEndpointA*(Binding: RPC_BINDING_HANDLE, DynamicEndpoint: ptr RPC_CSTR): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqDynamicEndpointW*(Binding: RPC_BINDING_HANDLE, DynamicEndpoint: ptr RPC_WSTR): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqLocalClientPID*(Binding: RPC_BINDING_HANDLE, Pid: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqMarshalledTargetInfo*(Binding: RPC_BINDING_HANDLE, MarshalledTargetInfoSize: ptr uint32, MarshalledTargetInfo: ptr RPC_CSTR): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqSecurityContext*(Binding: RPC_BINDING_HANDLE, SecurityContextHandle: ptr pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqSecurityContextKeyInfo*(Binding: RPC_BINDING_HANDLE, KeyInfo: pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqTransportType*(Binding: RPC_BINDING_HANDLE, Type: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingInqWireIdForSnego*(Binding: RPC_BINDING_HANDLE, WireId: ptr uint8): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingIsClientLocal*(BindingHandle: RPC_BINDING_HANDLE, ClientLocalFlag: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingIsServerLocal*(Binding: RPC_BINDING_HANDLE, ServerLocalFlag: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingSetPrivateOption*(hBinding: RPC_BINDING_HANDLE, option: uint32, optionValue: uint): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcBindingToStaticStringBindingW*(Binding: RPC_BINDING_HANDLE, StringBinding: ptr ptr uint16): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcClearMutex*(Mutex: I_RPC_MUTEX) {.sideEffect, importc, stdcall.}
proc I_RpcDeleteMutex*(Mutex: I_RPC_MUTEX) {.sideEffect, importc, stdcall.}
proc I_RpcFree*(Object: pointer) {.sideEffect, importc, stdcall.}
proc I_RpcFreeBuffer*(Message: ptr RPC_MESSAGE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcFreePipeBuffer*(Message: ptr RPC_MESSAGE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcGetBuffer*(Message: ptr RPC_MESSAGE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcGetBufferWithObject*(Message: ptr RPC_MESSAGE, ObjectUuid: ptr GUID): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcGetCurrentCallHandle*(): RPC_BINDING_HANDLE {.sideEffect, importc, stdcall.}
proc I_RpcGetDefaultSD*(ppSecurityDescriptor: ptr pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcGetExtendedError*(): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcIfInqTransferSyntaxes*(RpcIfHandle: RPC_IF_HANDLE, TransferSyntaxes: ptr RPC_TRANSFER_SYNTAX, TransferSyntaxSize: uint32, TransferSyntaxCount: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcMapWin32Status*(Status: RPC_STATUS): int32 {.sideEffect, importc, stdcall.}
proc I_RpcMgmtEnableDedicatedThreadPool*(): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcNegotiateTransferSyntax*(Message: ptr RPC_MESSAGE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcNsBindingSetEntryNameA*(Binding: RPC_BINDING_HANDLE, EntryNameSyntax: uint32, EntryName: ptr uint8): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcNsBindingSetEntryNameW*(Binding: RPC_BINDING_HANDLE, EntryNameSyntax: uint32, EntryName: ptr uint16): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcNsInterfaceExported*(EntryNameSyntax: uint32, EntryName: ptr uint16, RpcInterfaceInformation: ptr RPC_SERVER_INTERFACE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcNsInterfaceUnexported*(EntryNameSyntax: uint32, EntryName: ptr uint16, RpcInterfaceInformation: ptr RPC_SERVER_INTERFACE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcOpenClientProcess*(Binding: RPC_BINDING_HANDLE, DesiredAccess: uint32, ClientProcess: ptr pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcPauseExecution*(Milliseconds: uint32) {.sideEffect, importc, stdcall.}
proc I_RpcReallocPipeBuffer*(Message: ptr RPC_MESSAGE, NewSize: uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcReceive*(Message: ptr RPC_MESSAGE, Size: uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcRecordCalloutFailure*(RpcStatus: RPC_STATUS, CallOutState: ptr RDR_CALLOUT_STATE, DllName: ptr uint16) {.sideEffect, importc, stdcall.}
proc I_RpcRequestMutex*(Mutex: ptr I_RPC_MUTEX) {.sideEffect, importc, stdcall.}
proc I_RpcSend*(Message: ptr RPC_MESSAGE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcSendReceive*(Message: ptr RPC_MESSAGE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerCheckClientRestriction*(Context: RPC_BINDING_HANDLE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerDisableExceptionFilter*(): int32 {.sideEffect, importc, stdcall.}
proc I_RpcServerGetAssociationID*(Binding: RPC_BINDING_HANDLE, AssociationID: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerInqAddressChangeFn*(): RPC_ADDRESS_CHANGE_FN {.sideEffect, importc, stdcall.}
proc I_RpcServerInqLocalConnAddress*(Binding: RPC_BINDING_HANDLE, Buffer: pointer, BufferSize: ptr uint32, AddressFormat: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerInqRemoteConnAddress*(Binding: RPC_BINDING_HANDLE, Buffer: pointer, BufferSize: ptr uint32, AddressFormat: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerInqTransportType*(Type: ptr uint32): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerRegisterForwardFunction*(pForwardFunction: RPC_FORWARD_FUNCTION): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerSetAddressChangeFn*(pAddressChangeFn: RPC_ADDRESS_CHANGE_FN): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerStartService*(Protseq: ptr uint16, Endpoint: ptr uint16, IfSpec: RPC_IF_HANDLE): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerSubscribeForDisconnectNotification*(Binding: RPC_BINDING_HANDLE, hEvent: pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerSubscribeForDisconnectNotification2*(Binding: RPC_BINDING_HANDLE, hEvent: pointer, SubscriptionId: ptr GUID): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerUnsubscribeForDisconnectNotification*(Binding: RPC_BINDING_HANDLE, SubscriptionId: GUID): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerUseProtseq2A*(NetworkAddress: ptr uint8, Protseq: ptr uint8, MaxCalls: uint32, SecurityDescriptor: pointer, Policy: pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerUseProtseq2W*(NetworkAddress: ptr uint16, Protseq: ptr uint16, MaxCalls: uint32, SecurityDescriptor: pointer, Policy: pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerUseProtseqEp2A*(NetworkAddress: ptr uint8, Protseq: ptr uint8, MaxCalls: uint32, Endpoint: ptr uint8, SecurityDescriptor: pointer, Policy: pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcServerUseProtseqEp2W*(NetworkAddress: ptr uint16, Protseq: ptr uint16, MaxCalls: uint32, Endpoint: ptr uint16, SecurityDescriptor: pointer, Policy: pointer): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcSessionStrictContextHandle*() {.sideEffect, importc, stdcall.}
proc I_RpcSsDontSerializeContext*() {.sideEffect, importc, stdcall.}
proc I_RpcSystemHandleTypeSpecificWork*(Handle: pointer, ActualType: uint8, IdlType: uint8, MarshalDirection: LRPC_SYSTEM_HANDLE_MARSHAL_DIRECTION): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_RpcTurnOnEEInfoPropagation*(): RPC_STATUS {.sideEffect, importc, stdcall.}
proc I_UuidCreate*(Uuid: ptr GUID): RPC_STATUS {.sideEffect, importc, stdcall.}
{.pop.}
