# generated by winmd2nim from Windows.Win32.winmd — RTWorkQ.DLL (do not edit)
import ./[unknwnbase, winnt, minwindef, minwinbase]
export unknwnbase, winnt, minwindef, minwinbase

type

  # structs
  RTWQASYNCRESULT* {.completeStruct.} = object
    Base*: IRtwqAsyncResult
    overlapped*: OVERLAPPED
    pCallback*: IRtwqAsyncCallback
    hrStatusResult*: HRESULT
    dwBytesTransferred*: uint32
    hEvent*: HANDLE

  # typdefs
  RTWQWORKITEM_KEY* = distinct uint64

  # unscoped enums 
  RTWQ_WORKQUEUE_TYPE* = int32

  # delegates
  RTWQPERIODICCALLBACK* = proc (arg_1: IUnknown): void {.stdcall.}

  # interfaces
  IRtwqAsyncCallback* = distinct object
  IRtwqAsyncResult* = distinct object
  IRtwqPlatformEvents* = distinct object

const
  # free constants
  RTWQ_E_BUFFERTOOSMALL*: int32 = -1072875855'i32
  RTWQ_E_INVALID_WORKQUEUE*: int32 = -1072875777'i32
  RTWQ_E_NOT_FOUND*: int32 = -1072875819'i32
  RTWQ_E_NOT_INITIALIZED*: int32 = -1072875850'i32
  RTWQ_E_OPERATION_CANCELLED*: int32 = -1072875795'i32
  RTWQ_E_SHUTDOWN*: int32 = -1072873851'i32
  RTWQ_E_UNEXPECTED*: int32 = -1072875845'i32

  # unscoped enum members
  RTWQ_STANDARD_WORKQUEUE*: RTWQ_WORKQUEUE_TYPE = 0'i32
  RTWQ_WINDOW_WORKQUEUE*: RTWQ_WORKQUEUE_TYPE = 1'i32
  RTWQ_MULTITHREADED_WORKQUEUE*: RTWQ_WORKQUEUE_TYPE = 2'i32

{.push dynlib: "rtworkq".}
proc RtwqAddPeriodicCallback*(Callback: RTWQPERIODICCALLBACK, context: IUnknown, key: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqAllocateSerialWorkQueue*(workQueueIdIn: uint32, workQueueIdOut: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqAllocateWorkQueue*(WorkQueueType: RTWQ_WORKQUEUE_TYPE, workQueueId: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqBeginRegisterWorkQueueWithMMCSS*(workQueueId: uint32, usageClass: PCWSTR, dwTaskId: uint32, lPriority: int32, doneCallback: IRtwqAsyncCallback, doneState: IUnknown): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqBeginUnregisterWorkQueueWithMMCSS*(workQueueId: uint32, doneCallback: IRtwqAsyncCallback, doneState: IUnknown): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqCancelDeadline*(pRequest: HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqCancelWorkItem*(Key: RTWQWORKITEM_KEY): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqCreateAsyncResult*(appObject: IUnknown, callback: IRtwqAsyncCallback, appState: IUnknown, asyncResult: ptr IRtwqAsyncResult): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqEndRegisterWorkQueueWithMMCSS*(result: IRtwqAsyncResult, taskId: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqGetWorkQueueMMCSSClass*(workQueueId: uint32, usageClass: PWSTR, usageClassLength: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqGetWorkQueueMMCSSPriority*(workQueueId: uint32, priority: ptr int32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqGetWorkQueueMMCSSTaskId*(workQueueId: uint32, taskId: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqInvokeCallback*(result: IRtwqAsyncResult): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqJoinWorkQueue*(workQueueId: uint32, hFile: HANDLE, `out`: ptr HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqLockPlatform*(): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqLockSharedWorkQueue*(usageClass: PCWSTR, basePriority: int32, taskId: ptr uint32, id: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqLockWorkQueue*(workQueueId: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqPutWaitingWorkItem*(hEvent: HANDLE, lPriority: int32, result: IRtwqAsyncResult, key: ptr RTWQWORKITEM_KEY): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqPutWorkItem*(dwQueue: uint32, lPriority: int32, result: IRtwqAsyncResult): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqRegisterPlatformEvents*(platformEvents: IRtwqPlatformEvents): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqRegisterPlatformWithMMCSS*(usageClass: PCWSTR, taskId: ptr uint32, lPriority: int32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqRemovePeriodicCallback*(dwKey: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqScheduleWorkItem*(result: IRtwqAsyncResult, Timeout: int64, key: ptr RTWQWORKITEM_KEY): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqSetDeadline*(workQueueId: uint32, deadlineInHNS: int64, pRequest: ptr HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqSetDeadline2*(workQueueId: uint32, deadlineInHNS: int64, preDeadlineInHNS: int64, pRequest: ptr HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqSetLongRunning*(workQueueId: uint32, enable: BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqShutdown*(): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqStartup*(): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqUnjoinWorkQueue*(workQueueId: uint32, hFile: HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqUnlockPlatform*(): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqUnlockWorkQueue*(workQueueId: uint32): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqUnregisterPlatformEvents*(platformEvents: IRtwqPlatformEvents): HRESULT {.sideEffect, importc, stdcall.}
proc RtwqUnregisterPlatformFromMMCSS*(): HRESULT {.sideEffect, importc, stdcall.}
{.pop.}
