# generated by winmd2nim from Windows.Win32.winmd — strmif (do not edit)
import ./[ddraw, wingdi, unknwnbase, winnt, ksmedia, windef, minwindef, mmsyscom, guiddef]
export ddraw, wingdi, unknwnbase, winnt, ksmedia, windef, minwindef, mmsyscom, guiddef

type

  # structs
  ALLOCATOR_PROPERTIES* {.completeStruct.} = object
    cBuffers*: int32
    cbBuffer*: int32
    cbAlign*: int32
    cbPrefix*: int32
  AMCOPPCommand* {.completeStruct.} = object
    macKDI*: GUID
    guidCommandID*: GUID
    dwSequence*: uint32
    cbSizeData*: uint32
    CommandData*: array[4056, uint8]
  AMCOPPSignature* {.completeStruct.} = object
    Signature*: array[256, uint8]
  AMCOPPStatusInput* {.completeStruct.} = object
    rApp*: GUID
    guidStatusRequestID*: GUID
    dwSequence*: uint32
    cbSizeData*: uint32
    StatusData*: array[4056, uint8]
  AMCOPPStatusOutput* {.completeStruct.} = object
    macKDI*: GUID
    cbSizeData*: uint32
    COPPStatus*: array[4076, uint8]
  AM_DVD_RENDERSTATUS* {.completeStruct.} = object
    hrVPEStatus*: HRESULT
    bDvdVolInvalid*: BOOL
    bDvdVolUnknown*: BOOL
    bNoLine21In*: BOOL
    bNoLine21Out*: BOOL
    iNumStreams*: int32
    iNumStreamsFailed*: int32
    dwFailedStreamsFlag*: uint32
  AM_MEDIA_TYPE* {.completeStruct.} = object
    majortype*: GUID
    subtype*: GUID
    bFixedSizeSamples*: BOOL
    bTemporalCompression*: BOOL
    lSampleSize*: uint32
    formattype*: GUID
    pUnk*: IUnknown
    cbFormat*: uint32
    pbFormat*: ptr uint8
  AM_SAMPLE2_PROPERTIES* {.completeStruct.} = object
    cbData*: uint32
    dwTypeSpecificFlags*: uint32
    dwSampleFlags*: uint32
    lActual*: int32
    tStart*: REFERENCE_TIME
    tStop*: REFERENCE_TIME
    dwStreamId*: uint32
    pMediaType*: ptr AM_MEDIA_TYPE
    pbBuffer*: ptr uint8
    cbBuffer*: int32
  AM_STREAM_INFO* {.completeStruct.} = object
    tStart*: REFERENCE_TIME
    tStop*: REFERENCE_TIME
    dwStartCookie*: uint32
    dwStopCookie*: uint32
    dwFlags*: uint32
  AUDIO_STREAM_CONFIG_CAPS* {.completeStruct.} = object
    guid*: GUID
    MinimumChannels*: uint32
    MaximumChannels*: uint32
    ChannelsGranularity*: uint32
    MinimumBitsPerSample*: uint32
    MaximumBitsPerSample*: uint32
    BitsPerSampleGranularity*: uint32
    MinimumSampleFrequency*: uint32
    MaximumSampleFrequency*: uint32
    SampleFrequencyGranularity*: uint32
  COLORKEY* {.completeStruct.} = object
    KeyType*: uint32
    PaletteIndex*: uint32
    LowColorValue*: COLORREF
    HighColorValue*: COLORREF
  CodecAPIEventData* {.completeStruct.} = object
    guid*: GUID
    dataLength*: uint32
    reserved*: array[3, uint32]
  DVD_ATR* {.completeStruct.} = object
    ulCAT*: uint32
    pbATRI*: array[768, uint8]
  DVD_AudioAttributes* {.completeStruct.} = object
    AppMode*: DVD_AUDIO_APPMODE
    AppModeData*: uint8
    AudioFormat*: DVD_AUDIO_FORMAT
    Language*: LCID
    LanguageExtension*: DVD_AUDIO_LANG_EXT
    fHasMultichannelInfo*: BOOL
    dwFrequency*: uint32
    bQuantization*: uint8
    bNumberOfChannels*: uint8
    dwReserved*: array[2, uint32]
  DVD_DECODER_CAPS* {.completeStruct.} = object
    dwSize*: uint32
    dwAudioCaps*: uint32
    dFwdMaxRateVideo*: float64
    dFwdMaxRateAudio*: float64
    dFwdMaxRateSP*: float64
    dBwdMaxRateVideo*: float64
    dBwdMaxRateAudio*: float64
    dBwdMaxRateSP*: float64
    dwRes1*: uint32
    dwRes2*: uint32
    dwRes3*: uint32
    dwRes4*: uint32
  DVD_HMSF_TIMECODE* {.completeStruct.} = object
    bHours*: uint8
    bMinutes*: uint8
    bSeconds*: uint8
    bFrames*: uint8
  DVD_KaraokeAttributes* {.completeStruct.} = object
    bVersion*: uint8
    fMasterOfCeremoniesInGuideVocal1*: BOOL
    fDuet*: BOOL
    ChannelAssignment*: DVD_KARAOKE_ASSIGNMENT
    wChannelContents*: array[8, uint16]
  DVD_MUA_Coeff* {.completeStruct.} = object
    log2_alpha*: float64
    log2_beta*: float64
  DVD_MUA_MixingInfo* {.completeStruct.} = object
    fMixTo0*: BOOL
    fMixTo1*: BOOL
    fMix0InPhase*: BOOL
    fMix1InPhase*: BOOL
    dwSpeakerPosition*: uint32
  DVD_MenuAttributes* {.completeStruct.} = object
    fCompatibleRegion*: array[8, BOOL]
    VideoAttributes*: DVD_VideoAttributes
    fAudioPresent*: BOOL
    AudioAttributes*: DVD_AudioAttributes
    fSubpicturePresent*: BOOL
    SubpictureAttributes*: DVD_SubpictureAttributes
  DVD_MultichannelAudioAttributes* {.completeStruct.} = object
    Info*: array[8, DVD_MUA_MixingInfo]
    Coeff*: array[8, DVD_MUA_Coeff]
  DVD_PLAYBACK_LOCATION* {.completeStruct.} = object
    TitleNum*: uint32
    ChapterNum*: uint32
    TimeCode*: uint32
  DVD_PLAYBACK_LOCATION2* {.completeStruct.} = object
    TitleNum*: uint32
    ChapterNum*: uint32
    TimeCode*: DVD_HMSF_TIMECODE
    TimeCodeFlags*: uint32
  DVD_SubpictureAttributes* {.completeStruct.} = object
    Type*: DVD_SUBPICTURE_TYPE
    CodingMode*: DVD_SUBPICTURE_CODING
    Language*: LCID
    LanguageExtension*: DVD_SUBPICTURE_LANG_EXT
  DVD_TIMECODE* {.completeStruct.} = object
    X_bitfield*: uint32
  DVD_TitleAttributes* {.completeStruct.} = object
    Anonymous*: DVD_TitleAttributes_0
    VideoAttributes*: DVD_VideoAttributes
    ulNumberOfAudioStreams*: uint32
    AudioAttributes*: array[8, DVD_AudioAttributes]
    MultichannelAudioAttributes*: array[8, DVD_MultichannelAudioAttributes]
    ulNumberOfSubpictureStreams*: uint32
    SubpictureAttributes*: array[32, DVD_SubpictureAttributes]
  DVD_TitleAttributes_0* {.completeStruct, union.} = object
    AppMode*: DVD_TITLE_APPMODE
    TitleLength*: DVD_HMSF_TIMECODE
  DVD_VideoAttributes* {.completeStruct.} = object
    fPanscanPermitted*: BOOL
    fLetterboxPermitted*: BOOL
    ulAspectX*: uint32
    ulAspectY*: uint32
    ulFrameRate*: uint32
    ulFrameHeight*: uint32
    Compression*: DVD_VIDEO_COMPRESSION
    fLine21Field1InGOP*: BOOL
    fLine21Field2InGOP*: BOOL
    ulSourceResolutionX*: uint32
    ulSourceResolutionY*: uint32
    fIsSourceLetterboxed*: BOOL
    fIsFilmMode*: BOOL
  DVINFO* {.completeStruct.} = object
    dwDVAAuxSrc*: uint32
    dwDVAAuxCtl*: uint32
    dwDVAAuxSrc1*: uint32
    dwDVAAuxCtl1*: uint32
    dwDVVAuxSrc*: uint32
    dwDVVAuxCtl*: uint32
    dwDVReserved*: array[2, uint32]
  FILTER_INFO* {.completeStruct.} = object
    achName*: array[128, uint16]
    pGraph*: IFilterGraph
  NORMALIZEDRECT* {.completeStruct.} = object
    left*: float32
    top*: float32
    right*: float32
    bottom*: float32
  PIN_INFO* {.completeStruct.} = object
    pFilter*: IBaseFilter
    dir*: PIN_DIRECTION
    achName*: array[128, uint16]
  Quality* {.completeStruct.} = object
    Type*: QualityMessageType
    Proportion*: int32
    Late*: REFERENCE_TIME
    TimeStamp*: REFERENCE_TIME
  REGFILTER* {.completeStruct.} = object
    Clsid*: GUID
    Name*: PWSTR
  REGFILTER2* {.completeStruct.} = object
    dwVersion*: uint32
    dwMerit*: uint32
    Anonymous*: REGFILTER2_2
  REGFILTER2_2* {.completeStruct, union.} = object
    Anonymous*: REGFILTER2_2_0
    Anonymous2*: REGFILTER2_2_1
  REGFILTER2_2_0* {.completeStruct.} = object
    cPins*: uint32
    rgPins*: ptr REGFILTERPINS
  REGFILTER2_2_1* {.completeStruct.} = object
    cPins2*: uint32
    rgPins2*: ptr REGFILTERPINS2
  REGFILTERPINS* {.completeStruct.} = object
    strName*: PWSTR
    bRendered*: BOOL
    bOutput*: BOOL
    bZero*: BOOL
    bMany*: BOOL
    clsConnectsToFilter*: ptr GUID
    strConnectsToPin*: ptr uint16
    nMediaTypes*: uint32
    lpMediaType*: ptr REGPINTYPES
  REGFILTERPINS2* {.completeStruct.} = object
    dwFlags*: uint32
    cInstances*: uint32
    nMediaTypes*: uint32
    lpMediaType*: ptr REGPINTYPES
    nMediums*: uint32
    lpMedium*: ptr REGPINMEDIUM
    clsPinCategory*: ptr GUID
  REGPINMEDIUM* {.completeStruct.} = object
    clsMedium*: GUID
    dw1*: uint32
    dw2*: uint32
  REGPINTYPES* {.completeStruct.} = object
    clsMajorType*: ptr GUID
    clsMinorType*: ptr GUID
  STREAM_ID_MAP* {.completeStruct.} = object
    stream_id*: uint32
    dwMediaSampleContent*: uint32
    ulSubstreamFilterValue*: uint32
    iDataOffset*: int32
  VIDEO_STREAM_CONFIG_CAPS* {.completeStruct.} = object
    guid*: GUID
    VideoStandard*: uint32
    InputSize*: SIZE
    MinCroppingSize*: SIZE
    MaxCroppingSize*: SIZE
    CropGranularityX*: int32
    CropGranularityY*: int32
    CropAlignX*: int32
    CropAlignY*: int32
    MinOutputSize*: SIZE
    MaxOutputSize*: SIZE
    OutputGranularityX*: int32
    OutputGranularityY*: int32
    StretchTapsX*: int32
    StretchTapsY*: int32
    ShrinkTapsX*: int32
    ShrinkTapsY*: int32
    MinFrameInterval*: int64
    MaxFrameInterval*: int64
    MinBitsPerSecond*: int32
    MaxBitsPerSecond*: int32
  VMRALLOCATIONINFO* {.completeStruct.} = object
    dwFlags*: uint32
    lpHdr*: LPBITMAPINFOHEADER
    lpPixFmt*: LPDDPIXELFORMAT
    szAspectRatio*: SIZE
    dwMinBuffers*: uint32
    dwMaxBuffers*: uint32
    dwInterlaceFlags*: uint32
    szNativeSize*: SIZE
  VMRALPHABITMAP* {.completeStruct.} = object
    dwFlags*: uint32
    hdc*: HDC
    pDDS*: IDirectDrawSurface7
    rSrc*: RECT
    rDest*: NORMALIZEDRECT
    fAlpha*: float32
    clrSrcKey*: COLORREF
  VMRDeinterlaceCaps* {.completeStruct.} = object
    dwSize*: uint32
    dwNumPreviousOutputFrames*: uint32
    dwNumForwardRefSamples*: uint32
    dwNumBackwardRefSamples*: uint32
    DeinterlaceTechnology*: VMRDeinterlaceTech
  VMRFrequency* {.completeStruct.} = object
    dwNumerator*: uint32
    dwDenominator*: uint32
  VMRGUID* {.completeStruct.} = object
    pGUID*: ptr GUID
    GUID*: GUID
  VMRMONITORINFO* {.completeStruct.} = object
    guid*: VMRGUID
    rcMonitor*: RECT
    hMon*: HMONITOR
    dwFlags*: uint32
    szDevice*: array[32, uint16]
    szDescription*: array[256, uint16]
    liDriverVersion*: int64
    dwVendorId*: uint32
    dwDeviceId*: uint32
    dwSubSysId*: uint32
    dwRevision*: uint32
  VMRPRESENTATIONINFO* {.completeStruct.} = object
    dwFlags*: uint32
    lpSurf*: IDirectDrawSurface7
    rtStart*: REFERENCE_TIME
    rtEnd*: REFERENCE_TIME
    szAspectRatio*: SIZE
    rcSrc*: RECT
    rcDst*: RECT
    dwTypeSpecificFlags*: uint32
    dwInterlaceFlags*: uint32
  VMRVIDEOSTREAMINFO* {.completeStruct.} = object
    pddsVideoSurface*: IDirectDrawSurface7
    dwWidth*: uint32
    dwHeight*: uint32
    dwStrmID*: uint32
    fAlpha*: float32
    ddClrKey*: DDCOLORKEY
    rNormal*: NORMALIZEDRECT
  VMRVideoDesc* {.completeStruct.} = object
    dwSize*: uint32
    dwSampleWidth*: uint32
    dwSampleHeight*: uint32
    SingleFieldPerSample*: BOOL
    dwFourCC*: uint32
    InputSampleFreq*: VMRFrequency
    OutputFrameFreq*: VMRFrequency

  # typdefs
  DVD_AudioATR* = distinct array[8, uint8]
  DVD_REGISTER* = distinct uint16
  DVD_SubpictureATR* = distinct array[6, uint8]
  DVD_VideoATR* = distinct array[2, uint8]
  GPRMARRAY* = distinct array[16, DVD_REGISTER]
  HEVENT* = distinct uint
  HSEMAPHORE* = distinct uint
  LPAMCOPPCommand* = ptr AMCOPPCommand
  LPAMCOPPStatusInput* = ptr AMCOPPStatusInput
  LPAMCOPPStatusOutput* = ptr AMCOPPStatusOutput
  PDVINFO* = ptr DVINFO
  PNORMALIZEDRECT* = ptr NORMALIZEDRECT
  PVMRALPHABITMAP* = ptr VMRALPHABITMAP
  SPRMARRAY* = distinct array[24, DVD_REGISTER]
  VALID_UOP_SOMTHING_OR_OTHER* = distinct uint32

  # unscoped enums 
  AMOVERLAYFX* = int32
  AMPROPERTY_PIN* = int32
  AMTVAudioEventType* = int32
  AMTunerEventType* = int32
  AMTunerModeType* = int32
  AMTunerSignalStrength* = int32
  AMTunerSubChannel* = int32
  AM_DVD_GRAPH_FLAGS* = int32
  AM_DVD_STREAM_FLAGS* = int32
  AM_FILESINK_FLAGS* = int32
  AM_FILTER_FLAGS* = int32
  AM_GRAPH_CONFIG_RECONNECT_FLAGS* = int32
  AM_SEEKING_SEEKING_CAPABILITIES* = int32
  AM_SEEKING_SEEKING_FLAGS* = int32
  AM_STREAM_INFO_FLAGS* = int32
  AnalogVideoStandard* = int32
  CameraControlFlags* = int32
  CameraControlProperty* = int32
  CompressionCaps* = int32
  DECIMATION_USAGE* = int32
  DVD_AUDIO_APPMODE* = int32
  DVD_AUDIO_FORMAT* = int32
  DVD_AUDIO_LANG_EXT* = int32
  DVD_CMD_FLAGS* = int32
  DVD_DISC_SIDE* = int32
  DVD_DOMAIN* = int32
  DVD_FRAMERATE* = int32
  DVD_KARAOKE_ASSIGNMENT* = int32
  DVD_KARAOKE_CONTENTS* = int32
  DVD_KARAOKE_DOWNMIX* = int32
  DVD_MENU_ID* = int32
  DVD_NavCmdType* = int32
  DVD_OPTION_FLAG* = int32
  DVD_PARENTAL_LEVEL* = int32
  DVD_PREFERRED_DISPLAY_MODE* = int32
  DVD_RELATIVE_BUTTON* = int32
  DVD_SUBPICTURE_CODING* = int32
  DVD_SUBPICTURE_LANG_EXT* = int32
  DVD_SUBPICTURE_TYPE* = int32
  DVD_TIMECODE_FLAGS* = int32
  DVD_TITLE_APPMODE* = int32
  DVD_TextCharSet* = int32
  DVD_TextStringType* = int32
  DVD_VIDEO_COMPRESSION* = int32
  FILTER_STATE* = int32
  InterleavingMode* = int32
  PIN_DIRECTION* = int32
  PhysicalConnectorType* = int32
  QualityMessageType* = int32
  TVAudioMode* = int32
  TunerInputType* = int32
  VALID_UOP_FLAG* = int32
  VMRDeinterlacePrefs* = int32
  VMRDeinterlaceTech* = int32
  VMRMixerPrefs* = int32
  VMRMode* = int32
  VMRPresentationFlags* = int32
  VMRRenderPrefs* = int32
  VMRSurfaceAllocationFlags* = int32
  VMR_ASPECT_RATIO_MODE* = int32
  VfwCaptureDialogs* = int32
  VfwCompressDialogs* = int32
  VideoControlFlags* = int32
  VideoCopyProtectionType* = int32
  VideoProcAmpFlags* = int32
  VideoProcAmpProperty* = int32
  X_AMRESCTL_RESERVEFLAGS* = int32
  X_AMSTREAMSELECTENABLEFLAGS* = int32
  X_AMSTREAMSELECTINFOFLAGS* = int32
  X_AM_AUDIO_RENDERER_STAT_PARAM* = int32
  X_AM_FILTER_MISC_FLAGS* = int32
  X_AM_INTF_SEARCH_FLAGS* = int32
  X_AM_OVERLAY_NOTIFY_FLAGS* = int32
  X_AM_PIN_FLOW_CONTROL_BLOCK_FLAGS* = int32
  X_AM_PUSHSOURCE_FLAGS* = int32
  X_AM_RENSDEREXFLAGS* = int32
  X_DVDECODERRESOLUTION* = int32
  X_DVENCODERFORMAT* = int32
  X_DVENCODERRESOLUTION* = int32
  X_DVENCODERVIDEOFORMAT* = int32
  X_DVRESOLUTION* = int32
  X_REM_FILTER_FLAGS* = int32
  tagAM_MEDIAEVENT_FLAGS* = int32
  tagAM_SAMPLE_PROPERTY_FLAGS* = int32

  # interfaces
  IAMAnalogVideoDecoder* = distinct object
  IAMAnalogVideoEncoder* = distinct object
  IAMAsyncReaderTimestampScaling* = distinct object
  IAMAudioInputMixer* = distinct object
  IAMAudioRendererStats* = distinct object
  IAMBufferNegotiation* = distinct object
  IAMCameraControl* = distinct object
  IAMCertifiedOutputProtection* = distinct object
  IAMClockAdjust* = distinct object
  IAMClockSlave* = distinct object
  IAMCopyCaptureFileProgress* = distinct object
  IAMCrossbar* = distinct object
  IAMDecoderCaps* = distinct object
  IAMDevMemoryAllocator* = distinct object
  IAMDevMemoryControl* = distinct object
  IAMDeviceRemoval* = distinct object
  IAMDroppedFrames* = distinct object
  IAMExtDevice* = distinct object
  IAMExtTransport* = distinct object
  IAMFilterGraphCallback* = distinct object
  IAMFilterMiscFlags* = distinct object
  IAMGraphBuilderCallback* = distinct object
  IAMGraphStreams* = distinct object
  IAMLatency* = distinct object
  IAMOpenProgress* = distinct object
  IAMOverlayFX* = distinct object
  IAMPhysicalPinInfo* = distinct object
  IAMPluginControl* = distinct object
  IAMPushSource* = distinct object
  IAMResourceControl* = distinct object
  IAMStreamConfig* = distinct object
  IAMStreamControl* = distinct object
  IAMStreamSelect* = distinct object
  IAMTVAudio* = distinct object
  IAMTVAudioNotification* = distinct object
  IAMTVTuner* = distinct object
  IAMTimecodeDisplay* = distinct object
  IAMTimecodeGenerator* = distinct object
  IAMTimecodeReader* = distinct object
  IAMTuner* = distinct object
  IAMTunerNotification* = distinct object
  IAMVfwCaptureDialogs* = distinct object
  IAMVfwCompressDialogs* = distinct object
  IAMVideoCompression* = distinct object
  IAMVideoControl* = distinct object
  IAMVideoDecimationProperties* = distinct object
  IAMVideoProcAmp* = distinct object
  IAMovieSetup* = distinct object
  IAsyncReader* = distinct object
  IBPCSatelliteTuner* = distinct object
  IBaseFilter* = distinct object
  ICaptureGraphBuilder* = distinct object
  ICaptureGraphBuilder2* = distinct object
  ICodecAPI* = distinct object
  IConfigAviMux* = distinct object
  IConfigInterleaving* = distinct object
  ICreateDevEnum* = distinct object
  IDDrawExclModeVideo* = distinct object
  IDDrawExclModeVideoCallback* = distinct object
  IDVEnc* = distinct object
  IDVRGB219* = distinct object
  IDVSplitter* = distinct object
  IDecimateVideoImage* = distinct object
  IDistributorNotify* = distinct object
  IDrawVideoImage* = distinct object
  IDvdCmd* = distinct object
  IDvdControl* = distinct object
  IDvdControl2* = distinct object
  IDvdGraphBuilder* = distinct object
  IDvdInfo* = distinct object
  IDvdInfo2* = distinct object
  IDvdState* = distinct object
  IEncoderAPI* = distinct object
  IEnumFilters* = distinct object
  IEnumMediaTypes* = distinct object
  IEnumPins* = distinct object
  IEnumRegFilters* = distinct object
  IEnumStreamIdMap* = distinct object
  IFileSinkFilter* = distinct object
  IFileSinkFilter2* = distinct object
  IFileSourceFilter* = distinct object
  IFilterChain* = distinct object
  IFilterGraph* = distinct object
  IFilterGraph2* = distinct object
  IFilterGraph3* = distinct object
  IFilterMapper* = distinct object
  IFilterMapper2* = distinct object
  IFilterMapper3* = distinct object
  IGetCapabilitiesKey* = distinct object
  IGraphBuilder* = distinct object
  IGraphConfig* = distinct object
  IGraphConfigCallback* = distinct object
  IGraphVersion* = distinct object
  IIPDVDec* = distinct object
  IMPEG2StreamIdMap* = distinct object
  IMediaEventSink* = distinct object
  IMediaFilter* = distinct object
  IMediaPropertyBag* = distinct object
  IMediaSample* = distinct object
  IMediaSample2* = distinct object
  IMediaSample2Config* = distinct object
  IMediaSeeking* = distinct object
  IMemAllocator* = distinct object
  IMemAllocatorCallbackTemp* = distinct object
  IMemAllocatorNotifyCallbackTemp* = distinct object
  IMemInputPin* = distinct object
  IMpeg2Demultiplexer* = distinct object
  IOverlay* = distinct object
  IOverlayNotify* = distinct object
  IOverlayNotify2* = distinct object
  IPersistMediaPropertyBag* = distinct object
  IPin* = distinct object
  IPinConnection* = distinct object
  IPinFlowControl* = distinct object
  IQualityControl* = distinct object
  IReferenceClock2* = distinct object
  IReferenceClockTimerControl* = distinct object
  IRegisterServiceProvider* = distinct object
  IResourceConsumer* = distinct object
  IResourceManager* = distinct object
  ISeekingPassThru* = distinct object
  IStreamBuilder* = distinct object
  IVMRAspectRatioControl* = distinct object
  IVMRDeinterlaceControl* = distinct object
  IVMRFilterConfig* = distinct object
  IVMRImageCompositor* = distinct object
  IVMRImagePresenter* = distinct object
  IVMRImagePresenterConfig* = distinct object
  IVMRImagePresenterExclModeConfig* = distinct object
  IVMRMixerBitmap* = distinct object
  IVMRMixerControl* = distinct object
  IVMRMonitorConfig* = distinct object
  IVMRSurface* = distinct object
  IVMRSurfaceAllocator* = distinct object
  IVMRSurfaceAllocatorNotify* = distinct object
  IVMRVideoStreamControl* = distinct object
  IVMRWindowlessControl* = distinct object
  IVPManager* = distinct object
  IVideoEncoder* = distinct object
  IVideoFrameStep* = distinct object

const
  # free constants
  ADVISE_ALL*: int32 = 15'i32
  ADVISE_ALL2*: int32 = 31'i32
  ADVISE_CLIPPING*: int32 = 1'i32
  ADVISE_COLORKEY*: int32 = 4'i32
  ADVISE_DISPLAY_CHANGE*: int32 = 16'i32
  ADVISE_NONE*: int32 = 0'i32
  ADVISE_PALETTE*: int32 = 2'i32
  ADVISE_POSITION*: int32 = 8'i32
  AMF_AUTOMATICGAIN*: float64 = -1.0
  AM_GBF_NODDSURFACELOCK*: int32 = 8'i32
  AM_GBF_NOTASYNCPOINT*: int32 = 2'i32
  AM_GBF_NOWAIT*: int32 = 4'i32
  AM_GBF_PREVFRAMESKIPPED*: int32 = 1'i32
  AM_GETDECODERCAP_QUERY_EVR_SUPPORT*: int32 = 7'i32
  AM_GETDECODERCAP_QUERY_VMR9_SUPPORT*: int32 = 6'i32
  AM_GETDECODERCAP_QUERY_VMR_SUPPORT*: int32 = 1'i32
  AM_QUERY_DECODER_ATSC_HD_SUPPORT*: int32 = 5'i32
  AM_QUERY_DECODER_ATSC_SD_SUPPORT*: int32 = 4'i32
  AM_QUERY_DECODER_DVD_SUPPORT*: int32 = 3'i32
  AM_QUERY_DECODER_DXVA_1_SUPPORT*: int32 = 2'i32
  AM_QUERY_DECODER_VMR_SUPPORT*: int32 = 1'i32
  AnalogVideo_NTSC_Mask*: int32 = 7'i32
  AnalogVideo_PAL_Mask*: int32 = 1052656'i32
  AnalogVideo_SECAM_Mask*: int32 = 1044480'i32
  CDEF_BYPASS_CLASS_MANAGER*: int32 = 2'i32
  CDEF_CLASS_DEFAULT*: int32 = 1'i32
  CDEF_DEVMON_CMGR_DEVICE*: int32 = 16'i32
  CDEF_DEVMON_DMO*: int32 = 32'i32
  CDEF_DEVMON_FILTER*: int32 = 128'i32
  CDEF_DEVMON_PNP_DEVICE*: int32 = 64'i32
  CDEF_DEVMON_SELECTIVE_MASK*: int32 = 240'i32
  CDEF_MERIT_ABOVE_DO_NOT_USE*: int32 = 8'i32
  CHARS_IN_GUID*: int32 = 39'i32
  CK_INDEX*: int32 = 1'i32
  CK_NOCOLORKEY*: int32 = 0'i32
  CK_RGB*: int32 = 2'i32
  DECODER_CAP_NOTSUPPORTED*: int32 = 0'i32
  DECODER_CAP_SUPPORTED*: int32 = 1'i32
  DVD_AUDIO_CAPS_AC3*: int32 = 1'i32
  DVD_AUDIO_CAPS_DTS*: int32 = 8'i32
  DVD_AUDIO_CAPS_LPCM*: int32 = 4'i32
  DVD_AUDIO_CAPS_MPEG2*: int32 = 2'i32
  DVD_AUDIO_CAPS_SDDS*: int32 = 16'i32
  DVD_DEFAULT_AUDIO_STREAM*: int32 = 15'i32
  DVD_STREAM_DATA_CURRENT*: int32 = 2048'i32
  DVD_STREAM_DATA_VMGM*: int32 = 1024'i32
  DVD_STREAM_DATA_VTSM*: int32 = 1025'i32
  DVD_TITLE_MENU*: int32 = 0'i32
  MAX_FILTER_NAME*: int32 = 128'i32
  MAX_NUMBER_OF_STREAMS*: int32 = 16'i32
  MAX_PIN_NAME*: int32 = 128'i32
  MERIT_DO_NOT_USE*: int32 = 2097152'i32
  MERIT_HW_COMPRESSOR*: int32 = 1048656'i32
  MERIT_NORMAL*: int32 = 6291456'i32
  MERIT_PREFERRED*: int32 = 8388608'i32
  MERIT_SW_COMPRESSOR*: int32 = 1048576'i32
  MERIT_UNLIKELY*: int32 = 4194304'i32
  MPEG2_PROGRAM_DIRECTORY_PES_PACKET*: int32 = 2'i32
  MPEG2_PROGRAM_ELEMENTARY_STREAM*: int32 = 1'i32
  MPEG2_PROGRAM_PACK_HEADER*: int32 = 3'i32
  MPEG2_PROGRAM_PES_STREAM*: int32 = 4'i32
  MPEG2_PROGRAM_STREAM_MAP*: int32 = 0'i32
  MPEG2_PROGRAM_SYSTEM_HEADER*: int32 = 5'i32
  REG_PINFLAG_B_MANY*: int32 = 4'i32
  REG_PINFLAG_B_OUTPUT*: int32 = 8'i32
  REG_PINFLAG_B_RENDERER*: int32 = 2'i32
  REG_PINFLAG_B_ZERO*: int32 = 1'i32
  SUBSTREAM_FILTER_VAL_NONE*: int32 = 268435456'i32
  VMRBITMAP_DISABLE*: int32 = 1'i32
  VMRBITMAP_ENTIREDDS*: int32 = 4'i32
  VMRBITMAP_HDC*: int32 = 2'i32
  VMRBITMAP_SRCCOLORKEY*: int32 = 8'i32
  VMRBITMAP_SRCRECT*: int32 = 16'i32
  VMR_NOTSUPPORTED*: int32 = 0'i32
  VMR_SUPPORTED*: int32 = 1'i32

  # unscoped enum members
  AMOVERFX_NOFX*: AMOVERLAYFX = 0'i32
  AMOVERFX_MIRRORLEFTRIGHT*: AMOVERLAYFX = 2'i32
  AMOVERFX_MIRRORUPDOWN*: AMOVERLAYFX = 4'i32
  AMOVERFX_DEINTERLACE*: AMOVERLAYFX = 8'i32
  AMPROPERTY_PIN_CATEGORY*: AMPROPERTY_PIN = 0'i32
  AMPROPERTY_PIN_MEDIUM*: AMPROPERTY_PIN = 1'i32
  AMTVAUDIO_EVENT_CHANGED*: AMTVAudioEventType = 1'i32
  AMTUNER_EVENT_CHANGED*: AMTunerEventType = 1'i32
  AMTUNER_MODE_DEFAULT*: AMTunerModeType = 0'i32
  AMTUNER_MODE_TV*: AMTunerModeType = 1'i32
  AMTUNER_MODE_FM_RADIO*: AMTunerModeType = 2'i32
  AMTUNER_MODE_AM_RADIO*: AMTunerModeType = 4'i32
  AMTUNER_MODE_DSS*: AMTunerModeType = 8'i32
  AMTUNER_HASNOSIGNALSTRENGTH*: AMTunerSignalStrength = -1'i32
  AMTUNER_NOSIGNAL*: AMTunerSignalStrength = 0'i32
  AMTUNER_SIGNALPRESENT*: AMTunerSignalStrength = 1'i32
  AMTUNER_SUBCHAN_NO_TUNE*: AMTunerSubChannel = -2'i32
  AMTUNER_SUBCHAN_DEFAULT*: AMTunerSubChannel = -1'i32
  AM_DVD_HWDEC_PREFER*: AM_DVD_GRAPH_FLAGS = 1'i32
  AM_DVD_HWDEC_ONLY*: AM_DVD_GRAPH_FLAGS = 2'i32
  AM_DVD_SWDEC_PREFER*: AM_DVD_GRAPH_FLAGS = 4'i32
  AM_DVD_SWDEC_ONLY*: AM_DVD_GRAPH_FLAGS = 8'i32
  AM_DVD_NOVPE*: AM_DVD_GRAPH_FLAGS = 256'i32
  AM_DVD_DO_NOT_CLEAR*: AM_DVD_GRAPH_FLAGS = 512'i32
  AM_DVD_VMR9_ONLY*: AM_DVD_GRAPH_FLAGS = 2048'i32
  AM_DVD_EVR_ONLY*: AM_DVD_GRAPH_FLAGS = 4096'i32
  AM_DVD_EVR_QOS*: AM_DVD_GRAPH_FLAGS = 8192'i32
  AM_DVD_ADAPT_GRAPH*: AM_DVD_GRAPH_FLAGS = 16384'i32
  AM_DVD_MASK*: AM_DVD_GRAPH_FLAGS = 65535'i32
  AM_DVD_STREAM_VIDEO*: AM_DVD_STREAM_FLAGS = 1'i32
  AM_DVD_STREAM_AUDIO*: AM_DVD_STREAM_FLAGS = 2'i32
  AM_DVD_STREAM_SUBPIC*: AM_DVD_STREAM_FLAGS = 4'i32
  AM_FILE_OVERWRITE*: AM_FILESINK_FLAGS = 1'i32
  AM_FILTER_FLAGS_REMOVABLE*: AM_FILTER_FLAGS = 1'i32
  AM_GRAPH_CONFIG_RECONNECT_DIRECTCONNECT*: AM_GRAPH_CONFIG_RECONNECT_FLAGS = 1'i32
  AM_GRAPH_CONFIG_RECONNECT_CACHE_REMOVED_FILTERS*: AM_GRAPH_CONFIG_RECONNECT_FLAGS = 2'i32
  AM_GRAPH_CONFIG_RECONNECT_USE_ONLY_CACHED_FILTERS*: AM_GRAPH_CONFIG_RECONNECT_FLAGS = 4'i32
  AM_SEEKING_CanSeekAbsolute*: AM_SEEKING_SEEKING_CAPABILITIES = 1'i32
  AM_SEEKING_CanSeekForwards*: AM_SEEKING_SEEKING_CAPABILITIES = 2'i32
  AM_SEEKING_CanSeekBackwards*: AM_SEEKING_SEEKING_CAPABILITIES = 4'i32
  AM_SEEKING_CanGetCurrentPos*: AM_SEEKING_SEEKING_CAPABILITIES = 8'i32
  AM_SEEKING_CanGetStopPos*: AM_SEEKING_SEEKING_CAPABILITIES = 16'i32
  AM_SEEKING_CanGetDuration*: AM_SEEKING_SEEKING_CAPABILITIES = 32'i32
  AM_SEEKING_CanPlayBackwards*: AM_SEEKING_SEEKING_CAPABILITIES = 64'i32
  AM_SEEKING_CanDoSegments*: AM_SEEKING_SEEKING_CAPABILITIES = 128'i32
  AM_SEEKING_Source*: AM_SEEKING_SEEKING_CAPABILITIES = 256'i32
  AM_SEEKING_NoPositioning*: AM_SEEKING_SEEKING_FLAGS = 0'i32
  AM_SEEKING_AbsolutePositioning*: AM_SEEKING_SEEKING_FLAGS = 1'i32
  AM_SEEKING_RelativePositioning*: AM_SEEKING_SEEKING_FLAGS = 2'i32
  AM_SEEKING_IncrementalPositioning*: AM_SEEKING_SEEKING_FLAGS = 3'i32
  AM_SEEKING_PositioningBitsMask*: AM_SEEKING_SEEKING_FLAGS = 3'i32
  AM_SEEKING_SeekToKeyFrame*: AM_SEEKING_SEEKING_FLAGS = 4'i32
  AM_SEEKING_ReturnTime*: AM_SEEKING_SEEKING_FLAGS = 8'i32
  AM_SEEKING_Segment*: AM_SEEKING_SEEKING_FLAGS = 16'i32
  AM_SEEKING_NoFlush*: AM_SEEKING_SEEKING_FLAGS = 32'i32
  AM_STREAM_INFO_START_DEFINED*: AM_STREAM_INFO_FLAGS = 1'i32
  AM_STREAM_INFO_STOP_DEFINED*: AM_STREAM_INFO_FLAGS = 2'i32
  AM_STREAM_INFO_DISCARDING*: AM_STREAM_INFO_FLAGS = 4'i32
  AM_STREAM_INFO_STOP_SEND_EXTRA*: AM_STREAM_INFO_FLAGS = 16'i32
  AnalogVideo_None*: AnalogVideoStandard = 0'i32
  AnalogVideo_NTSC_M*: AnalogVideoStandard = 1'i32
  AnalogVideo_NTSC_M_J*: AnalogVideoStandard = 2'i32
  AnalogVideo_NTSC_433*: AnalogVideoStandard = 4'i32
  AnalogVideo_PAL_B*: AnalogVideoStandard = 16'i32
  AnalogVideo_PAL_D*: AnalogVideoStandard = 32'i32
  AnalogVideo_PAL_G*: AnalogVideoStandard = 64'i32
  AnalogVideo_PAL_H*: AnalogVideoStandard = 128'i32
  AnalogVideo_PAL_I*: AnalogVideoStandard = 256'i32
  AnalogVideo_PAL_M*: AnalogVideoStandard = 512'i32
  AnalogVideo_PAL_N*: AnalogVideoStandard = 1024'i32
  AnalogVideo_PAL_60*: AnalogVideoStandard = 2048'i32
  AnalogVideo_SECAM_B*: AnalogVideoStandard = 4096'i32
  AnalogVideo_SECAM_D*: AnalogVideoStandard = 8192'i32
  AnalogVideo_SECAM_G*: AnalogVideoStandard = 16384'i32
  AnalogVideo_SECAM_H*: AnalogVideoStandard = 32768'i32
  AnalogVideo_SECAM_K*: AnalogVideoStandard = 65536'i32
  AnalogVideo_SECAM_K1*: AnalogVideoStandard = 131072'i32
  AnalogVideo_SECAM_L*: AnalogVideoStandard = 262144'i32
  AnalogVideo_SECAM_L1*: AnalogVideoStandard = 524288'i32
  AnalogVideo_PAL_N_COMBO*: AnalogVideoStandard = 1048576'i32
  AnalogVideoMask_MCE_NTSC*: AnalogVideoStandard = 1052167'i32
  AnalogVideoMask_MCE_PAL*: AnalogVideoStandard = 496'i32
  AnalogVideoMask_MCE_SECAM*: AnalogVideoStandard = 1044480'i32
  CameraControl_Flags_Auto*: CameraControlFlags = 1'i32
  CameraControl_Flags_Manual*: CameraControlFlags = 2'i32
  CameraControl_Pan*: CameraControlProperty = 0'i32
  CameraControl_Tilt*: CameraControlProperty = 1'i32
  CameraControl_Roll*: CameraControlProperty = 2'i32
  CameraControl_Zoom*: CameraControlProperty = 3'i32
  CameraControl_Exposure*: CameraControlProperty = 4'i32
  CameraControl_Iris*: CameraControlProperty = 5'i32
  CameraControl_Focus*: CameraControlProperty = 6'i32
  CompressionCaps_CanQuality*: CompressionCaps = 1'i32
  CompressionCaps_CanCrunch*: CompressionCaps = 2'i32
  CompressionCaps_CanKeyFrame*: CompressionCaps = 4'i32
  CompressionCaps_CanBFrame*: CompressionCaps = 8'i32
  CompressionCaps_CanWindow*: CompressionCaps = 16'i32
  DECIMATION_LEGACY*: DECIMATION_USAGE = 0'i32
  DECIMATION_USE_DECODER_ONLY*: DECIMATION_USAGE = 1'i32
  DECIMATION_USE_VIDEOPORT_ONLY*: DECIMATION_USAGE = 2'i32
  DECIMATION_USE_OVERLAY_ONLY*: DECIMATION_USAGE = 3'i32
  DECIMATION_DEFAULT*: DECIMATION_USAGE = 4'i32
  DVD_AudioMode_None*: DVD_AUDIO_APPMODE = 0'i32
  DVD_AudioMode_Karaoke*: DVD_AUDIO_APPMODE = 1'i32
  DVD_AudioMode_Surround*: DVD_AUDIO_APPMODE = 2'i32
  DVD_AudioMode_Other*: DVD_AUDIO_APPMODE = 3'i32
  DVD_AudioFormat_AC3*: DVD_AUDIO_FORMAT = 0'i32
  DVD_AudioFormat_MPEG1*: DVD_AUDIO_FORMAT = 1'i32
  DVD_AudioFormat_MPEG1_DRC*: DVD_AUDIO_FORMAT = 2'i32
  DVD_AudioFormat_MPEG2*: DVD_AUDIO_FORMAT = 3'i32
  DVD_AudioFormat_MPEG2_DRC*: DVD_AUDIO_FORMAT = 4'i32
  DVD_AudioFormat_LPCM*: DVD_AUDIO_FORMAT = 5'i32
  DVD_AudioFormat_DTS*: DVD_AUDIO_FORMAT = 6'i32
  DVD_AudioFormat_SDDS*: DVD_AUDIO_FORMAT = 7'i32
  DVD_AudioFormat_Other*: DVD_AUDIO_FORMAT = 8'i32
  DVD_AUD_EXT_NotSpecified*: DVD_AUDIO_LANG_EXT = 0'i32
  DVD_AUD_EXT_Captions*: DVD_AUDIO_LANG_EXT = 1'i32
  DVD_AUD_EXT_VisuallyImpaired*: DVD_AUDIO_LANG_EXT = 2'i32
  DVD_AUD_EXT_DirectorComments1*: DVD_AUDIO_LANG_EXT = 3'i32
  DVD_AUD_EXT_DirectorComments2*: DVD_AUDIO_LANG_EXT = 4'i32
  DVD_CMD_FLAG_None*: DVD_CMD_FLAGS = 0'i32
  DVD_CMD_FLAG_Flush*: DVD_CMD_FLAGS = 1'i32
  DVD_CMD_FLAG_SendEvents*: DVD_CMD_FLAGS = 2'i32
  DVD_CMD_FLAG_Block*: DVD_CMD_FLAGS = 4'i32
  DVD_CMD_FLAG_StartWhenRendered*: DVD_CMD_FLAGS = 8'i32
  DVD_CMD_FLAG_EndAfterRendered*: DVD_CMD_FLAGS = 16'i32
  DVD_SIDE_A*: DVD_DISC_SIDE = 1'i32
  DVD_SIDE_B*: DVD_DISC_SIDE = 2'i32
  DVD_DOMAIN_FirstPlay*: DVD_DOMAIN = 1'i32
  DVD_DOMAIN_VideoManagerMenu*: DVD_DOMAIN = 2'i32
  DVD_DOMAIN_VideoTitleSetMenu*: DVD_DOMAIN = 3'i32
  DVD_DOMAIN_Title*: DVD_DOMAIN = 4'i32
  DVD_DOMAIN_Stop*: DVD_DOMAIN = 5'i32
  DVD_FPS_25*: DVD_FRAMERATE = 1'i32
  DVD_FPS_30NonDrop*: DVD_FRAMERATE = 3'i32
  DVD_Assignment_reserved0*: DVD_KARAOKE_ASSIGNMENT = 0'i32
  DVD_Assignment_reserved1*: DVD_KARAOKE_ASSIGNMENT = 1'i32
  DVD_Assignment_LR*: DVD_KARAOKE_ASSIGNMENT = 2'i32
  DVD_Assignment_LRM*: DVD_KARAOKE_ASSIGNMENT = 3'i32
  DVD_Assignment_LR1*: DVD_KARAOKE_ASSIGNMENT = 4'i32
  DVD_Assignment_LRM1*: DVD_KARAOKE_ASSIGNMENT = 5'i32
  DVD_Assignment_LR12*: DVD_KARAOKE_ASSIGNMENT = 6'i32
  DVD_Assignment_LRM12*: DVD_KARAOKE_ASSIGNMENT = 7'i32
  DVD_Karaoke_GuideVocal1*: DVD_KARAOKE_CONTENTS = 1'i32
  DVD_Karaoke_GuideVocal2*: DVD_KARAOKE_CONTENTS = 2'i32
  DVD_Karaoke_GuideMelody1*: DVD_KARAOKE_CONTENTS = 4'i32
  DVD_Karaoke_GuideMelody2*: DVD_KARAOKE_CONTENTS = 8'i32
  DVD_Karaoke_GuideMelodyA*: DVD_KARAOKE_CONTENTS = 16'i32
  DVD_Karaoke_GuideMelodyB*: DVD_KARAOKE_CONTENTS = 32'i32
  DVD_Karaoke_SoundEffectA*: DVD_KARAOKE_CONTENTS = 64'i32
  DVD_Karaoke_SoundEffectB*: DVD_KARAOKE_CONTENTS = 128'i32
  DVD_Mix_0to0*: DVD_KARAOKE_DOWNMIX = 1'i32
  DVD_Mix_1to0*: DVD_KARAOKE_DOWNMIX = 2'i32
  DVD_Mix_2to0*: DVD_KARAOKE_DOWNMIX = 4'i32
  DVD_Mix_3to0*: DVD_KARAOKE_DOWNMIX = 8'i32
  DVD_Mix_4to0*: DVD_KARAOKE_DOWNMIX = 16'i32
  DVD_Mix_Lto0*: DVD_KARAOKE_DOWNMIX = 32'i32
  DVD_Mix_Rto0*: DVD_KARAOKE_DOWNMIX = 64'i32
  DVD_Mix_0to1*: DVD_KARAOKE_DOWNMIX = 256'i32
  DVD_Mix_1to1*: DVD_KARAOKE_DOWNMIX = 512'i32
  DVD_Mix_2to1*: DVD_KARAOKE_DOWNMIX = 1024'i32
  DVD_Mix_3to1*: DVD_KARAOKE_DOWNMIX = 2048'i32
  DVD_Mix_4to1*: DVD_KARAOKE_DOWNMIX = 4096'i32
  DVD_Mix_Lto1*: DVD_KARAOKE_DOWNMIX = 8192'i32
  DVD_Mix_Rto1*: DVD_KARAOKE_DOWNMIX = 16384'i32
  DVD_MENU_Title*: DVD_MENU_ID = 2'i32
  DVD_MENU_Root*: DVD_MENU_ID = 3'i32
  DVD_MENU_Subpicture*: DVD_MENU_ID = 4'i32
  DVD_MENU_Audio*: DVD_MENU_ID = 5'i32
  DVD_MENU_Angle*: DVD_MENU_ID = 6'i32
  DVD_MENU_Chapter*: DVD_MENU_ID = 7'i32
  DVD_NavCmdType_Pre*: DVD_NavCmdType = 1'i32
  DVD_NavCmdType_Post*: DVD_NavCmdType = 2'i32
  DVD_NavCmdType_Cell*: DVD_NavCmdType = 3'i32
  DVD_NavCmdType_Button*: DVD_NavCmdType = 4'i32
  DVD_ResetOnStop*: DVD_OPTION_FLAG = 1'i32
  DVD_NotifyParentalLevelChange*: DVD_OPTION_FLAG = 2'i32
  DVD_HMSF_TimeCodeEvents*: DVD_OPTION_FLAG = 3'i32
  DVD_AudioDuringFFwdRew*: DVD_OPTION_FLAG = 4'i32
  DVD_EnableNonblockingAPIs*: DVD_OPTION_FLAG = 5'i32
  DVD_CacheSizeInMB*: DVD_OPTION_FLAG = 6'i32
  DVD_EnablePortableBookmarks*: DVD_OPTION_FLAG = 7'i32
  DVD_EnableExtendedCopyProtectErrors*: DVD_OPTION_FLAG = 8'i32
  DVD_NotifyPositionChange*: DVD_OPTION_FLAG = 9'i32
  DVD_IncreaseOutputControl*: DVD_OPTION_FLAG = 10'i32
  DVD_EnableStreaming*: DVD_OPTION_FLAG = 11'i32
  DVD_EnableESOutput*: DVD_OPTION_FLAG = 12'i32
  DVD_EnableTitleLength*: DVD_OPTION_FLAG = 13'i32
  DVD_DisableStillThrottle*: DVD_OPTION_FLAG = 14'i32
  DVD_EnableLoggingEvents*: DVD_OPTION_FLAG = 15'i32
  DVD_MaxReadBurstInKB*: DVD_OPTION_FLAG = 16'i32
  DVD_ReadBurstPeriodInMS*: DVD_OPTION_FLAG = 17'i32
  DVD_RestartDisc*: DVD_OPTION_FLAG = 18'i32
  DVD_EnableCC*: DVD_OPTION_FLAG = 19'i32
  DVD_PARENTAL_LEVEL_8*: DVD_PARENTAL_LEVEL = 32768'i32
  DVD_PARENTAL_LEVEL_7*: DVD_PARENTAL_LEVEL = 16384'i32
  DVD_PARENTAL_LEVEL_6*: DVD_PARENTAL_LEVEL = 8192'i32
  DVD_PARENTAL_LEVEL_5*: DVD_PARENTAL_LEVEL = 4096'i32
  DVD_PARENTAL_LEVEL_4*: DVD_PARENTAL_LEVEL = 2048'i32
  DVD_PARENTAL_LEVEL_3*: DVD_PARENTAL_LEVEL = 1024'i32
  DVD_PARENTAL_LEVEL_2*: DVD_PARENTAL_LEVEL = 512'i32
  DVD_PARENTAL_LEVEL_1*: DVD_PARENTAL_LEVEL = 256'i32
  DISPLAY_CONTENT_DEFAULT*: DVD_PREFERRED_DISPLAY_MODE = 0'i32
  DISPLAY_16x9*: DVD_PREFERRED_DISPLAY_MODE = 1'i32
  DISPLAY_4x3_PANSCAN_PREFERRED*: DVD_PREFERRED_DISPLAY_MODE = 2'i32
  DISPLAY_4x3_LETTERBOX_PREFERRED*: DVD_PREFERRED_DISPLAY_MODE = 3'i32
  DVD_Relative_Upper*: DVD_RELATIVE_BUTTON = 1'i32
  DVD_Relative_Lower*: DVD_RELATIVE_BUTTON = 2'i32
  DVD_Relative_Left*: DVD_RELATIVE_BUTTON = 3'i32
  DVD_Relative_Right*: DVD_RELATIVE_BUTTON = 4'i32
  DVD_SPCoding_RunLength*: DVD_SUBPICTURE_CODING = 0'i32
  DVD_SPCoding_Extended*: DVD_SUBPICTURE_CODING = 1'i32
  DVD_SPCoding_Other*: DVD_SUBPICTURE_CODING = 2'i32
  DVD_SP_EXT_NotSpecified*: DVD_SUBPICTURE_LANG_EXT = 0'i32
  DVD_SP_EXT_Caption_Normal*: DVD_SUBPICTURE_LANG_EXT = 1'i32
  DVD_SP_EXT_Caption_Big*: DVD_SUBPICTURE_LANG_EXT = 2'i32
  DVD_SP_EXT_Caption_Children*: DVD_SUBPICTURE_LANG_EXT = 3'i32
  DVD_SP_EXT_CC_Normal*: DVD_SUBPICTURE_LANG_EXT = 5'i32
  DVD_SP_EXT_CC_Big*: DVD_SUBPICTURE_LANG_EXT = 6'i32
  DVD_SP_EXT_CC_Children*: DVD_SUBPICTURE_LANG_EXT = 7'i32
  DVD_SP_EXT_Forced*: DVD_SUBPICTURE_LANG_EXT = 9'i32
  DVD_SP_EXT_DirectorComments_Normal*: DVD_SUBPICTURE_LANG_EXT = 13'i32
  DVD_SP_EXT_DirectorComments_Big*: DVD_SUBPICTURE_LANG_EXT = 14'i32
  DVD_SP_EXT_DirectorComments_Children*: DVD_SUBPICTURE_LANG_EXT = 15'i32
  DVD_SPType_NotSpecified*: DVD_SUBPICTURE_TYPE = 0'i32
  DVD_SPType_Language*: DVD_SUBPICTURE_TYPE = 1'i32
  DVD_SPType_Other*: DVD_SUBPICTURE_TYPE = 2'i32
  DVD_TC_FLAG_25fps*: DVD_TIMECODE_FLAGS = 1'i32
  DVD_TC_FLAG_30fps*: DVD_TIMECODE_FLAGS = 2'i32
  DVD_TC_FLAG_DropFrame*: DVD_TIMECODE_FLAGS = 4'i32
  DVD_TC_FLAG_Interpolated*: DVD_TIMECODE_FLAGS = 8'i32
  DVD_AppMode_Not_Specified*: DVD_TITLE_APPMODE = 0'i32
  DVD_AppMode_Karaoke*: DVD_TITLE_APPMODE = 1'i32
  DVD_AppMode_Other*: DVD_TITLE_APPMODE = 3'i32
  DVD_CharSet_Unicode*: DVD_TextCharSet = 0'i32
  DVD_CharSet_ISO646*: DVD_TextCharSet = 1'i32
  DVD_CharSet_JIS_Roman_Kanji*: DVD_TextCharSet = 2'i32
  DVD_CharSet_ISO8859_1*: DVD_TextCharSet = 3'i32
  DVD_CharSet_ShiftJIS_Kanji_Roman_Katakana*: DVD_TextCharSet = 4'i32
  DVD_Struct_Volume*: DVD_TextStringType = 1'i32
  DVD_Struct_Title*: DVD_TextStringType = 2'i32
  DVD_Struct_ParentalID*: DVD_TextStringType = 3'i32
  DVD_Struct_PartOfTitle*: DVD_TextStringType = 4'i32
  DVD_Struct_Cell*: DVD_TextStringType = 5'i32
  DVD_Stream_Audio*: DVD_TextStringType = 16'i32
  DVD_Stream_Subpicture*: DVD_TextStringType = 17'i32
  DVD_Stream_Angle*: DVD_TextStringType = 18'i32
  DVD_Channel_Audio*: DVD_TextStringType = 32'i32
  DVD_General_Name*: DVD_TextStringType = 48'i32
  DVD_General_Comments*: DVD_TextStringType = 49'i32
  DVD_Title_Series*: DVD_TextStringType = 56'i32
  DVD_Title_Movie*: DVD_TextStringType = 57'i32
  DVD_Title_Video*: DVD_TextStringType = 58'i32
  DVD_Title_Album*: DVD_TextStringType = 59'i32
  DVD_Title_Song*: DVD_TextStringType = 60'i32
  DVD_Title_Other*: DVD_TextStringType = 63'i32
  DVD_Title_Sub_Series*: DVD_TextStringType = 64'i32
  DVD_Title_Sub_Movie*: DVD_TextStringType = 65'i32
  DVD_Title_Sub_Video*: DVD_TextStringType = 66'i32
  DVD_Title_Sub_Album*: DVD_TextStringType = 67'i32
  DVD_Title_Sub_Song*: DVD_TextStringType = 68'i32
  DVD_Title_Sub_Other*: DVD_TextStringType = 71'i32
  DVD_Title_Orig_Series*: DVD_TextStringType = 72'i32
  DVD_Title_Orig_Movie*: DVD_TextStringType = 73'i32
  DVD_Title_Orig_Video*: DVD_TextStringType = 74'i32
  DVD_Title_Orig_Album*: DVD_TextStringType = 75'i32
  DVD_Title_Orig_Song*: DVD_TextStringType = 76'i32
  DVD_Title_Orig_Other*: DVD_TextStringType = 79'i32
  DVD_Other_Scene*: DVD_TextStringType = 80'i32
  DVD_Other_Cut*: DVD_TextStringType = 81'i32
  DVD_Other_Take*: DVD_TextStringType = 82'i32
  DVD_VideoCompression_Other*: DVD_VIDEO_COMPRESSION = 0'i32
  DVD_VideoCompression_MPEG1*: DVD_VIDEO_COMPRESSION = 1'i32
  DVD_VideoCompression_MPEG2*: DVD_VIDEO_COMPRESSION = 2'i32
  State_Stopped*: FILTER_STATE = 0'i32
  State_Paused*: FILTER_STATE = 1'i32
  State_Running*: FILTER_STATE = 2'i32
  INTERLEAVE_NONE*: InterleavingMode = 0'i32
  INTERLEAVE_CAPTURE*: InterleavingMode = 1'i32
  INTERLEAVE_FULL*: InterleavingMode = 2'i32
  INTERLEAVE_NONE_BUFFERED*: InterleavingMode = 3'i32
  PINDIR_INPUT*: PIN_DIRECTION = 0'i32
  PINDIR_OUTPUT*: PIN_DIRECTION = 1'i32
  PhysConn_Video_Tuner*: PhysicalConnectorType = 1'i32
  PhysConn_Video_Composite*: PhysicalConnectorType = 2'i32
  PhysConn_Video_SVideo*: PhysicalConnectorType = 3'i32
  PhysConn_Video_RGB*: PhysicalConnectorType = 4'i32
  PhysConn_Video_YRYBY*: PhysicalConnectorType = 5'i32
  PhysConn_Video_SerialDigital*: PhysicalConnectorType = 6'i32
  PhysConn_Video_ParallelDigital*: PhysicalConnectorType = 7'i32
  PhysConn_Video_SCSI*: PhysicalConnectorType = 8'i32
  PhysConn_Video_AUX*: PhysicalConnectorType = 9'i32
  PhysConn_Video_1394*: PhysicalConnectorType = 10'i32
  PhysConn_Video_USB*: PhysicalConnectorType = 11'i32
  PhysConn_Video_VideoDecoder*: PhysicalConnectorType = 12'i32
  PhysConn_Video_VideoEncoder*: PhysicalConnectorType = 13'i32
  PhysConn_Video_SCART*: PhysicalConnectorType = 14'i32
  PhysConn_Video_Black*: PhysicalConnectorType = 15'i32
  PhysConn_Audio_Tuner*: PhysicalConnectorType = 4096'i32
  PhysConn_Audio_Line*: PhysicalConnectorType = 4097'i32
  PhysConn_Audio_Mic*: PhysicalConnectorType = 4098'i32
  PhysConn_Audio_AESDigital*: PhysicalConnectorType = 4099'i32
  PhysConn_Audio_SPDIFDigital*: PhysicalConnectorType = 4100'i32
  PhysConn_Audio_SCSI*: PhysicalConnectorType = 4101'i32
  PhysConn_Audio_AUX*: PhysicalConnectorType = 4102'i32
  PhysConn_Audio_1394*: PhysicalConnectorType = 4103'i32
  PhysConn_Audio_USB*: PhysicalConnectorType = 4104'i32
  PhysConn_Audio_AudioDecoder*: PhysicalConnectorType = 4105'i32
  Famine*: QualityMessageType = 0'i32
  Flood*: QualityMessageType = 1'i32
  AMTVAUDIO_MODE_MONO*: TVAudioMode = 1'i32
  AMTVAUDIO_MODE_STEREO*: TVAudioMode = 2'i32
  AMTVAUDIO_MODE_LANG_A*: TVAudioMode = 16'i32
  AMTVAUDIO_MODE_LANG_B*: TVAudioMode = 32'i32
  AMTVAUDIO_MODE_LANG_C*: TVAudioMode = 64'i32
  AMTVAUDIO_PRESET_STEREO*: TVAudioMode = 512'i32
  AMTVAUDIO_PRESET_LANG_A*: TVAudioMode = 4096'i32
  AMTVAUDIO_PRESET_LANG_B*: TVAudioMode = 8192'i32
  AMTVAUDIO_PRESET_LANG_C*: TVAudioMode = 16384'i32
  TunerInputCable*: TunerInputType = 0'i32
  TunerInputAntenna*: TunerInputType = 1'i32
  UOP_FLAG_Play_Title_Or_AtTime*: VALID_UOP_FLAG = 1'i32
  UOP_FLAG_Play_Chapter*: VALID_UOP_FLAG = 2'i32
  UOP_FLAG_Play_Title*: VALID_UOP_FLAG = 4'i32
  UOP_FLAG_Stop*: VALID_UOP_FLAG = 8'i32
  UOP_FLAG_ReturnFromSubMenu*: VALID_UOP_FLAG = 16'i32
  UOP_FLAG_Play_Chapter_Or_AtTime*: VALID_UOP_FLAG = 32'i32
  UOP_FLAG_PlayPrev_Or_Replay_Chapter*: VALID_UOP_FLAG = 64'i32
  UOP_FLAG_PlayNext_Chapter*: VALID_UOP_FLAG = 128'i32
  UOP_FLAG_Play_Forwards*: VALID_UOP_FLAG = 256'i32
  UOP_FLAG_Play_Backwards*: VALID_UOP_FLAG = 512'i32
  UOP_FLAG_ShowMenu_Title*: VALID_UOP_FLAG = 1024'i32
  UOP_FLAG_ShowMenu_Root*: VALID_UOP_FLAG = 2048'i32
  UOP_FLAG_ShowMenu_SubPic*: VALID_UOP_FLAG = 4096'i32
  UOP_FLAG_ShowMenu_Audio*: VALID_UOP_FLAG = 8192'i32
  UOP_FLAG_ShowMenu_Angle*: VALID_UOP_FLAG = 16384'i32
  UOP_FLAG_ShowMenu_Chapter*: VALID_UOP_FLAG = 32768'i32
  UOP_FLAG_Resume*: VALID_UOP_FLAG = 65536'i32
  UOP_FLAG_Select_Or_Activate_Button*: VALID_UOP_FLAG = 131072'i32
  UOP_FLAG_Still_Off*: VALID_UOP_FLAG = 262144'i32
  UOP_FLAG_Pause_On*: VALID_UOP_FLAG = 524288'i32
  UOP_FLAG_Select_Audio_Stream*: VALID_UOP_FLAG = 1048576'i32
  UOP_FLAG_Select_SubPic_Stream*: VALID_UOP_FLAG = 2097152'i32
  UOP_FLAG_Select_Angle*: VALID_UOP_FLAG = 4194304'i32
  UOP_FLAG_Select_Karaoke_Audio_Presentation_Mode*: VALID_UOP_FLAG = 8388608'i32
  UOP_FLAG_Select_Video_Mode_Preference*: VALID_UOP_FLAG = 16777216'i32
  DeinterlacePref_NextBest*: VMRDeinterlacePrefs = 1'i32
  DeinterlacePref_BOB*: VMRDeinterlacePrefs = 2'i32
  DeinterlacePref_Weave*: VMRDeinterlacePrefs = 4'i32
  DeinterlacePref_Mask*: VMRDeinterlacePrefs = 7'i32
  DeinterlaceTech_Unknown*: VMRDeinterlaceTech = 0'i32
  DeinterlaceTech_BOBLineReplicate*: VMRDeinterlaceTech = 1'i32
  DeinterlaceTech_BOBVerticalStretch*: VMRDeinterlaceTech = 2'i32
  DeinterlaceTech_MedianFiltering*: VMRDeinterlaceTech = 4'i32
  DeinterlaceTech_EdgeFiltering*: VMRDeinterlaceTech = 16'i32
  DeinterlaceTech_FieldAdaptive*: VMRDeinterlaceTech = 32'i32
  DeinterlaceTech_PixelAdaptive*: VMRDeinterlaceTech = 64'i32
  DeinterlaceTech_MotionVectorSteered*: VMRDeinterlaceTech = 128'i32
  MixerPref_NoDecimation*: VMRMixerPrefs = 1'i32
  MixerPref_DecimateOutput*: VMRMixerPrefs = 2'i32
  MixerPref_ARAdjustXorY*: VMRMixerPrefs = 4'i32
  MixerPref_DecimationReserved*: VMRMixerPrefs = 8'i32
  MixerPref_DecimateMask*: VMRMixerPrefs = 15'i32
  MixerPref_BiLinearFiltering*: VMRMixerPrefs = 16'i32
  MixerPref_PointFiltering*: VMRMixerPrefs = 32'i32
  MixerPref_FilteringMask*: VMRMixerPrefs = 240'i32
  MixerPref_RenderTargetRGB*: VMRMixerPrefs = 256'i32
  MixerPref_RenderTargetYUV*: VMRMixerPrefs = 4096'i32
  MixerPref_RenderTargetYUV420*: VMRMixerPrefs = 512'i32
  MixerPref_RenderTargetYUV422*: VMRMixerPrefs = 1024'i32
  MixerPref_RenderTargetYUV444*: VMRMixerPrefs = 2048'i32
  MixerPref_RenderTargetReserved*: VMRMixerPrefs = 57344'i32
  MixerPref_RenderTargetMask*: VMRMixerPrefs = 65280'i32
  MixerPref_DynamicSwitchToBOB*: VMRMixerPrefs = 65536'i32
  MixerPref_DynamicDecimateBy2*: VMRMixerPrefs = 131072'i32
  MixerPref_DynamicReserved*: VMRMixerPrefs = 786432'i32
  MixerPref_DynamicMask*: VMRMixerPrefs = 983040'i32
  VMRMode_Windowed*: VMRMode = 1'i32
  VMRMode_Windowless*: VMRMode = 2'i32
  VMRMode_Renderless*: VMRMode = 4'i32
  VMRMode_Mask*: VMRMode = 7'i32
  VMRSample_SyncPoint*: VMRPresentationFlags = 1'i32
  VMRSample_Preroll*: VMRPresentationFlags = 2'i32
  VMRSample_Discontinuity*: VMRPresentationFlags = 4'i32
  VMRSample_TimeValid*: VMRPresentationFlags = 8'i32
  VMRSample_SrcDstRectsValid*: VMRPresentationFlags = 16'i32
  RenderPrefs_RestrictToInitialMonitor*: VMRRenderPrefs = 0'i32
  RenderPrefs_ForceOffscreen*: VMRRenderPrefs = 1'i32
  RenderPrefs_ForceOverlays*: VMRRenderPrefs = 2'i32
  RenderPrefs_AllowOverlays*: VMRRenderPrefs = 0'i32
  RenderPrefs_AllowOffscreen*: VMRRenderPrefs = 0'i32
  RenderPrefs_DoNotRenderColorKeyAndBorder*: VMRRenderPrefs = 8'i32
  RenderPrefs_Reserved*: VMRRenderPrefs = 16'i32
  RenderPrefs_PreferAGPMemWhenMixing*: VMRRenderPrefs = 32'i32
  RenderPrefs_Mask*: VMRRenderPrefs = 63'i32
  AMAP_PIXELFORMAT_VALID*: VMRSurfaceAllocationFlags = 1'i32
  AMAP_3D_TARGET*: VMRSurfaceAllocationFlags = 2'i32
  AMAP_ALLOW_SYSMEM*: VMRSurfaceAllocationFlags = 4'i32
  AMAP_FORCE_SYSMEM*: VMRSurfaceAllocationFlags = 8'i32
  AMAP_DIRECTED_FLIP*: VMRSurfaceAllocationFlags = 16'i32
  AMAP_DXVA_TARGET*: VMRSurfaceAllocationFlags = 32'i32
  VMR_ARMODE_NONE*: VMR_ASPECT_RATIO_MODE = 0'i32
  VMR_ARMODE_LETTER_BOX*: VMR_ASPECT_RATIO_MODE = 1'i32
  VfwCaptureDialog_Source*: VfwCaptureDialogs = 1'i32
  VfwCaptureDialog_Format*: VfwCaptureDialogs = 2'i32
  VfwCaptureDialog_Display*: VfwCaptureDialogs = 4'i32
  VfwCompressDialog_Config*: VfwCompressDialogs = 1'i32
  VfwCompressDialog_About*: VfwCompressDialogs = 2'i32
  VfwCompressDialog_QueryConfig*: VfwCompressDialogs = 4'i32
  VfwCompressDialog_QueryAbout*: VfwCompressDialogs = 8'i32
  VideoControlFlag_FlipHorizontal*: VideoControlFlags = 1'i32
  VideoControlFlag_FlipVertical*: VideoControlFlags = 2'i32
  VideoControlFlag_ExternalTriggerEnable*: VideoControlFlags = 4'i32
  VideoControlFlag_Trigger*: VideoControlFlags = 8'i32
  VideoCopyProtectionMacrovisionBasic*: VideoCopyProtectionType = 0'i32
  VideoCopyProtectionMacrovisionCBI*: VideoCopyProtectionType = 1'i32
  VideoProcAmp_Flags_Auto*: VideoProcAmpFlags = 1'i32
  VideoProcAmp_Flags_Manual*: VideoProcAmpFlags = 2'i32
  VideoProcAmp_Brightness*: VideoProcAmpProperty = 0'i32
  VideoProcAmp_Contrast*: VideoProcAmpProperty = 1'i32
  VideoProcAmp_Hue*: VideoProcAmpProperty = 2'i32
  VideoProcAmp_Saturation*: VideoProcAmpProperty = 3'i32
  VideoProcAmp_Sharpness*: VideoProcAmpProperty = 4'i32
  VideoProcAmp_Gamma*: VideoProcAmpProperty = 5'i32
  VideoProcAmp_ColorEnable*: VideoProcAmpProperty = 6'i32
  VideoProcAmp_WhiteBalance*: VideoProcAmpProperty = 7'i32
  VideoProcAmp_BacklightCompensation*: VideoProcAmpProperty = 8'i32
  VideoProcAmp_Gain*: VideoProcAmpProperty = 9'i32
  AMRESCTL_RESERVEFLAGS_RESERVE*: X_AMRESCTL_RESERVEFLAGS = 0'i32
  AMRESCTL_RESERVEFLAGS_UNRESERVE*: X_AMRESCTL_RESERVEFLAGS = 1'i32
  AMSTREAMSELECTENABLE_ENABLE*: X_AMSTREAMSELECTENABLEFLAGS = 1'i32
  AMSTREAMSELECTENABLE_ENABLEALL*: X_AMSTREAMSELECTENABLEFLAGS = 2'i32
  AMSTREAMSELECTINFO_ENABLED*: X_AMSTREAMSELECTINFOFLAGS = 1'i32
  AMSTREAMSELECTINFO_EXCLUSIVE*: X_AMSTREAMSELECTINFOFLAGS = 2'i32
  AM_AUDREND_STAT_PARAM_BREAK_COUNT*: X_AM_AUDIO_RENDERER_STAT_PARAM = 1'i32
  AM_AUDREND_STAT_PARAM_SLAVE_MODE*: X_AM_AUDIO_RENDERER_STAT_PARAM = 2'i32
  AM_AUDREND_STAT_PARAM_SILENCE_DUR*: X_AM_AUDIO_RENDERER_STAT_PARAM = 3'i32
  AM_AUDREND_STAT_PARAM_LAST_BUFFER_DUR*: X_AM_AUDIO_RENDERER_STAT_PARAM = 4'i32
  AM_AUDREND_STAT_PARAM_DISCONTINUITIES*: X_AM_AUDIO_RENDERER_STAT_PARAM = 5'i32
  AM_AUDREND_STAT_PARAM_SLAVE_RATE*: X_AM_AUDIO_RENDERER_STAT_PARAM = 6'i32
  AM_AUDREND_STAT_PARAM_SLAVE_DROPWRITE_DUR*: X_AM_AUDIO_RENDERER_STAT_PARAM = 7'i32
  AM_AUDREND_STAT_PARAM_SLAVE_HIGHLOWERROR*: X_AM_AUDIO_RENDERER_STAT_PARAM = 8'i32
  AM_AUDREND_STAT_PARAM_SLAVE_LASTHIGHLOWERROR*: X_AM_AUDIO_RENDERER_STAT_PARAM = 9'i32
  AM_AUDREND_STAT_PARAM_SLAVE_ACCUMERROR*: X_AM_AUDIO_RENDERER_STAT_PARAM = 10'i32
  AM_AUDREND_STAT_PARAM_BUFFERFULLNESS*: X_AM_AUDIO_RENDERER_STAT_PARAM = 11'i32
  AM_AUDREND_STAT_PARAM_JITTER*: X_AM_AUDIO_RENDERER_STAT_PARAM = 12'i32
  AM_FILTER_MISC_FLAGS_IS_RENDERER*: X_AM_FILTER_MISC_FLAGS = 1'i32
  AM_FILTER_MISC_FLAGS_IS_SOURCE*: X_AM_FILTER_MISC_FLAGS = 2'i32
  AM_INTF_SEARCH_INPUT_PIN*: X_AM_INTF_SEARCH_FLAGS = 1'i32
  AM_INTF_SEARCH_OUTPUT_PIN*: X_AM_INTF_SEARCH_FLAGS = 2'i32
  AM_INTF_SEARCH_FILTER*: X_AM_INTF_SEARCH_FLAGS = 4'i32
  AM_OVERLAY_NOTIFY_VISIBLE_CHANGE*: X_AM_OVERLAY_NOTIFY_FLAGS = 1'i32
  AM_OVERLAY_NOTIFY_SOURCE_CHANGE*: X_AM_OVERLAY_NOTIFY_FLAGS = 2'i32
  AM_OVERLAY_NOTIFY_DEST_CHANGE*: X_AM_OVERLAY_NOTIFY_FLAGS = 4'i32
  AM_PIN_FLOW_CONTROL_BLOCK*: X_AM_PIN_FLOW_CONTROL_BLOCK_FLAGS = 1'i32
  AM_PUSHSOURCECAPS_INTERNAL_RM*: X_AM_PUSHSOURCE_FLAGS = 1'i32
  AM_PUSHSOURCECAPS_NOT_LIVE*: X_AM_PUSHSOURCE_FLAGS = 2'i32
  AM_PUSHSOURCECAPS_PRIVATE_CLOCK*: X_AM_PUSHSOURCE_FLAGS = 4'i32
  AM_PUSHSOURCEREQS_USE_STREAM_CLOCK*: X_AM_PUSHSOURCE_FLAGS = 65536'i32
  AM_PUSHSOURCEREQS_USE_CLOCK_CHAIN*: X_AM_PUSHSOURCE_FLAGS = 131072'i32
  AM_RENDEREX_RENDERTOEXISTINGRENDERERS*: X_AM_RENSDEREXFLAGS = 1'i32
  DVDECODERRESOLUTION_720x480*: X_DVDECODERRESOLUTION = 1000'i32
  DVDECODERRESOLUTION_360x240*: X_DVDECODERRESOLUTION = 1001'i32
  DVDECODERRESOLUTION_180x120*: X_DVDECODERRESOLUTION = 1002'i32
  DVDECODERRESOLUTION_88x60*: X_DVDECODERRESOLUTION = 1003'i32
  DVENCODERFORMAT_DVSD*: X_DVENCODERFORMAT = 2007'i32
  DVENCODERFORMAT_DVHD*: X_DVENCODERFORMAT = 2008'i32
  DVENCODERFORMAT_DVSL*: X_DVENCODERFORMAT = 2009'i32
  DVENCODERRESOLUTION_720x480*: X_DVENCODERRESOLUTION = 2012'i32
  DVENCODERRESOLUTION_360x240*: X_DVENCODERRESOLUTION = 2013'i32
  DVENCODERRESOLUTION_180x120*: X_DVENCODERRESOLUTION = 2014'i32
  DVENCODERRESOLUTION_88x60*: X_DVENCODERRESOLUTION = 2015'i32
  DVENCODERVIDEOFORMAT_NTSC*: X_DVENCODERVIDEOFORMAT = 2000'i32
  DVENCODERVIDEOFORMAT_PAL*: X_DVENCODERVIDEOFORMAT = 2001'i32
  DVRESOLUTION_FULL*: X_DVRESOLUTION = 1000'i32
  DVRESOLUTION_HALF*: X_DVRESOLUTION = 1001'i32
  DVRESOLUTION_QUARTER*: X_DVRESOLUTION = 1002'i32
  DVRESOLUTION_DC*: X_DVRESOLUTION = 1003'i32
  REMFILTERF_LEAVECONNECTED*: X_REM_FILTER_FLAGS = 1'i32
  AM_MEDIAEVENT_NONOTIFY*: tagAM_MEDIAEVENT_FLAGS = 1'i32
  AM_SAMPLE_SPLICEPOINT*: tagAM_SAMPLE_PROPERTY_FLAGS = 1'i32
  AM_SAMPLE_PREROLL*: tagAM_SAMPLE_PROPERTY_FLAGS = 2'i32
  AM_SAMPLE_DATADISCONTINUITY*: tagAM_SAMPLE_PROPERTY_FLAGS = 4'i32
  AM_SAMPLE_TYPECHANGED*: tagAM_SAMPLE_PROPERTY_FLAGS = 8'i32
  AM_SAMPLE_TIMEVALID*: tagAM_SAMPLE_PROPERTY_FLAGS = 16'i32
  AM_SAMPLE_TIMEDISCONTINUITY*: tagAM_SAMPLE_PROPERTY_FLAGS = 64'i32
  AM_SAMPLE_FLUSH_ON_PAUSE*: tagAM_SAMPLE_PROPERTY_FLAGS = 128'i32
  AM_SAMPLE_STOPVALID*: tagAM_SAMPLE_PROPERTY_FLAGS = 256'i32
  AM_SAMPLE_ENDOFSTREAM*: tagAM_SAMPLE_PROPERTY_FLAGS = 512'i32
  AM_STREAM_MEDIA*: tagAM_SAMPLE_PROPERTY_FLAGS = 0'i32
  AM_STREAM_CONTROL*: tagAM_SAMPLE_PROPERTY_FLAGS = 1'i32

{.push dynlib: "winmm".}
proc SendDriverMessage*(hDriver: HDRVR, message: uint32, lParam1: LPARAM, lParam2: LPARAM): LRESULT {.sideEffect, importc, stdcall.}
{.pop.}
