# generated by winmd2nim from Windows.Win32.winmd — strsafe (do not edit)
import ./[winnt]
export winnt

type

  # typdefs
  STRSAFE_LPCSTR* = distinct ptr int8
  STRSAFE_LPCUWSTR* = distinct ptr uint16
  STRSAFE_LPCWSTR* = distinct ptr uint16
  STRSAFE_LPSTR* = distinct ptr int8
  STRSAFE_LPWSTR* = distinct ptr uint16
  STRSAFE_PCNZCH* = distinct ptr int8
  STRSAFE_PCNZWCH* = distinct ptr uint16
  STRSAFE_PCUNZWCH* = distinct ptr uint16

const
  # free constants
  STRSAFE_E_END_OF_FILE*: HRESULT = HRESULT(-2147024858'i32)
  STRSAFE_E_INSUFFICIENT_BUFFER*: HRESULT = HRESULT(-2147024774'i32)
  STRSAFE_E_INVALID_PARAMETER*: HRESULT = HRESULT(-2147024809'i32)
  STRSAFE_FILL_BEHIND_NULL*: int32 = 512'i32
  STRSAFE_FILL_ON_FAILURE*: int32 = 1024'i32
  STRSAFE_IGNORE_NULLS*: int32 = 256'i32
  STRSAFE_MAX_CCH*: int32 = 2147483647'i32
  STRSAFE_MAX_LENGTH*: int32 = 2147483646'i32
  STRSAFE_NO_TRUNCATION*: int32 = 4096'i32
  STRSAFE_NULL_ON_FAILURE*: int32 = 2048'i32
  STRSAFE_USE_SECURE_CRT*: int32 = 0'i32
  STRSAFE_VALID_FLAGS*: int32 = 8191'i32

