# generated by winmd2nim from Windows.Win32.winmd — wbemprov (do not edit)
import ./[winnt, oaidl, minwindef]
export winnt, oaidl, minwindef

type

  # typdefs
  WBEM_CWSTR* = PCWSTR
  WBEM_VARIANT* = VARIANT
  WBEM_WSTR* = PWSTR

  # unscoped enums 
  WBEM_BATCH_TYPE* = int32
  WBEM_EXTRA_RETURN_CODES* = int32
  WBEM_PROVIDER_FLAGS* = int32
  WBEM_PROVIDER_REQUIREMENTS_TYPE* = int32

  # interfaces
  IWbemDecoupledBasicEventProvider* = distinct object
  IWbemDecoupledRegistrar* = distinct object
  IWbemEventConsumerProvider* = distinct object
  IWbemEventProvider* = distinct object
  IWbemEventProviderQuerySink* = distinct object
  IWbemEventProviderSecurity* = distinct object
  IWbemEventSink* = distinct object
  IWbemHiPerfProvider* = distinct object
  IWbemPropertyProvider* = distinct object
  IWbemProviderIdentity* = distinct object
  IWbemProviderInit* = distinct object
  IWbemProviderInitSink* = distinct object
  IWbemUnboundObjectSink* = distinct object

const
  # unscoped enum members
  WBEM_FLAG_BATCH_IF_NEEDED*: WBEM_BATCH_TYPE = 0'i32
  WBEM_FLAG_MUST_BATCH*: WBEM_BATCH_TYPE = 1'i32
  WBEM_FLAG_MUST_NOT_BATCH*: WBEM_BATCH_TYPE = 2'i32
  WBEM_S_INITIALIZED*: WBEM_EXTRA_RETURN_CODES = 0'i32
  WBEM_S_LIMITED_SERVICE*: WBEM_EXTRA_RETURN_CODES = 274433'i32
  WBEM_S_INDIRECTLY_UPDATED*: WBEM_EXTRA_RETURN_CODES = 274434'i32
  WBEM_S_SUBJECT_TO_SDS*: WBEM_EXTRA_RETURN_CODES = 274435'i32
  WBEM_E_RETRY_LATER*: WBEM_EXTRA_RETURN_CODES = -2147209215'i32
  WBEM_E_RESOURCE_CONTENTION*: WBEM_EXTRA_RETURN_CODES = -2147209214'i32
  WBEM_FLAG_OWNER_UPDATE*: WBEM_PROVIDER_FLAGS = 65536'i32
  WBEM_REQUIREMENTS_START_POSTFILTER*: WBEM_PROVIDER_REQUIREMENTS_TYPE = 0'i32
  WBEM_REQUIREMENTS_STOP_POSTFILTER*: WBEM_PROVIDER_REQUIREMENTS_TYPE = 1'i32
  WBEM_REQUIREMENTS_RECHECK_SUBSCRIPTIONS*: WBEM_PROVIDER_REQUIREMENTS_TYPE = 2'i32

{.push dynlib: "advapi32".}
proc AccessCheck*(pSecurityDescriptor: PSECURITY_DESCRIPTOR, ClientToken: HANDLE, DesiredAccess: uint32, GenericMapping: ptr GENERIC_MAPPING, PrivilegeSet: ptr PRIVILEGE_SET, PrivilegeSetLength: ptr uint32, GrantedAccess: ptr uint32, AccessStatus: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
