# generated by winmd2nim from Windows.Win32.winmd — websocket.dll (do not edit)
import ./[winnt, minwindef]
export winnt, minwindef

type

  # structs
  WEB_SOCKET_BUFFER* {.completeStruct, union.} = object
    Data*: WEB_SOCKET_BUFFER_0
    CloseStatus*: WEB_SOCKET_BUFFER_1
  WEB_SOCKET_BUFFER_0* {.completeStruct.} = object
    pbBuffer*: PBYTE
    ulBufferLength*: uint32
  WEB_SOCKET_BUFFER_1* {.completeStruct.} = object
    pbReason*: PBYTE
    ulReasonLength*: uint32
    usStatus*: uint16
  WEB_SOCKET_HTTP_HEADER* {.completeStruct.} = object
    pcName*: PCHAR
    ulNameLength*: uint32
    pcValue*: PCHAR
    ulValueLength*: uint32
  WEB_SOCKET_PROPERTY* {.completeStruct.} = object
    Type*: WEB_SOCKET_PROPERTY_TYPE
    pvValue*: pointer
    ulValueSize*: uint32

  # typdefs
  PWEB_SOCKET_ACTION* = distinct ptr WEB_SOCKET_ACTION
  PWEB_SOCKET_BUFFER* = ptr WEB_SOCKET_BUFFER
  PWEB_SOCKET_HTTP_HEADER* = ptr WEB_SOCKET_HTTP_HEADER
  PWEB_SOCKET_PROPERTY* = ptr WEB_SOCKET_PROPERTY
  WEB_SOCKET_HANDLE* = distinct pointer

  # unscoped enums 
  WEB_SOCKET_ACTION* = int32
  WEB_SOCKET_ACTION_QUEUE* = int32
  WEB_SOCKET_BUFFER_TYPE* = int32
  WEB_SOCKET_CLOSE_STATUS* = int32
  WEB_SOCKET_PROPERTY_TYPE* = int32

const
  # free constants
  WEB_SOCKET_MAX_CLOSE_REASON_LENGTH*: int32 = 123'i32

  # unscoped enum members
  WEB_SOCKET_NO_ACTION*: WEB_SOCKET_ACTION = 0'i32
  WEB_SOCKET_SEND_TO_NETWORK_ACTION*: WEB_SOCKET_ACTION = 1'i32
  WEB_SOCKET_INDICATE_SEND_COMPLETE_ACTION*: WEB_SOCKET_ACTION = 2'i32
  WEB_SOCKET_RECEIVE_FROM_NETWORK_ACTION*: WEB_SOCKET_ACTION = 3'i32
  WEB_SOCKET_INDICATE_RECEIVE_COMPLETE_ACTION*: WEB_SOCKET_ACTION = 4'i32
  WEB_SOCKET_SEND_ACTION_QUEUE*: WEB_SOCKET_ACTION_QUEUE = 1'i32
  WEB_SOCKET_RECEIVE_ACTION_QUEUE*: WEB_SOCKET_ACTION_QUEUE = 2'i32
  WEB_SOCKET_ALL_ACTION_QUEUE*: WEB_SOCKET_ACTION_QUEUE = 3'i32
  WEB_SOCKET_UTF8_MESSAGE_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483648'i32
  WEB_SOCKET_UTF8_FRAGMENT_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483647'i32
  WEB_SOCKET_BINARY_MESSAGE_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483646'i32
  WEB_SOCKET_BINARY_FRAGMENT_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483645'i32
  WEB_SOCKET_CLOSE_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483644'i32
  WEB_SOCKET_PING_PONG_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483643'i32
  WEB_SOCKET_UNSOLICITED_PONG_BUFFER_TYPE*: WEB_SOCKET_BUFFER_TYPE = -2147483642'i32
  WEB_SOCKET_SUCCESS_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1000'i32
  WEB_SOCKET_ENDPOINT_UNAVAILABLE_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1001'i32
  WEB_SOCKET_PROTOCOL_ERROR_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1002'i32
  WEB_SOCKET_INVALID_DATA_TYPE_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1003'i32
  WEB_SOCKET_EMPTY_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1005'i32
  WEB_SOCKET_ABORTED_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1006'i32
  WEB_SOCKET_INVALID_PAYLOAD_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1007'i32
  WEB_SOCKET_POLICY_VIOLATION_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1008'i32
  WEB_SOCKET_MESSAGE_TOO_BIG_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1009'i32
  WEB_SOCKET_UNSUPPORTED_EXTENSIONS_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1010'i32
  WEB_SOCKET_SERVER_ERROR_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1011'i32
  WEB_SOCKET_SECURE_HANDSHAKE_ERROR_CLOSE_STATUS*: WEB_SOCKET_CLOSE_STATUS = 1015'i32
  WEB_SOCKET_RECEIVE_BUFFER_SIZE_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 0'i32
  WEB_SOCKET_SEND_BUFFER_SIZE_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 1'i32
  WEB_SOCKET_DISABLE_MASKING_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 2'i32
  WEB_SOCKET_ALLOCATED_BUFFER_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 3'i32
  WEB_SOCKET_DISABLE_UTF8_VERIFICATION_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 4'i32
  WEB_SOCKET_KEEPALIVE_INTERVAL_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 5'i32
  WEB_SOCKET_SUPPORTED_VERSIONS_PROPERTY_TYPE*: WEB_SOCKET_PROPERTY_TYPE = 6'i32

{.push dynlib: "websocket".}
proc WebSocketAbortHandle*(hWebSocket: WEB_SOCKET_HANDLE) {.sideEffect, importc, stdcall.}
proc WebSocketBeginClientHandshake*(hWebSocket: WEB_SOCKET_HANDLE, pszSubprotocols: ptr PCSTR, ulSubprotocolCount: uint32, pszExtensions: ptr PCSTR, ulExtensionCount: uint32, pInitialHeaders: ptr WEB_SOCKET_HTTP_HEADER, ulInitialHeaderCount: uint32, pAdditionalHeaders: ptr PWEB_SOCKET_HTTP_HEADER, pulAdditionalHeaderCount: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketBeginServerHandshake*(hWebSocket: WEB_SOCKET_HANDLE, pszSubprotocolSelected: PCSTR, pszExtensionSelected: ptr PCSTR, ulExtensionSelectedCount: uint32, pRequestHeaders: ptr WEB_SOCKET_HTTP_HEADER, ulRequestHeaderCount: uint32, pResponseHeaders: ptr PWEB_SOCKET_HTTP_HEADER, pulResponseHeaderCount: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketCompleteAction*(hWebSocket: WEB_SOCKET_HANDLE, pvActionContext: pointer, ulBytesTransferred: uint32) {.sideEffect, importc, stdcall.}
proc WebSocketCreateClientHandle*(pProperties: ptr WEB_SOCKET_PROPERTY, ulPropertyCount: uint32, phWebSocket: ptr WEB_SOCKET_HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketCreateServerHandle*(pProperties: ptr WEB_SOCKET_PROPERTY, ulPropertyCount: uint32, phWebSocket: ptr WEB_SOCKET_HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketDeleteHandle*(hWebSocket: WEB_SOCKET_HANDLE) {.sideEffect, importc, stdcall.}
proc WebSocketEndClientHandshake*(hWebSocket: WEB_SOCKET_HANDLE, pResponseHeaders: ptr WEB_SOCKET_HTTP_HEADER, ulReponseHeaderCount: uint32, pulSelectedExtensions: ptr uint32, pulSelectedExtensionCount: ptr uint32, pulSelectedSubprotocol: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketEndServerHandshake*(hWebSocket: WEB_SOCKET_HANDLE): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketGetAction*(hWebSocket: WEB_SOCKET_HANDLE, eActionQueue: WEB_SOCKET_ACTION_QUEUE, pDataBuffers: ptr WEB_SOCKET_BUFFER, pulDataBufferCount: ptr uint32, pAction: ptr WEB_SOCKET_ACTION, pBufferType: ptr WEB_SOCKET_BUFFER_TYPE, pvApplicationContext: ptr pointer, pvActionContext: ptr pointer): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketGetGlobalProperty*(eType: WEB_SOCKET_PROPERTY_TYPE, pvValue: pointer, ulSize: ptr uint32): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketReceive*(hWebSocket: WEB_SOCKET_HANDLE, pBuffer: ptr WEB_SOCKET_BUFFER, pvContext: pointer): HRESULT {.sideEffect, importc, stdcall.}
proc WebSocketSend*(hWebSocket: WEB_SOCKET_HANDLE, BufferType: WEB_SOCKET_BUFFER_TYPE, pBuffer: ptr WEB_SOCKET_BUFFER, Context: pointer): HRESULT {.sideEffect, importc, stdcall.}
{.pop.}
