# generated by winmd2nim from Windows.Win32.winmd — wincred (do not edit)
import ./[sspi, winnt, windef, minwindef]
export sspi, winnt, windef, minwindef

type

  # structs
  BINARY_BLOB_CREDENTIAL_INFO* {.completeStruct.} = object
    cbBlob*: uint32
    pbBlob*: LPBYTE
  CERT_CREDENTIAL_INFO* {.completeStruct.} = object
    cbSize*: uint32
    rgbHashOfCert*: array[20, uint8]
  CREDENTIALA* {.completeStruct.} = object
    Flags*: uint32
    Type*: uint32
    TargetName*: PSTR
    Comment*: PSTR
    LastWritten*: FILETIME
    CredentialBlobSize*: uint32
    CredentialBlob*: LPBYTE
    Persist*: uint32
    AttributeCount*: uint32
    Attributes*: PCREDENTIAL_ATTRIBUTEA
    TargetAlias*: PSTR
    UserName*: PSTR
  CREDENTIALW* {.completeStruct.} = object
    Flags*: uint32
    Type*: uint32
    TargetName*: PWSTR
    Comment*: PWSTR
    LastWritten*: FILETIME
    CredentialBlobSize*: uint32
    CredentialBlob*: LPBYTE
    Persist*: uint32
    AttributeCount*: uint32
    Attributes*: PCREDENTIAL_ATTRIBUTEW
    TargetAlias*: PWSTR
    UserName*: PWSTR
  CREDENTIAL_ATTRIBUTEA* {.completeStruct.} = object
    Keyword*: PSTR
    Flags*: uint32
    ValueSize*: uint32
    Value*: LPBYTE
  CREDENTIAL_ATTRIBUTEW* {.completeStruct.} = object
    Keyword*: PWSTR
    Flags*: uint32
    ValueSize*: uint32
    Value*: LPBYTE
  CREDENTIAL_TARGET_INFORMATIONA* {.completeStruct.} = object
    TargetName*: PSTR
    NetbiosServerName*: PSTR
    DnsServerName*: PSTR
    NetbiosDomainName*: PSTR
    DnsDomainName*: PSTR
    DnsTreeName*: PSTR
    PackageName*: PSTR
    Flags*: uint32
    CredTypeCount*: uint32
    CredTypes*: LPDWORD
  CREDENTIAL_TARGET_INFORMATIONW* {.completeStruct.} = object
    TargetName*: PWSTR
    NetbiosServerName*: PWSTR
    DnsServerName*: PWSTR
    NetbiosDomainName*: PWSTR
    DnsDomainName*: PWSTR
    DnsTreeName*: PWSTR
    PackageName*: PWSTR
    Flags*: uint32
    CredTypeCount*: uint32
    CredTypes*: LPDWORD
  CREDUI_INFOA* {.completeStruct.} = object
    cbSize*: uint32
    hwndParent*: HWND
    pszMessageText*: PCSTR
    pszCaptionText*: PCSTR
    hbmBanner*: HBITMAP
  CREDUI_INFOW* {.completeStruct.} = object
    cbSize*: uint32
    hwndParent*: HWND
    pszMessageText*: PCWSTR
    pszCaptionText*: PCWSTR
    hbmBanner*: HBITMAP
  USERNAME_TARGET_CREDENTIAL_INFO* {.completeStruct.} = object
    UserName*: PWSTR

  # typdefs
  PBINARY_BLOB_CREDENTIAL_INFO* = ptr BINARY_BLOB_CREDENTIAL_INFO
  PCERT_CREDENTIAL_INFO* = ptr CERT_CREDENTIAL_INFO
  PCREDENTIALA* = ptr CREDENTIALA
  PCREDENTIALW* = ptr CREDENTIALW
  PCREDENTIAL_ATTRIBUTEA* = ptr CREDENTIAL_ATTRIBUTEA
  PCREDENTIAL_ATTRIBUTEW* = ptr CREDENTIAL_ATTRIBUTEW
  PCREDENTIAL_TARGET_INFORMATIONA* = ptr CREDENTIAL_TARGET_INFORMATIONA
  PCREDENTIAL_TARGET_INFORMATIONW* = ptr CREDENTIAL_TARGET_INFORMATIONW
  PCREDUI_INFOA* = ptr CREDUI_INFOA
  PCREDUI_INFOW* = ptr CREDUI_INFOW
  PCRED_MARSHAL_TYPE* = distinct ptr CRED_MARSHAL_TYPE
  PCRED_PROTECTION_TYPE* = distinct ptr CRED_PROTECTION_TYPE
  PUSERNAME_TARGET_CREDENTIAL_INFO* = ptr USERNAME_TARGET_CREDENTIAL_INFO

  # unscoped enums 
  CRED_MARSHAL_TYPE* = int32
  CRED_PROTECTION_TYPE* = int32

const
  # free constants
  BACK_BUTTON_IDENTIFY_AUTH_PACKAGE*: uint32 = 0xcad00001'u32
  CERT_HASH_LENGTH*: int32 = 20'i32
  CREDUIWIN_AUTHPACKAGE_ONLY*: int32 = 16'i32
  CREDUIWIN_CHECKBOX*: int32 = 2'i32
  CREDUIWIN_DOWNLEVEL_HELLO_AS_SMART_CARD*: uint32 = 0x80000000'u32
  CREDUIWIN_ENUMERATE_ADMINS*: int32 = 256'i32
  CREDUIWIN_ENUMERATE_CURRENT_USER*: int32 = 512'i32
  CREDUIWIN_GENERIC*: int32 = 1'i32
  CREDUIWIN_IGNORE_CLOUDAUTHORITY_NAME*: int32 = 262144'i32
  CREDUIWIN_IN_CRED_ONLY*: int32 = 32'i32
  CREDUIWIN_PACK_32_WOW*: int32 = 268435456'i32
  CREDUIWIN_PREPROMPTING*: int32 = 8192'i32
  CREDUIWIN_SECURE_PROMPT*: int32 = 4096'i32
  CREDUIWIN_USE_V2*: int32 = 64'i32
  CREDUIWIN_VALID_FLAGS*: uint32 = 0x90043333'u32
  CREDUI_FLAGS_ALWAYS_SHOW_UI*: int32 = 128'i32
  CREDUI_FLAGS_COMPLETE_USERNAME*: int32 = 2048'i32
  CREDUI_FLAGS_DO_NOT_PERSIST*: int32 = 2'i32
  CREDUI_FLAGS_EXCLUDE_CERTIFICATES*: int32 = 8'i32
  CREDUI_FLAGS_EXPECT_CONFIRMATION*: int32 = 131072'i32
  CREDUI_FLAGS_GENERIC_CREDENTIALS*: int32 = 262144'i32
  CREDUI_FLAGS_INCORRECT_PASSWORD*: int32 = 1'i32
  CREDUI_FLAGS_KEEP_USERNAME*: int32 = 1048576'i32
  CREDUI_FLAGS_PASSWORD_ONLY_OK*: int32 = 512'i32
  CREDUI_FLAGS_PERSIST*: int32 = 4096'i32
  CREDUI_FLAGS_PROMPT_VALID*: int32 = 1990623'i32
  CREDUI_FLAGS_REQUEST_ADMINISTRATOR*: int32 = 4'i32
  CREDUI_FLAGS_REQUIRE_CERTIFICATE*: int32 = 16'i32
  CREDUI_FLAGS_REQUIRE_SMARTCARD*: int32 = 256'i32
  CREDUI_FLAGS_SERVER_CREDENTIAL*: int32 = 16384'i32
  CREDUI_FLAGS_SHOW_SAVE_CHECK_BOX*: int32 = 64'i32
  CREDUI_FLAGS_USERNAME_TARGET_CREDENTIALS*: int32 = 524288'i32
  CREDUI_FLAGS_VALIDATE_USERNAME*: int32 = 1024'i32
  CREDUI_FOOTER_LINK_AUTHPACKAGE_ID*: int32 = 212664322'i32
  CREDUI_MAX_CAPTION_LENGTH*: int32 = 128'i32
  CREDUI_MAX_DOMAIN_TARGET_LENGTH*: int32 = 337'i32
  CREDUI_MAX_GENERIC_TARGET_LENGTH*: int32 = 32767'i32
  CREDUI_MAX_MESSAGE_LENGTH*: int32 = 1024'i32
  CREDUI_MAX_PASSWORD_LENGTH*: int32 = 256'i32
  CREDUI_MAX_USERNAME_LENGTH*: int32 = 513'i32
  CREDUI_PICKERSCREEN_AUTHPACKAGE_ID*: int32 = 212664323'i32
  CRED_ALLOW_NAME_RESOLUTION*: int32 = 1'i32
  CRED_CACHE_TARGET_INFORMATION*: int32 = 1'i32
  CRED_ENUMERATE_ALL_CREDENTIALS*: int32 = 1'i32
  CRED_FLAGS_NGC_CERT*: int32 = 128'i32
  CRED_FLAGS_OWF_CRED_BLOB*: int32 = 8'i32
  CRED_FLAGS_PASSWORD_FOR_CERT*: int32 = 1'i32
  CRED_FLAGS_PROMPT_NOW*: int32 = 2'i32
  CRED_FLAGS_REQUIRE_CONFIRMATION*: int32 = 16'i32
  CRED_FLAGS_USERNAME_TARGET*: int32 = 4'i32
  CRED_FLAGS_VALID_FLAGS*: int32 = 61695'i32
  CRED_FLAGS_VALID_INPUT_FLAGS*: int32 = 61599'i32
  CRED_FLAGS_VSM_PROTECTED*: int32 = 64'i32
  CRED_FLAGS_WILDCARD_MATCH*: int32 = 32'i32
  CRED_LOGON_TYPES_MASK*: int32 = 61440'i32
  CRED_MAX_ATTRIBUTES*: int32 = 64'i32
  CRED_MAX_CREDENTIAL_BLOB_SIZE*: int32 = 2560'i32
  CRED_MAX_DOMAIN_TARGET_NAME_LENGTH*: int32 = 337'i32
  CRED_MAX_GENERIC_TARGET_NAME_LENGTH*: int32 = 32767'i32
  CRED_MAX_STRING_LENGTH*: int32 = 256'i32
  CRED_MAX_TARGETNAME_ATTRIBUTE_LENGTH*: int32 = 256'i32
  CRED_MAX_TARGETNAME_NAMESPACE_LENGTH*: int32 = 256'i32
  CRED_MAX_USERNAME_LENGTH*: int32 = 513'i32
  CRED_MAX_VALUE_SIZE*: int32 = 256'i32
  CRED_PACK_GENERIC_CREDENTIALS*: int32 = 4'i32
  CRED_PACK_ID_PROVIDER_CREDENTIALS*: int32 = 8'i32
  CRED_PACK_PROTECTED_CREDENTIALS*: int32 = 1'i32
  CRED_PACK_WOW_BUFFER*: int32 = 2'i32
  CRED_PERSIST_ENTERPRISE*: int32 = 3'i32
  CRED_PERSIST_LOCAL_MACHINE*: int32 = 2'i32
  CRED_PERSIST_NONE*: int32 = 0'i32
  CRED_PERSIST_SESSION*: int32 = 1'i32
  CRED_PRESERVE_CREDENTIAL_BLOB*: int32 = 1'i32
  CRED_PROTECT_AS_SELF*: int32 = 1'i32
  CRED_PROTECT_TO_SYSTEM*: int32 = 2'i32
  CRED_PROTECT_VALID_FLAGS*: int32 = 3'i32
  CRED_SESSION_WILDCARD_NAME_A*: string = "*Session"
  # CRED_SESSION_WILDCARD_NAME_W = "*Session"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_BATCH_A*: string = "batch"
  # CRED_TARGETNAME_ATTRIBUTE_BATCH_W = "batch"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_CACHEDINTERACTIVE_A*: string = "cachedinteractive"
  # CRED_TARGETNAME_ATTRIBUTE_CACHEDINTERACTIVE_W = "cachedinteractive"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_INTERACTIVE_A*: string = "interactive"
  # CRED_TARGETNAME_ATTRIBUTE_INTERACTIVE_W = "interactive"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_NAME_A*: string = "name"
  # CRED_TARGETNAME_ATTRIBUTE_NAME_W = "name"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_NETWORKCLEARTEXT_A*: string = "networkcleartext"
  # CRED_TARGETNAME_ATTRIBUTE_NETWORKCLEARTEXT_W = "networkcleartext"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_NETWORK_A*: string = "network"
  # CRED_TARGETNAME_ATTRIBUTE_NETWORK_W = "network"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_REMOTEINTERACTIVE_A*: string = "remoteinteractive"
  # CRED_TARGETNAME_ATTRIBUTE_REMOTEINTERACTIVE_W = "remoteinteractive"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_SEPERATOR_A*: uint32 = 0x3d'u32
  CRED_TARGETNAME_ATTRIBUTE_SEPERATOR_W*: uint32 = 0x3d'u32
  CRED_TARGETNAME_ATTRIBUTE_SERVICE_A*: string = "service"
  # CRED_TARGETNAME_ATTRIBUTE_SERVICE_W = "service"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_ATTRIBUTE_TARGET_A*: string = "target"
  # CRED_TARGETNAME_ATTRIBUTE_TARGET_W = "target"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_DOMAIN_EXTENDED_USERNAME_SEPARATOR_A*: uint32 = 0x7c'u32
  CRED_TARGETNAME_DOMAIN_EXTENDED_USERNAME_SEPARATOR_W*: uint32 = 0x7c'u32
  CRED_TARGETNAME_DOMAIN_NAMESPACE_A*: string = "Domain"
  # CRED_TARGETNAME_DOMAIN_NAMESPACE_W = "Domain"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_LEGACYGENERIC_NAMESPACE_A*: string = "LegacyGeneric"
  # CRED_TARGETNAME_LEGACYGENERIC_NAMESPACE_W = "LegacyGeneric"  # TODO: wide string constant (utf-16)
  CRED_TARGETNAME_NAMESPACE_SEPERATOR_A*: uint32 = 0x3a'u32
  CRED_TARGETNAME_NAMESPACE_SEPERATOR_W*: uint32 = 0x3a'u32
  CRED_TI_CREATE_EXPLICIT_CRED*: int32 = 16'i32
  CRED_TI_DNSTREE_IS_DFS_SERVER*: int32 = 64'i32
  CRED_TI_DOMAIN_FORMAT_UNKNOWN*: int32 = 2'i32
  CRED_TI_ONLY_PASSWORD_REQUIRED*: int32 = 4'i32
  CRED_TI_SERVER_FORMAT_UNKNOWN*: int32 = 1'i32
  CRED_TI_USERNAME_TARGET*: int32 = 8'i32
  CRED_TI_VALID_FLAGS*: int32 = 61567'i32
  CRED_TI_WORKGROUP_MEMBER*: int32 = 32'i32
  CRED_TYPE_DOMAIN_CERTIFICATE*: int32 = 3'i32
  CRED_TYPE_DOMAIN_EXTENDED*: int32 = 6'i32
  CRED_TYPE_DOMAIN_PASSWORD*: int32 = 2'i32
  CRED_TYPE_DOMAIN_VISIBLE_PASSWORD*: int32 = 4'i32
  CRED_TYPE_GENERIC*: int32 = 1'i32
  CRED_TYPE_GENERIC_CERTIFICATE*: int32 = 5'i32
  CRED_TYPE_MAXIMUM*: int32 = 7'i32
  CRED_TYPE_MAXIMUM_EX*: int32 = 1007'i32
  CRED_UNIVERSAL_WILDCARD_A*: uint32 = 0x2a'u32
  CRED_UNIVERSAL_WILDCARD_W*: uint32 = 0x2a'u32
  CRED_UNPROTECT_ALLOW_TO_SYSTEM*: int32 = 2'i32
  CRED_UNPROTECT_AS_SELF*: int32 = 1'i32
  CRED_UNPROTECT_VALID_FLAGS*: int32 = 3'i32
  NERR_BASE*: int32 = 2100'i32
  NERR_PasswordExpired*: int32 = 2242'i32

  # unscoped enum members
  CertCredential*: CRED_MARSHAL_TYPE = 1'i32
  UsernameTargetCredential*: CRED_MARSHAL_TYPE = 2'i32
  BinaryBlobCredential*: CRED_MARSHAL_TYPE = 3'i32
  UsernameForPackedCredentials*: CRED_MARSHAL_TYPE = 4'i32
  BinaryBlobForSystem*: CRED_MARSHAL_TYPE = 5'i32
  CredUnprotected*: CRED_PROTECTION_TYPE = 0'i32
  CredUserProtection*: CRED_PROTECTION_TYPE = 1'i32
  CredTrustedProtection*: CRED_PROTECTION_TYPE = 2'i32
  CredForSystemProtection*: CRED_PROTECTION_TYPE = 3'i32

{.push dynlib: "advapi32".}
proc CredDeleteA*(TargetName: PCSTR, Type: uint32, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredDeleteW*(TargetName: PCWSTR, Type: uint32, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredEnumerateA*(Filter: PCSTR, Flags: uint32, Count: ptr uint32, Credential: ptr ptr PCREDENTIALA): BOOL {.sideEffect, importc, stdcall.}
proc CredEnumerateW*(Filter: PCWSTR, Flags: uint32, Count: ptr uint32, Credential: ptr ptr PCREDENTIALW): BOOL {.sideEffect, importc, stdcall.}
proc CredFindBestCredentialA*(TargetName: PCSTR, Type: uint32, Flags: uint32, Credential: ptr PCREDENTIALA): BOOL {.sideEffect, importc, stdcall.}
proc CredFindBestCredentialW*(TargetName: PCWSTR, Type: uint32, Flags: uint32, Credential: ptr PCREDENTIALW): BOOL {.sideEffect, importc, stdcall.}
proc CredFree*(Buffer: pointer) {.sideEffect, importc, stdcall.}
proc CredGetSessionTypes*(MaximumPersistCount: uint32, MaximumPersist: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredGetTargetInfoA*(TargetName: PCSTR, Flags: uint32, TargetInfo: ptr PCREDENTIAL_TARGET_INFORMATIONA): BOOL {.sideEffect, importc, stdcall.}
proc CredGetTargetInfoW*(TargetName: PCWSTR, Flags: uint32, TargetInfo: ptr PCREDENTIAL_TARGET_INFORMATIONW): BOOL {.sideEffect, importc, stdcall.}
proc CredIsMarshaledCredentialA*(MarshaledCredential: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc CredIsMarshaledCredentialW*(MarshaledCredential: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc CredIsProtectedA*(pszProtectedCredentials: PCSTR, pProtectionType: ptr CRED_PROTECTION_TYPE): BOOL {.sideEffect, importc, stdcall.}
proc CredIsProtectedW*(pszProtectedCredentials: PCWSTR, pProtectionType: ptr CRED_PROTECTION_TYPE): BOOL {.sideEffect, importc, stdcall.}
proc CredMarshalCredentialA*(CredType: CRED_MARSHAL_TYPE, Credential: pointer, MarshaledCredential: ptr PSTR): BOOL {.sideEffect, importc, stdcall.}
proc CredMarshalCredentialW*(CredType: CRED_MARSHAL_TYPE, Credential: pointer, MarshaledCredential: ptr PWSTR): BOOL {.sideEffect, importc, stdcall.}
proc CredProtectA*(fAsSelf: BOOL, pszCredentials: PCSTR, cchCredentials: uint32, pszProtectedCredentials: PSTR, pcchMaxChars: ptr uint32, ProtectionType: ptr CRED_PROTECTION_TYPE): BOOL {.sideEffect, importc, stdcall.}
proc CredProtectW*(fAsSelf: BOOL, pszCredentials: PCWSTR, cchCredentials: uint32, pszProtectedCredentials: PWSTR, pcchMaxChars: ptr uint32, ProtectionType: ptr CRED_PROTECTION_TYPE): BOOL {.sideEffect, importc, stdcall.}
proc CredReadA*(TargetName: PCSTR, Type: uint32, Flags: uint32, Credential: ptr PCREDENTIALA): BOOL {.sideEffect, importc, stdcall.}
proc CredReadDomainCredentialsA*(TargetInfo: ptr CREDENTIAL_TARGET_INFORMATIONA, Flags: uint32, Count: ptr uint32, Credential: ptr ptr PCREDENTIALA): BOOL {.sideEffect, importc, stdcall.}
proc CredReadDomainCredentialsW*(TargetInfo: ptr CREDENTIAL_TARGET_INFORMATIONW, Flags: uint32, Count: ptr uint32, Credential: ptr ptr PCREDENTIALW): BOOL {.sideEffect, importc, stdcall.}
proc CredReadW*(TargetName: PCWSTR, Type: uint32, Flags: uint32, Credential: ptr PCREDENTIALW): BOOL {.sideEffect, importc, stdcall.}
proc CredRenameA*(OldTargetName: PCSTR, NewTargetName: PCSTR, Type: uint32, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredRenameW*(OldTargetName: PCWSTR, NewTargetName: PCWSTR, Type: uint32, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredUnmarshalCredentialA*(MarshaledCredential: PCSTR, CredType: ptr CRED_MARSHAL_TYPE, Credential: ptr pointer): BOOL {.sideEffect, importc, stdcall.}
proc CredUnmarshalCredentialW*(MarshaledCredential: PCWSTR, CredType: ptr CRED_MARSHAL_TYPE, Credential: ptr pointer): BOOL {.sideEffect, importc, stdcall.}
proc CredUnprotectA*(fAsSelf: BOOL, pszProtectedCredentials: PCSTR, cchProtectedCredentials: uint32, pszCredentials: PSTR, pcchMaxChars: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredUnprotectW*(fAsSelf: BOOL, pszProtectedCredentials: PCWSTR, cchProtectedCredentials: uint32, pszCredentials: PWSTR, pcchMaxChars: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredWriteA*(Credential: ptr CREDENTIALA, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredWriteDomainCredentialsA*(TargetInfo: ptr CREDENTIAL_TARGET_INFORMATIONA, Credential: ptr CREDENTIALA, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredWriteDomainCredentialsW*(TargetInfo: ptr CREDENTIAL_TARGET_INFORMATIONW, Credential: ptr CREDENTIALW, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredWriteW*(Credential: ptr CREDENTIALW, Flags: uint32): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
{.push dynlib: "credui".}
proc CredPackAuthenticationBufferA*(dwFlags: uint32, pszUserName: PCSTR, pszPassword: PCSTR, pPackedCredentials: ptr uint8, pcbPackedCredentials: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredPackAuthenticationBufferW*(dwFlags: uint32, pszUserName: PCWSTR, pszPassword: PCWSTR, pPackedCredentials: ptr uint8, pcbPackedCredentials: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredUICmdLinePromptForCredentialsA*(pszTargetName: PCSTR, pContext: PCtxtHandle, dwAuthError: uint32, UserName: PSTR, ulUserBufferSize: uint32, pszPassword: PSTR, ulPasswordBufferSize: uint32, pfSave: ptr BOOL, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUICmdLinePromptForCredentialsW*(pszTargetName: PCWSTR, pContext: PCtxtHandle, dwAuthError: uint32, UserName: PWSTR, ulUserBufferSize: uint32, pszPassword: PWSTR, ulPasswordBufferSize: uint32, pfSave: ptr BOOL, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIConfirmCredentialsA*(pszTargetName: PCSTR, bConfirm: BOOL): uint32 {.sideEffect, importc, stdcall.}
proc CredUIConfirmCredentialsW*(pszTargetName: PCWSTR, bConfirm: BOOL): uint32 {.sideEffect, importc, stdcall.}
proc CredUIParseUserNameA*(userName: PCSTR, user: ptr int8, userBufferSize: uint32, domain: ptr int8, domainBufferSize: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIParseUserNameW*(UserName: PCWSTR, user: ptr uint16, userBufferSize: uint32, domain: ptr uint16, domainBufferSize: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIPromptForCredentialsA*(pUiInfo: ptr CREDUI_INFOA, pszTargetName: PCSTR, pContext: PCtxtHandle, dwAuthError: uint32, pszUserName: PSTR, ulUserNameBufferSize: uint32, pszPassword: PSTR, ulPasswordBufferSize: uint32, save: ptr BOOL, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIPromptForCredentialsW*(pUiInfo: ptr CREDUI_INFOW, pszTargetName: PCWSTR, pContext: PCtxtHandle, dwAuthError: uint32, pszUserName: PWSTR, ulUserNameBufferSize: uint32, pszPassword: PWSTR, ulPasswordBufferSize: uint32, save: ptr BOOL, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIPromptForWindowsCredentialsA*(pUiInfo: ptr CREDUI_INFOA, dwAuthError: uint32, pulAuthPackage: ptr uint32, pvInAuthBuffer: pointer, ulInAuthBufferSize: uint32, ppvOutAuthBuffer: ptr pointer, pulOutAuthBufferSize: ptr uint32, pfSave: ptr BOOL, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIPromptForWindowsCredentialsW*(pUiInfo: ptr CREDUI_INFOW, dwAuthError: uint32, pulAuthPackage: ptr uint32, pvInAuthBuffer: pointer, ulInAuthBufferSize: uint32, ppvOutAuthBuffer: ptr pointer, pulOutAuthBufferSize: ptr uint32, pfSave: ptr BOOL, dwFlags: uint32): uint32 {.sideEffect, importc, stdcall.}
proc CredUIReadSSOCredW*(pszRealm: PCWSTR, ppszUsername: ptr PWSTR): uint32 {.sideEffect, importc, stdcall.}
proc CredUIStoreSSOCredW*(pszRealm: PCWSTR, pszUsername: PCWSTR, pszPassword: PCWSTR, bPersist: BOOL): uint32 {.sideEffect, importc, stdcall.}
proc CredUnPackAuthenticationBufferA*(dwFlags: uint32, pAuthBuffer: pointer, cbAuthBuffer: uint32, pszUserName: PSTR, pcchlMaxUserName: ptr uint32, pszDomainName: PSTR, pcchMaxDomainName: ptr uint32, pszPassword: PSTR, pcchMaxPassword: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc CredUnPackAuthenticationBufferW*(dwFlags: uint32, pAuthBuffer: pointer, cbAuthBuffer: uint32, pszUserName: PWSTR, pcchMaxUserName: ptr uint32, pszDomainName: PWSTR, pcchMaxDomainName: ptr uint32, pszPassword: PWSTR, pcchMaxPassword: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
{.pop.}
