# generated by winmd2nim from Windows.Win32.winmd — winreg (do not edit)
import ./[winnt, minwindef, minwinbase]
export winnt, minwindef, minwinbase

type

  # structs
  PVALUEA* {.completeStruct.} = object
    pv_valuename*: PSTR
    pv_valuelen*: int32
    pv_value_context*: pointer
    pv_type*: uint32
  PVALUEW* {.completeStruct.} = object
    pv_valuename*: PWSTR
    pv_valuelen*: int32
    pv_value_context*: pointer
    pv_type*: uint32
  REG_PROVIDER* {.completeStruct.} = object
    pi_R0_1val*: PQUERYHANDLER
    pi_R0_allvals*: PQUERYHANDLER
    pi_R3_1val*: PQUERYHANDLER
    pi_R3_allvals*: PQUERYHANDLER
    pi_flags*: uint32
    pi_key_context*: pointer
  VALENTA* {.completeStruct.} = object
    ve_valuename*: PSTR
    ve_valuelen*: uint32
    ve_valueptr*: uint
    ve_type*: uint32
  VALENTW* {.completeStruct.} = object
    ve_valuename*: PWSTR
    ve_valuelen*: uint32
    ve_valueptr*: uint
    ve_type*: uint32
  val_context* {.completeStruct.} = object
    valuelen*: int32
    value_context*: pointer
    val_buff_ptr*: pointer

  # typdefs
  LSTATUS* = distinct int32
  PPROVIDER* = ptr REG_PROVIDER
  PPVALUEA* = ptr PVALUEA
  PPVALUEW* = ptr PVALUEW
  PVALCONTEXT* = ptr val_context
  PVALENTA* = ptr VALENTA
  PVALENTW* = ptr VALENTW
  REGSAM* = ACCESS_MASK

  # delegates
  PQUERYHANDLER* = proc (arg_1: pointer, arg_2: ptr val_context, arg_3: uint32, arg_4: pointer, arg_5: ptr uint32, arg_6: uint32): uint32 {.stdcall.}
  QUERYHANDLER* = proc (arg_1: pointer, arg_2: ptr val_context, arg_3: uint32, arg_4: pointer, arg_5: ptr uint32, arg_6: uint32): uint32 {.stdcall.}

template HKEY_CLASSES_ROOT*: untyped = cast[HKEY](-2147483648)
template HKEY_CURRENT_CONFIG*: untyped = cast[HKEY](-2147483643)
template HKEY_CURRENT_USER*: untyped = cast[HKEY](-2147483647)
template HKEY_CURRENT_USER_LOCAL_SETTINGS*: untyped = cast[HKEY](-2147483641)
template HKEY_DYN_DATA*: untyped = cast[HKEY](-2147483642)
template HKEY_LOCAL_MACHINE*: untyped = cast[HKEY](-2147483646)
template HKEY_PERFORMANCE_DATA*: untyped = cast[HKEY](-2147483644)
template HKEY_PERFORMANCE_NLSTEXT*: untyped = cast[HKEY](-2147483552)
template HKEY_PERFORMANCE_TEXT*: untyped = cast[HKEY](-2147483568)
template HKEY_USERS*: untyped = cast[HKEY](-2147483645)
const
  # free constants
  MAX_SHUTDOWN_TIMEOUT*: int32 = 315360000'i32
  PROVIDER_KEEPS_VALUE_LENGTH*: int32 = 1'i32
  REASON_HWINSTALL*: int32 = 65538'i32
  REASON_LEGACY_API*: uint32 = 0x80070000'u32
  REASON_OTHER*: int32 = 0'i32
  REASON_PLANNED_FLAG*: uint32 = 0x80000000'u32
  REASON_SERVICEHANG*: int32 = 196613'i32
  REASON_SWHWRECONF*: int32 = 196612'i32
  REASON_SWINSTALL*: int32 = 196610'i32
  REASON_UNKNOWN*: int32 = 255'i32
  REASON_UNSTABLE*: int32 = 327686'i32
  REG_ALLOW_TRANSPORT_FALLBACK*: int32 = 2'i32
  REG_ALLOW_UNSECURE_CONNECTION*: int32 = 4'i32
  REG_MUI_STRING_TRUNCATE*: int32 = 1'i32
  REG_PROCESS_APPKEY*: int32 = 1'i32
  REG_SECURE_CONNECTION*: int32 = 1'i32
  REG_USE_CURRENT_SECURITY_CONTEXT*: int32 = 2'i32
  RRF_NOEXPAND*: int32 = 268435456'i32
  RRF_RT_ANY*: int32 = 65535'i32
  RRF_RT_DWORD*: int32 = 24'i32
  RRF_RT_QWORD*: int32 = 72'i32
  RRF_RT_REG_BINARY*: int32 = 8'i32
  RRF_RT_REG_DWORD*: int32 = 16'i32
  RRF_RT_REG_EXPAND_SZ*: int32 = 4'i32
  RRF_RT_REG_MULTI_SZ*: int32 = 32'i32
  RRF_RT_REG_NONE*: int32 = 1'i32
  RRF_RT_REG_QWORD*: int32 = 64'i32
  RRF_RT_REG_SZ*: int32 = 2'i32
  RRF_SUBKEY_WOW6432KEY*: int32 = 131072'i32
  RRF_SUBKEY_WOW6464KEY*: int32 = 65536'i32
  RRF_WOW64_MASK*: int32 = 196608'i32
  RRF_ZEROONFAILURE*: int32 = 536870912'i32
  SHUTDOWN_ARSO*: int32 = 8192'i32
  SHUTDOWN_CHECK_SAFE_FOR_SERVER*: int32 = 16384'i32
  SHUTDOWN_FORCE_OTHERS*: int32 = 1'i32
  SHUTDOWN_FORCE_SELF*: int32 = 2'i32
  SHUTDOWN_GRACE_OVERRIDE*: int32 = 32'i32
  SHUTDOWN_HYBRID*: int32 = 512'i32
  SHUTDOWN_INSTALL_UPDATES*: int32 = 64'i32
  SHUTDOWN_MOBILE_UI*: int32 = 4096'i32
  SHUTDOWN_NOREBOOT*: int32 = 16'i32
  SHUTDOWN_POWEROFF*: int32 = 8'i32
  SHUTDOWN_RESTART*: int32 = 4'i32
  SHUTDOWN_RESTARTAPPS*: int32 = 128'i32
  SHUTDOWN_RESTART_BOOTOPTIONS*: int32 = 1024'i32
  SHUTDOWN_SKIP_SVC_PRESHUTDOWN*: int32 = 256'i32
  SHUTDOWN_SOFT_REBOOT*: int32 = 2048'i32
  SHUTDOWN_SYSTEM_INITIATED*: int32 = 65536'i32
  SHUTDOWN_UPDATE_POWEROFF*: int32 = 131072'i32
  SHUTDOWN_VAIL_CONTAINER*: int32 = 32768'i32
  WIN31_CLASS*: int32 = 0'i32

{.push dynlib: "advapi32".}
proc AbortSystemShutdownA*(lpMachineName: PCSTR): BOOL {.sideEffect, importc, stdcall.}
proc AbortSystemShutdownW*(lpMachineName: PCWSTR): BOOL {.sideEffect, importc, stdcall.}
proc CheckForHiberboot*(pHiberboot: ptr bool, bClearFlag: bool): uint32 {.sideEffect, importc, stdcall.}
proc InitiateShutdownA*(lpMachineName: PCSTR, lpMessage: PCSTR, dwGracePeriod: uint32, dwShutdownFlags: uint32, dwReason: uint32): uint32 {.sideEffect, importc, stdcall.}
proc InitiateShutdownW*(lpMachineName: PCWSTR, lpMessage: PCWSTR, dwGracePeriod: uint32, dwShutdownFlags: uint32, dwReason: uint32): uint32 {.sideEffect, importc, stdcall.}
proc InitiateSystemShutdownA*(lpMachineName: PCSTR, lpMessage: PCSTR, dwTimeout: uint32, bForceAppsClosed: BOOL, bRebootAfterShutdown: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc InitiateSystemShutdownExA*(lpMachineName: PCSTR, lpMessage: PCSTR, dwTimeout: uint32, bForceAppsClosed: BOOL, bRebootAfterShutdown: BOOL, dwReason: uint32): BOOL {.sideEffect, importc, stdcall.}
proc InitiateSystemShutdownExW*(lpMachineName: PCWSTR, lpMessage: PCWSTR, dwTimeout: uint32, bForceAppsClosed: BOOL, bRebootAfterShutdown: BOOL, dwReason: uint32): BOOL {.sideEffect, importc, stdcall.}
proc InitiateSystemShutdownW*(lpMachineName: PCWSTR, lpMessage: PCWSTR, dwTimeout: uint32, bForceAppsClosed: BOOL, bRebootAfterShutdown: BOOL): BOOL {.sideEffect, importc, stdcall.}
proc RegCloseKey*(hKey: HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegConnectRegistryA*(lpMachineName: PCSTR, hKey: HKEY, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegConnectRegistryExA*(lpMachineName: PCSTR, hKey: HKEY, Flags: uint32, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegConnectRegistryExW*(lpMachineName: PCWSTR, hKey: HKEY, Flags: uint32, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegConnectRegistryW*(lpMachineName: PCWSTR, hKey: HKEY, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCopyTreeA*(hKeySrc: HKEY, lpSubKey: PCSTR, hKeyDest: HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCopyTreeW*(hKeySrc: HKEY, lpSubKey: PCWSTR, hKeyDest: HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCreateKeyA*(hKey: HKEY, lpSubKey: PCSTR, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCreateKeyExA*(hKey: HKEY, lpSubKey: PCSTR, Reserved: uint32, lpClass: PCSTR, dwOptions: uint32, samDesired: REGSAM, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, phkResult: ptr HKEY, lpdwDisposition: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCreateKeyExW*(hKey: HKEY, lpSubKey: PCWSTR, Reserved: uint32, lpClass: PCWSTR, dwOptions: uint32, samDesired: REGSAM, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, phkResult: ptr HKEY, lpdwDisposition: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCreateKeyTransactedA*(hKey: HKEY, lpSubKey: PCSTR, Reserved: uint32, lpClass: PCSTR, dwOptions: uint32, samDesired: REGSAM, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, phkResult: ptr HKEY, lpdwDisposition: ptr uint32, hTransaction: HANDLE, pExtendedParemeter: pointer): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCreateKeyTransactedW*(hKey: HKEY, lpSubKey: PCWSTR, Reserved: uint32, lpClass: PCWSTR, dwOptions: uint32, samDesired: REGSAM, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, phkResult: ptr HKEY, lpdwDisposition: ptr uint32, hTransaction: HANDLE, pExtendedParemeter: pointer): LSTATUS {.sideEffect, importc, stdcall.}
proc RegCreateKeyW*(hKey: HKEY, lpSubKey: PCWSTR, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyA*(hKey: HKEY, lpSubKey: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyExA*(hKey: HKEY, lpSubKey: PCSTR, samDesired: REGSAM, Reserved: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyExW*(hKey: HKEY, lpSubKey: PCWSTR, samDesired: REGSAM, Reserved: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyTransactedA*(hKey: HKEY, lpSubKey: PCSTR, samDesired: REGSAM, Reserved: uint32, hTransaction: HANDLE, pExtendedParameter: pointer): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyTransactedW*(hKey: HKEY, lpSubKey: PCWSTR, samDesired: REGSAM, Reserved: uint32, hTransaction: HANDLE, pExtendedParameter: pointer): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyValueA*(hKey: HKEY, lpSubKey: PCSTR, lpValueName: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyValueW*(hKey: HKEY, lpSubKey: PCWSTR, lpValueName: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteKeyW*(hKey: HKEY, lpSubKey: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteTreeA*(hKey: HKEY, lpSubKey: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteTreeW*(hKey: HKEY, lpSubKey: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteValueA*(hKey: HKEY, lpValueName: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDeleteValueW*(hKey: HKEY, lpValueName: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDisablePredefinedCache*(): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDisablePredefinedCacheEx*(): LSTATUS {.sideEffect, importc, stdcall.}
proc RegDisableReflectionKey*(hBase: HKEY): int32 {.sideEffect, importc, stdcall.}
proc RegEnableReflectionKey*(hBase: HKEY): int32 {.sideEffect, importc, stdcall.}
proc RegEnumKeyA*(hKey: HKEY, dwIndex: uint32, lpName: PSTR, cchName: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegEnumKeyExA*(hKey: HKEY, dwIndex: uint32, lpName: PSTR, lpcchName: ptr uint32, lpReserved: ptr uint32, lpClass: PSTR, lpcchClass: ptr uint32, lpftLastWriteTime: ptr FILETIME): LSTATUS {.sideEffect, importc, stdcall.}
proc RegEnumKeyExW*(hKey: HKEY, dwIndex: uint32, lpName: PWSTR, lpcchName: ptr uint32, lpReserved: ptr uint32, lpClass: PWSTR, lpcchClass: ptr uint32, lpftLastWriteTime: ptr FILETIME): LSTATUS {.sideEffect, importc, stdcall.}
proc RegEnumKeyW*(hKey: HKEY, dwIndex: uint32, lpName: PWSTR, cchName: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegEnumValueA*(hKey: HKEY, dwIndex: uint32, lpValueName: PSTR, lpcchValueName: ptr uint32, lpReserved: ptr uint32, lpType: ptr uint32, lpData: ptr uint8, lpcbData: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegEnumValueW*(hKey: HKEY, dwIndex: uint32, lpValueName: PWSTR, lpcchValueName: ptr uint32, lpReserved: ptr uint32, lpType: ptr uint32, lpData: ptr uint8, lpcbData: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegFlushKey*(hKey: HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegGetKeySecurity*(hKey: HKEY, SecurityInformation: SECURITY_INFORMATION, pSecurityDescriptor: PSECURITY_DESCRIPTOR, lpcbSecurityDescriptor: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegGetValueA*(hkey: HKEY, lpSubKey: PCSTR, lpValue: PCSTR, dwFlags: uint32, pdwType: ptr uint32, pvData: pointer, pcbData: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegGetValueW*(hkey: HKEY, lpSubKey: PCWSTR, lpValue: PCWSTR, dwFlags: uint32, pdwType: ptr uint32, pvData: pointer, pcbData: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegLoadAppKeyA*(lpFile: PCSTR, phkResult: ptr HKEY, samDesired: REGSAM, dwOptions: uint32, Reserved: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegLoadAppKeyW*(lpFile: PCWSTR, phkResult: ptr HKEY, samDesired: REGSAM, dwOptions: uint32, Reserved: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegLoadKeyA*(hKey: HKEY, lpSubKey: PCSTR, lpFile: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegLoadKeyW*(hKey: HKEY, lpSubKey: PCWSTR, lpFile: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegLoadMUIStringA*(hKey: HKEY, pszValue: PCSTR, pszOutBuf: PSTR, cbOutBuf: uint32, pcbData: ptr uint32, Flags: uint32, pszDirectory: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegLoadMUIStringW*(hKey: HKEY, pszValue: PCWSTR, pszOutBuf: PWSTR, cbOutBuf: uint32, pcbData: ptr uint32, Flags: uint32, pszDirectory: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegNotifyChangeKeyValue*(hKey: HKEY, bWatchSubtree: BOOL, dwNotifyFilter: uint32, hEvent: HANDLE, fAsynchronous: BOOL): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenCurrentUser*(samDesired: REGSAM, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenKeyA*(hKey: HKEY, lpSubKey: PCSTR, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenKeyExA*(hKey: HKEY, lpSubKey: PCSTR, ulOptions: uint32, samDesired: REGSAM, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenKeyExW*(hKey: HKEY, lpSubKey: PCWSTR, ulOptions: uint32, samDesired: REGSAM, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenKeyTransactedA*(hKey: HKEY, lpSubKey: PCSTR, ulOptions: uint32, samDesired: REGSAM, phkResult: ptr HKEY, hTransaction: HANDLE, pExtendedParemeter: pointer): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenKeyTransactedW*(hKey: HKEY, lpSubKey: PCWSTR, ulOptions: uint32, samDesired: REGSAM, phkResult: ptr HKEY, hTransaction: HANDLE, pExtendedParemeter: pointer): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenKeyW*(hKey: HKEY, lpSubKey: PCWSTR, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOpenUserClassesRoot*(hToken: HANDLE, dwOptions: uint32, samDesired: REGSAM, phkResult: ptr HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegOverridePredefKey*(hKey: HKEY, hNewHKey: HKEY): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryInfoKeyA*(hKey: HKEY, lpClass: PSTR, lpcchClass: ptr uint32, lpReserved: ptr uint32, lpcSubKeys: ptr uint32, lpcbMaxSubKeyLen: ptr uint32, lpcbMaxClassLen: ptr uint32, lpcValues: ptr uint32, lpcbMaxValueNameLen: ptr uint32, lpcbMaxValueLen: ptr uint32, lpcbSecurityDescriptor: ptr uint32, lpftLastWriteTime: ptr FILETIME): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryInfoKeyW*(hKey: HKEY, lpClass: PWSTR, lpcchClass: ptr uint32, lpReserved: ptr uint32, lpcSubKeys: ptr uint32, lpcbMaxSubKeyLen: ptr uint32, lpcbMaxClassLen: ptr uint32, lpcValues: ptr uint32, lpcbMaxValueNameLen: ptr uint32, lpcbMaxValueLen: ptr uint32, lpcbSecurityDescriptor: ptr uint32, lpftLastWriteTime: ptr FILETIME): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryMultipleValuesA*(hKey: HKEY, val_list: ptr VALENTA, num_vals: uint32, lpValueBuf: PSTR, ldwTotsize: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryMultipleValuesW*(hKey: HKEY, val_list: ptr VALENTW, num_vals: uint32, lpValueBuf: PWSTR, ldwTotsize: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryReflectionKey*(hBase: HKEY, bIsReflectionDisabled: ptr BOOL): int32 {.sideEffect, importc, stdcall.}
proc RegQueryValueA*(hKey: HKEY, lpSubKey: PCSTR, lpData: PSTR, lpcbData: ptr int32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryValueExA*(hKey: HKEY, lpValueName: PCSTR, lpReserved: ptr uint32, lpType: ptr uint32, lpData: ptr uint8, lpcbData: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryValueExW*(hKey: HKEY, lpValueName: PCWSTR, lpReserved: ptr uint32, lpType: ptr uint32, lpData: ptr uint8, lpcbData: ptr uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegQueryValueW*(hKey: HKEY, lpSubKey: PCWSTR, lpData: PWSTR, lpcbData: ptr int32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegRenameKey*(hKey: HKEY, lpSubKeyName: PCWSTR, lpNewKeyName: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegReplaceKeyA*(hKey: HKEY, lpSubKey: PCSTR, lpNewFile: PCSTR, lpOldFile: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegReplaceKeyW*(hKey: HKEY, lpSubKey: PCWSTR, lpNewFile: PCWSTR, lpOldFile: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegRestoreKeyA*(hKey: HKEY, lpFile: PCSTR, dwFlags: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegRestoreKeyW*(hKey: HKEY, lpFile: PCWSTR, dwFlags: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSaveKeyA*(hKey: HKEY, lpFile: PCSTR, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSaveKeyExA*(hKey: HKEY, lpFile: PCSTR, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, Flags: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSaveKeyExW*(hKey: HKEY, lpFile: PCWSTR, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES, Flags: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSaveKeyW*(hKey: HKEY, lpFile: PCWSTR, lpSecurityAttributes: ptr SECURITY_ATTRIBUTES): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetKeySecurity*(hKey: HKEY, SecurityInformation: SECURITY_INFORMATION, pSecurityDescriptor: PSECURITY_DESCRIPTOR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetKeyValueA*(hKey: HKEY, lpSubKey: PCSTR, lpValueName: PCSTR, dwType: uint32, lpData: pointer, cbData: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetKeyValueW*(hKey: HKEY, lpSubKey: PCWSTR, lpValueName: PCWSTR, dwType: uint32, lpData: pointer, cbData: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetValueA*(hKey: HKEY, lpSubKey: PCSTR, dwType: uint32, lpData: PCSTR, cbData: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetValueExA*(hKey: HKEY, lpValueName: PCSTR, Reserved: uint32, dwType: uint32, lpData: ptr uint8, cbData: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetValueExW*(hKey: HKEY, lpValueName: PCWSTR, Reserved: uint32, dwType: uint32, lpData: ptr uint8, cbData: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegSetValueW*(hKey: HKEY, lpSubKey: PCWSTR, dwType: uint32, lpData: PCWSTR, cbData: uint32): LSTATUS {.sideEffect, importc, stdcall.}
proc RegUnLoadKeyA*(hKey: HKEY, lpSubKey: PCSTR): LSTATUS {.sideEffect, importc, stdcall.}
proc RegUnLoadKeyW*(hKey: HKEY, lpSubKey: PCWSTR): LSTATUS {.sideEffect, importc, stdcall.}
{.pop.}
