# generated by winmd2nim from Windows.Win32.winmd — winsock2 (do not edit)
import ./[winnt, ws2def, windef, minwindef, wtypesbase, minwinbase, qos, guiddef, inaddr]
export winnt, ws2def, windef, minwindef, wtypesbase, minwinbase, qos, guiddef, inaddr

type

  # structs
  AFPROTOCOLS* {.completeStruct.} = object
    iAddressFamily*: int32
    iProtocol*: int32
  QOS* {.completeStruct.} = object
    SendingFlowspec*: FLOWSPEC
    ReceivingFlowspec*: FLOWSPEC
    ProviderSpecific*: WSABUF
  SOCK_NOTIFY_REGISTRATION* {.completeStruct.} = object
    socket*: SOCKET
    completionKey*: pointer
    eventFilter*: uint16
    operation*: uint8
    triggerFlags*: uint8
    registrationResult*: uint32
  WSACOMPLETION* {.completeStruct.} = object
    Type*: WSACOMPLETIONTYPE
    Parameters*: WSACOMPLETION_1
  WSACOMPLETION_1* {.completeStruct, union.} = object
    WindowMessage*: WSACOMPLETION_1_0
    Event*: WSACOMPLETION_1_1
    Apc*: WSACOMPLETION_1_2
    Port*: WSACOMPLETION_1_3
  WSACOMPLETION_1_0* {.completeStruct.} = object
    hWnd*: HWND
    uMsg*: uint32
    context*: WPARAM
  WSACOMPLETION_1_1* {.completeStruct.} = object
    lpOverlapped*: LPWSAOVERLAPPED
  WSACOMPLETION_1_2* {.completeStruct.} = object
    lpOverlapped*: LPWSAOVERLAPPED
    lpfnCompletionProc*: LPWSAOVERLAPPED_COMPLETION_ROUTINE
  WSACOMPLETION_1_3* {.completeStruct.} = object
    lpOverlapped*: LPWSAOVERLAPPED
    hPort*: HANDLE
    Key*: uint
  WSADATA_I386* {.completeStruct.} = object
    wVersion*: uint16
    wHighVersion*: uint16
    szDescription*: array[257, int8]
    szSystemStatus*: array[129, int8]
    iMaxSockets*: uint16
    iMaxUdpDg*: uint16
    lpVendorInfo*: ptr int8
  WSADATA_AMD64_ARM64* {.completeStruct.} = object
    wVersion*: uint16
    wHighVersion*: uint16
    iMaxSockets*: uint16
    iMaxUdpDg*: uint16
    lpVendorInfo*: ptr int8
    szDescription*: array[257, int8]
    szSystemStatus*: array[129, int8]
  WSANAMESPACE_INFOA* {.completeStruct.} = object
    NSProviderId*: GUID
    dwNameSpace*: uint32
    fActive*: BOOL
    dwVersion*: uint32
    lpszIdentifier*: PSTR
  WSANAMESPACE_INFOEXA* {.completeStruct.} = object
    NSProviderId*: GUID
    dwNameSpace*: uint32
    fActive*: BOOL
    dwVersion*: uint32
    lpszIdentifier*: PSTR
    ProviderSpecific*: BLOB
  WSANAMESPACE_INFOEXW* {.completeStruct.} = object
    NSProviderId*: GUID
    dwNameSpace*: uint32
    fActive*: BOOL
    dwVersion*: uint32
    lpszIdentifier*: PWSTR
    ProviderSpecific*: BLOB
  WSANAMESPACE_INFOW* {.completeStruct.} = object
    NSProviderId*: GUID
    dwNameSpace*: uint32
    fActive*: BOOL
    dwVersion*: uint32
    lpszIdentifier*: PWSTR
  WSANETWORKEVENTS* {.completeStruct.} = object
    lNetworkEvents*: int32
    iErrorCode*: array[10, int32]
  WSANSCLASSINFOA* {.completeStruct.} = object
    lpszName*: PSTR
    dwNameSpace*: uint32
    dwValueType*: uint32
    dwValueSize*: uint32
    lpValue*: pointer
  WSANSCLASSINFOW* {.completeStruct.} = object
    lpszName*: PWSTR
    dwNameSpace*: uint32
    dwValueType*: uint32
    dwValueSize*: uint32
    lpValue*: pointer
  WSAPOLLFD* {.completeStruct.} = object
    fd*: SOCKET
    events*: int16
    revents*: int16
  WSAPROTOCOLCHAIN* {.completeStruct.} = object
    ChainLen*: int32
    ChainEntries*: array[7, uint32]
  WSAPROTOCOL_INFOA* {.completeStruct.} = object
    dwServiceFlags1*: uint32
    dwServiceFlags2*: uint32
    dwServiceFlags3*: uint32
    dwServiceFlags4*: uint32
    dwProviderFlags*: uint32
    ProviderId*: GUID
    dwCatalogEntryId*: uint32
    ProtocolChain*: WSAPROTOCOLCHAIN
    iVersion*: int32
    iAddressFamily*: int32
    iMaxSockAddr*: int32
    iMinSockAddr*: int32
    iSocketType*: int32
    iProtocol*: int32
    iProtocolMaxOffset*: int32
    iNetworkByteOrder*: int32
    iSecurityScheme*: int32
    dwMessageSize*: uint32
    dwProviderReserved*: uint32
    szProtocol*: array[256, int8]
  WSAPROTOCOL_INFOW* {.completeStruct.} = object
    dwServiceFlags1*: uint32
    dwServiceFlags2*: uint32
    dwServiceFlags3*: uint32
    dwServiceFlags4*: uint32
    dwProviderFlags*: uint32
    ProviderId*: GUID
    dwCatalogEntryId*: uint32
    ProtocolChain*: WSAPROTOCOLCHAIN
    iVersion*: int32
    iAddressFamily*: int32
    iMaxSockAddr*: int32
    iMinSockAddr*: int32
    iSocketType*: int32
    iProtocol*: int32
    iProtocolMaxOffset*: int32
    iNetworkByteOrder*: int32
    iSecurityScheme*: int32
    dwMessageSize*: uint32
    dwProviderReserved*: uint32
    szProtocol*: array[256, uint16]
  WSAQUERYSET2A* {.completeStruct.} = object
    dwSize*: uint32
    lpszServiceInstanceName*: PSTR
    lpVersion*: LPWSAVERSION
    lpszComment*: PSTR
    dwNameSpace*: uint32
    lpNSProviderId*: LPGUID
    lpszContext*: PSTR
    dwNumberOfProtocols*: uint32
    lpafpProtocols*: LPAFPROTOCOLS
    lpszQueryString*: PSTR
    dwNumberOfCsAddrs*: uint32
    lpcsaBuffer*: LPCSADDR_INFO
    dwOutputFlags*: uint32
    lpBlob*: LPBLOB
  WSAQUERYSET2W* {.completeStruct.} = object
    dwSize*: uint32
    lpszServiceInstanceName*: PWSTR
    lpVersion*: LPWSAVERSION
    lpszComment*: PWSTR
    dwNameSpace*: uint32
    lpNSProviderId*: LPGUID
    lpszContext*: PWSTR
    dwNumberOfProtocols*: uint32
    lpafpProtocols*: LPAFPROTOCOLS
    lpszQueryString*: PWSTR
    dwNumberOfCsAddrs*: uint32
    lpcsaBuffer*: LPCSADDR_INFO
    dwOutputFlags*: uint32
    lpBlob*: LPBLOB
  WSAQUERYSETA* {.completeStruct.} = object
    dwSize*: uint32
    lpszServiceInstanceName*: PSTR
    lpServiceClassId*: LPGUID
    lpVersion*: LPWSAVERSION
    lpszComment*: PSTR
    dwNameSpace*: uint32
    lpNSProviderId*: LPGUID
    lpszContext*: PSTR
    dwNumberOfProtocols*: uint32
    lpafpProtocols*: LPAFPROTOCOLS
    lpszQueryString*: PSTR
    dwNumberOfCsAddrs*: uint32
    lpcsaBuffer*: LPCSADDR_INFO
    dwOutputFlags*: uint32
    lpBlob*: LPBLOB
  WSAQUERYSETW* {.completeStruct.} = object
    dwSize*: uint32
    lpszServiceInstanceName*: PWSTR
    lpServiceClassId*: LPGUID
    lpVersion*: LPWSAVERSION
    lpszComment*: PWSTR
    dwNameSpace*: uint32
    lpNSProviderId*: LPGUID
    lpszContext*: PWSTR
    dwNumberOfProtocols*: uint32
    lpafpProtocols*: LPAFPROTOCOLS
    lpszQueryString*: PWSTR
    dwNumberOfCsAddrs*: uint32
    lpcsaBuffer*: LPCSADDR_INFO
    dwOutputFlags*: uint32
    lpBlob*: LPBLOB
  WSASERVICECLASSINFOA* {.completeStruct.} = object
    lpServiceClassId*: LPGUID
    lpszServiceClassName*: PSTR
    dwCount*: uint32
    lpClassInfos*: LPWSANSCLASSINFOA
  WSASERVICECLASSINFOW* {.completeStruct.} = object
    lpServiceClassId*: LPGUID
    lpszServiceClassName*: PWSTR
    dwCount*: uint32
    lpClassInfos*: LPWSANSCLASSINFOW
  WSAVERSION* {.completeStruct.} = object
    dwVersion*: uint32
    ecHow*: WSAECOMPARATOR
  fd_set* {.completeStruct.} = object
    fd_count*: u_int_2
    fd_array*: array[64, SOCKET]
  hostent* {.completeStruct.} = object
    h_name*: ptr int8
    h_aliases*: ptr ptr int8
    h_addrtype*: int16
    h_length*: int16
    h_addr_list*: ptr ptr int8
  linger* {.completeStruct.} = object
    l_onoff*: u_short
    l_linger*: u_short
  netent* {.completeStruct.} = object
    n_name*: ptr int8
    n_aliases*: ptr ptr int8
    n_addrtype*: int16
    n_net*: u_long
  protoent* {.completeStruct.} = object
    p_name*: ptr int8
    p_aliases*: ptr ptr int8
    p_proto*: int16
  servent_I386* {.completeStruct.} = object
    s_name*: ptr int8
    s_aliases*: ptr ptr int8
    s_port*: int16
    s_proto*: ptr int8
  servent_AMD64_ARM64* {.completeStruct.} = object
    s_name*: ptr int8
    s_aliases*: ptr ptr int8
    s_proto*: ptr int8
    s_port*: int16
  sockproto* {.completeStruct.} = object
    sp_family*: u_short
    sp_protocol*: u_short
  timeval* {.completeStruct.} = object
    tv_sec*: int32
    tv_usec*: int32

  # typdefs
  FD_SET* = fd_set
  GROUP* = distinct uint32
  HOSTENT* = hostent
  LINGER* = linger
  LPAFPROTOCOLS* = ptr AFPROTOCOLS
  LPFD_SET* = ptr fd_set
  LPHOSTENT* = ptr hostent
  LPLINGER* = ptr linger
  LPPROTOENT* = ptr protoent
  LPQOS* = ptr QOS
  LPSOCKADDR_IN* = ptr SOCKADDR_IN
  LPTIMEVAL* = ptr timeval
  LPWSACOMPLETION* = ptr WSACOMPLETION
  LPWSACOMPLETIONTYPE* = distinct ptr WSACOMPLETIONTYPE
  LPWSAECOMPARATOR* = distinct ptr WSAECOMPARATOR
  LPWSAESETSERVICEOP* = distinct ptr WSAESETSERVICEOP
  LPWSANAMESPACE_INFOA* = ptr WSANAMESPACE_INFOA
  LPWSANAMESPACE_INFOEXA* = ptr WSANAMESPACE_INFOEXA
  LPWSANAMESPACE_INFOEXW* = ptr WSANAMESPACE_INFOEXW
  LPWSANAMESPACE_INFOW* = ptr WSANAMESPACE_INFOW
  LPWSANETWORKEVENTS* = ptr WSANETWORKEVENTS
  LPWSANSCLASSINFOA* = ptr WSANSCLASSINFOA
  LPWSANSCLASSINFOW* = ptr WSANSCLASSINFOW
  LPWSAOVERLAPPED* = ptr OVERLAPPED
  LPWSAPOLLFD* = ptr WSAPOLLFD
  LPWSAPROTOCOLCHAIN* = ptr WSAPROTOCOLCHAIN
  LPWSAPROTOCOL_INFOA* = ptr WSAPROTOCOL_INFOA
  LPWSAPROTOCOL_INFOW* = ptr WSAPROTOCOL_INFOW
  LPWSAQUERYSET2A* = ptr WSAQUERYSET2A
  LPWSAQUERYSET2W* = ptr WSAQUERYSET2W
  LPWSAQUERYSETA* = ptr WSAQUERYSETA
  LPWSAQUERYSETW* = ptr WSAQUERYSETW
  LPWSASERVICECLASSINFOA* = ptr WSASERVICECLASSINFOA
  LPWSASERVICECLASSINFOW* = ptr WSASERVICECLASSINFOW
  LPWSAVERSION* = ptr WSAVERSION
  PAFPROTOCOLS* = ptr AFPROTOCOLS
  PFD_SET* = ptr fd_set
  PHOSTENT* = ptr hostent
  PLINGER* = ptr linger
  PPROTOENT* = ptr protoent
  PROTOENT* = protoent
  PTIMEVAL* = ptr timeval
  PWSACOMPLETION* = ptr WSACOMPLETION
  PWSACOMPLETIONTYPE* = distinct ptr WSACOMPLETIONTYPE
  PWSAECOMPARATOR* = distinct ptr WSAECOMPARATOR
  PWSAESETSERVICEOP* = distinct ptr WSAESETSERVICEOP
  PWSANAMESPACE_INFOA* = ptr WSANAMESPACE_INFOA
  PWSANAMESPACE_INFOEXA* = ptr WSANAMESPACE_INFOEXA
  PWSANAMESPACE_INFOEXW* = ptr WSANAMESPACE_INFOEXW
  PWSANAMESPACE_INFOW* = ptr WSANAMESPACE_INFOW
  PWSANSCLASSINFOA* = ptr WSANSCLASSINFOA
  PWSANSCLASSINFOW* = ptr WSANSCLASSINFOW
  PWSAPOLLFD* = ptr WSAPOLLFD
  PWSAQUERYSET2A* = ptr WSAQUERYSET2A
  PWSAQUERYSET2W* = ptr WSAQUERYSET2W
  PWSAQUERYSETA* = ptr WSAQUERYSETA
  PWSAQUERYSETW* = ptr WSAQUERYSETW
  PWSASERVICECLASSINFOA* = ptr WSASERVICECLASSINFOA
  PWSASERVICECLASSINFOW* = ptr WSASERVICECLASSINFOW
  PWSAVERSION* = ptr WSAVERSION
  SOCKET* = distinct uint
  TIMEVAL* = timeval
  u_char* = distinct uint8
  u_int_2* = distinct uint32
  u_int64_2* = distinct uint64
  u_long* = distinct uint32
  u_short* = distinct uint16

  # unscoped enums 
  WSACOMPLETIONTYPE* = int32
  WSAECOMPARATOR* = int32
  WSAESETSERVICEOP* = int32

  # delegates
  LPCONDITIONPROC* = proc (arg_1: ptr WSABUF, arg_2: ptr WSABUF, arg_3: ptr QOS, arg_4: ptr QOS, arg_5: ptr WSABUF, arg_6: ptr WSABUF, arg_7: ptr GROUP, arg_8: uint): int32 {.stdcall.}
  LPWSAOVERLAPPED_COMPLETION_ROUTINE* = proc (arg_1: uint32, arg_2: uint32, arg_3: ptr OVERLAPPED, arg_4: uint32): void {.stdcall.}

when defined(i386):
  type WSADATA* = WSADATA_I386
elif defined(amd64) or defined(arm64):
  type WSADATA* = WSADATA_AMD64_ARM64
else:
  type WSADATA* = WSADATA_I386
when defined(i386):
  type servent* = servent_I386
elif defined(amd64) or defined(arm64):
  type servent* = servent_AMD64_ARM64
else:
  type servent* = servent_I386

type

  # typdefs
  LPSERVENT* = ptr servent
  LPWSADATA* = ptr WSADATA
  PSERVENT* = ptr servent
  SERVENT* = servent

const
  # free constants
  ADDR_ANY*: uint32 = 0x0'u32
  BASE_PROTOCOL*: int32 = 1'i32
  BIGENDIAN*: int32 = 0'i32
  CF_ACCEPT*: int32 = 0'i32
  CF_DEFER*: int32 = 2'i32
  CF_REJECT*: int32 = 1'i32
  FD_ACCEPT*: int32 = 8'i32
  FD_ACCEPT_BIT*: int32 = 3'i32
  FD_ADDRESS_LIST_CHANGE*: int32 = 512'i32
  FD_ADDRESS_LIST_CHANGE_BIT*: int32 = 9'i32
  FD_ALL_EVENTS*: int32 = 1023'i32
  FD_CLOSE*: int32 = 32'i32
  FD_CLOSE_BIT*: int32 = 5'i32
  FD_CONNECT*: int32 = 16'i32
  FD_CONNECT_BIT*: int32 = 4'i32
  FD_GROUP_QOS*: int32 = 128'i32
  FD_GROUP_QOS_BIT*: int32 = 7'i32
  FD_MAX_EVENTS*: int32 = 10'i32
  FD_OOB*: int32 = 4'i32
  FD_OOB_BIT*: int32 = 2'i32
  FD_QOS*: int32 = 64'i32
  FD_QOS_BIT*: int32 = 6'i32
  FD_READ*: int32 = 1'i32
  FD_READ_BIT*: int32 = 0'i32
  FD_ROUTING_INTERFACE_CHANGE*: int32 = 256'i32
  FD_ROUTING_INTERFACE_CHANGE_BIT*: int32 = 8'i32
  FD_SETSIZE*: int32 = 64'i32
  FD_WRITE*: int32 = 2'i32
  FD_WRITE_BIT*: int32 = 1'i32
  FIOASYNC*: uint32 = 0x8004667d'u32
  FIONBIO*: uint32 = 0x8004667e'u32
  FIONREAD*: int32 = 1074030207'i32
  FROM_PROTOCOL_INFO*: int32 = -1'i32
  HOST_NOT_FOUND*: int32 = 11001'i32
  IMPLINK_HIGHEXPER*: int32 = 158'i32
  IMPLINK_IP*: int32 = 155'i32
  IMPLINK_LOWEXPER*: int32 = 156'i32
  INCL_WINSOCK_API_PROTOTYPES*: int32 = 1'i32
  INCL_WINSOCK_API_TYPEDEFS*: int32 = 0'i32
  INVALID_SOCKET*: SOCKET = SOCKET(0xffffffffffffffff'u)
  JL_BOTH*: int32 = 4'i32
  JL_RECEIVER_ONLY*: int32 = 2'i32
  JL_SENDER_ONLY*: int32 = 1'i32
  LAYERED_PROTOCOL*: int32 = 0'i32
  LITTLEENDIAN*: int32 = 1'i32
  LUP_ADDRCONFIG*: int32 = 1048576'i32
  LUP_API_ANSI*: int32 = 16777216'i32
  LUP_CONTAINERS*: int32 = 2'i32
  LUP_DEEP*: int32 = 1'i32
  LUP_DISABLE_IDN_ENCODING*: int32 = 8388608'i32
  LUP_DNS_ONLY*: int32 = 131072'i32
  LUP_DUAL_ADDR*: int32 = 2097152'i32
  LUP_EXCLUSIVE_CUSTOM_SERVERS*: int32 = 134217728'i32
  LUP_EXTENDED_QUERYSET*: int32 = 33554432'i32
  LUP_FILESERVER*: int32 = 4194304'i32
  LUP_FLUSHCACHE*: int32 = 4096'i32
  LUP_FLUSHPREVIOUS*: int32 = 8192'i32
  LUP_FORCE_CLEAR_TEXT*: int32 = 1073741824'i32
  LUP_NEAREST*: int32 = 8'i32
  LUP_NOCONTAINERS*: int32 = 4'i32
  LUP_NON_AUTHORITATIVE*: int32 = 16384'i32
  LUP_REQUIRE_SECURE*: int32 = 268435456'i32
  LUP_RESERVED_UNUSED*: int32 = 524288'i32
  LUP_RESOLUTION_HANDLE*: uint32 = 0x80000000'u32
  LUP_RES_SERVICE*: int32 = 32768'i32
  LUP_RETURN_ADDR*: int32 = 256'i32
  LUP_RETURN_ALIASES*: int32 = 1024'i32
  LUP_RETURN_ALL*: int32 = 4080'i32
  LUP_RETURN_BLOB*: int32 = 512'i32
  LUP_RETURN_COMMENT*: int32 = 128'i32
  LUP_RETURN_NAME*: int32 = 16'i32
  LUP_RETURN_PREFERRED_NAMES*: int32 = 65536'i32
  LUP_RETURN_QUERY_STRING*: int32 = 2048'i32
  LUP_RETURN_RESPONSE_FLAGS*: int32 = 262144'i32
  LUP_RETURN_TTL*: int32 = 536870912'i32
  LUP_RETURN_TYPE*: int32 = 32'i32
  LUP_RETURN_VERSION*: int32 = 64'i32
  LUP_SECURE*: int32 = 32768'i32
  LUP_SECURE_WITH_FALLBACK*: int32 = 67108864'i32
  MAXGETHOSTSTRUCT*: int32 = 1024'i32
  MAX_PROTOCOL_CHAIN*: int32 = 7'i32
  MSG_DONTROUTE*: int32 = 4'i32
  MSG_INTERRUPT*: int32 = 16'i32
  MSG_MAXIOVLEN*: int32 = 16'i32
  MSG_OOB*: int32 = 1'i32
  MSG_PARTIAL*: int32 = 32768'i32
  MSG_PEEK*: int32 = 2'i32
  MSG_PUSH_IMMEDIATE*: int32 = 32'i32
  MSG_WAITALL*: int32 = 8'i32
  NO_ADDRESS*: int32 = 11004'i32
  NO_DATA*: int32 = 11004'i32
  NO_RECOVERY*: int32 = 11003'i32
  NS_LOCALNAME*: int32 = 19'i32
  PFL_HIDDEN*: int32 = 4'i32
  PFL_MATCHES_PROTOCOL_ZERO*: int32 = 8'i32
  PFL_MULTIPLE_PROTO_ENTRIES*: int32 = 1'i32
  PFL_NETWORKDIRECT_PROVIDER*: int32 = 16'i32
  PFL_RECOMMENDED_PROTO_ENTRY*: int32 = 2'i32
  PF_APPLETALK*: int32 = 16'i32
  PF_ATM*: int32 = 22'i32
  PF_BAN*: int32 = 21'i32
  PF_BTH*: int32 = 32'i32
  PF_CCITT*: int32 = 10'i32
  PF_CHAOS*: int32 = 5'i32
  PF_DATAKIT*: int32 = 9'i32
  PF_DECnet*: int32 = 12'i32
  PF_DLI*: int32 = 13'i32
  PF_ECMA*: int32 = 8'i32
  PF_FIREFOX*: int32 = 19'i32
  PF_HYLINK*: int32 = 15'i32
  PF_IMPLINK*: int32 = 3'i32
  PF_INET*: int32 = 2'i32
  PF_INET6*: int32 = 23'i32
  PF_IPX*: int32 = 6'i32
  PF_ISO*: int32 = 7'i32
  PF_LAT*: int32 = 14'i32
  PF_MAX*: int32 = 35'i32
  PF_NS*: int32 = 6'i32
  PF_OSI*: int32 = 7'i32
  PF_PUP*: int32 = 4'i32
  PF_SNA*: int32 = 11'i32
  PF_UNIX*: int32 = 1'i32
  PF_UNKNOWN1*: int32 = 20'i32
  PF_UNSPEC*: int32 = 0'i32
  PF_VOICEVIEW*: int32 = 18'i32
  POLLERR*: int32 = 1'i32
  POLLHUP*: int32 = 2'i32
  POLLIN*: int32 = 768'i32
  POLLNVAL*: int32 = 4'i32
  POLLOUT*: int32 = 16'i32
  POLLPRI*: int32 = 1024'i32
  POLLRDBAND*: int32 = 512'i32
  POLLRDNORM*: int32 = 256'i32
  POLLWRBAND*: int32 = 32'i32
  POLLWRNORM*: int32 = 16'i32
  PVD_CONFIG*: int32 = 12289'i32
  RESULT_IS_ADDED*: int32 = 16'i32
  RESULT_IS_ALIAS*: int32 = 1'i32
  RESULT_IS_CHANGED*: int32 = 32'i32
  RESULT_IS_DELETED*: int32 = 64'i32
  RES_FLUSH_CACHE*: int32 = 2'i32
  RES_SERVICE*: int32 = 4'i32
  RES_UNUSED_1*: int32 = 1'i32
  SD_BOTH*: int32 = 2'i32
  SD_RECEIVE*: int32 = 0'i32
  SD_SEND*: int32 = 1'i32
  SECURITY_PROTOCOL_NONE*: int32 = 0'i32
  SERVICE_MULTIPLE*: int32 = 1'i32
  SERVICE_TYPE_VALUE_IPXPORTA*: string = "IpxSocket"
  # SERVICE_TYPE_VALUE_IPXPORTW = "IpxSocket"  # TODO: wide string constant (utf-16)
  SERVICE_TYPE_VALUE_OBJECTIDA*: string = "ObjectId"
  # SERVICE_TYPE_VALUE_OBJECTIDW = "ObjectId"  # TODO: wide string constant (utf-16)
  SERVICE_TYPE_VALUE_SAPIDA*: string = "SapId"
  # SERVICE_TYPE_VALUE_SAPIDW = "SapId"  # TODO: wide string constant (utf-16)
  SERVICE_TYPE_VALUE_TCPPORTA*: string = "TcpPort"
  # SERVICE_TYPE_VALUE_TCPPORTW = "TcpPort"  # TODO: wide string constant (utf-16)
  SERVICE_TYPE_VALUE_UDPPORTA*: string = "UdpPort"
  # SERVICE_TYPE_VALUE_UDPPORTW = "UdpPort"  # TODO: wide string constant (utf-16)
  SG_CONSTRAINED_GROUP*: int32 = 2'i32
  SG_UNCONSTRAINED_GROUP*: int32 = 1'i32
  SIOCATMARK*: int32 = 1074033415'i32
  SIOCGHIWAT*: int32 = 1074033409'i32
  SIOCGLOWAT*: int32 = 1074033411'i32
  SIOCSHIWAT*: uint32 = 0x80047300'u32
  SIOCSLOWAT*: uint32 = 0x80047302'u32
  SIO_NSP_NOTIFY_CHANGE*: uint32 = 0x88000019'u32
  SOCKET_ERROR*: int32 = -1'i32
  SOCK_NOTIFY_EVENTS_ALL*: int32 = 199'i32
  SOCK_NOTIFY_EVENT_ERR*: int32 = 64'i32
  SOCK_NOTIFY_EVENT_HANGUP*: int32 = 4'i32
  SOCK_NOTIFY_EVENT_IN*: int32 = 1'i32
  SOCK_NOTIFY_EVENT_OUT*: int32 = 2'i32
  SOCK_NOTIFY_EVENT_REMOVE*: int32 = 128'i32
  SOCK_NOTIFY_OP_DISABLE*: int32 = 2'i32
  SOCK_NOTIFY_OP_ENABLE*: int32 = 1'i32
  SOCK_NOTIFY_OP_NONE*: int32 = 0'i32
  SOCK_NOTIFY_OP_REMOVE*: int32 = 4'i32
  SOCK_NOTIFY_REGISTER_EVENTS_ALL*: int32 = 7'i32
  SOCK_NOTIFY_REGISTER_EVENT_HANGUP*: int32 = 4'i32
  SOCK_NOTIFY_REGISTER_EVENT_IN*: int32 = 1'i32
  SOCK_NOTIFY_REGISTER_EVENT_NONE*: int32 = 0'i32
  SOCK_NOTIFY_REGISTER_EVENT_OUT*: int32 = 2'i32
  SOCK_NOTIFY_TRIGGER_ALL*: int32 = 15'i32
  SOCK_NOTIFY_TRIGGER_EDGE*: int32 = 8'i32
  SOCK_NOTIFY_TRIGGER_LEVEL*: int32 = 4'i32
  SOCK_NOTIFY_TRIGGER_ONESHOT*: int32 = 1'i32
  SOCK_NOTIFY_TRIGGER_PERSISTENT*: int32 = 2'i32
  SOMAXCONN*: int32 = 2147483647'i32
  SO_PROTOCOL_INFO*: int32 = 8196'i32
  SO_PROTOCOL_INFOA*: int32 = 8196'i32
  SO_PROTOCOL_INFOW*: int32 = 8197'i32
  TH_NETDEV*: int32 = 1'i32
  TH_TAPI*: int32 = 2'i32
  TRY_AGAIN*: int32 = 11002'i32
  WINSOCK_VERSION*: uint32 = 0x202'u32
  WSADESCRIPTION_LEN*: int32 = 256'i32
  WSANO_ADDRESS*: int32 = 11004'i32
  WSAPROTOCOL_LEN*: int32 = 255'i32
  WSASYS_STATUS_LEN*: int32 = 128'i32
  WSA_FLAG_ACCESS_SYSTEM_SECURITY*: int32 = 64'i32
  WSA_FLAG_MULTIPOINT_C_LEAF*: int32 = 4'i32
  WSA_FLAG_MULTIPOINT_C_ROOT*: int32 = 2'i32
  WSA_FLAG_MULTIPOINT_D_LEAF*: int32 = 16'i32
  WSA_FLAG_MULTIPOINT_D_ROOT*: int32 = 8'i32
  WSA_FLAG_NO_HANDLE_INHERIT*: int32 = 128'i32
  WSA_FLAG_OVERLAPPED*: int32 = 1'i32
  WSA_FLAG_REGISTERED_IO*: int32 = 256'i32
  WSA_INFINITE*: uint32 = 0xffffffff'u32
  WSA_INVALID_HANDLE*: int32 = 6'i32
  WSA_INVALID_PARAMETER*: int32 = 87'i32
  WSA_IO_INCOMPLETE*: int32 = 996'i32
  WSA_IO_PENDING*: int32 = 997'i32
  WSA_MAXIMUM_WAIT_EVENTS*: int32 = 64'i32
  WSA_NOT_ENOUGH_MEMORY*: int32 = 8'i32
  WSA_OPERATION_ABORTED*: int32 = 995'i32
  WSA_WAIT_EVENT_0*: int32 = 0'i32
  WSA_WAIT_FAILED*: uint32 = 0xffffffff'u32
  WSA_WAIT_IO_COMPLETION*: int32 = 192'i32
  WSA_WAIT_TIMEOUT*: int32 = 258'i32
  XP1_CONNECTIONLESS*: int32 = 1'i32
  XP1_CONNECT_DATA*: int32 = 128'i32
  XP1_DISCONNECT_DATA*: int32 = 256'i32
  XP1_EXPEDITED_DATA*: int32 = 64'i32
  XP1_GRACEFUL_CLOSE*: int32 = 32'i32
  XP1_GUARANTEED_DELIVERY*: int32 = 2'i32
  XP1_GUARANTEED_ORDER*: int32 = 4'i32
  XP1_IFS_HANDLES*: int32 = 131072'i32
  XP1_INTERRUPT*: int32 = 16384'i32
  XP1_MESSAGE_ORIENTED*: int32 = 8'i32
  XP1_MULTIPOINT_CONTROL_PLANE*: int32 = 2048'i32
  XP1_MULTIPOINT_DATA_PLANE*: int32 = 4096'i32
  XP1_PARTIAL_MESSAGE*: int32 = 262144'i32
  XP1_PSEUDO_STREAM*: int32 = 16'i32
  XP1_QOS_SUPPORTED*: int32 = 8192'i32
  XP1_SAN_SUPPORT_SDP*: int32 = 524288'i32
  XP1_SUPPORT_BROADCAST*: int32 = 512'i32
  XP1_SUPPORT_MULTIPOINT*: int32 = 1024'i32
  XP1_UNI_RECV*: int32 = 65536'i32
  XP1_UNI_SEND*: int32 = 32768'i32

  # unscoped enum members
  NSP_NOTIFY_IMMEDIATELY*: WSACOMPLETIONTYPE = 0'i32
  NSP_NOTIFY_HWND*: WSACOMPLETIONTYPE = 1'i32
  NSP_NOTIFY_EVENT*: WSACOMPLETIONTYPE = 2'i32
  NSP_NOTIFY_PORT*: WSACOMPLETIONTYPE = 3'i32
  NSP_NOTIFY_APC*: WSACOMPLETIONTYPE = 4'i32
  COMP_EQUAL*: WSAECOMPARATOR = 0'i32
  COMP_NOTLESS*: WSAECOMPARATOR = 1'i32
  RNRSERVICE_REGISTER*: WSAESETSERVICEOP = 0'i32
  RNRSERVICE_DEREGISTER*: WSAESETSERVICEOP = 1'i32
  RNRSERVICE_DELETE*: WSAESETSERVICEOP = 2'i32

{.push dynlib: "ws2_32".}
proc GetHostNameW*(name: PWSTR, namelen: int32): int32 {.sideEffect, importc, stdcall.}
proc ProcessSocketNotifications*(completionPort: HANDLE, registrationCount: uint32, registrationInfos: ptr SOCK_NOTIFY_REGISTRATION, timeoutMs: uint32, completionCount: uint32, completionPortEntries: ptr OVERLAPPED_ENTRY, receivedEntryCount: ptr uint32): uint32 {.sideEffect, importc, stdcall.}
proc WSAAccept*(s: SOCKET, `addr`: ptr SOCKADDR, addrlen: ptr int32, lpfnCondition: LPCONDITIONPROC, dwCallbackData: uint): SOCKET {.sideEffect, importc, stdcall.}
proc WSAAddressToStringA*(lpsaAddress: ptr SOCKADDR, dwAddressLength: uint32, lpProtocolInfo: ptr WSAPROTOCOL_INFOA, lpszAddressString: PSTR, lpdwAddressStringLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc WSAAddressToStringW*(lpsaAddress: ptr SOCKADDR, dwAddressLength: uint32, lpProtocolInfo: ptr WSAPROTOCOL_INFOW, lpszAddressString: PWSTR, lpdwAddressStringLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc WSAAsyncGetHostByAddr*(hWnd: HWND, wMsg: u_int_2, `addr`: ptr int8, len: int32, `type`: int32, buf: ptr int8, buflen: int32): HANDLE {.sideEffect, importc, stdcall.}
proc WSAAsyncGetHostByName*(hWnd: HWND, wMsg: u_int_2, name: PCSTR, buf: ptr int8, buflen: int32): HANDLE {.sideEffect, importc, stdcall.}
proc WSAAsyncGetProtoByName*(hWnd: HWND, wMsg: u_int_2, name: PCSTR, buf: ptr int8, buflen: int32): HANDLE {.sideEffect, importc, stdcall.}
proc WSAAsyncGetProtoByNumber*(hWnd: HWND, wMsg: u_int_2, number: int32, buf: ptr int8, buflen: int32): HANDLE {.sideEffect, importc, stdcall.}
proc WSAAsyncGetServByName*(hWnd: HWND, wMsg: u_int_2, name: PCSTR, proto: PCSTR, buf: ptr int8, buflen: int32): HANDLE {.sideEffect, importc, stdcall.}
proc WSAAsyncGetServByPort*(hWnd: HWND, wMsg: u_int_2, port: int32, proto: ptr int8, buf: ptr int8, buflen: int32): HANDLE {.sideEffect, importc, stdcall.}
proc WSAAsyncSelect*(s: SOCKET, hWnd: HWND, wMsg: u_int_2, lEvent: int32): int32 {.sideEffect, importc, stdcall.}
proc WSACancelAsyncRequest*(hAsyncTaskHandle: HANDLE): int32 {.sideEffect, importc, stdcall.}
proc WSACancelBlockingCall*(): int32 {.sideEffect, importc, stdcall.}
proc WSACleanup*(): int32 {.sideEffect, importc, stdcall.}
proc WSACloseEvent*(hEvent: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc WSAConnect*(s: SOCKET, name: ptr SOCKADDR, namelen: int32, lpCallerData: ptr WSABUF, lpCalleeData: ptr WSABUF, lpSQOS: ptr QOS, lpGQOS: ptr QOS): int32 {.sideEffect, importc, stdcall.}
proc WSAConnectByList*(s: SOCKET, SocketAddress: ptr SOCKET_ADDRESS_LIST, LocalAddressLength: ptr uint32, LocalAddress: ptr SOCKADDR, RemoteAddressLength: ptr uint32, RemoteAddress: ptr SOCKADDR, timeout: ptr timeval, Reserved: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc WSAConnectByNameA*(s: SOCKET, nodename: PCSTR, servicename: PCSTR, LocalAddressLength: ptr uint32, LocalAddress: ptr SOCKADDR, RemoteAddressLength: ptr uint32, RemoteAddress: ptr SOCKADDR, timeout: ptr timeval, Reserved: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc WSAConnectByNameW*(s: SOCKET, nodename: PCWSTR, servicename: PCWSTR, LocalAddressLength: ptr uint32, LocalAddress: ptr SOCKADDR, RemoteAddressLength: ptr uint32, RemoteAddress: ptr SOCKADDR, timeout: ptr timeval, Reserved: ptr OVERLAPPED): BOOL {.sideEffect, importc, stdcall.}
proc WSACreateEvent*(): HANDLE {.sideEffect, importc, stdcall.}
proc WSADuplicateSocketA*(s: SOCKET, dwProcessId: uint32, lpProtocolInfo: ptr WSAPROTOCOL_INFOA): int32 {.sideEffect, importc, stdcall.}
proc WSADuplicateSocketW*(s: SOCKET, dwProcessId: uint32, lpProtocolInfo: ptr WSAPROTOCOL_INFOW): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumNameSpaceProvidersA*(lpdwBufferLength: ptr uint32, lpnspBuffer: ptr WSANAMESPACE_INFOA): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumNameSpaceProvidersExA*(lpdwBufferLength: ptr uint32, lpnspBuffer: ptr WSANAMESPACE_INFOEXA): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumNameSpaceProvidersExW*(lpdwBufferLength: ptr uint32, lpnspBuffer: ptr WSANAMESPACE_INFOEXW): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumNameSpaceProvidersW*(lpdwBufferLength: ptr uint32, lpnspBuffer: ptr WSANAMESPACE_INFOW): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumNetworkEvents*(s: SOCKET, hEventObject: HANDLE, lpNetworkEvents: ptr WSANETWORKEVENTS): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumProtocolsA*(lpiProtocols: ptr int32, lpProtocolBuffer: ptr WSAPROTOCOL_INFOA, lpdwBufferLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc WSAEnumProtocolsW*(lpiProtocols: ptr int32, lpProtocolBuffer: ptr WSAPROTOCOL_INFOW, lpdwBufferLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc WSAEventSelect*(s: SOCKET, hEventObject: HANDLE, lNetworkEvents: int32): int32 {.sideEffect, importc, stdcall.}
proc WSAGetLastError*(): int32 {.sideEffect, importc, stdcall.}
proc WSAGetOverlappedResult*(s: SOCKET, lpOverlapped: ptr OVERLAPPED, lpcbTransfer: ptr uint32, fWait: BOOL, lpdwFlags: ptr uint32): BOOL {.sideEffect, importc, stdcall.}
proc WSAGetQOSByName*(s: SOCKET, lpQOSName: ptr WSABUF, lpQOS: ptr QOS): BOOL {.sideEffect, importc, stdcall.}
proc WSAGetServiceClassInfoA*(lpProviderId: ptr GUID, lpServiceClassId: ptr GUID, lpdwBufSize: ptr uint32, lpServiceClassInfo: ptr WSASERVICECLASSINFOA): int32 {.sideEffect, importc, stdcall.}
proc WSAGetServiceClassInfoW*(lpProviderId: ptr GUID, lpServiceClassId: ptr GUID, lpdwBufSize: ptr uint32, lpServiceClassInfo: ptr WSASERVICECLASSINFOW): int32 {.sideEffect, importc, stdcall.}
proc WSAGetServiceClassNameByClassIdA*(lpServiceClassId: ptr GUID, lpszServiceClassName: PSTR, lpdwBufferLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc WSAGetServiceClassNameByClassIdW*(lpServiceClassId: ptr GUID, lpszServiceClassName: PWSTR, lpdwBufferLength: ptr uint32): int32 {.sideEffect, importc, stdcall.}
proc WSAHtonl*(s: SOCKET, hostlong: u_long, lpnetlong: ptr u_long): int32 {.sideEffect, importc, stdcall.}
proc WSAHtons*(s: SOCKET, hostshort: u_short, lpnetshort: ptr u_short): int32 {.sideEffect, importc, stdcall.}
proc WSAInstallServiceClassA*(lpServiceClassInfo: ptr WSASERVICECLASSINFOA): int32 {.sideEffect, importc, stdcall.}
proc WSAInstallServiceClassW*(lpServiceClassInfo: ptr WSASERVICECLASSINFOW): int32 {.sideEffect, importc, stdcall.}
proc WSAIoctl*(s: SOCKET, dwIoControlCode: uint32, lpvInBuffer: pointer, cbInBuffer: uint32, lpvOutBuffer: pointer, cbOutBuffer: uint32, lpcbBytesReturned: ptr uint32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc, stdcall.}
proc WSAIsBlocking*(): BOOL {.sideEffect, importc, stdcall.}
proc WSAJoinLeaf*(s: SOCKET, name: ptr SOCKADDR, namelen: int32, lpCallerData: ptr WSABUF, lpCalleeData: ptr WSABUF, lpSQOS: ptr QOS, lpGQOS: ptr QOS, dwFlags: uint32): SOCKET {.sideEffect, importc, stdcall.}
proc WSALookupServiceBeginA*(lpqsRestrictions: ptr WSAQUERYSETA, dwControlFlags: uint32, lphLookup: ptr HANDLE): int32 {.sideEffect, importc, stdcall.}
proc WSALookupServiceBeginW*(lpqsRestrictions: ptr WSAQUERYSETW, dwControlFlags: uint32, lphLookup: ptr HANDLE): int32 {.sideEffect, importc, stdcall.}
proc WSALookupServiceEnd*(hLookup: HANDLE): int32 {.sideEffect, importc, stdcall.}
proc WSALookupServiceNextA*(hLookup: HANDLE, dwControlFlags: uint32, lpdwBufferLength: ptr uint32, lpqsResults: ptr WSAQUERYSETA): int32 {.sideEffect, importc, stdcall.}
proc WSALookupServiceNextW*(hLookup: HANDLE, dwControlFlags: uint32, lpdwBufferLength: ptr uint32, lpqsResults: ptr WSAQUERYSETW): int32 {.sideEffect, importc, stdcall.}
proc WSANSPIoctl*(hLookup: HANDLE, dwControlCode: uint32, lpvInBuffer: pointer, cbInBuffer: uint32, lpvOutBuffer: pointer, cbOutBuffer: uint32, lpcbBytesReturned: ptr uint32, lpCompletion: ptr WSACOMPLETION): int32 {.sideEffect, importc, stdcall.}
proc WSANtohl*(s: SOCKET, netlong: u_long, lphostlong: ptr u_long): int32 {.sideEffect, importc, stdcall.}
proc WSANtohs*(s: SOCKET, netshort: u_short, lphostshort: ptr u_short): int32 {.sideEffect, importc, stdcall.}
proc WSAPoll*(fdArray: ptr WSAPOLLFD, fds: uint32, timeout: int32): int32 {.sideEffect, importc, stdcall.}
proc WSAProviderConfigChange*(lpNotificationHandle: ptr HANDLE, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc, stdcall.}
proc WSARecv*(s: SOCKET, lpBuffers: ptr WSABUF, dwBufferCount: uint32, lpNumberOfBytesRecvd: ptr uint32, lpFlags: ptr uint32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc, stdcall.}
proc WSARecvDisconnect*(s: SOCKET, lpInboundDisconnectData: ptr WSABUF): int32 {.sideEffect, importc, stdcall.}
proc WSARecvFrom*(s: SOCKET, lpBuffers: ptr WSABUF, dwBufferCount: uint32, lpNumberOfBytesRecvd: ptr uint32, lpFlags: ptr uint32, lpFrom: ptr SOCKADDR, lpFromlen: ptr int32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc, stdcall.}
proc WSARemoveServiceClass*(lpServiceClassId: ptr GUID): int32 {.sideEffect, importc, stdcall.}
proc WSAResetEvent*(hEvent: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc WSASend*(s: SOCKET, lpBuffers: ptr WSABUF, dwBufferCount: uint32, lpNumberOfBytesSent: ptr uint32, dwFlags: uint32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc, stdcall.}
proc WSASendDisconnect*(s: SOCKET, lpOutboundDisconnectData: ptr WSABUF): int32 {.sideEffect, importc, stdcall.}
proc WSASendMsg_2*(Handle: SOCKET, lpMsg: ptr WSAMSG, dwFlags: uint32, lpNumberOfBytesSent: ptr uint32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc: "WSASendMsg", stdcall.}
proc WSASendTo*(s: SOCKET, lpBuffers: ptr WSABUF, dwBufferCount: uint32, lpNumberOfBytesSent: ptr uint32, dwFlags: uint32, lpTo: ptr SOCKADDR, iTolen: int32, lpOverlapped: ptr OVERLAPPED, lpCompletionRoutine: LPWSAOVERLAPPED_COMPLETION_ROUTINE): int32 {.sideEffect, importc, stdcall.}
proc WSASetBlockingHook*(lpBlockFunc: FARPROC): FARPROC {.sideEffect, importc, stdcall.}
proc WSASetEvent*(hEvent: HANDLE): BOOL {.sideEffect, importc, stdcall.}
proc WSASetLastError*(iError: int32) {.sideEffect, importc, stdcall.}
proc WSASetServiceA*(lpqsRegInfo: ptr WSAQUERYSETA, essoperation: WSAESETSERVICEOP, dwControlFlags: uint32): int32 {.sideEffect, importc, stdcall.}
proc WSASetServiceW*(lpqsRegInfo: ptr WSAQUERYSETW, essoperation: WSAESETSERVICEOP, dwControlFlags: uint32): int32 {.sideEffect, importc, stdcall.}
proc WSASocketA*(af: int32, `type`: int32, protocol: int32, lpProtocolInfo: ptr WSAPROTOCOL_INFOA, g: GROUP, dwFlags: uint32): SOCKET {.sideEffect, importc, stdcall.}
proc WSASocketW*(af: int32, `type`: int32, protocol: int32, lpProtocolInfo: ptr WSAPROTOCOL_INFOW, g: GROUP, dwFlags: uint32): SOCKET {.sideEffect, importc, stdcall.}
proc WSAStartup*(wVersionRequested: uint16, lpWSAData: ptr WSADATA): int32 {.sideEffect, importc, stdcall.}
proc WSAStringToAddressA*(AddressString: PCSTR, AddressFamily: int32, lpProtocolInfo: ptr WSAPROTOCOL_INFOA, lpAddress: ptr SOCKADDR, lpAddressLength: ptr int32): int32 {.sideEffect, importc, stdcall.}
proc WSAStringToAddressW*(AddressString: PCWSTR, AddressFamily: int32, lpProtocolInfo: ptr WSAPROTOCOL_INFOW, lpAddress: ptr SOCKADDR, lpAddressLength: ptr int32): int32 {.sideEffect, importc, stdcall.}
proc WSAUnhookBlockingHook*(): int32 {.sideEffect, importc, stdcall.}
proc WSAWaitForMultipleEvents*(cEvents: uint32, lphEvents: ptr HANDLE, fWaitAll: BOOL, dwTimeout: uint32, fAlertable: BOOL): uint32 {.sideEffect, importc, stdcall.}
proc X_WSAFDIsSet*(fd: SOCKET, param1: ptr fd_set): int32 {.sideEffect, importc: "__WSAFDIsSet", stdcall.}
proc accept*(s: SOCKET, `addr`: ptr SOCKADDR, addrlen: ptr int32): SOCKET {.sideEffect, importc, stdcall.}
proc bind_2*(s: SOCKET, name: ptr SOCKADDR, namelen: int32): int32 {.sideEffect, importc: "bind", stdcall.}
proc closesocket*(s: SOCKET): int32 {.sideEffect, importc, stdcall.}
proc connect*(s: SOCKET, name: ptr SOCKADDR, namelen: int32): int32 {.sideEffect, importc, stdcall.}
proc gethostbyaddr*(`addr`: ptr int8, len: int32, `type`: int32): ptr hostent {.sideEffect, importc, stdcall.}
proc gethostbyname*(name: PCSTR): ptr hostent {.sideEffect, importc, stdcall.}
proc gethostname*(name: ptr int8, namelen: int32): int32 {.sideEffect, importc, stdcall.}
proc getpeername*(s: SOCKET, name: ptr SOCKADDR, namelen: ptr int32): int32 {.sideEffect, importc, stdcall.}
proc getprotobyname*(name: PCSTR): ptr protoent {.sideEffect, importc, stdcall.}
proc getprotobynumber*(number: int32): ptr protoent {.sideEffect, importc, stdcall.}
proc getservbyname*(name: PCSTR, proto: PCSTR): ptr servent {.sideEffect, importc, stdcall.}
proc getservbyport*(port: int32, proto: PCSTR): ptr servent {.sideEffect, importc, stdcall.}
proc getsockname*(s: SOCKET, name: ptr SOCKADDR, namelen: ptr int32): int32 {.sideEffect, importc, stdcall.}
proc getsockopt*(s: SOCKET, level: int32, optname: int32, optval: ptr int8, optlen: ptr int32): int32 {.sideEffect, importc, stdcall.}
proc htonl*(hostlong: u_long): u_long {.sideEffect, importc, stdcall.}
proc htons*(hostshort: u_short): u_short {.sideEffect, importc, stdcall.}
proc inet_addr*(cp: PCSTR): uint32 {.sideEffect, importc, stdcall.}
proc inet_ntoa*(`in`: IN_ADDR): ptr int8 {.sideEffect, importc, stdcall.}
proc ioctlsocket*(s: SOCKET, cmd: int32, argp: ptr u_long): int32 {.sideEffect, importc, stdcall.}
proc listen*(s: SOCKET, backlog: int32): int32 {.sideEffect, importc, stdcall.}
proc ntohl*(netlong: u_long): u_long {.sideEffect, importc, stdcall.}
proc ntohs*(netshort: u_short): u_short {.sideEffect, importc, stdcall.}
proc recv*(s: SOCKET, buf: ptr int8, len: int32, flags: int32): int32 {.sideEffect, importc, stdcall.}
proc recvfrom*(s: SOCKET, buf: ptr int8, len: int32, flags: int32, `from`: ptr SOCKADDR, fromlen: ptr int32): int32 {.sideEffect, importc, stdcall.}
proc select*(nfds: int32, readfds: ptr fd_set, writefds: ptr fd_set, exceptfds: ptr fd_set, timeout: ptr timeval): int32 {.sideEffect, importc, stdcall.}
proc send*(s: SOCKET, buf: ptr int8, len: int32, flags: int32): int32 {.sideEffect, importc, stdcall.}
proc sendto*(s: SOCKET, buf: ptr int8, len: int32, flags: int32, to: ptr SOCKADDR, tolen: int32): int32 {.sideEffect, importc, stdcall.}
proc setsockopt*(s: SOCKET, level: int32, optname: int32, optval: ptr int8, optlen: int32): int32 {.sideEffect, importc, stdcall.}
proc shutdown*(s: SOCKET, how: int32): int32 {.sideEffect, importc, stdcall.}
proc socket*(af: int32, `type`: int32, protocol: int32): SOCKET {.sideEffect, importc, stdcall.}
{.pop.}
