# generated by winmd2nim from Windows.Win32.winmd — wow64apiset (do not edit)
import ./[winnt, minwindef]
export winnt, minwindef

{.push dynlib: "api-ms-win-core-wow64-l1-1-1".}
proc GetSystemWow64Directory2A*(lpBuffer: PSTR, uSize: uint32, ImageFileMachineType: uint16): uint32 {.sideEffect, importc, stdcall.}
proc GetSystemWow64Directory2W*(lpBuffer: PWSTR, uSize: uint32, ImageFileMachineType: uint16): uint32 {.sideEffect, importc, stdcall.}
proc Wow64SetThreadDefaultGuestMachine*(Machine: uint16): uint16 {.sideEffect, importc, stdcall.}
{.pop.}
{.push dynlib: "kernel32".}
proc GetSystemWow64DirectoryA*(lpBuffer: PSTR, uSize: uint32): uint32 {.sideEffect, importc, stdcall.}
proc GetSystemWow64DirectoryW*(lpBuffer: PWSTR, uSize: uint32): uint32 {.sideEffect, importc, stdcall.}
proc IsWow64GuestMachineSupported*(WowGuestMachine: uint16, MachineIsSupported: ptr BOOL): HRESULT {.sideEffect, importc, stdcall.}
proc IsWow64Process*(hProcess: HANDLE, Wow64Process: ptr BOOL): BOOL {.sideEffect, importc, stdcall.}
proc IsWow64Process2*(hProcess: HANDLE, pProcessMachine: ptr uint16, pNativeMachine: ptr uint16): BOOL {.sideEffect, importc, stdcall.}
proc Wow64DisableWow64FsRedirection*(OldValue: ptr pointer): BOOL {.sideEffect, importc, stdcall.}
proc Wow64EnableWow64FsRedirection*(Wow64FsEnableRedirection: bool): bool {.sideEffect, importc, stdcall.}
proc Wow64GetThreadContext*(hThread: HANDLE, lpContext: ptr WOW64_CONTEXT): BOOL {.sideEffect, importc, stdcall.}
proc Wow64RevertWow64FsRedirection*(OlValue: pointer): BOOL {.sideEffect, importc, stdcall.}
proc Wow64SetThreadContext*(hThread: HANDLE, lpContext: ptr WOW64_CONTEXT): BOOL {.sideEffect, importc, stdcall.}
proc Wow64SuspendThread*(hThread: HANDLE): uint32 {.sideEffect, importc, stdcall.}
{.pop.}
