# generated by winmd2nim from Windows.Win32.winmd — ws2def (do not edit)
import ./[winnt, guiddef, inaddr]
export winnt, guiddef, inaddr

type

  # structs
  ADDRINFOA* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: ptr int8
    ai_addr*: ptr SOCKADDR
    ai_next*: ptr ADDRINFOA
  ADDRINFOEX2A* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: ptr int8
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: LPGUID
    ai_next*: ptr ADDRINFOEX2A
    ai_version*: int32
    ai_fqdn*: ptr int8
  ADDRINFOEX2W* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: LPGUID
    ai_next*: ptr ADDRINFOEX2W
    ai_version*: int32
    ai_fqdn*: PWSTR
  ADDRINFOEX3* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: LPGUID
    ai_next*: ptr ADDRINFOEX3
    ai_version*: int32
    ai_fqdn*: PWSTR
    ai_interfaceindex*: int32
  ADDRINFOEX4* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: ptr GUID
    ai_next*: ptr ADDRINFOEX4
    ai_version*: int32
    ai_fqdn*: PWSTR
    ai_interfaceindex*: int32
    ai_resolutionhandle*: HANDLE
  ADDRINFOEX5* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: ptr GUID
    ai_next*: ptr ADDRINFOEX5
    ai_version*: int32
    ai_fqdn*: PWSTR
    ai_interfaceindex*: int32
    ai_resolutionhandle*: HANDLE
    ai_ttl*: uint32
  ADDRINFOEX6* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: ptr GUID
    ai_next*: ptr ADDRINFOEX5
    ai_version*: int32
    ai_fqdn*: PWSTR
    ai_interfaceindex*: int32
    ai_resolutionhandle*: HANDLE
    ai_ttl*: uint32
    ai_numservers*: uint32
    ai_servers*: ptr ADDRINFO_DNS_SERVER
    ai_responseflags*: uint64
  ADDRINFOEX7* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: ptr GUID
    ai_next*: ptr ADDRINFOEX7
    ai_version*: int32
    ai_fqdn*: PWSTR
    ai_interfaceindex*: int32
    ai_resolutionhandle*: HANDLE
    ai_ttl*: uint32
    ai_numservers*: uint32
    ai_servers*: ptr ADDRINFO_DNS_SERVER
    ai_responseflags*: uint64
    ai_extraflags*: uint64
  ADDRINFOEXA* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: ptr int8
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: LPGUID
    ai_next*: ptr ADDRINFOEXA
  ADDRINFOEXW* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_blob*: pointer
    ai_bloblen*: uint
    ai_provider*: LPGUID
    ai_next*: ptr ADDRINFOEXW
  ADDRINFOW* {.completeStruct.} = object
    ai_flags*: int32
    ai_family*: int32
    ai_socktype*: int32
    ai_protocol*: int32
    ai_addrlen*: uint
    ai_canonname*: PWSTR
    ai_addr*: ptr SOCKADDR
    ai_next*: ptr ADDRINFOW
  ADDRINFO_DNS_SERVER* {.completeStruct.} = object
    ai_servertype*: uint32
    ai_flags*: uint64
    ai_addrlen*: uint32
    ai_addr*: ptr SOCKADDR
    Anonymous*: ADDRINFO_DNS_SERVER_4
  ADDRINFO_DNS_SERVER_4* {.completeStruct, union.} = object
    ai_template*: PWSTR
    ai_hostname*: PWSTR
  CSADDR_INFO* {.completeStruct.} = object
    LocalAddr*: SOCKET_ADDRESS
    RemoteAddr*: SOCKET_ADDRESS
    iSocketType*: int32
    iProtocol*: int32
  SCOPE_ID* {.completeStruct.} = object
    Anonymous*: SCOPE_ID_0
  SCOPE_ID_0* {.completeStruct, union.} = object
    Anonymous*: SCOPE_ID_0_0
    Value*: uint32
  SCOPE_ID_0_0* {.completeStruct.} = object
    X_bitfield*: uint32
  SOCKADDR* {.completeStruct.} = object
    sa_family*: ADDRESS_FAMILY
    sa_data*: array[14, int8]
  SOCKADDR_DL* {.completeStruct.} = object
    sdl_family*: ADDRESS_FAMILY
    sdl_data*: array[8, uint8]
    sdl_zero*: array[4, uint8]
  SOCKADDR_IN* {.completeStruct.} = object
    sin_family*: ADDRESS_FAMILY
    sin_port*: uint16
    sin_addr*: IN_ADDR
    sin_zero*: array[8, int8]
  SOCKADDR_STORAGE_LH* {.completeStruct.} = object
    ss_family*: ADDRESS_FAMILY
    X_ss_pad1*: array[6, int8]
    X_ss_align*: int64
    X_ss_pad2*: array[112, int8]
  SOCKADDR_STORAGE_XP* {.completeStruct.} = object
    ss_family*: int16
    X_ss_pad1*: array[6, int8]
    X_ss_align*: int64
    X_ss_pad2*: array[112, int8]
  SOCKET_ADDRESS* {.completeStruct.} = object
    lpSockaddr*: LPSOCKADDR
    iSockaddrLength*: int32
  SOCKET_ADDRESS_LIST* {.completeStruct.} = object
    iAddressCount*: int32
    Address*: array[1, SOCKET_ADDRESS]
  SOCKET_PROCESSOR_AFFINITY* {.completeStruct.} = object
    Processor*: PROCESSOR_NUMBER
    NumaNodeId*: uint16
    Reserved*: uint16
  WSABUF* {.completeStruct.} = object
    len*: uint32
    buf*: ptr int8
  WSACMSGHDR* {.completeStruct.} = object
    cmsg_len*: uint
    cmsg_level*: int32
    cmsg_type*: int32
  WSAMSG* {.completeStruct.} = object
    name*: LPSOCKADDR
    namelen*: int32
    lpBuffers*: LPWSABUF
    dwBufferCount*: uint32
    Control*: WSABUF
    dwFlags*: uint32

  # typdefs
  ADDRESS_FAMILY* = distinct uint16
  CMSGHDR* = WSACMSGHDR
  LPADDRINFOEX2A* = ptr ADDRINFOEX2A
  LPADDRINFOEX2W* = ptr ADDRINFOEX2W
  LPADDRINFOEX3* = ptr ADDRINFOEX3
  LPADDRINFOEX4* = ptr ADDRINFOEX4
  LPADDRINFOEX5* = ptr ADDRINFOEX5
  LPADDRINFOEXA* = ptr ADDRINFOEXA
  LPADDRINFOEXW* = ptr ADDRINFOEXW
  LPCSADDR_INFO* = ptr CSADDR_INFO
  LPSOCKADDR* = ptr SOCKADDR
  LPSOCKADDR_STORAGE* = ptr SOCKADDR_STORAGE
  LPSOCKADDR_STORAGE_LH* = ptr SOCKADDR_STORAGE_LH
  LPSOCKADDR_STORAGE_XP* = ptr SOCKADDR_STORAGE_XP
  LPSOCKET_ADDRESS* = ptr SOCKET_ADDRESS
  LPSOCKET_ADDRESS_LIST* = ptr SOCKET_ADDRESS_LIST
  LPWSABUF* = ptr WSABUF
  LPWSACMSGHDR* = ptr WSACMSGHDR
  LPWSAMSG* = ptr WSAMSG
  PADDRINFOA* = ptr ADDRINFOA
  PADDRINFOEX2A* = ptr ADDRINFOEX2A
  PADDRINFOEX2W* = ptr ADDRINFOEX2W
  PADDRINFOEX3* = ptr ADDRINFOEX3
  PADDRINFOEX4* = ptr ADDRINFOEX4
  PADDRINFOEX5* = ptr ADDRINFOEX5
  PADDRINFOEX6* = ptr ADDRINFOEX6
  PADDRINFOEX7* = ptr ADDRINFOEX7
  PADDRINFOEXA* = ptr ADDRINFOEXA
  PADDRINFOEXW* = ptr ADDRINFOEXW
  PADDRINFOW* = ptr ADDRINFOW
  PCMSGHDR* = ptr WSACMSGHDR
  PCSADDR_INFO* = ptr CSADDR_INFO
  PIPROTO* = distinct ptr IPPROTO
  PSCOPE_ID* = ptr SCOPE_ID
  PSOCKADDR* = ptr SOCKADDR
  PSOCKADDR_DL* = ptr SOCKADDR_DL
  PSOCKADDR_IN* = ptr SOCKADDR_IN
  PSOCKADDR_STORAGE* = ptr SOCKADDR_STORAGE
  PSOCKADDR_STORAGE_LH* = ptr SOCKADDR_STORAGE_LH
  PSOCKADDR_STORAGE_XP* = ptr SOCKADDR_STORAGE_XP
  PSOCKET_ADDRESS* = ptr SOCKET_ADDRESS
  PSOCKET_ADDRESS_LIST* = ptr SOCKET_ADDRESS_LIST
  PSOCKET_PROCESSOR_AFFINITY* = ptr SOCKET_PROCESSOR_AFFINITY
  PWSACMSGHDR* = ptr WSACMSGHDR
  PWSAMSG* = ptr WSAMSG
  SOCKADDR_STORAGE* = SOCKADDR_STORAGE_LH

  # unscoped enums 
  IPPROTO* = int32
  SCOPE_LEVEL* = int32

const
  # free constants
  ADDRINFOEX_VERSION_2*: int32 = 2'i32
  ADDRINFOEX_VERSION_3*: int32 = 3'i32
  ADDRINFOEX_VERSION_4*: int32 = 4'i32
  ADDRINFOEX_VERSION_5*: int32 = 5'i32
  ADDRINFOEX_VERSION_6*: int32 = 6'i32
  ADDRINFOEX_VERSION_7*: int32 = 7'i32
  AF_12844*: int32 = 25'i32
  AF_APPLETALK*: int32 = 16'i32
  AF_ATM*: int32 = 22'i32
  AF_BAN*: int32 = 21'i32
  AF_BTH*: int32 = 32'i32
  AF_CCITT*: int32 = 10'i32
  AF_CHAOS*: int32 = 5'i32
  AF_CLUSTER*: int32 = 24'i32
  AF_DATAKIT*: int32 = 9'i32
  AF_DECnet*: int32 = 12'i32
  AF_DLI*: int32 = 13'i32
  AF_ECMA*: int32 = 8'i32
  AF_FIREFOX*: int32 = 19'i32
  AF_HYLINK*: int32 = 15'i32
  AF_HYPERV*: int32 = 34'i32
  AF_ICLFXBM*: int32 = 31'i32
  AF_IMPLINK*: int32 = 3'i32
  AF_INET*: int32 = 2'i32
  AF_INET6*: int32 = 23'i32
  AF_IPX*: int32 = 6'i32
  AF_IRDA*: int32 = 26'i32
  AF_ISO*: int32 = 7'i32
  AF_LAT*: int32 = 14'i32
  AF_LINK*: int32 = 33'i32
  AF_MAX*: int32 = 35'i32
  AF_NETBIOS*: int32 = 17'i32
  AF_NETDES*: int32 = 28'i32
  AF_NS*: int32 = 6'i32
  AF_OSI*: int32 = 7'i32
  AF_PUP*: int32 = 4'i32
  AF_SNA*: int32 = 11'i32
  AF_TCNMESSAGE*: int32 = 30'i32
  AF_TCNPROCESS*: int32 = 29'i32
  AF_UNIX*: int32 = 1'i32
  AF_UNKNOWN1*: int32 = 20'i32
  AF_UNSPEC*: int32 = 0'i32
  AF_VOICEVIEW*: int32 = 18'i32
  AI_ADDRCONFIG*: int32 = 1024'i32
  AI_ALL*: int32 = 256'i32
  AI_BYPASS_DNS_CACHE*: int32 = 64'i32
  AI_CANONNAME*: int32 = 2'i32
  AI_DISABLE_IDN_ENCODING*: int32 = 524288'i32
  AI_DNS_ONLY*: int32 = 16'i32
  AI_DNS_RESPONSE_HOSTFILE*: int32 = 2'i32
  AI_DNS_RESPONSE_SECURE*: int32 = 1'i32
  AI_DNS_SERVER_TYPE_DOH*: int32 = 2'i32
  AI_DNS_SERVER_TYPE_DOT*: int32 = 3'i32
  AI_DNS_SERVER_TYPE_UDP*: int32 = 1'i32
  AI_DNS_SERVER_UDP_FALLBACK*: int32 = 1'i32
  AI_EXCLUSIVE_CUSTOM_SERVERS*: int32 = 2097152'i32
  AI_EXTENDED*: uint32 = 0x80000000'u32
  AI_EXTRA_DNSSEC_REQUIRED*: int32 = 1'i32
  AI_FILESERVER*: int32 = 262144'i32
  AI_FORCE_CLEAR_TEXT*: int32 = 32'i32
  AI_FQDN*: int32 = 131072'i32
  AI_NON_AUTHORITATIVE*: int32 = 16384'i32
  AI_NUMERICHOST*: int32 = 4'i32
  AI_NUMERICSERV*: int32 = 8'i32
  AI_PASSIVE*: int32 = 1'i32
  AI_REQUIRE_SECURE*: int32 = 536870912'i32
  AI_RESOLUTION_HANDLE*: int32 = 1073741824'i32
  AI_RETURN_PREFERRED_NAMES*: int32 = 65536'i32
  AI_RETURN_RESPONSE_FLAGS*: int32 = 268435456'i32
  AI_RETURN_TTL*: int32 = 128'i32
  AI_SECURE*: int32 = 32768'i32
  AI_SECURE_WITH_FALLBACK*: int32 = 1048576'i32
  AI_V4MAPPED*: int32 = 2048'i32
  INADDR_ANY*: uint32 = 0x0'u32
  INADDR_BROADCAST*: uint32 = 0xffffffff'u32
  INADDR_LOOPBACK*: int32 = 2130706433'i32
  INADDR_NONE*: uint32 = 0xffffffff'u32
  IN_CLASSA_HOST*: int32 = 16777215'i32
  IN_CLASSA_MAX*: int32 = 128'i32
  IN_CLASSA_NET*: uint32 = 0xff000000'u32
  IN_CLASSA_NSHIFT*: int32 = 24'i32
  IN_CLASSB_HOST*: int32 = 65535'i32
  IN_CLASSB_MAX*: int32 = 65536'i32
  IN_CLASSB_NET*: uint32 = 0xffff0000'u32
  IN_CLASSB_NSHIFT*: int32 = 16'i32
  IN_CLASSC_HOST*: int32 = 255'i32
  IN_CLASSC_NET*: uint32 = 0xffffff00'u32
  IN_CLASSC_NSHIFT*: int32 = 8'i32
  IN_CLASSD_HOST*: int32 = 268435455'i32
  IN_CLASSD_NET*: uint32 = 0xf0000000'u32
  IN_CLASSD_NSHIFT*: int32 = 28'i32
  IOCPARM_MASK*: int32 = 127'i32
  IOC_IN*: uint32 = 0x80000000'u32
  IOC_INOUT*: uint32 = 0xc0000000'u32
  IOC_OUT*: int32 = 1073741824'i32
  IOC_PROTOCOL*: int32 = 268435456'i32
  IOC_UNIX*: int32 = 0'i32
  IOC_VENDOR*: int32 = 402653184'i32
  IOC_VOID*: int32 = 536870912'i32
  IOC_WS2*: int32 = 134217728'i32
  IOC_WSK*: int32 = 251658240'i32
  IP6T_SO_ORIGINAL_DST*: int32 = 12303'i32
  IPPORT_BIFFUDP*: int32 = 512'i32
  IPPORT_CHARGEN*: int32 = 19'i32
  IPPORT_CMDSERVER*: int32 = 514'i32
  IPPORT_DAYTIME*: int32 = 13'i32
  IPPORT_DISCARD*: int32 = 9'i32
  IPPORT_DYNAMIC_MAX*: int32 = 65535'i32
  IPPORT_DYNAMIC_MIN*: int32 = 49152'i32
  IPPORT_ECHO*: int32 = 7'i32
  IPPORT_EFSSERVER*: int32 = 520'i32
  IPPORT_EPMAP*: int32 = 135'i32
  IPPORT_EXECSERVER*: int32 = 512'i32
  IPPORT_FINGER*: int32 = 79'i32
  IPPORT_FTP*: int32 = 21'i32
  IPPORT_FTP_DATA*: int32 = 20'i32
  IPPORT_HTTPS*: int32 = 443'i32
  IPPORT_IMAP*: int32 = 143'i32
  IPPORT_IMAP3*: int32 = 220'i32
  IPPORT_LDAP*: int32 = 389'i32
  IPPORT_LOGINSERVER*: int32 = 513'i32
  IPPORT_MICROSOFT_DS*: int32 = 445'i32
  IPPORT_MSP*: int32 = 18'i32
  IPPORT_MTP*: int32 = 57'i32
  IPPORT_NAMESERVER*: int32 = 42'i32
  IPPORT_NETBIOS_DGM*: int32 = 138'i32
  IPPORT_NETBIOS_NS*: int32 = 137'i32
  IPPORT_NETBIOS_SSN*: int32 = 139'i32
  IPPORT_NETSTAT*: int32 = 15'i32
  IPPORT_NTP*: int32 = 123'i32
  IPPORT_POP3*: int32 = 110'i32
  IPPORT_QOTD*: int32 = 17'i32
  IPPORT_REGISTERED_MAX*: int32 = 49151'i32
  IPPORT_REGISTERED_MIN*: int32 = 1024'i32
  IPPORT_RESERVED*: int32 = 1024'i32
  IPPORT_RJE*: int32 = 77'i32
  IPPORT_ROUTESERVER*: int32 = 520'i32
  IPPORT_SMTP*: int32 = 25'i32
  IPPORT_SNMP*: int32 = 161'i32
  IPPORT_SNMP_TRAP*: int32 = 162'i32
  IPPORT_SUPDUP*: int32 = 95'i32
  IPPORT_SYSTAT*: int32 = 11'i32
  IPPORT_TCPMUX*: int32 = 1'i32
  IPPORT_TELNET*: int32 = 23'i32
  IPPORT_TFTP*: int32 = 69'i32
  IPPORT_TIMESERVER*: int32 = 37'i32
  IPPORT_TTYLINK*: int32 = 87'i32
  IPPORT_WHOIS*: int32 = 43'i32
  IPPORT_WHOSERVER*: int32 = 513'i32
  IPPROTO_IP*: int32 = 0'i32
  MSG_BCAST*: int32 = 1024'i32
  MSG_CTRUNC*: int32 = 512'i32
  MSG_ERRQUEUE*: int32 = 4096'i32
  MSG_MCAST*: int32 = 2048'i32
  MSG_TRUNC*: int32 = 256'i32
  NI_DGRAM*: int32 = 16'i32
  NI_MAXHOST*: int32 = 1025'i32
  NI_MAXSERV*: int32 = 32'i32
  NI_NAMEREQD*: int32 = 4'i32
  NI_NOFQDN*: int32 = 1'i32
  NI_NUMERICHOST*: int32 = 2'i32
  NI_NUMERICSERV*: int32 = 8'i32
  NS_ALL*: int32 = 0'i32
  NS_BTH*: int32 = 16'i32
  NS_DHCP*: int32 = 6'i32
  NS_DNS*: int32 = 12'i32
  NS_EMAIL*: int32 = 37'i32
  NS_MS*: int32 = 30'i32
  NS_NBP*: int32 = 20'i32
  NS_NDS*: int32 = 2'i32
  NS_NETBT*: int32 = 13'i32
  NS_NETDES*: int32 = 60'i32
  NS_NIS*: int32 = 41'i32
  NS_NISPLUS*: int32 = 42'i32
  NS_NLA*: int32 = 15'i32
  NS_NTDS*: int32 = 32'i32
  NS_PEER_BROWSE*: int32 = 3'i32
  NS_PNRPCLOUD*: int32 = 39'i32
  NS_PNRPNAME*: int32 = 38'i32
  NS_SAP*: int32 = 1'i32
  NS_SLP*: int32 = 5'i32
  NS_STDA*: int32 = 31'i32
  NS_TCPIP_HOSTS*: int32 = 11'i32
  NS_TCPIP_LOCAL*: int32 = 10'i32
  NS_WINS*: int32 = 14'i32
  NS_WRQ*: int32 = 50'i32
  NS_X500*: int32 = 40'i32
  SIO_ADDRESS_LIST_CHANGE*: int32 = 671088663'i32
  SIO_ADDRESS_LIST_QUERY*: int32 = 1207959574'i32
  SIO_ADDRESS_LIST_SORT*: uint32 = 0xc8000019'u32
  SIO_ASSOCIATE_HANDLE*: uint32 = 0x88000001'u32
  SIO_ENABLE_CIRCULAR_QUEUEING*: int32 = 671088642'i32
  SIO_FIND_ROUTE*: int32 = 1207959555'i32
  SIO_FLUSH*: int32 = 671088644'i32
  SIO_GET_BROADCAST_ADDRESS*: int32 = 1207959557'i32
  SIO_GET_EXTENSION_FUNCTION_POINTER*: uint32 = 0xc8000006'u32
  SIO_GET_GROUP_QOS*: uint32 = 0xc8000008'u32
  SIO_GET_MULTIPLE_EXTENSION_FUNCTION_POINTER*: uint32 = 0xc8000024'u32
  SIO_GET_QOS*: uint32 = 0xc8000007'u32
  SIO_MULTICAST_SCOPE*: uint32 = 0x8800000a'u32
  SIO_MULTIPOINT_LOOPBACK*: uint32 = 0x88000009'u32
  SIO_QUERY_RSS_PROCESSOR_INFO*: int32 = 1207959589'i32
  SIO_QUERY_TARGET_PNP_HANDLE*: int32 = 1207959576'i32
  SIO_RESERVED_1*: uint32 = 0x8800001a'u32
  SIO_RESERVED_2*: uint32 = 0x88000021'u32
  SIO_ROUTING_INTERFACE_CHANGE*: uint32 = 0x88000015'u32
  SIO_ROUTING_INTERFACE_QUERY*: uint32 = 0xc8000014'u32
  SIO_SET_GROUP_QOS*: uint32 = 0x8800000c'u32
  SIO_SET_QOS*: uint32 = 0x8800000b'u32
  SIO_TRANSLATE_HANDLE*: uint32 = 0xc800000d'u32
  SOCK_DGRAM*: int32 = 2'i32
  SOCK_RAW*: int32 = 3'i32
  SOCK_RDM*: int32 = 4'i32
  SOCK_SEQPACKET*: int32 = 5'i32
  SOCK_STREAM*: int32 = 1'i32
  SOL_IP*: int32 = 65531'i32
  SOL_IPV6*: int32 = 65530'i32
  SOL_SOCKET*: int32 = 65535'i32
  SO_ACCEPTCONN*: int32 = 2'i32
  SO_BROADCAST*: int32 = 32'i32
  SO_BSP_STATE*: int32 = 4105'i32
  SO_COMPARTMENT_ID*: int32 = 12292'i32
  SO_CONDITIONAL_ACCEPT*: int32 = 12290'i32
  SO_DEBUG*: int32 = 1'i32
  SO_DONTLINGER*: int32 = -129'i32
  SO_DONTROUTE*: int32 = 16'i32
  SO_ERROR*: int32 = 4103'i32
  SO_EXCLUSIVEADDRUSE*: int32 = -5'i32
  SO_GROUP_ID*: int32 = 8193'i32
  SO_GROUP_PRIORITY*: int32 = 8194'i32
  SO_KEEPALIVE*: int32 = 8'i32
  SO_LINGER*: int32 = 128'i32
  SO_MAX_MSG_SIZE*: int32 = 8195'i32
  SO_OOBINLINE*: int32 = 256'i32
  SO_ORIGINAL_DST*: int32 = 12303'i32
  SO_PAUSE_ACCEPT*: int32 = 12291'i32
  SO_PORT_SCALABILITY*: int32 = 12294'i32
  SO_RANDOMIZE_PORT*: int32 = 12293'i32
  SO_RCVBUF*: int32 = 4098'i32
  SO_RCVLOWAT*: int32 = 4100'i32
  SO_RCVTIMEO*: int32 = 4102'i32
  SO_RECEIVED_HOPLIMIT*: int32 = 12304'i32
  SO_RECEIVED_PROCESSOR*: int32 = 12305'i32
  SO_REUSEADDR*: int32 = 4'i32
  SO_REUSE_MULTICASTPORT*: int32 = 12296'i32
  SO_REUSE_UNICASTPORT*: int32 = 12295'i32
  SO_SNDBUF*: int32 = 4097'i32
  SO_SNDLOWAT*: int32 = 4099'i32
  SO_SNDTIMEO*: int32 = 4101'i32
  SO_TYPE*: int32 = 4104'i32
  SO_USELOOPBACK*: int32 = 64'i32
  TCP_NODELAY*: int32 = 1'i32
  WSK_SO_BASE*: int32 = 16384'i32

  # unscoped enum members
  IPPROTO_HOPOPTS*: IPPROTO = 0'i32
  IPPROTO_ICMP*: IPPROTO = 1'i32
  IPPROTO_IGMP*: IPPROTO = 2'i32
  IPPROTO_GGP*: IPPROTO = 3'i32
  IPPROTO_IPV4*: IPPROTO = 4'i32
  IPPROTO_ST*: IPPROTO = 5'i32
  IPPROTO_TCP*: IPPROTO = 6'i32
  IPPROTO_CBT*: IPPROTO = 7'i32
  IPPROTO_EGP*: IPPROTO = 8'i32
  IPPROTO_IGP*: IPPROTO = 9'i32
  IPPROTO_PUP*: IPPROTO = 12'i32
  IPPROTO_UDP*: IPPROTO = 17'i32
  IPPROTO_IDP*: IPPROTO = 22'i32
  IPPROTO_RDP*: IPPROTO = 27'i32
  IPPROTO_IPV6*: IPPROTO = 41'i32
  IPPROTO_ROUTING*: IPPROTO = 43'i32
  IPPROTO_FRAGMENT*: IPPROTO = 44'i32
  IPPROTO_ESP*: IPPROTO = 50'i32
  IPPROTO_AH*: IPPROTO = 51'i32
  IPPROTO_ICMPV6*: IPPROTO = 58'i32
  IPPROTO_NONE*: IPPROTO = 59'i32
  IPPROTO_DSTOPTS*: IPPROTO = 60'i32
  IPPROTO_ND*: IPPROTO = 77'i32
  IPPROTO_ICLFXBM*: IPPROTO = 78'i32
  IPPROTO_PIM*: IPPROTO = 103'i32
  IPPROTO_PGM*: IPPROTO = 113'i32
  IPPROTO_L2TP*: IPPROTO = 115'i32
  IPPROTO_SCTP*: IPPROTO = 132'i32
  IPPROTO_RAW*: IPPROTO = 255'i32
  IPPROTO_MAX*: IPPROTO = 256'i32
  IPPROTO_RESERVED_RAW*: IPPROTO = 257'i32
  IPPROTO_RESERVED_IPSEC*: IPPROTO = 258'i32
  IPPROTO_RESERVED_IPSECOFFLOAD*: IPPROTO = 259'i32
  IPPROTO_RESERVED_WNV*: IPPROTO = 260'i32
  IPPROTO_RESERVED_MAX*: IPPROTO = 261'i32
  ScopeLevelInterface*: SCOPE_LEVEL = 1'i32
  ScopeLevelLink*: SCOPE_LEVEL = 2'i32
  ScopeLevelSubnet*: SCOPE_LEVEL = 3'i32
  ScopeLevelAdmin*: SCOPE_LEVEL = 4'i32
  ScopeLevelSite*: SCOPE_LEVEL = 5'i32
  ScopeLevelOrganization*: SCOPE_LEVEL = 8'i32
  ScopeLevelGlobal*: SCOPE_LEVEL = 14'i32
  ScopeLevelCount*: SCOPE_LEVEL = 16'i32

